### ISSUE TITLE
Transaction labels

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#10]
- Assign multiple labels to one transaction for better filtering.
- Labels screen
- See transactions by labels

**Comment by 8227846265** [comment]
Labels would be nice. In my case, my primary use case for labels is to use it for the place where the expense happened.

Situation
- I eat on McDonald and spent $20 paid by cash at 12:30 PM (lunchtime)

A Transaction Record may look like this:
- `Account` = Cash
- `Transaction Type` = Expense
- `Transaction Category` = Food & Drinks
- `Transaction Sub-Category` = Lunch
- `Label` = McDonald
- `Expense Description` = Cheeseburger and Large Coke

Wherein if there's an analytics for Filters, I can see how many times I eat on McDonald and see which expenses are highest (e.g. Breakfast, Lunch, or Dinner)

**Comment by zebrapurring** [comment]
Was this issue closed intentionally?
