### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by vishnu-prasads** [Ivy-Apps/ivy-wallet#1009]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

The interest on a loan is not getting deducted from the original account. There is no transaction about the loan interest deduction in the main account (cash/card). 

### To Reproduce

1.  Add an interest paid for the loan and select an account from where the interest is paid. 
2. The interest paid details will be shown in the loan but there is no such transaction recorded for the account selected. 

### Smartphone

Samsung M51

**Comment by Vishwa-Raghavendra** [comment]
@vprsad did you select the option "create a main transaction" when adding a loan record?

**Comment by vprsad** [comment]
> @vprsad did you select the option "create a main transaction" when adding a loan record?

There are 2 options for adding a record. Mark as a main transaction or mark it as interest. I was using the second option to log the interest I have paid. It is getting added into the loan but not reflecting on the source from where I paid. Hope it is clear.

**Comment by Vishwa-Raghavendra** [comment]
Hey @vprsad, Thanks for the detailed explanation :)

You can select both the options i.e "create a main transaction" and "mark as interest"

The first option creates a transaction with the associated account and the second option marks it as interest


![IMG_20220608_174449](https://user-images.githubusercontent.com/42895647/172613851-8a6c76f3-7b35-4d75-9edf-03e327b0691f.jpg)

**Comment by vprsad** [comment]
Thank you for that details. Now I got it. :)
