### ISSUE TITLE
Being able to set conversion rate manually 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1010]

**Comment by Pkcarreno** [comment]
adjusting the conversion rate is already possible, see here https://github.com/ILIYANGERMANOV/ivy-wallet/issues/582, maybe it refers to this other https://github.com/ILIYANGERMANOV/ivy-wallet/issues/1004

**Comment by code-a1** [comment]
#1004 Duplicate
