### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by jdleval** [Ivy-Apps/ivy-wallet#1012]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

Some how the cash input shows a dollar, even when I adjust it to zero. Not only that, other times when I set an adjustment, it sets it a dollar off, for example, if I had 50 Dollars in a catagory, in this case cash, and I go in and change it to 0, it will show. That I have 1 dollar as the balance. This seems to only happen when I open the account, select it's balance, and change it

### To Reproduce

1. Select account that has a balance of 50
2. Change the current balance to zero.
3. Save it.
4. When returning to the home screen, the balance shows 1 dollar

### Expected behavior

It should display a balance of zero

### Smartphone

Samsung Galaxy s21 ultra

**Comment by Pkcarreno** [comment]
I think I have presented this problem too, look at this https://github.com/ILIYANGERMANOV/ivy-wallet/issues/685

**Comment by ILIYANGERMANOV** [comment]
Duplicate
