### ISSUE TITLE
[BUDGETS] A way to see all transactions for a budget

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#103]
**What do you want to be added or improved?**
As a user I want to be able to see all transactions for a given budget.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- see where I spent my budget
- see all transactions included in the budget

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- when clicking a budget to open a new screen for it
- this Budget screen should display all transactions for the given budget

**Comment by muzafakar** [comment]
I just started using budget in Ivy wallet and find this feature request is very important. 

@ILIYANGERMANOV, I wonder if there's already someone who started working on it? If no, I want to contribute on this request.

**Comment by muzafakar** [comment]
I'm on it!
