### ISSUE TITLE
[FEATURES] ... Ever thought of integrating UPI Transactions?

### ISSUE THREAD

**Issue by ninetynin** [Ivy-Apps/ivy-wallet#1036]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to see upi transactions to be tracked automatically 

### Why do you need it?

- because it just makes my life easier what else and im sure there are many people need it
- and there is some app called wallnut but its not open source and this is imp stuff and i dont trust it on non open source apps
- i was trying to implement it but im a beginner and was struck i will try to improve if i get anything 
- incase ur intrested contact me because i know what to do i mean like i was struck at half of what i was trying to implement

**Comment by ILIYANGERMANOV** [comment]
Out of scope
