### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by ahmedWaelSalem** [Ivy-Apps/ivy-wallet#1039]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

Fix the White screen when launching the app

### To Reproduce

1. 

### Smartphone

Xiaomi Redmi Note 7

**Comment by ILIYANGERMANOV** [comment]
App version?
