### ISSUE TITLE
[FEATURES] 

### ISSUE THREAD

**Issue by Upaxah** [Ivy-Apps/ivy-wallet#1045]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

Hello, I want to suggest you some features
- add a chart of the expenses and incomes
- add the option to drag a picture or pdf into a expens, for a bill or invoice
- add the option to favorite or mark a expense/income and an extra channel to see all your marks, for a range of time

### Why do you need it?

They're features which just makes the app better. On the charts I can see on which days a have big expenses/incomes and on which don't. Also the mark features let me finde much faster an expense/income, btw a invoice, check or bill which I need really quick

### How do you imagine it?

The chart option could be in the "quick access" area. And the mark option while creating or as a small symbol at the right side of transaction in the "Home" area.
I hope that I could help you a little bit :)

**Comment by ILIYANGERMANOV** [comment]
Out of scope
