### ISSUE TITLE
[BUG] Widget updation issue 

### ISSUE THREAD

**Issue by Kuladeep1996** [Ivy-Apps/ivy-wallet#1046]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I delete a transaction, widget won't update and shows wrong balance 

### To Reproduce

1. Place a balance widget on home screen
2. Delete a transaction inside app

### Expected behavior

widget should update according to changes happens inside app

### Smartphone

Realme 7 and Android v11

**Comment by ILIYANGERMANOV** [comment]
Can you please try to reproduce it on Ivy Wallet "4.4.7" (147)?

**Comment by Kuladeep1996** [comment]
I have used 4.4.7(147) version to produce this issue.
After deleting a transaction still widget is updating automatically.
Widget gets updated when I click on widget to open app

**Comment by ILIYANGERMANOV** [comment]
Got it - thank you!
