### ISSUE TITLE
Budgets That Don't Reset Every Month

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1050]

**Comment by yaoandy107** [comment]
I would like to work on this issue. I really need this feature!

**Comment by ILIYANGERMANOV** [comment]
Go ahead! That's a great feature 👍 Just add setting in Settings and the default behavior to be the current budgets that reset.

**Comment by yaoandy107** [comment]
@ILIYANGERMANOV Would it be better to add an option to enable it when creating a budget? So that it could be set it independently per budget.

**Comment by ILIYANGERMANOV** [comment]
Yes, that's even better and offers greater flexibility!
