### ISSUE TITLE
[BUG] Mismatch in day calculation for not UTC timezone

### ISSUE THREAD

**Issue by ryg-git** [Ivy-Apps/ivy-wallet#1054]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

When user adds a transaction, in transaction history,
the app wrongly sets day as tomorrow instead of today or yesterday instead of today.

(in the screenshot attached below even though 22 June is `today` the app sets it as `tomorrow`)

### To Reproduce

1. Add a transaction.
2. Check the transaction history on main screen.

### Expected behavior

Day calculations should be properly done for non UTC Time zones also.

### Screenshots

![issue](https://user-images.githubusercontent.com/69393483/174873835-3cc81227-d2b7-4db1-a25b-611162c2b00b.jpeg)

### Smartphone

realme GT neo 2.

**Comment by ryg-git** [comment]
If it is okay, I would like to work on this issue.

**Comment by tnnyx** [comment]
I have the same issue too
