### ISSUE TITLE
[BUG] In the reports the button of skip, skip all and pay doesn't work

### ISSUE THREAD

**Issue by jevo160296** [Ivy-Apps/ivy-wallet#1086]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I have planned payments and go to the report area, the buttons skip, skip all and delete doesn't work.

### To Reproduce

1. Add planned payment
2. Go to reports
3. Push any button (skip, skip all or pay)
4. Nothing happens

### Expected behavior

When I touch those button the expecting behaviour should trigger.

### Smartphone

Motorola moto one fusion

**Comment by ILIYANGERMANOV** [comment]
Hey @jevo160296 does that still reproduce on the latest Ivy Wallet?

**Comment by MaratKhakim** [comment]
What are the expected behaviors? They should be exactly the same as Home screen?

**Comment by ILIYANGERMANOV** [comment]
> What are the expected behaviors? They should be exactly the same as Home screen?

Yup, exactly as the home screen

**Comment by MaratKhakim** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @MaratKhakim! 🎉
Issue #1086 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
