### ISSUE TITLE
Credit cards support

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#11]
To be defined... Comment if you have any ideas.

From Reviews:
- "* Add credit card (preferable an option for multiple credit cards for same account). * Installments/payments. * add ability to set planed day of payment without automatically change 'created on'. I love to keep track when i bought the item, regardless the time it eventually sean on bank account."

User requests:
- Allowing to make a credit card account type with billing dates so that out standing can be marked paid from an account
- Credit card account where we set monthly credit card limit and record expenses/bill which we have to pay at the end of the month.

**Comment by quebin31** [comment]
There are two important dates for credit cards, settlement date and payment date, the first one is usually fixed but the second one could be fixed or based on the settlement date (e.g. 15 days after settlement)

**Comment by quebin31** [comment]
We should also take into consideration [this comment](https://github.com/ILIYANGERMANOV/ivy-wallet/issues/12#issuecomment-963745043) from #12

**Comment by ILIYANGERMANOV** [comment]
Hi @quebin31 thank you for starting a discussion! Those are all valid comments. I'm not familiar with the spec as I've never used a credit card in my life but we'll do our best to take all feedback in consideration and implement an elegant Credit Card support.

Currently we're focused on #68 (open source the design) so you and the other contributors can comment on it and suggest improvements.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
