### ISSUE TITLE
[BUG] Can't enter numbers 

### ISSUE THREAD

**Issue by rezakelidari** [Ivy-Apps/ivy-wallet#1104]
### Please confirm the following

- [x] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

I can't enter numbers in Add income page with Persian pattern:
۱۲۳۴۵۶۷۸۹۰

### To Reproduce

1.Go to Add Income
2.Just enter numbers
* When phone language is set to Persian, you can just enter one or two number

### Expected behavior

The app should enter numbers in English pattern (0123...9) instead of Persian pattern (۰۱۲۳...۹)

### Screenshots

![Screenshot_۲۰۲۲-۰۷-۰۹-۱۶-۲۴-۵۲-۲۶۳_com ivy wallet](https://user-images.githubusercontent.com/62962597/178104641-a088b0b8-fbe9-4737-bc27-2f704d0e02c5.jpg)

### Smartphone

Xiaomi Redmi 8 Global (Olive)

### Additional context

This bug also maybe happen with Arabic language, because this languages are in Right to Left pattern

**Comment by TheMilanTej** [comment]
i want to work on this issue @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
@TheMilanTej assigned to you ✅️

**Comment by TheMilanTej** [comment]
i unassigned myself from the issue @ILIYANGERMANOV

**Comment by AndroidPoet** [comment]
Hi, @ILIYANGERMANOV , I would like to work on this one.

**Comment by ILIYANGERMANOV** [comment]
Hey @AndroidPoet say the magic words from CONTRIBUTING. All issues are assigned automatically - you just need to say the words

**Comment by AndroidPoet** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @AndroidPoet! 🎉
Issue #1104 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
