### ISSUE TITLE
[FEATURES] Income categories

### ISSUE THREAD

**Issue by rezakelidari** [Ivy-Apps/ivy-wallet#1105]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to say this app should have income categories

### Why do you need it?

income categories like:
- Job income
- Rent received
- loan receive
- ...

**Comment by Aditya137x** [comment]
You can already add categories for Income
