### ISSUE TITLE
Saving Goals (savings account)

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#111]
**What do you want to be added or improved?**
As a user, I want to set and pursue savings goals.

**User Feedback:**
"Its a great app. Just hope they soon add a feature to pursue a certain amount of a saving goal. Or a savings account"

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- set savings goals and track their progress
- achieve something more than the current "Savings Goals" (savings buffer) feautre
- e.g. motivate to save for a TV/Vacation/Car etc

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- have Savings Accounts
- transfer money to my savings account

**Comment by jevo160296** [comment]
https://user-images.githubusercontent.com/73767449/173572466-d90ecbca-6346-4cfe-b40a-5ec6c288fb67.mp4

1. We can use the same idea used in the loans feature.
2. We add a saving goal and we can create a transaction from every time we add money to the goal.
3. This feature could beneficiate from the planned movements, we can add a recurrent planned movement to the saving account (The option will be available on the creation of the goal).

**Comment by MasonPorter** [comment]
Why is this not planned? This seems like an essential element to the app.
