### ISSUE TITLE
[FEATURE] Dynamically set amount of income/outcome based on interest percentage

### ISSUE THREAD

**Issue by nattadasu** [Ivy-Apps/ivy-wallet#1114]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have a feature for scheduled income/outcome in percentage based on current account balance due to daily/weekly/monthly interest rate given by bank. 

### Why do you need it?

- Some of Indonesian neobanks offer daily/weekly/monthly interest rates ranging from 6% to 8% p.a.
- By introducing this feature, account balance on both Ivy wallet and bank balance would be accurate or slightly accurate.

### How do you imagine it?

Similar on how planned income/outcome featured in app already, interest income should be accessible from the such menu and asks user if the interest has been deposited/withdrew from account manually, or can be added into account settings and automatically set the balance.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
