### ISSUE TITLE
Add haptic Feedback for numbers in expense entry and calculator 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1118]

**Comment by timmyCoder** [comment]
Has this been attended to? @ILIYANGERMANOV 
I'll like to take a look at it

**Comment by ILIYANGERMANOV** [comment]
Welcome back @timmyCoder! It hasn't been, feel free to have look 👍

**Comment by timmyCoder** [comment]
alright, I'm on it

**Comment by timmyCoder** [comment]
@ILIYANGERMANOV the project doesn't build on my laptop again, been a while, and I'm trying to remember how we fixed it last time

**Comment by ILIYANGERMANOV** [comment]
@timmyCoder you need Android Studio Dolphin +

**Comment by timmyCoder** [comment]
thank you
