### ISSUE TITLE
[Architecture] Migrate Home string resources from `:app-base` to `:home`

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#1128]
### What would you like to improve?

Architecture **[ADR#1: Modularization](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/develop/docs/architecture/ADR%231:%20Modularization%20(Passed).md)**.

**Goal:**  Simplify `app-base` and de-couple resources. 

$MODULE = `:home`
**How to:**
1. Find the strings that are used only in $MODULE
2. Create `res` folder in $MODULE
3. Create value folders for all locales:
- `value`
- `value-en`
- `value-it`
- ...
4. Move the strings used only in $MODULE to its newly created string resources folder.
5. Delete the strings resources from `:app-base` strings.
6. Run all tests and verify that everything works.

### Because...

- refactoring
- isolation
- reduces complexity 
- reduces coupling

**Comment by rubenquadros** [comment]
Hey @ILIYANGERMANOV, can I pick this up?
