### ISSUE TITLE
[IMPORT] MoneyWallet

### ISSUE THREAD

**Issue by Skril3366** [Ivy-Apps/ivy-wallet#1143]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Google PlayStore URL to the app from which you want to import

https://play.google.com/store/apps/details?id=com.oriondev.moneywallet&hl=en_US&gl=US

### Attach Samples CSV from the app

[MoneyWallet sample.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/9140320/MoneyWallet.sample.csv)

### CSV file requirements

includes Income type transaction, includes Expense type transaction, includes Transfer type transaction (optional), includes title, description, all attributes available in the app (optional)

### Is CSV export from the app free?

Yes

### Developer/Contributor Notes

- Checkout this **[Sample Commit](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/323ed68343a0904ee33f226480716a30368fd646)** to see how import CSV works in Ivy Wallet
- Make sure that the imported dates of the transactions are correct"

**Comment by yshalsager** [comment]
+1 for this, ivy seems promising and money wallet is no longer in development

**Comment by ILIYANGERMANOV** [comment]
You can try our "Manual CSV import" feature, fingers crossed that it works 🤞
