### ISSUE TITLE
Visual inconsistency on buttons [BUG] ...

### ISSUE THREAD

**Issue by Saikur0n** [Ivy-Apps/ivy-wallet#1148]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

There is a visual inconsistency in the buttons 'Add income' and 'Add expense' in the 'Accounts' section on the main screen of the app. Buttons text is not centered.

### To Reproduce

1. Just move to the Accounts section and enter into any of your account to see these buttons.

### Expected behavior

The text on the buttons should be centered.

### Smartphone

OnePlus 8, Android 12, OxygenOS 12.1

### Additional context

Screen resolution 1080x2400.

**Comment by ILIYANGERMANOV** [comment]
The UI isn't scaleabe, we'll rework it
