### ISSUE TITLE
Add quick settings title support

### ISSUE THREAD

**Issue by Zewar-G** [Ivy-Apps/ivy-wallet#117]
**What do you want to be added or improved?**
As a user I want to be able to add an expenses directly from the quick settings menu via a title directly.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- a_ it makes it easier and faster to enter the expenses.

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- a_ a title in the quick settings menu, i press it, and then this menu appears to me 
- 
![Screenshot_20211112-183552_Ivy_Wallet](https://user-images.githubusercontent.com/93976248/141492899-3ada5cc0-41ca-48dc-a2b8-fec45d502570.png)

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G that's an interesting one! Can you give us more details? How do you imagine in it as a flow?
1. Click plus buttonn
2. ...
3. so on

**Comment by Zewar-G** [comment]
> Hi @Zewar-G that's an interesting one! Can you give us more details? How do you imagine in it as a flow?
> 
> 1. Click plus buttonn
> 2. it works as a shortcut to this window, and then it continues to work normally
> 3. Just a fast way to reach the app faster and directly to the adding expenses menu

**Comment by StarHamster** [comment]
Did you mean a tile? Smth like this?
![image](https://user-images.githubusercontent.com/91747573/165269112-45bcba68-b515-4322-8771-2fddbf6f76f1.png)

**Comment by ILIYANGERMANOV** [comment]
> Did you mean a tile? Smth like this? ![image](https://user-images.githubusercontent.com/91747573/165269112-45bcba68-b515-4322-8771-2fddbf6f76f1.png)

Yes, I assume it's about this. Marked it as "good first issue"

**Comment by Aadhithya-D** [comment]
Hello @ILIYANGERMANOV , I am new to this repo, can I take up this issue/feature? Thank you!!

**Comment by ILIYANGERMANOV** [comment]
> Hello @ILIYANGERMANOV , I am new to this repo, can I take up this issue/feature? Thank you!!

Ofc, @Aadhithya-D assigned it to you
