### ISSUE TITLE
[FEATURES] Custom CSV Export

### ISSUE THREAD

**Issue by Aarekaz** [Ivy-Apps/ivy-wallet#1181]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user, I want to be able to import CSV transaction data exports from my banks/wallets or any other app that is not supported. 

### Why do you need it?

- Helps to import transactions even if the app is not supported
- Dev will also have to focus less on adding more app integrations if there is a specific standard to import. 

### How do you imagine it?

- A set of guidelines that explains the format in which the CSV must be. ( I can help in writing the documentation and guidelines  for the format)
- A option in the import section of the app which lets a user select a CSV file from their storage. 
- A quick view of the data to be imported so that the user can verify it's correct.

**Comment by guitarhero22** [comment]
It will be very helpful
