### ISSUE TITLE
Make a FAQ for customers

### ISSUE THREAD

**Issue by snowboulder** [Ivy-Apps/ivy-wallet#1190]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What would you like to improve?

- I want to create the FAQ section for customers so that customers are more supported when they have questions or issues. 
- Redirect customers questions and inquiries to the FAQ
- FAQ link can be added to App Settings

### Because...

- A lot of questions seems to be unanswered in the Ivy Telegram chat or repeatedly asked
- Support customers when they need help

### Other

The FAQ will significantly reduce the number of questions and inquiries that is asked in the Ivy Telegram chat. This improves the quality of customer support and the quality of the discussions in the chat.

**Comment by snowboulder** [comment]
I want to work on this, however, the Help Center is in the Wiki, and not part of the repository. That means I cannot fork and clone this. 

Please advice on how to work on this and contribute.

**Comment by ILIYANGERMANOV** [comment]
That's a good one! We can create a `docs/FAQ.md` in the repo
