### ISSUE TITLE
Complete the Help Center Section

### ISSUE THREAD

**Issue by snowboulder** [Ivy-Apps/ivy-wallet#1191]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What would you like to improve?

- Complete the Help Center Section in Wiki

### Because...

- Guides customers on how to use Ivy Wallet
- Help customers discover features
- Answer some of customers' questions and issues

### Other

The Help Center can be the User-Friendly Guide/Documentation for customers who want to learn how to use Ivy Wallet to its full potential. Every app needs a guide/documentation that users can search through to help themselves.

**Comment by snowboulder** [comment]
@ILIYANGERMANOV I want to work on this, however, the Help Center is in the Wiki, and not part of the repository. That means I cannot fork and clone this. Can you let me know how you want to go about this? I can make a draft of a Help Center and send it to you, or you can let me know how I can upload this to the Wiki.

**Comment by ILIYANGERMANOV** [comment]
Hi @snowboulder that's really cool! You can share a Google Docs with me and I'll be happy to update it :)

**Comment by snowboulder** [comment]
@ILIYANGERMANOV that works for me. I'm on it.

Since this isn't on the repository and external, is there a way for me to get contribution records like merged PRs?

**Comment by ILIYANGERMANOV** [comment]
You  create Markdown files in `/docs` this way would be better - both contribution and usability 👍

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV that works for me. I'm on it.
> 
> Since this isn't on the repository and external, is there a way for me to get contribution records like merged PRs?

Hey @snowboulder the `/docs` is on the main repo so when we merge your PR in `main` you'll be listed as an Ivy Wallet contributor and your merged PR will be visible.
