### ISSUE TITLE
[DEV] Building a API to make it users to submit language contribution

### ISSUE THREAD

**Issue by Aarekaz** [Ivy-Apps/ivy-wallet#1203]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What would you like to improve?

- A basic website that gets the data from Ivy translations file and a basic text field to add the corresponding language translation
Once the translations are added an XML can be generated so that it can be directly added to the codebase .

### Because...

Currently, no such website exists and it is quite a task to submit simple translations.

### Other

Will be building this using Python and REST API. Will take some time.

**Comment by Aarekaz** [comment]
I will be working on this

**Comment by ILIYANGERMANOV** [comment]
Out of scope
