### ISSUE TITLE
[BUG] edit planned payments while overdue

### ISSUE THREAD

**Issue by Pkcarreno** [Ivy-Apps/ivy-wallet#1206]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

I experienced a bug related to overdue planned payments. 
Editing the amount of a planned payment from the planned payments screen (which was due at the time of the error) tripled the list of overdue planned payments (in my case I had 2 overdue planned payments and they became 6 repeating the two that were originally due).

### To Reproduce

1. have 2 planned payments overdue
2. go to the planned payments screen and edit the amount in one of the planned payments that is currently overdue and save the changes
3. when you return to the main screen the list of overdue planned payments will have tripled.

### Expected behavior

expected the same 2 planned payments to be overdue but with one of them with a different amount.

### Smartphone

Xiaomi Redmi Note 9S, Android 11

### Additional context

This is the first time I edit a planned payment, in this case the planned payment I edited was overdue in the current month.

**Comment by ILIYANGERMANOV** [comment]
Can you please add a screen recording?

**Comment by Pkcarreno** [comment]
Hey @ILIYANGERMANOV, I am able to recreate the error yet, but I have not managed to start the app in the emulator to test but I understand the problem better.

The overdue payments are not "tripled" but when editing a planned payment all the previous months are displayed from the first day of the start of that planned payment.

In this way the only condition to recreate the error is to have planned payments that started several months (or cycles) ago and to have skipped or paid them, when you edit any data of that planned payment then it is saved as new from the start date and all the planned payments (due) appear from the start date of the same.

I would like to show you a video about it but I can only recreate it with my data and there is not much privacy here, and I have not had time to install android studio beta yet.
