### ISSUE TITLE
Expenses In Calendar And A Bar Chart

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1233]
The app must show a calender in which below each day our expense is shown and a bar chart  representation of how much we spend in a day, week, month without category.

**Comment by master-coding** [comment]
![Screenshot_20220822_072033.jpg](https://user-images.githubusercontent.com/67449082/185823443-2af0b403-be55-4b5e-a8b1-aecf9cf6b9bd.jpg)

**Comment by Pkcarreno** [comment]
I thought about using the calendar but for planned payments, integrate them into the phone's calendar app, so they can be used with the widgets of this and remember them more easily, this is especially useful for those who use the calendar a lot (my case)
