### ISSUE TITLE
[IMAGES] Add the ability to attach images to transactions

### ISSUE THREAD

**Issue by code-a1** [Ivy-Apps/ivy-wallet#1241]
All issues requiring the ability to attach images to transactions will be linked here.

**Comment by StarHamster** [comment]
Hello, @code-a1

Let's keep linking such issues with #6. And I would like to ask if I may close all the duplicate issues as not planned or you have other plans for them 🤔

![image](https://user-images.githubusercontent.com/91747573/185997815-44558d08-4d3c-42b5-9bc1-cf25d4026bed.png)
