### ISSUE TITLE
[BUG] App doesn't calculate BNB value in fiat

### ISSUE THREAD

**Issue by Quernest** [Ivy-Apps/ivy-wallet#1254]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

App doesn't calculate BNB value in fiat (USD, EUR, etc.) at the current exchange rate. Is it a known issue?

### To Reproduce

1. create account in BNB (currency in settings is USD)
2. set value (for example 1)
3. there is no calculated value in USD

### Expected behavior

I want to see what is the value of BNB in fiat (USD)

### Screenshots

![photo_2022-08-27_22-11-12](https://user-images.githubusercontent.com/21086792/187044793-784f798a-3070-4197-a0d0-d23bd20ba972.jpg)

### Smartphone

Google Pixel 4a, Android 13

### Additional context

Nice app, thank you :)

**Comment by ILIYANGERMANOV** [comment]
You're base currency shouldn't be BNB or it failed to fetch rates
