### ISSUE TITLE
Ability To Set Negative Balances

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1256]
I am trying to set one of the accounts as a credit card and then want to show negative balance in that account so that my total on the home screen shows the net. Right now I can only enter positive values in accounts. Which prevents me from entering credit cards

**Comment by afgveloso** [comment]
I was going to ask exactly the same, so I would like to emphasize this.

**Comment by afgveloso** [comment]
Reading comments found out the solution: when setting the initial value, use the calculator and just enter 
0 - amount
