### ISSUE TITLE
Removing Loans from loan section doesn’t remove from account

### ISSUE THREAD

**Issue by avinal** [Ivy-Apps/ivy-wallet#1288]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

I have added some loans in the loan section and marked as main transaction. When I delete them from the loan section the transaction is not removed from the accounts.

### To Reproduce

1. Go to settings->loans
2. Add a loan and mark as main transaction 
3. Remove the loan
4. Check account transaction 
5. The loan is not removed 

### Expected behavior

I would expect that the loans are removed from the accounts as well. Or in other case there must me an option to remove main transaction while deleting the loan.

### Smartphone

Pixel 4a, Android 13

**Comment by ILIYANGERMANOV** [comment]
Loans are broken, we'll rework them
