### ISSUE TITLE
Loan repayment Period 

### ISSUE THREAD

**Issue by missyraja** [Ivy-Apps/ivy-wallet#1292]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to know how many day there are left and how much i need to save per day,week to finish my Loan

### Why do you need it?

- Need the Loan categories to display no of days to due date with how much i need to save per day or week

### How do you imagine it?

![Screenshot_20220911-154854](https://user-images.githubusercontent.com/40870763/189522451-1df6ab93-c7d1-41ad-8b77-935783e56415.png)
This app uses this functionality and it is really helpful

**Comment by ILIYANGERMANOV** [comment]
Out of scope
