### ISSUE TITLE
[FEATURES] ...

### ISSUE THREAD

**Issue by Zakariyya-47** [Ivy-Apps/ivy-wallet#1333]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have an ios app

### Why do you need it?

- I just bought an ios and sadly i cant use the app and must find something similar which soo far isnt going well

### How do you imagine it?

not sure how the implementation would work

**Comment by code-a1** [comment]
Duplicate of #81
