### ISSUE TITLE
Link Loan tag to Loan page

### ISSUE THREAD

**Issue by Abbaskt** [Ivy-Apps/ivy-wallet#1387]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I would want that when I input a transaction as loan, it should automatically be adding to loans section. This eliminates the process of manually adding the same transaction at both places.

### Why do you need it?

- Easier process to input loans
- Elimination of duplicate workflow

**Comment by ILIYANGERMANOV** [comment]
Out of scope for now
