### ISSUE TITLE
Flutter version iOS/Android (cross platform )

### ISSUE THREAD

**Issue by braysonjohn148** [Ivy-Apps/ivy-wallet#1412]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user, I want to get the app working on multiple os.

### Why do you need it?

- Build a flutter version

### How do you imagine it?

iOS and Android

**Comment by nferdazel** [comment]
I'm leaving my mark here to see the progress. Thank you.

**Comment by myounus96** [comment]
Following

**Comment by ILIYANGERMANOV** [comment]
For now, it'll be Android only. Our best chance for multiplatform is Kotlin & Compose Multiplatform
