### ISSUE TITLE
Add category to account transfer

### ISSUE THREAD

**Issue by husseinaltaaf** [Ivy-Apps/ivy-wallet#142]
**What do you want to be added or improved?**
As a user I want to request a new feature to be able to add catergory to my account transfers. Currently its being categorised as Unspecified.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [ ] No, it's a new issue.
- [x] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- Well its better so i can categorised my expense along with a transfer

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- be able to add for e.g a catergory where i did a transaction but was refunded.
- So by adding the transfer to that category, my budgets will stay untouched

**Comment by Marshwiggle1** [comment]
I am just using the app for the first time. I'd like to set up repeat transfers. I transfer money each month to saving accounts, so they are outside of my daily spending. 
Also I have a percentage taken out of my wage once it is deposited which goes toward tax at the end of the year, I am not sure how to manage this as its not a dollar amount. I'm sure others might use this method to save money so it might be something to include.
