### ISSUE TITLE
Limited number of occurrencies for planned expenses

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#143]
I'd like to have the possibility to set in advance the number of times that a planned expense will repeat (i.e. every month BUT for the next 5 months. Then, stop)

**Comment by ILIYANGERMANOV** [comment]
Add "endDate" to Planned Payments + UI to calculate endDate based on number of occurrences

**Comment by ccrowles** [comment]
Is this still not a priority/not planned in the near future? Asking because now that PayPal allows 3-monthly payments too this is probably a very important feature for a lot of people (myself included).
