### ISSUE TITLE
Viewing future assets/value after a certain time

### ISSUE THREAD

**Issue by husseinaltaaf** [Ivy-Apps/ivy-wallet#146]
**What do you want to be added or improved?**
As a user I want to be able to view how much assets/value i will have after an specified time

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- I wish to know how much money I will have after an specified time.
- It will be easier to manage my future expenses.
- I will be able to know if next month or the month after I will have enough money to invest in a new thing.

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- have a screen with all future transactions & transfers applied
- see total amount of money that I will have from all my account (checked 'included in balance') in that month will be displayed

**Comment by ILIYANGERMANOV** [comment]
Hi @husseinaltaaf try clicking on your balance in the "Home" screen. There you can see "BALANCE AFTER PLANNED PAYMENTS" and you can switch the time period to observe the future.

What more can we add to this screen to make it better?
- a
- b
- c
- d

**Comment by husseinaltaaf** [comment]
Okay sorry, I didn't see that. Hmmm i think there is a bug though:
- Selecting a month (not the next month) in the future it will simply calculate my current balance added to that selected time's balance instead of the balance from the previous month added to the balance of that selected time

Expected behavior
- It should calculate the balance from today until that selected month.
- For e.g right now i am trying to see in december how much money i will have in total it just takes my current balance and add it to the balance that it will be in the month of december not taking into account the transactions from today till 31th november.

What more can we add to this screen to make it better?
- List of ALL transactions (past/future) happened for the balance to be at an amount.

**Comment by ILIYANGERMANOV** [comment]
Thank you @husseinaltaaf! That's a great idea :) This way the people can see why the app predicts that balance.

**Comment by ILIYANGERMANOV** [comment]
This feature definitely needs improvement. Currently, it do:
- BALANCE_AFTER_PLANNED = CURRENT_BALANCE + PLANNED_PAYMENTS_AMOUNT (salary - expenses)

```kotlin
     val plannedPaymentsAmount = ioThread {
                plannedPaymentsLogic.plannedPaymentsAmountFor(period.toRange(ivyContext.startDayOfMonth)) //+ positive if Income > Expenses else - negative
            }
      _plannedPaymentsAmount.value = plannedPaymentsAmount

      _balanceAfterPlannedPayments.value = currentBalance + plannedPaymentsAmount
```
