### ISSUE TITLE
Change transaction date & time UX

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#15]
Currently, to change a transaction's time you have to first select a date (the preselected is today which is wrong) and then select a time. This is a bad user experience.

**Solution:**
Have different click events for Date & Time.

**Tips:**
- use ivyContext.datePicker {}
- use ivyContext.timePicker {}

**Comment by illutic** [comment]
I'm on it! 😄

**Comment by rubenquadros** [comment]
Can this be closed? I see that there is already a PR merged?

**Comment by ILIYANGERMANOV** [comment]
Yup, thank you!
