### ISSUE TITLE
[FEATURES] Scheduled/Automatic local data export/ backup 

### ISSUE THREAD

**Issue by Aritzherrero4** [Ivy-Apps/ivy-wallet#1514]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

Now that the cloud backend is shutting down, managing backups can be a bit complicated if a manual export is required. It would be really nice to be able to scheduled (daily, weekly, ...) data exports as .zip to a user selectable directory.

This makes it easier to keep a regular backup and it's less probable to lose data if something goes wrong.

### Why do you need it?

- No cloud backup to keep data safe.
- This guarantees a regular backup
- Destination directory can be easily synced to cloud providers or locally with apps like syncthing.

### How do you imagine it?

I imagine the feature as two new entries in settings. 
One of the entries would be a toggle to enable/disable the periodic backup. And the other to select the time between backups.

Another option is to implement only the time selector and add an option for "never" that will act as disabling the backup.

The setup process of the app could prompt the user to enable the backup too. So new users will be able to easily configure it.

**Comment by chall3ng3r** [comment]
Visited repo for posting same feature request with added option to make it a rolling backup, like keep last 7 backups and remove old ones automatically. It will make it simple to manage with alos like syncthing or Resilio.

**Comment by ILIYANGERMANOV** [comment]
We've implemented GitHub auto backups
