### ISSUE TITLE
[BUG] ... issue with transfer records when importing from csv

### ISSUE THREAD

**Issue by myounus96** [Ivy-Apps/ivy-wallet#1629]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Importing CSV from wallet by budgetbackers treating transfers as separate category. I also confirmed the toggle is off in settings. Also confirmed when exported from budgetbackers 'account transfer include' is checked.

### To Reproduce

1. Create transfer record in wallet by budgetbackers, export the csv and import that to ivy.

### Expected behavior

It should treat transfers as transfer in ivy as well.

### Screenshots

NA

### Smartphone

Samsung A32

### Additional context

NA

**Comment by ILIYANGERMANOV** [comment]
Use "Manual CSV import", out of scope
