### ISSUE TITLE
Link To Online Banking

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1642]

**Comment by NikolaSivkov** [comment]
One of the most popular API for banking is : https://www.saltedge.com/
used by 2 of the most popular apps on android already

**Comment by ILIYANGERMANOV** [comment]
And it costs a lot! I researched it before and we can't afford it although it's a nice API.

**Comment by NikolaSivkov** [comment]
If it's a paid feature, i'm willing to pay for it, and I already am for budgetbakers (logo is on saltedge website even).
This doesn't stop this app being opensource, but having bank transactions be a paid feature :)
