### ISSUE TITLE
Cross fade transition on tab switching on main screen

### ISSUE THREAD

**Issue by javedh-dev** [Ivy-Apps/ivy-wallet#1658]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Is the project building?

Yes

### What would you like to improve?

- Currently on main screen tabs are switching without animation. there should be some transition animation to simulate switching

### Because...

Without animation that switch looks very plain.

**Comment by javedh-dev** [comment]
I am on it

**Comment by ILIYANGERMANOV** [comment]
Stale, we'll redesign the Home navigation anyway
