### ISSUE TITLE
Track Credit/ Debit/ prepaid Card transactions using SMS

### ISSUE THREAD

**Issue by Kop3sh** [Ivy-Apps/ivy-wallet#1670]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to track my cards spending using SMS parsing

### Why do you need it?

- because often times card transaction doesn't get tracked (forgotten)
- decrease friction, by decreasing the time it takes to add transactions

### How do you imagine it?

1. Give access for SMS
2. Develop a smart enough algorithm to parse SMS text from the bank
The bank name, card ending in XXXX and its corresponding account, transaction amount, possibly parse the merchant (category if possible)
3. Display a notification to show the newly added transaction and any possible edits/ confirmation.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
