### ISSUE TITLE
[FEATURES] Changing account currency

### ISSUE THREAD

**Issue by markisha64** [Ivy-Apps/ivy-wallet#1680]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to change my account currency without an adjust balance. 

### Why do you need it?

I live in Croatia and we just changed from HRK to EUR. Changing account currency isn't a problem but doing it forces you to adjust balance which just looks bad. It would be very nice to be able to change currency without an adjust balance.

### How do you imagine it?

Making it similar to the screen from account transfer between accounts of different currencies would be very nice and it would make a lot of sense.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
