### ISSUE TITLE
translate to my language 

### ISSUE THREAD

**Issue by herotux** [Ivy-Apps/ivy-wallet#1688]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to translate app to other languages
Just show me a way to do it

### Why do you need it?

-

**Comment by Pkcarreno** [comment]
Currently you can translate the app

The text below is by @StarHamster 
>You will find all the necessary information [here](https://elastic-burglar-ec5.notion.site/How-to-translate-Ivy-Wallet-c20256f024a7448a96c2e13fed84d170) or you can just watch [this video](https://www.youtube.com/watch?v=LXbpsBtIIeM&t=139s) (starts on 2:20)

And [this](https://github.com/Ivy-Apps/ivy-wallet/issues/342) is the issue with all the translations, but it is outdated, actually there are more translations completed

**Comment by ILIYANGERMANOV** [comment]
Stale
