### ISSUE TITLE
[BUG] Updating Category data bug

### ISSUE THREAD

**Issue by Hazaaa** [Ivy-Apps/ivy-wallet#1702]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I've found small bug where when you go to any category and then update any of its data (icon or name), all expenses listed below will still have old name or icon.

### To Reproduce

1. Go to any category
2. Change icon or name
3. Check expenses below - they show old name/icon

### Expected behavior

It should update icon/name of category to all expenses listed in that category.

### Smartphone

Samsung Galaxy S21 FE, Andoid 13

**Comment by ILIYANGERMANOV** [comment]
Hey @Hazaaa does restarting the app fix the bug?
