### ISSUE TITLE
[FEATURES] Add wearOS compatible app

### ISSUE THREAD

**Issue by Propo41** [Ivy-Apps/ivy-wallet#1705]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

It would be really nice to have a wearOS version of the app for smart watches

### Why do you need it?

- add transactions directly from the watch without bringing out my phone every time

### How do you imagine it?

Maybe just an interface to add a transaction. Nothing bulky. Just a GUI to add a transaction and a category and it will get updated in the mobile app.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
