### ISSUE TITLE
[Feature] Change app language from "Settings"

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#1740]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to be able to change Ivy Wallet's app language to any language supported by the app.

### Why do you need it?

- No need to change the entire device's language. 

### How do you imagine it?

- Language button in Settings
- when clicked a modal with all available translations shows
- click the Language => the app restarts in the new language

**Comment by Min-Jae-Bae** [comment]
Hi @ILIYANGERMANOV , I would like to contribute to this too.

**Comment by ILIYANGERMANOV** [comment]
@Min-Jae-Bae thank you! Feel free to implement that issue. One contributor also mentioned that would help: https://developer.android.com/guide/topics/resources/app-languages
