### ISSUE TITLE
[FEATURE] Override and create new exchange rates in the new Ivy Wallet

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#1769]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to add new custom exchange rates and edit existing ones.

### How do you imagine it?

Replicate the settings exchange rates functionality from the prod app.

1. Create `:exchange-rates` module
2. Use `RatesDao`
3. Use the stuff from `:core` modules (there's a modal for settings exchange rate)

![photo_2023-01-20_15-26-28](https://user-images.githubusercontent.com/5564499/213705623-4563ad34-b1c1-4150-9cc7-52051952b442.jpg)

**Comment by stetimi** [comment]
This looks like it's already done? I see a screen on the beta app.

**Comment by shashank-0-0** [comment]
I don't see the exchange rates functionality in the develop branch..Should it be implemented? If yes, then i would like to do it

**Comment by ILIYANGERMANOV** [comment]
Yes, feel free to give it a try if you want :)
