### ISSUE TITLE
[TRANSLATION] Spanish

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#179]

**Comment by Pkcarreno** [comment]
Hello

@ILIYANGERMANOV  Thanks for closing the other issues.

I would like to help you with the Spanish translations, if you can provide some structure to manage languages, I will gladly do my part with the Spanish

Sorry for not being able to help more, I don't work with kotlin or native app development, so I can't help much, but I'm excited about the project and I want to collaborate.

**Comment by StarHamster** [comment]
@Pkcarreno, hi!

I think it's the coolest project too! Thanks for your desire to help! We are preparing some things to the application can be translated. I think the opportunity will appear soon!

But for now I need your help: #281 is about Spanish too. Am I right?

**Comment by Pkcarreno** [comment]
@StarHamster, Hi!

I am happy to hear that things are being prepared to be able to translate the app, I will be waiting to do my part with Spanish


> But for now I need your help: https://github.com/ILIYANGERMANOV/ivy-wallet/issues/281 is about Spanish too. Am I right?

Yes, https://github.com/ILIYANGERMANOV/ivy-wallet/issues/281 is about the Spanish translation too

**Comment by StarHamster** [comment]
@Pkcarreno, hello!

Now, it is possible to translate the app. But it's still not very convenient to do and require Android Studio 😭

You will find all the necessary information [here](https://elastic-burglar-ec5.notion.site/How-to-translate-Ivy-Wallet-c20256f024a7448a96c2e13fed84d170) or you can just watch [this video](https://www.youtube.com/watch?v=LXbpsBtIIeM&t=139s) (starts on 2:20).

We'll work for a more user-friendly translations mechanism in future. And remember that we are always ready to help here or in our [Telegram Community](https://t.me/+ETavgioAvWg4NThk).

**Comment by Pkcarreno** [comment]
@StarHamster , Hi!

This is great news! Don't worry, I don't have android studio since I managed to install just the emulator via cli tool (I'm a react native developer, and vscode suits me better). However if necessary I will install it.

Thank you very much for all the work done to make the translations possible.

I'm going to do my part now.

**Comment by jevo160296** [comment]
Hi, @Pkcarreno I'm also a Spanish speaker, yesterday I started to translate the app, I haven't finished it yet, but of you like we can do it together, I can start from bottom to up and we can meet in the middle.

**Comment by Pkcarreno** [comment]
@jevo160296, hi!

I'm working in it. I've been a bit busy at work this week. I'm about 70% complete and I planned to finish it today.

however, if you could test it and review the translations if they seem correct, you would help me a lot with that feedback.
let me know if you want to help me test it and as soon as I upload the changes I'll tag you so you can have them.

**Comment by jevo160296** [comment]
Sure! I can review the translations and give you feedback.

**Comment by Pkcarreno** [comment]
@jevo160296, Hi!

I already created the pull request of the translations, you can check them here https://github.com/ILIYANGERMANOV/ivy-wallet/pull/865.

I tested the application, and the translations are being seen properly. please check if you find the terms suitable or have any suggestions for another word or phrase to use.

Thank you very much
Best regards
