### ISSUE TITLE
I'd like to be able to enter negative expenses

### ISSUE THREAD

**Issue by stetimi** [Ivy-Apps/ivy-wallet#1813]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to enter a negative expense.

There's no way of directly entering a negative number as an expense as far as I can see. 
I tried entering the calculator view and 0 - 100 which gave a negative number, but when I clicked the enter button nothing happened.

### Why do you need it?

- To represent a refund of (all or part of) a previous expense.

### How do you imagine it?

A - key on the expenses entry screen.

**Comment by stetimi** [comment]
Perhaps add a toggle on the expense entry dialog: expense/rebate.

**Comment by ILIYANGERMANOV** [comment]
You can enter an income for the refund or delete the expense
