### ISSUE TITLE
How hard is it to build an IOS version of this app?

### ISSUE THREAD

**Issue by realtechz** [Ivy-Apps/ivy-wallet#1816]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to use it on iphone and android at same time in sync. 

### Why do you need it?

- If you can guide me with resources, I would love to help build a IOS version of it.

**Comment by ILIYANGERMANOV** [comment]
I want it on Desktop, too! We bet on Kotlin and Compose multiplatform but I'm a solo developer most of the time => the answer is very very hard.

Also, bear in mind that Ivy Wallet is a side/hobby project that I work on in my free time because I can't make a living out of it.

**Comment by realtechz** [comment]
I appreciate your time and effort 🙂. Thanks for creating it for Android! 

I am not a mobile application developer , but I think I can work on IOS version of it in the coming weeks. ( I will let you know)
Anyways keep up the good work!

**Comment by ILIYANGERMANOV** [comment]
Our best hope is Kotlin Multiplatform but that's currently out of scope
