### ISSUE TITLE
Can you please add a setting option to switch off time and just keep date while adding an record.

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1843]

**Comment by stetimi** [comment]
I find it inconvenient to have to set the time after setting the date. Perhaps they could be set together in the same dialog, with the time defaulting to "now".

**Comment by ILIYANGERMANOV** [comment]
In the new Ivy Wallet, the date and time will be set separately => if you don't want to set the time, it'll default to now.
