### ISSUE TITLE
[FEATURES] Posibility of importation a formula for exchange rates

### ISSUE THREAD

**Issue by matemonta97** [Ivy-Apps/ivy-wallet#1858]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to import a formula like =VALOR(SUSTITUIR(REGEXEXTRACT(INDICE(IMPORTDATA("https://api.binance.com/api/v3/ticker/price?symbol="BTCUSDT);1;2);"[\d.]+");".";",")) 

I use this in Excel to know the btc value in usdt

### Why do you need it?

- Because in Argentina the exchange rate change every time and is difficult keep this updated in the app

### How do you imagine it?

I imagine that when i set the usdt (as example) exchage rate i can use a formula instead of a value. You can place it in an input in a side o something like that. 
Thanks.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
