### ISSUE TITLE
Show Current Remaining Amount With Every Transaction, We Have This Feature In Budget Bakers App

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1888]

**Comment by myounus96** [comment]
Hi @ILIYANGERMANOV I see you marked this as completed, but actually we really don't have this feature in ivy, sharing snapshot from wallet by budget backers and ivy.
ivy: ![image](https://github.com/Ivy-Apps/ivy-wallet/assets/13608139/75748741-7797-49ca-980e-f63be5651bd2)
wallet by budget backers: ![image](https://github.com/Ivy-Apps/ivy-wallet/assets/13608139/6e60b5b1-4fbe-4bb0-8aaf-463f17bedcdc)

You can see in wallet by BB, the _-15k_ is expense, the green _38k_ is amount before expense, they show this for every transaction and every account. This is actually so much helpful.

I actually explored the code but unable to understand where I need to make changes( a backend dev here), if you can help/give some context/hints in which module I need to do this I can raise the PR, gut feelings are its not that much complex. Thank you.

**Comment by ILIYANGERMANOV** [comment]
@myounus96 it was auto-closed because of lack of activity

**Comment by myounus96** [comment]
@ILIYANGERMANOV its closed again as not planned, can you please reopen and plan it? Thanks

**Comment by myounus96** [comment]
Hi @ILIYANGERMANOV sorry to ping you again, reminder on the above.

**Comment by myounus96** [comment]
_I actually explored the code but unable to understand where I need to make changes( a backend dev here), if you can help/give some context/hints in which module I need to do this I can raise the PR, gut feelings are its not that much complex._
