### ISSUE TITLE
[FEATURES] Resize Add Expense Keypad to Fit Screen

### ISSUE THREAD

**Issue by aphilas** [Ivy-Apps/ivy-wallet#1890]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to enter an expense's amount without scrolling to use the last row of buttons on the keypad.

<details>
<summary>
View screenshot
</summary>

![Screenshot_20230212-045656_Ivy Wallet](https://user-images.githubusercontent.com/31406314/218289174-c040727a-c965-44bd-8d00-0dfe9d1c2f19.jpg)

</details>

### Why do you need it?

Makes adding transactions a lot faster

### How do you imagine it?

Resize the keypad button size and reduce the padding in order to fit the page contents on one screen.

---

### Device info

Model number - SM-J727S

**Comment by Shreyachauhan0303** [comment]
Hi, I am new to open source. I want to contribute to your project. Can you guide me on which file I should look for this issue?

**Comment by ILIYANGERMANOV** [comment]
Hey @Shreyachauhan0303 assigned to you. Read the CONTRIBUTING md file. For this issue, it's the legacy code. View AmountModal
