### ISSUE TITLE
[FEATURES] Collapse Smart Suggest

### ISSUE THREAD

**Issue by aphilas** [Ivy-Apps/ivy-wallet#1947]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to collapse suggested titles.

### Why do you need it?

- Edit the date of a transaction without having to scroll through the length of the suggestions

### How do you imagine it?

A small button icon with an arrow just below the title field. The app should remember the collapse choice.

**Comment by divyansh169** [comment]
Hi,
I am new to open source. I want to contribute to your project. Can you guide me on which file I should look for this issue?

**Comment by ILIYANGERMANOV** [comment]
> Hi, I am new to open source. I want to contribute to your project. Can you guide me on which file I should look for this issue?

Read CONTRIBUTING md from repo. @divyansh169

**Comment by priyatanu** [comment]
Hi @ILIYANGERMANOV , i can work on this issue ?

**Comment by ILIYANGERMANOV** [comment]
Say the magic words, it's not taken

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

**Comment by priyatanu** [comment]
I'm on it
