### ISSUE TITLE
[FEATURES] Option to display BTC currency as Satoshis (sats)

### ISSUE THREAD

**Issue by sonalder-darlene** [Ivy-Apps/ivy-wallet#1949]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a Bitcoiner I want to track my spending in BTC currency this is possible. However many of my transactions are small and so displaying BTC as Sats would be more conveniant for me.

### Why do you need it?

I'm using more and more Bitcoin in my life

### How do you imagine it?

An option to choose between displaying price bitcoin or sats.
100'000'000 sats = 1 bitcoin so it's just divide this value by 100 millions so should be easy to implement

**Comment by ILIYANGERMANOV** [comment]
Out of scope

**Comment by sonalder-darlene** [comment]
Sorry but as someone that is using Bitcoin on a weekly basis I would rather note my spends in sats as it's how I see my spending and saving. It's way easier to put 26'000 sats rather than 0.00026 BTC. Sorry not to be rich I guess

**Comment by ILIYANGERMANOV** [comment]
> Sorry but as someone that is using Bitcoin on a weekly basis I would rather note my spends in sats as it's how I see my spending and saving. It's way easier to put 26'000 sats rather than 0.00026 BTC. Sorry not to be rich I guess

I understand and it makes sense for you, unfortunately very few people have that use case. You can the base currency of the app to BTC but it won't be sats. I'll re-open it in case a contributor wants to implement it.
