### ISSUE TITLE
Hide transactions

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2]
USES-CASES:
- As a user, I want to be able to hide transactions so they don't appear in the transaction history and as income/expenses
- As a user, I want to be able to see all hidden transactions
- As a user, I want to be able to unhide a transaction
- As a user, I want to be able to filter hidden transactions in "Reports"

**Comment by ILIYANGERMANOV** [comment]
Say the magic words from CONTRIBUTING to take the issue. @divyansh169 
Regarding file, have a look at `TransactionEntity`

**Comment by divyansh169** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @divyansh169! 🎉
Issue #2 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
