### ISSUE TITLE
[BUG] UI Misalignment

### ISSUE THREAD

**Issue by MuftiAnees** [Ivy-Apps/ivy-wallet#2037]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The Calendar button and The drop down buttons are overlapping on my device. It is consistent and to reproduce I just have to open up the application and log in using the Fingerprint.

### To Reproduce

1. Open up the app.
2. Authenticate using Fingerprint Scanner.
3. Arrive at home screen and on the top right corner the items overlap

### Expected behavior

The UI elements should not overlap and display next to each other.

### Screenshots

![Screenshot_2023-03-16-12-45-58-231_com ivy wallet](https://user-images.githubusercontent.com/89216202/225549532-c3b0389e-6aff-4195-bb15-428ca7c357a0.jpg)

### Smartphone

Xiaomi Redmi note 11, Android 12

### Additional context

The phones MIUI version is 13.0.7 stable (I personally don't think this matters but the more info the better)

**Comment by MuftiAnees** [comment]
![Screenshot_2023-03-16-12-45-58-23_com ivy wallet](https://user-images.githubusercontent.com/89216202/225552266-7608f28d-dddb-43d9-879c-a4278bcb0ed1.jpg)


Screenshot with the Issue Highlighted.

**Comment by ILIYANGERMANOV** [comment]
**Solution:**
- Cut the user's name using "..."

**Comment by FielderNik** [comment]
i'm on it

**Comment by ILIYANGERMANOV** [comment]
Fixed by https://github.com/Ivy-Apps/ivy-wallet/pull/2639 Thank you @FielderNik!
