### ISSUE TITLE
(Request) F-Droid

### ISSUE THREAD

**Issue by tokenmath** [Ivy-Apps/ivy-wallet#2049]
Since it is an open project, why not include it in the F-Droid app platform?

**Comment by ILIYANGERMANOV** [comment]
I'm happy to do so! If someone can create a GitHub Action workflow to upload it to FDroid - let's do it!

**Comment by ILIYANGERMANOV** [comment]
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/104

**Comment by CodeCubeNeo** [comment]
Any updates on this?

**Comment by ILIYANGERMANOV** [comment]
#104 this is the open-ticket; no contributors want to work on it so far :/
