### ISSUE TITLE
[BUG] Upon removing account, all planned and paid payment stuck on dashboard and thus affecting budget and calculation. How do i remove/rest my back from the App or at least remove all payments related to a deleted account.

### ISSUE THREAD

**Issue by ItsAFBs** [Ivy-Apps/ivy-wallet#205]
**Is the project building?**
Yes/No

**What would you like to improve?**
I want to:
- a
- b
- c
- d

Because:

- e
- f
- g

**Other**
Share your thoughts in free format.

**Logs**
Share any logs or information that might help us resolve your issue faster.

**Comment by ILIYANGERMANOV** [comment]
Hi that shouldn't happen. I'm investigating and can't reproduce it :/ 

- Can you send us screen recording / screenshots so we can reproduce it?
- Steps to reproduce would be extremely helpful
- Are you using Ivy Wallet on multiple accounts?
