### ISSUE TITLE
Budget Chart Monthly Overview

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#2114]
Display monthly income and expenses in a chart that show how much income increased/decreased over months. To be like a graph to easily figure out how much a month added to your overall budget.

**Comment by Chandra-Mauli-Sharma** [comment]
Hello @ivywallet, can you please assign this issue to me? I would like to work on it. Thank you!

**Comment by aymanyounis** [comment]
Thanks for the great app and picking this issue. 

To be more pressie with how I imagine the chart, it should be a chart showing monthly income, expenses and profit.

It could be more advanced and complex to show even charts per filter (for each account and period for example).

Here are some examples:
![images (2)](https://user-images.githubusercontent.com/7750693/230820616-60cf4b38-a6f5-4670-b4d1-b921cdf388a4.jpeg)
![images (1)](https://user-images.githubusercontent.com/7750693/230820621-bd9e7ebf-4ff7-42de-8924-781d547a4d02.jpeg)

**Comment by aymanyounis** [comment]
![Screenshot_20230410_053928_Google Play Store](https://user-images.githubusercontent.com/7750693/230821191-9f696e3f-7f43-4bd5-a356-7b1bc9961d82.jpg)
![Screenshot_20230410_054038_Google Play Store](https://user-images.githubusercontent.com/7750693/230821198-086f7142-0c35-4d4c-bb78-fe429c73d18f.jpg)

Current pi chart shows only distripution of overall budget not showing changes over months.

**Comment by Chandra-Mauli-Sharma** [comment]
I think a line chart would be a good idea when working for changes over the months.
