### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#2121]
I would like to see my expenses or incomes in pie charts, identifying percentage

**Comment by Chandra-Mauli-Sharma** [comment]
Hey @ivywallet, can you please assign this issue to me? I would like to work on it. Thank you!

**Comment by ILIYANGERMANOV** [comment]
Hi @Chandra-Mauli-Sharma I think that exactly is already implemented - when you click "Income" or "Expense" you see a PieChart. But if you're up to creating more advanced and nicer graphs - feel free to do so :)

Note: We'll be migrating Ivy Wallet to Compose Multiplatform in the `multiplatform` brach. Make sure that your implementation is Multiplatform so we can use it in all apps.

**Comment by Chandra-Mauli-Sharma** [comment]
Thanks, @ILIYANGERMANOV for your help. The implementation of the pie chat is seamless. I think should move with this #2114.
