### ISSUE TITLE
[FEATURES] Remote Backup/Sync with WebDav/S3

### ISSUE THREAD

**Issue by 1itt1eB0y** [Ivy-Apps/ivy-wallet#2123]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have a function to sync or backup with remote storage.

### Why do you need it?

- Fast sync
- Save my data securely on different place conveniently

**Comment by ILIYANGERMANOV** [comment]
We got GitHub, other options are out of scope for now
