### ISSUE TITLE
[FEATURES] Allow IvyWallet to be backed up automatically by system backups, if backups are encrypted

### ISSUE THREAD

**Issue by m0byn** [Ivy-Apps/ivy-wallet#2135]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want the app to be included in the automatic system backups, only if backups are encrypted.

### Why do you need it?

- Data not lost if phone breaks
- Much easier/less work when restoring a backup

### How do you imagine it?

Of course, it is not desireable to have automatic, unencrypted backups since financial records are sensitive data. However, if the backups are encrypted, then it would be very convenient, if also this app would be included in the automatic backups. I am running LineageOS 20 (Android 13). The included backup app "Seedvault", excludes the app from automatic backups as the app does not allow that. However, as outlined nicely in the [FAQs](https://github.com/seedvault-app/seedvault/wiki/FAQ) of Seedvault, apps can actually differentiate between the cases of backups being encrypted, or not encrypted. So, if backups are encrypted, then include this app in system backups. In the FAQs, there is also a link to an example of how to program the app to differentiate!

OS: LineageOS 20 (Android 13)
Backup solution: Seedvault
Device: Samsung Galaxy A50

PS: I opened this issue since there are just too many uninformative issues. Hopefully, this issue is a bit more detailed.

**Comment by ILIYANGERMANOV** [comment]
We're going only with GitHub auto-backups in a private repo
