### ISSUE TITLE
[FEATURES] Add option for round up savings

### ISSUE THREAD

**Issue by m0byn** [Ivy-Apps/ivy-wallet#2136]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to enable round up savings. In more detail, round up saving means that with every transaction a specific amount is automatically transferred to savings. So, every decimal amount is rounded to the next integer, e.g 6.90€ is rounded to 7€ and the 0.1€ are automatically transferred to savings (a pre-set account). 

### Why do you need it?

- To keep track of my savings!

### How do you imagine it?

There exist several cases:
1) round to next integer value, e.g. for 6.9€ there is going to be 0.1€ saved
2) round to next integer value + x€, e.g. for 6.9€ there is going to be 1.1€ saved
3) round to next value for which a bank note exists, e.g. for 6.9 there is going to be 3.1€ saved (10€ being the next possibility for bank notes change), or for 12.3€ there is going to be 2.7€ saved (15€ being the next possibility for bank notes change)

Scenarios:
Cases 1) and 2) are particularly useful for card payments. For example, my bank (Erste Bank, Austria) includes such settings in their online banking. So, it would be a very nice feature to keep track of your savings.
Case 3) comes in very handy for cash payments. I usually pay only with notes. In the evening, when coming home, I take my coins which I received as change during the day, and put them into a jar. Once in a while I go to my bank and add them to my savings account. So, in order to keep track of all the savings this feature would be very nice.

Hopefully, it is clear what I am trying to elaborate on. If not, please comment and I will try to clarify!

Apart from that: KEEP UP THE GOOD WORK!

**Comment by ILIYANGERMANOV** [comment]
That's out of scope for the moment
