### ISSUE TITLE
Translation for Ivy Wallet

### ISSUE THREAD

**Issue by Ngapa** [Ivy-Apps/ivy-wallet#2147]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to make translation, so that easily user if they don't understand English language.

### Why do you need it?

- translation documentation
- translation folder for every language

### How do you imagine it?

- User can change the language in application
- User can change number format in application

**Comment by ILIYANGERMANOV** [comment]
Yes, we accept translations PR - feel free to do so https://elastic-burglar-ec5.notion.site/How-to-translate-Ivy-Wallet-c20256f024a7448a96c2e13fed84d170
