### ISSUE TITLE
Contirbutor request for triage role.

### ISSUE THREAD

**Issue by dinesh-58** [Ivy-Apps/ivy-wallet#2153]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Is the project building?

None

### What would you like to improve?

- help identify duplicate issues. 

### Because...

Users can open issues from inside the app without having to specify that they checked for duplicates. Currently, the `duplicate` label isn't being utilized much. I think we should have more main issues like #1240 and link duplicates there. This would allow us to properly place issues in the Project view as well

### Other

An alternative would be to only allow users to create an issue directly inside GitHub so they check for duplicates themselves. Though, that would require them to have an account & may deter non tech-savvy users from submitting useful feedback.

**Comment by ILIYANGERMANOV** [comment]
Good call! Users can now only create issues from the GitHub repo and the great spam from "ivywallet" has been stopped.
