### ISSUE TITLE
[FEATURES] Add more icons

### ISSUE THREAD

**Issue by Ansem93** [Ivy-Apps/ivy-wallet#2156]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want some new icons:
Amazon
A Food category with 
Pizza
Sushi
Cocktail drink
Hamburger
Beer

### Why do you need it?

Having only the restaurant icons is limiting if I want to have different categories

**Comment by ILIYANGERMANOV** [comment]
The icons must be free and open-source

**Comment by kirillkin693** [comment]
Hi, as if [this](https://medium.com/microsoft-design/designing-in-the-open-source-5c62be73a599) is supposed to help. I really would like to see emojis instead of icons

**Comment by Ansem93** [comment]
pizza icon: https://lucide.dev/icons/pizza

Do you think that it would be possible to have the user load their own icons instead?

**Comment by Ansem93** [comment]
This website should have all open source icons:
https://iconduck.com
Amazon: https://iconduck.com/search?query=amazon
A Food category with
Pizza: https://iconduck.com/search?query=pizza
Sushi: https://iconduck.com/search?query=sushi
Cocktail drink: https://iconduck.com/search?query=cocktail
Hamburger: https://iconduck.com/search?query=hamburger
Beer: https://iconduck.com/search?query=beer
