### ISSUE TITLE
AndroidStudio Settings Screen different from Cellphone Settings Screen

### ISSUE THREAD

**Issue by marceloruilova** [Ivy-Apps/ivy-wallet#2165]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Is the project building?

Yes

### What would you like to improve?

- I am facing a problem, I wanted to add a functionality but at the moment of comparing the settings screen on my cellphone (I downloaded it from play store) and the screen on androidstudio I saw that they are differents. What is happening? May be the cellphone version... I do not know...

**Comment by ILIYANGERMANOV** [comment]
Can you try the updated `main` branch? Most likely you've used our legacy default branch `develop` which was a re-write of the app
