### ISSUE TITLE
[BUG] Repeating lines in multiline description

### ISSUE THREAD

**Issue by nityapatel19** [Ivy-Apps/ivy-wallet#2201]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When adding a new line in the description, it copies the previous line in the input field, which you have to backspace everytime.

### To Reproduce

1. Add an expense.
2. When adding the description, type something in one line.
3. Press enter to move to the next line.
4. The previous line gets copied again.

### Expected behavior

It should just move to a blank new line.

### Smartphone

Samsung Galaxy M31 (Android 12)

**Comment by ILIYANGERMANOV** [comment]
Hi @nityapatel19, I tried to reproduce it but unfortunately couldn't. Can you add a screen recording? It'll help us out to try to fix it 🙏

**Comment by nityapatel19** [comment]
https://github.com/Ivy-Apps/ivy-wallet/assets/72748894/4037e3a3-65e6-4f17-b1c0-55216cc71da9

My hypothesis is that this happens for lines with single words.

**Comment by beradeep** [comment]
Hey I was not able to reproduce this issue, even with single words whatsoever.
