### ISSUE TITLE
[DESIGN] Make the design less bulky and nicer

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#227]
**What do you want to be added or improved?**
As a user, I want the app to be less bulky and look better on smaller devices.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- aesthetics
- optimize space on the screen
- looks weird on devices with smaller screens

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- reduce font sizes
- reduce unnecessary margins

**Comment by edsnchz** [comment]
Please remove all the gradients. I thing the solid colors give a better general look to the app.
