### ISSUE TITLE
[FEATURES] Mongolian language `mn`

### ISSUE THREAD

**Issue by sadespresso** [Ivy-Apps/ivy-wallet#2315]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have Mongolian language user interface

### Why do you need it?

- Add `mn` localization to Ivy Wallet app

### How do you imagine it?

Add new localization for `mn`

**Comment by ILIYANGERMANOV** [comment]
If someone can translate the app, we can add it

**Comment by sadespresso** [comment]
I am working on it! Will make a PR.
