### ISSUE TITLE
Remember Scroll Position In List After Navigating Inside An Expense 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#2348]
While scrolling through a long expense list, if we open a particular expense to know the time of transaction then the whole list starts to scroll from the top when we navigate back. Remembering the scroll position in the list will save the user from having to scroll from the top again.

**Comment by zebrapurring** [comment]
This is currently not working for me on Ivy Wallet 4.5.0, should the issue be re-opened?

**Comment by ILIYANGERMANOV** [comment]
Good point @zebrapurring, re-opened

**Comment by MaratKhakim** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @MaratKhakim! 🎉
Issue #2348 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
