### ISSUE TITLE
[FEATURES] Add People & Place to transactions

### ISSUE THREAD

**Issue by Humam-Hamdan** [Ivy-Apps/ivy-wallet#2399]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to set who I got this from or who I paid it to, also I'd like to see where [Shops and whatnot] I spend my money

### How do you imagine it?

Like how it's done in MoneyWallet, you set people and places, and when adding transactions select where and who if there's a need.

**Comment by ILIYANGERMANOV** [comment]
We plan to implement transaction "tags/labels" feature that can be used for that purpose. 
See #10
