### ISSUE TITLE
Spendee "Transfer" Support in CSV Import

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#2403]
The Import CSV functionality for Spendee skips over all transfers between Spendee Wallets and marks them as an import error. 

The other way around: If a manual CSV Import is attempted with a Spendee CSV source file, transfers can be correctly identified alongside income and expenses, however the import cannot be completed because the timestamp in the CSV file does not match date format suggested by Ivy Wallet. It does not let you continue the import as the timestamp field remains with a red rectangle, not correctly configured according to Ivy with no option to fix it.

Keep up the great work.

**Comment by zebrapurring** [comment]
Is this issue resolved? I'm also seeing all Spendee CSV rows marked as transfer not being imported on Ivy Wallet 4.5.0.

**Comment by ILIYANGERMANOV** [comment]
Nope, it isn't. Closed all issues created by "ivywallet" user
