### ISSUE TITLE
Upgrade Gradle wrapper and automate it 

### ISSUE THREAD

**Issue by StefMa** [Ivy-Apps/ivy-wallet#2449]
The current Gradle version is quite old (7.5). This ticket should update the Gradle wrapper as well as adding an automation to update it as soon as a new release is available.
We can make use of [this plugin](https://plugins.gradle.org/plugin/org.gradle.wrapper-upgrade) for it.

**Comment by ILIYANGERMANOV** [comment]
I recently updated to Gradle 8.2

**Comment by ILIYANGERMANOV** [comment]
Can you do the automation part? I'm not aware of it. We make sure that it's compatible with Kotlin and Jetpack Compose. Thank you for raising these well described tickets 🙏

**Comment by ILIYANGERMANOV** [comment]
Might this cause issues with AS, I'll close it for now 👍

**Comment by StefMa** [comment]
Hey,
Sure, I can over it 🙃.
