### ISSUE TITLE
Add Dependabot for dependency updates 

### ISSUE THREAD

**Issue by StefMa** [Ivy-Apps/ivy-wallet#2450]
Right now you have to manually run the update dependency task, then check search for the updated release notes to finally create a PR for it.

We should automate this by adding dependabot to the project.

Be aware that this depends on the usage of the Gradle Version Catalog. Which somewhat depends on the Gradle version (#2449).

**Comment by ILIYANGERMANOV** [comment]
Hey @StefMa - dependabot would be an awesome addition! Can you take the lead on that effort?
I can push forward #2451

**Comment by StefMa** [comment]
Yep, I am do this. Let me first do the other ones as they are dependencies
for this one...

**Comment by ILIYANGERMANOV** [comment]
Thank you! I'm assigning them to you :)

**Comment by StefMa** [comment]
It seems it was about to time to automate this 😅
