### ISSUE TITLE
Move to Gradle Version Catalog 

### ISSUE THREAD

**Issue by StefMa** [Ivy-Apps/ivy-wallet#2451]
To enable dependabot (#2450) it makes sense to move to Gradle Version Catalog.
However we should first update Gradle (#2449) for this.

**Comment by ILIYANGERMANOV** [comment]
That's a good one and it's planned. I'm incrementally trying to migrate it. Feel free to open a PR to support this initiative 👍

**Comment by StefMa** [comment]
I will check what I can do 👍

**Comment by StefMa** [comment]
Is this already done? 🤔
It seems so?!
Or is there anything left to do?

**Comment by ILIYANGERMANOV** [comment]
Hey @StefMa it's partly done - `dependencies.kt` in buildSrc. About 50% of dependencies are migrated.
Affected modules `:app` and `:ivy-design`

**Comment by ILIYANGERMANOV** [comment]
Hi again @StefMa I'll take this one cuz I need to extract to configure dependabot anyway 👍 I hope that you haven't started working on it - apologies for the last minute change

**Comment by ILIYANGERMANOV** [comment]
Done in https://github.com/Ivy-Apps/ivy-wallet/pull/2552
