### ISSUE TITLE
[BUG] Stuck in Import Ui after deleting all local user data

### ISSUE THREAD

**Issue by Tiihi** [Ivy-Apps/ivy-wallet#2519]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

So when i delete all user data and want to import afterwards a backup csv file im getting stuck in the import ui screen.
Normally i we would navigate forward to set our currency after successfully importing a csv file but somehow i end up again in the import ui and cant do much about it.

### To Reproduce

1. create offline account
2. complete onboarding (do not import data yet!)
3. go to settings
4. delete all user data
5. create offline account (do not restart the app!)
6. import backup file
7. from ivy wallet
8. import a valid backup csv file
9. finish

### Expected behavior

After successfully importing the backup file we should navigate in to the Currency Selection UI.

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/71343607/081633a2-d189-40c3-9694-9318d7a6af2f

### Smartphone

Pixel 5 Android 11

**Comment by Tiihi** [comment]
Alright thanks! 😄 
I'm on it! 🚀

**Comment by mohammednawas8** [comment]
Hi, i got the same bug.
i will work on it too

**Comment by ILIYANGERMANOV** [comment]
Hey guys, can you make sure that you're not both working on the same thing? Sync in the comments and make sure to pick different tickets

**Comment by ILIYANGERMANOV** [comment]
@mohammednawas8 I see that @Tiihi already started working on it, please ping another one - I'm pretty certain that Ivy Wallet has a lot of bugs and room for improvement 😀

**Comment by mohammednawas8** [comment]
@ILIYANGERMANOV okay got it
