### ISSUE TITLE
Show balance on Dashboard with full Number for 100% accuracy [FEATURE] 

### ISSUE THREAD

**Issue by saytowork** [Ivy-Apps/ivy-wallet#2522]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to see my clear funds, for example in dashboard it shows me like 503.04k , but I wanna see exact number like 503045.

Please add support to toggle on/off to see full or round off numbers on dashboard over balance.

### Why do you need it?

- accuracy is what I want
- even to notice small expenditures
- will help in a better planning

**Comment by ILIYANGERMANOV** [comment]
Hey, this is a valid and well described issue 👏 Unfortunately, we have othee priorities atm.
@stefanilijev97 the new Home screen UI should support scaling.

**Requirements:**
- Provide this feature as customization
- Switch in "Settings"
