### ISSUE TITLE
[BUG] On version click in the settings screen shows an empty ui screen

### ISSUE THREAD

**Issue by mohammednawas8** [Ivy-Apps/ivy-wallet#2523]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

[ivy_wallet_vid.webm](https://github.com/Ivy-Apps/ivy-wallet/assets/78867217/1bc7dcf9-03f9-430b-8012-4e2db2a7825e)

### To Reproduce

1. Go to the settings screen
2. Click on the app's version

### Expected behavior

I am not sure what about expected behavior of this click, but waiting for @ILIYANGERMANOV  to provide me enough information about this.

### Smartphone

Pixel 7 Api 34

**Comment by ILIYANGERMANOV** [comment]
Thanks for reporting @mohammednawas8! That's known maybe we can fix it. It opens a `TestScreen` which is used for dev purposes - currently is empty because we haven't mocked any actions there.

Feel free to fix it by Disabled the click when `!BuildConfig.Debug`

**Comment by ILIYANGERMANOV** [comment]
Also please use our naming template where the ticket starts with [BUG] Lorem ipsum

**Comment by mohammednawas8** [comment]
I got that
