### ISSUE TITLE
[CI] Add Detekt CI check

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2526]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Is the project building?

Yes

### What would you like to improve?

- Detect common code issue 
- Detect Jetpack Compose issues

Configure it for:
- Kotlin 
- Jetpack Compose 

### Because...

- automate code quality 
- fix PR issues

**Comment by rougsig** [comment]
I'm on it
