### ISSUE TITLE
[CI] Add Ktlint CI check

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2527]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Is the project building?

Yes

### What would you like to improve?

- Enforce code style in the CI
- Improve code quality 

### Because...

- it'll simplify code reviews
- make our dev experience better

**Comment by rougsig** [comment]
I'm on it
