### ISSUE TITLE
Add Kotlinx Immutable collections

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2534]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Add https://github.com/Kotlin/kotlinx.collections.immutable
- Replace `List` usages with `ImmutableList` whenever you feel confident (optional)

### Because...

- Will greatly optimize the Compose code
- The CI will be happy
- Ivy Wallet transactions screens will run smoothly

**Comment by mohammednawas8** [comment]
I will take this one

**Comment by mohammednawas8** [comment]
I noticed that the AnalyticsReportScreen is not reachable by the user, however, i changed the fields in the AnalyticsReportResponse to ImmutableList instead of List. But i could not test it because the getReport HTTP request in AnalyticsService produces an exception.

**Comment by ILIYANGERMANOV** [comment]
The AnalyticsReportScreen is obsolete and I've deleted it in a branch that I'm working on
