### ISSUE TITLE
[FEATURE] Support for Indian number system

### ISSUE THREAD

**Issue by sreevatsa-h** [Ivy-Apps/ivy-wallet#2537]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

Can support for Indian number system be added? This is different from the international system and looks like this:

https://www.cuemath.com/numbers/indian-numeral-system/

### Why do you need it?

When selecting currency as INR the usual expectation (at least for me, as an Indian) is that the numerical system also shows up in Indian system, since this is the system used in all the banks and for most transactions in the country.

### How do you imagine it?

If currency is selected as INR, change the numerical system to Indian (With commas and decimal points in the right place)

**Comment by poorankharol** [comment]
@ILIYANGERMANOV Do we have a centralized currency decimal function/code or do we have to do it manually every where?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV Do we have a centralized currency decimal function/code or do we have to do it manually everywhere?

We have some legacy code in temp-legacy-code. Double.format() ext

**Comment by chhotuver** [comment]
Even i want this feature of indian number format too.
