### ISSUE TITLE
[BUG] Unable to import Paisa data

### ISSUE THREAD

**Issue by nagarajhere** [Ivy-Apps/ivy-wallet#2548]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I tried to import all my paisa app data into ivy wallet
Everything worked well except data format is not supporting..

### To Reproduce

1. 

### Expected behavior

It is supposed to work 
I don't what's the issue🥲

### Screenshots

![Screenshot_20230903_173745](https://github.com/Ivy-Apps/ivy-wallet/assets/143933556/f81e4840-077c-40eb-9da0-9aff1c3c973b)
![Screenshot_20230903_173750](https://github.com/Ivy-Apps/ivy-wallet/assets/143933556/a8aaf635-9b69-42bc-8c79-25783ae80eea)

### Smartphone

Vivo y33s, Android 13

**Comment by ILIYANGERMANOV** [comment]
Thanks for reporting @nagarajhere! Can you also attach a few rows from the Paisa CSV so devs can test?
