### ISSUE TITLE
Add a seperate option - Credit Card (like cash & bank)

### ISSUE THREAD

**Issue by Abhy-Manoj** [Ivy-Apps/ivy-wallet#2577]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Add a new option - Credit Card to the wallet.
An option to set the credit limit.

Seperate account balances instead of combining all.

### Because...

It will be much easier to differentiate between normal banks/cash & credit card

**Comment by Abhy-Manoj** [comment]
Make life easier

**Comment by ILIYANGERMANOV** [comment]
> Seperate account balances instead of combining all.

Thanks for requesting!
We can't do that. Credit cards request is a good feature and already added to the board 👍 
I'm closing this as duplicate and inactionable right now.
