### ISSUE TITLE
[FEATURE] Add expense categories from the onboarding suggest after the onboarding 

### ISSUE THREAD

**Issue by LexLeontiev** [Ivy-Apps/ivy-wallet#2578]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user I want to add expense categories from the onboarding suggest after I complete onboarding 

### Why do you need it?

- I picked 5 or 6 expense categories during the onboarding. I decided to add others later. But found out that I don't have that option after the onboarding. I had to add basic categories (bus/taxi/food/etc.) myself. This is boring! I want to quickly add extra popular categories after the onboarding

### How do you imagine it?

When you click on "Add Category" button, the app can show popular categories and "Other" option. When you tap on "Other", the default "Create Category" interface is displayed.

**Comment by ILIYANGERMANOV** [comment]
That's a good one 👍

**Comment by yogirajthombre** [comment]
![Screenshot_2023-09-26-11-00-43-54_25a5cbee76b0e8af12aa5b9c322cd4a3_2_200x480](https://github.com/Ivy-Apps/ivy-wallet/assets/68183759/14786c39-27a1-47f2-99ea-f6f91877bbc2)

Hello @ILIYANGERMANOV and @LexLeontiev ,

Greetings

When you click on the "Add Categories" button, you'll notice a list of popular categories already available. 

Would you like to replace the "+Add New" button with "Other" text label?

Regards

**Comment by ILIYANGERMANOV** [comment]
> ![Screenshot_2023-09-26-11-00-43-54_25a5cbee76b0e8af12aa5b9c322cd4a3_2_200x480](https://user-images.githubusercontent.com/68183759/270638788-14786c39-27a1-47f2-99ea-f6f91877bbc2.jpeg)
> 
> Hello @ILIYANGERMANOV and @LexLeontiev ,
> 
> Greetings
> 
> When you click on the "Add Categories" button, you'll notice a list of popular categories already available.
> 
> Would you like to replace the "+Add New" button with "Other" text label?
> 
> Regards

Hi, "Add new" makes more sense because that's exactly what the button does - prompts you to add a new Category.

**Comment by yogirajthombre** [comment]
> > ![Screenshot_2023-09-26-11-00-43-54_25a5cbee76b0e8af12aa5b9c322cd4a3_2_200x480](https://user-images.githubusercontent.com/68183759/270638788-14786c39-27a1-47f2-99ea-f6f91877bbc2.jpeg)
> > Hello @ILIYANGERMANOV and @LexLeontiev ,
> > Greetings
> > When you click on the "Add Categories" button, you'll notice a list of popular categories already available.
> > Would you like to replace the "+Add New" button with "Other" text label?
> > Regards
> 
> Hi, "Add new" makes more sense because that's exactly what the button does - prompts you to add a new Category.

So if the popular categories are already there and "Add new" button makes more sense then what addition can be done here?

**Comment by LexLeontiev** [comment]
> > > ![Screenshot_2023-09-26-11-00-43-54_25a5cbee76b0e8af12aa5b9c322cd4a3_2_200x480](https://user-images.githubusercontent.com/68183759/270638788-14786c39-27a1-47f2-99ea-f6f91877bbc2.jpeg)
> > > Hello @ILIYANGERMANOV and @LexLeontiev ,
> > > Greetings
> > > When you click on the "Add Categories" button, you'll notice a list of popular categories already available.
> > > Would you like to replace the "+Add New" button with "Other" text label?
> > > Regards
> > 
> > 
> > Hi, "Add new" makes more sense because that's exactly what the button does - prompts you to add a new Category.
> 
> So if the popular categories are already there and "Add new" button makes more sense then what addition can be done here?

Hi! You can only see this screen once when you just download the app. I skipped this screen, as I'm used to using similar mechanics later, after I've have a look at the whole app and was ready to completely set it up. But in this case, I can't select these predefined categories after this initial screen, I have to create them manually in the "Categories" section.

**Comment by ILIYANGERMANOV** [comment]
I read between the lines, but I think that I get it.
When the user clicks "Add new" should:
- open modal to add a new category
- in the modal to add a new category there must be button to create a category from the pre-defined ones

**Comment by yogirajthombre** [comment]
![Screenshot_2023-09-26-17-35-13-61_25a5cbee76b0e8af12aa5b9c322cd4a3_50](https://github.com/Ivy-Apps/ivy-wallet/assets/68183759/acacfde3-1ee0-4695-b676-e8038fe74900)

On this screen there should be a button to create category from predefined ones .
Am I correct

**Comment by ILIYANGERMANOV** [comment]
> ![Screenshot_2023-09-26-17-35-13-61_25a5cbee76b0e8af12aa5b9c322cd4a3_50](https://user-images.githubusercontent.com/68183759/270650868-acacfde3-1ee0-4695-b676-e8038fe74900.jpeg)
> 
> On this screen there should be a button to create category from predefined ones . Am I correct

Exactly! This is the way.
When clicked this button should open a modal with the pre-defined categories. After clicking a pre-defined category it should be automatically created.

**Comment by yogirajthombre** [comment]
> > ![Screenshot_2023-09-26-17-35-13-61_25a5cbee76b0e8af12aa5b9c322cd4a3_50](https://user-images.githubusercontent.com/68183759/270650868-acacfde3-1ee0-4695-b676-e8038fe74900.jpeg)
> > On this screen there should be a button to create category from predefined ones . Am I correct
> 
> Exactly! This is the way. When clicked this button should open a modal with the pre-defined categories. After clicking a pre-defined category it should be automatically created.

So below the Choose Color and color options there should be **popular predefined categories** listed . When I click on the predefined category then the category should be automatically created

**Comment by ILIYANGERMANOV** [comment]
Hey @yogirajthombre do you want to take this one?
