### ISSUE TITLE
[FEATURE] Delete Acccount 3rd confirmation

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2583]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user, I want to not delete my accounts by accident/mistake. That's why I need a very serious final confirmation before deleting an account.

### Why do you need it?

- Users accidentally delete accounts and lose data
- People don't read the delete confirmation and just click delete

### How do you imagine it?

After confirming delete a 3rd delete confirmation must show up.
In this final delete confirmation, the user must type the name of the Account correctly in order to delete.
You can see GitHub has a similar UX when deleting repos.

You can use a Material3 dialog with TextField inside it.

UX goal:
- User clicks delete account
- A confirmation modal shows up (already implemented)
- User clicks delete again
- A final confirmation dialog shows.
- The user must type the name of the account.
- After typing the name of the account, the final "DELETE PERMANENTLY" button will become enabled.
- After the user clicks the final "DELETE PERMANENTLY" button thee account will be gone for good.

**Comment by mohammednawas8** [comment]
But what if the User doesn't have a name for his account? What should he type?

**Comment by ILIYANGERMANOV** [comment]
Hi @mohammednawas8 that should be impossible but good catch. If that's the case nothing, the Delete button should be enabled by default but it seems like a big edge case

**Comment by mohammednawas8** [comment]
Here is an example, the user can actually go to the settings and delete the name of his account. 
![Screenshot_20230909_011519_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/78867217/8f23ba8a-5502-4427-aa68-75dcbab0c2ac)

**Comment by ILIYANGERMANOV** [comment]
Hey @mohammednawas8 no no, I'm talking about deleting a Wallet account like "Cash", "Bank" from the accounts tab where you store money. Some people delete this accounts by accident even though there's a confirmation. And they lose transactions. We need to add 3 confirmations

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/4185ace0-56a4-46a4-bab2-fe753494b6d9

**Comment by mohammednawas8** [comment]
I get it, and it makes sense to show a final confirmation dialog, i could work this one.

**Comment by ILIYANGERMANOV** [comment]
> What should i show if the user types a wrong account name?

Nothing, just disable the "Delete" button in the 3d confirmation dialog. 

enabled = if name is typed correctly else false

**Comment by mohammednawas8** [comment]
Instead of A Dialog i used the IvyModal and added a IvyTextField 
https://github.com/Ivy-Apps/ivy-wallet/assets/78867217/40dbb75b-5569-481c-b9ed-ef589e5285fb

**Comment by ILIYANGERMANOV** [comment]
> Instead of A Dialog i used the IvyModal and added a IvyTextField https://github.com/Ivy-Apps/ivy-wallet/assets/78867217/40dbb75b-5569-481c-b9ed-ef589e5285fb

Looks good! I like the experience and it should prevent users from accidentally deleting their account 👍
