### ISSUE TITLE
[FEATURE] Smaller account cards and multi-line account selection

### ISSUE THREAD

**Issue by AbhirupRK** [Ivy-Apps/ivy-wallet#2587]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

The account cards are quite large and hence it's diffcult to glance through all the accounts. Especially, when one has 6-7 accounts including banks and cards. So, I request to make them smaller to fit all in a one screen.

Also, while adding expense/income, account is shown in a single line. Hence, need to scroll a long to get desired account when one has multiple bank accounts and cards. I request to make this account selection to multi-line mode, like:

```
Banks: Bank-A | Bank-B | Bank-C
Cards: Card-X | Card-Y | Card-Z
Wallet: Wallet-M | Wallet-N | Wallet-O
Cash
```

Thanks :-)

### Why do you need it?

-

**Comment by ILIYANGERMANOV** [comment]
**Scope:**
Make the account cards smaller

**Comment by MayankRaje** [comment]
Hi,
I am new to open source. I want to contribute to your project. Can you guide me on which file I should look for this issue?

**Comment by ILIYANGERMANOV** [comment]
@MayankRaje assigned to you. See CONTRIBUTING.MD, TransactionCard and HomeScreen.kt

**Comment by MayankRaje** [comment]
working on it

**Comment by ILIYANGERMANOV** [comment]
> working on it

@MayankRaje comment the magic words from CONTRIBUTING otherwise this won't be automatically assigned to you
