### ISSUE TITLE
Choose multiple categories 

### ISSUE THREAD

**Issue by riyad671** [Ivy-Apps/ivy-wallet#2589]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user I want to choose multiple categories. I think, It will be beneficial for so many user. 

### Why do you need it?

- 

### How do you imagine it?

When we meet with our friends we eat lots of thing. At that moment, if we can select multiple categories like 'food', 'friends' then it will be helpful for us to maintain our expenses.

**Comment by ILIYANGERMANOV** [comment]
Ivy Wallet will support only one category per transaction. Otherwise the reports and calculations will be messed up.

We'll create a separate "transsction tags" / "transaction labels" where you can multiple tags on the same transaction.
