### ISSUE TITLE
[FEATURE] Archive paid off loans

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2597]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

I'd like to have the loans screen organized, and have the paid off loans entries to be accessible. It takes up too much space to have all the active and currently paid off loans listed together in the case of multiple loan cards. 

### Why do you need it?

- will make it easier to read the list

### How do you imagine it?

I see it as a button below all the active loan cards that shows a new screen with only the paid off loans. These will only appear here, as it's about clearing up the loan list to show only active (not yet paid off) entries.

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV This _Stale_ tag should not be applied to currently approved tickets, in my opinion.

That's true! But idk how we can configure Github's stale action to do that? If you know, feel free to submit a PR 💯
