### ISSUE TITLE
[FEATURE]  Group based on account, month and category

### ISSUE THREAD

**Issue by Srimatdee** [Ivy-Apps/ivy-wallet#2602]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user I want to, group based on account, month and category. [As a total] Please refer below link for screenshots

[(https://t.me/c/1647280565/8172/17848)]
[
](https://t.me/c/1647280565/8172/17850)

### Why do you need it?

- Usability, because i want see the total amount spend based on account and selected category as total...don't want to see all line items under that category.

### How do you imagine it?

![Screenshot 2023-09-09 at 8 50 27 PM](https://github.com/Ivy-Apps/ivy-wallet/assets/144546654/8dd0fa23-6aab-4c35-b606-9b78c74bf167)![image](https://github.com/Ivy-Apps/ivy-wallet/assets/144546654/e2acbf7a-61c8-4b65-af4c-e9f665cc2885)

**Comment by ILIYANGERMANOV** [comment]
Must be done as a separate screen
