### ISSUE TITLE
[FEATURE] Budget Durations

### ISSUE THREAD

**Issue by BlackDragonIX** [Ivy-Apps/ivy-wallet#2605]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user I want to set budgets with various durations, such as weekly, quarterly, annually etc.

### Why do you need it?

- Regular expenditures often adhere better to a weekly schedule, and as such a monthly budget would be less consistent as the number of days in a month fluctuates.
- Being paid every other week my by currently employer, it is often easier for me to budget many of my expenses per paycheque where possible.

### How do you imagine it?

Whenever you select "+ Add Budget", the interface would have a new "Duration" or "Schedule" subcategory with the following input row containing two fields (Within []'s). The first being numerical entry, the second a drop-down
"Resets every [n] [Day(s), Week(s), Month(s), Year(s)]"

It would default to "Resets every [1] [month]"

Depending on the duration set by the user, they may need to specify when the budget starts, as such here are a few examples of what that might look like.

• If the duration is "Resets every 1 Day", the user would have no starting window to adjust. It's a daily budget.
• If the duration is "Resets every 1 Week", the user would be able to choose which day of the week it begins on "Begins each [Monday, Tuesday, etc..]" (A drop-down)
• If the duration is "Resets every 1 Month", the day of the month would need to be specified (with a note about how values above 28 are managed) "Begins on the [N] (st,nd,rd,th) of each month" (Numerical entry)
• In many other instances, the user will need to select a calendar date to be unambiguous. For example, if the budget is "Resets every 2 months", selecting the day of the month isn't enough, as it is unclear whether it should begin in the current month, or in the previous/next month. "Begins every 2 months, starting on [CALENDAR DATE]" (Calendar selection)

**Comment by ILIYANGERMANOV** [comment]
That's a good one! Very well defined, thank you 👍

**Comment by BlackDragonIX** [comment]
I'm on it
