### ISSUE TITLE
Migrate `:screen-transaction` to ComposeViewModel and our new architecture

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2632]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md) and migrate the screens in the module to `ComposeViewModel`.
- Try to fix Detekt and Lint errors on the go.
- Refactor and optimize the code for Compose.

### Because...

- Legacy code isn't nice.
- It's tech debt.
- Using modern technologies and the new architecture will make our dev life easier.
- The project maintainers and other contributors will be grateful.

### Description

Migrate the screen by extending `ComposeViewModel` and following the pattern described here:
https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md

### Success Criteria

- You didn't break the screen. All features that were in it before, work as expected after the migration.
- You can attach a screen recording after the migration, testing all features on the screen to prove that it still works.
- The screen's performance is the same or better.
- The code after the migration is shorter and simpler.
- You've addressed all Detekt and Lint issues in your PR _(there might be exceptions but they must be approved by your reviewers)_

**Comment by nicolegeorgieva** [comment]
I'm on it
