### ISSUE TITLE
[FEATURE] separation of paid and unpaid loans

### ISSUE THREAD

**Issue by h4MeMengoding** [Ivy-Apps/ivy-wallet#2642]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user I want to request feature in the loans menu, loans that have been paid (0) should be entered in the hidden menu with the title: "Loans Paid" maybe?, which can be accessed with a separate button so it doesn't interfere if you want to see other loans

### Why do you need it?

- To make it easier to check unpaid loans with those that have been paid
- The appearance is more organized and neat
- No confusion when looking for loans

### How do you imagine it?

I'm not very familiar with kotlin, I hope the feature I want can be done by ivy wallet contribution

**Comment by theabhishekbhujang** [comment]
+1

**Comment by ILIYANGERMANOV** [comment]
@theabhishekbhujang @h4MeMengoding can you provide more info how do you imagine it in terms of UI/UX?
