### ISSUE TITLE
Hide Amount in 'Cashflow' When 'Hide Amount' Option Is Enabled

### ISSUE THREAD

**Issue by theabhishekbhujang** [Ivy-Apps/ivy-wallet#2643]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I enable the 'Hide Amount' option, it successfully hides amounts in most places, but in the 'Cashflow' section, the amounts are still visible, even though the setting is enabled. This inconsistency makes it less effective for users who wish to keep their financial data private.

### To Reproduce

1. Open the IVY Wallet's Homepage

### Expected behavior

The 'Cashflow' on the homepage shows the amount even when the balance is hidden.

Consider fixing this issue by ensuring that the 'Cashflow' section also respects the 'Hide Amount' setting. This will enhance the privacy and consistency of the application's user experience.

### Screenshots

![image](https://github.com/Ivy-Apps/ivy-wallet/assets/59395512/b9d1a667-840f-4fe7-a806-bc87445997bd)

### Smartphone

Redmi Note 5 Pro (whyred); Android: 9 (pie)

**Comment by luispacheco-dev** [comment]
I'm on it
