### ISSUE TITLE
[FEATURE] Prompt the user to backup data before deleting an account

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2647]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user I want to be prompted to backup my Ivy Wallet data before deleting an account so I don't lose valuable information.

### Why do you need it?

- Deleting an account is a dangerous operation that's irreversible and many people lose transactions and endup with a messed balance.
- A good place to prompt the user to backup.end up

### How do you imagine it?

Add a secondary action in the Delete account dialog to Backup data or prompt the user with an m3 alterdialog after confirming account deletion. Note: the account backup must be done before deleting the account. In simple words, the backup made should contain the deleted account.

**Comment by amitYadavDev** [comment]
@ILIYANGERMANOV is backup stored on cloud ?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV is backup stored on cloud ?

We don't support cloud backup at the moment.

**Comment by amitYadavDev** [comment]
So, backup should be saved on local storage, right?

**Comment by amitYadavDev** [comment]
Hi @ILIYANGERMANOV, I'm on it.

**Comment by ivywallet** [comment]
Thank you for your interest @amitYadavDev! 🎉
Issue #2647 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by amitYadavDev** [comment]
Hi @ILIYANGERMANOV, I've resolved the issue, can you pls look at it and suggest me if something can be done more better?

https://github.com/Ivy-Apps/ivy-wallet/assets/45551012/f9babaf2-e19f-4d25-8d3f-0abdfccd0265

**Comment by ILIYANGERMANOV** [comment]
> Hi @ILIYANGERMANOV, I've resolved the issue, can you pls look at it and suggest me if something can be done more better or it is fine?
> 
>  WhatsApp.Video.2023-10-08.at.10.40.34.PM.mp4

Looks good @amitYadavDev! Just make the  "Backup Data" button to say "Backup and Delete". Also, btw this issue is about deleting Accounts not the entire app sata. But it's good, too.

Steps:
1. Create an account e.g. Cash
2. Click it
3. Click Delete (top right)

**Comment by amitYadavDev** [comment]
@ILIYANGERMANOV, oh I was completely working on wrong place. Should I push the code of above video also?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV, oh I was completely working on wrong place. Should I push the code of above video also?

Yeah, push it - it's good

**Comment by amitYadavDev** [comment]
Hi @ILIYANGERMANOV, how can I execute these 2 methods sequentially?
 
![Screenshot (389)](https://github.com/Ivy-Apps/ivy-wallet/assets/45551012/8caab7c4-7890-4b1d-80c4-9199912843ae)

**Comment by ILIYANGERMANOV** [comment]
@amitYadavDev I don't understand your question/problem exactly but all these must be done in the ViewModel, not in the UI. Check our Architecture guidelines for more info
