### ISSUE TITLE
Too much empty space in the UI

### ISSUE THREAD

**Issue by buk7456** [Ivy-Apps/ivy-wallet#2654]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Make the user interface compact so users do not have to scroll endlessly. 

### Because...

Improves user experience and functionality, other than just the 'looks'

**Comment by poorankharol** [comment]
@buk7456 Can you share some of screenshots?
