### ISSUE TITLE
System setting per-app language API

### ISSUE THREAD

**Issue by jedi1150** [Ivy-Apps/ivy-wallet#2662]
I want to add the ability to change the app language in Android system settings using the per-app language settings - [https://developer.android.com/guide/topics/resources/app-languages](https://developer.android.com/guide/topics/resources/app-languages).
Just "System settings" without additional APIs inside the app.

**Comment by jedi1150** [comment]
@ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
Nice one @jedi1150! I'm assigning it to you
