### ISSUE TITLE
[TESTING] Room DB migration tests and drop "users" table

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2672]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Support for Room DB migration unit tests. 
https://developer.android.com/training/data-storage/room/testing-db

- We need to support Room unit tests that run on the JVM and **not** on an Android device because our CI can support efficiently only JVM tests.

- Add support for migration tests specifically:
https://developer.android.com/training/data-storage/room/migrating-db-versions#test

To test your migration tests successfully delete the `UserEntity` that is no longer needed and write a DB migration test. 
For the user's name use Datastore instead.

### Because...

- We plan to do many DB migrations to fix the legacy Ivy Wallet data model
- Migrations are critical! If a migration fails, the app will crash on app start and users will give us 1-star reviews instantly.
- It's a good practice and will give us peace of mind.

### Description

Room DB migration unit tests that run on the JVM via our test framework - Kotest.

### Success Criteria

- The migration tests run on the JVM in the "Unit tests" CI workflow.
- The test does **not** require actual Android device.
- The tests aren't flaky.
- This change doesn't affect or break the app.

**Comment by YatinGarg07** [comment]
Hi @ILIYANGERMANOV, Assign this issue to me. I think i will require some help in it from your side, so please bear with me.

**Comment by ILIYANGERMANOV** [comment]
> Hi @ILIYANGERMANOV, Assign this issue to me. I think i will require some help in it from your side, so please bear with me.

Sure @YatinGarg07 , will do. Keep in mind that these days I'm very busy but you can for help in our Telegram community, too 🚀  Regarding this task, if the migration tests are impossible w/o an emulator you can drop that requirement 👍

**Comment by YatinGarg07** [comment]
Hi @ILIYANGERMANOV, I am getting this error
![image](https://github.com/Ivy-Apps/ivy-wallet/assets/73949161/6e35e5de-5f57-4a6c-9b39-d6303b4f3f11)
![image](https://github.com/Ivy-Apps/ivy-wallet/assets/73949161/69a80b3f-1ac7-4452-8ab7-5c01c79ba234)

Please Help me solve this

**Comment by ILIYANGERMANOV** [comment]
> Hi @ILIYANGERMANOV, I am getting this error ![image](https://user-images.githubusercontent.com/73949161/273449746-6e35e5de-5f57-4a6c-9b39-d6303b4f3f11.png) ![image](https://user-images.githubusercontent.com/73949161/273449797-69a80b3f-1ac7-4452-8ab7-5c01c79ba234.png)
> 
> Please Help me solve this

Hey @YatinGarg07 I assume it requires an Android Emulator. Also you need to setup https://developer.android.com/reference/android/test/InstrumentationTestRunner. How to do that exactly, I don't know you should research how to setup "androidTests" (instrumentation" tests in Android Developers
