### ISSUE TITLE
[FEATURE] Add "GitHub" button in the Settings screen

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2675]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user, I want to have a "GitHub" button in Ivy Wallet's Settings screen that open the Ivy Wallet GitHub repo.

### Why do you need it?

- I want to see the project's open-source repo.
- The more people that see the repo, the more contributors we'll get.

### How do you imagine it?

I colorful "GitHub' button in the Settings screen right below "Share Ivy Wallet" in the "Other" section.
When click the button should open:

https://github.com/Ivy-Apps/ivy-wallet

**Comment by ILIYANGERMANOV** [comment]
Thank you for your interest! Done ✅

**Comment by ILIYANGERMANOV** [comment]
> Hi there, I'm pretty much impressed towards the UI/UX environment of the entire app and I wish to work on this feature. If possible, can I get assigned to Il

> Hi there, I'm pretty much impressed towards the UI/UX environment of the entire app and I wish to work on this feature. If possible, can I get assigned to this?

Ups, my bad! Sorry, stupid me misclicked and assigned the wrong person 😬 It's yours, my friend.

**Comment by ILIYANGERMANOV** [comment]
Ohh shit it's taken, I should stop watching between the lines. It was originally assigned to @tarunsamanta2k20. @TharunBalaji2004 let's wait and see if @tarunsamanta2k20 is still on it?

**Comment by TharunBalaji2004** [comment]
Yeah its okay alright, multiple persons could not work on same issue?

**Comment by ILIYANGERMANOV** [comment]
Currently, nope because at the end of the day - I'll be able to merge only one PR and someone who worked will have to discard their efforts and that's not fair
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

**Comment by ILIYANGERMANOV** [comment]
@TharunBalaji2004 do you still want to take this one? I see that @tarunsamanta2k20 removed his assessment.

**Comment by TharunBalaji2004** [comment]
Yeah sure, I'm interested to work on this also. Can you assign it to me

**Comment by ILIYANGERMANOV** [comment]
Thank you! Assigned to you

**Comment by TharunBalaji2004** [comment]
![GitHub Button Feature](https://github.com/Ivy-Apps/ivy-wallet/assets/95350584/c111fe4e-5d78-4d6e-9b8b-d7a51b5cab6b)

I have added new GitHub button in "Others" section, it supports both Light and Dark mode and redirects to GitHub repo page 👍

**Comment by ILIYANGERMANOV** [comment]
> ![GitHub Button Feature](https://user-images.githubusercontent.com/95350584/270933883-c111fe4e-5d78-4d6e-9b8b-d7a51b5cab6b.gif) [ ![GitHub Button Feature](https://user-images.githubusercontent.com/95350584/270933883-c111fe4e-5d78-4d6e-9b8b-d7a51b5cab6b.gif) ](https://user-images.githubusercontent.com/95350584/270933883-c111fe4e-5d78-4d6e-9b8b-d7a51b5cab6b.gif) [ ](https://user-images.githubusercontent.com/95350584/270933883-c111fe4e-5d78-4d6e-9b8b-d7a51b5cab6b.gif)
> 
> @ILIYANGERMANOV I have added new GitHub button in "Others" section, it supports both Light and Dark mode and redirects to GitHub repo page 👍

Goood!! Raise it as PR

**Comment by TharunBalaji2004** [comment]
Yeah I have given a PR request, kindly review it 👍
