### ISSUE TITLE
[FEATURE] Filter historical titles list

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2678]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

I want the transaction title drop-down list (this one with historical titles below the input field) to display only titles that match the current text.

### Why do you need it?

- it'd make the transaction handling easier

### How do you imagine it?

When we type some text in the transaction title, we get the drop-down list to filter only the historical titles that contain the typed text. This way we can easily type just part of the title and use any historical title that matches. It would also be good to make sure the filtering isn't case-sensitive.

**Comment by ILIYANGERMANOV** [comment]
Hey @nvllz, Ivy Wallet's current logic sometimes makes very good predictions based on "Category" and "Account" so we can't make that. Maybe, we can introduce as a customization option "Suggest only exact titles". Wdyt?

**Comment by ILIYANGERMANOV** [comment]
> I get your point. But if none of the items on the prediction list match your current title, you start typing and have the unrelated list still cluttering the UI. If unmatching items got filtered on the go, we could not only have it easier to reach the 6th and latter list element (it'd become the top item if titles match enough) but have the list hidden if it's not necessary (as in this case when we don't need any historical title).
> 
> Or make it as easy as moving the typing cursor to the description input field when tapping a "Next" on the keyboard. It currently acts as the Save button shortcut. Maybe it's just me who see this list annoying hahah :D
> 
> If it'd be that easy as it sounds, the option you described would also be a solution. But name it something like "Title Suggestion List Filtering" as we want to see a list containing the text (for "abc" show both "xxabcx" and "abcdef").

We need to fix the algorithm. The logic should be:
- Exact match (title)
- By Category
- By Account

At least that's how I think it is. Gotta investigate it and improve it. I won't "approve" the issue, yet because I don't won't the "By Category" and "By Account" part getting removed.
