### ISSUE TITLE
Migrate Dagger/Hilt to KSP

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2682]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Migrate Hilt to KSP
- Get rid of KAPT entirely
- The project to build faster and still work properly

### Because...

- KSP is faster than KAPT

### Description

https://dagger.dev/dev-guide/ksp.html

### Success Criteria

- Hilt is migrated to KSP
- The project builds successfully
- All of the CI checks still work and pass
- There are no runtime crashes in the app
- We no longer use KSP

**Comment by aritra-tech** [comment]
I will try to pick this one.

**Comment by lovemhjn** [comment]
> I will try to pick this one.

@aritra-tech Can i try to pick this?

**Comment by lovemhjn** [comment]
@aritra-tech Let me know if you face any issue. @ILIYANGERMANOV Can i pick this if @aritra-tech faces any issues as i have recently migrated one of my project from hilt kapt to ksp

**Comment by ILIYANGERMANOV** [comment]
Hey @lovemhjn sure, if @aritra-tech has any difficulties and can't submit a PR till Tuesday EOD feel free to take it 👍 You can also communicate with each other and support each other. I should add this to the contributing rules but I'm planning on defining a general 1-2 days deadline for each task.

**Comment by ILIYANGERMANOV** [comment]
> Hey, @ILIYANGERMANOV actually I'm stuck with my office work so please assign this issue to @lovemhjn. Thank you.

Got it. Thank you for pinging us @aritra-tech! Appreciated. @lovemhjn - it's yours now
