### ISSUE TITLE
Swiping Action Improvement

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2683]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

I want to improve the monthly swiping action

### Because...

It causes a problem where you swipe into the accounts section by accident

https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/365fffb8-cedd-47d0-8816-72b42931fdbd

### Success Criteria

Add "minWidth = X.dp" to the button

**Comment by ILIYANGERMANOV** [comment]
Ofc, assigned to you ✅ Thank you for your interest!
