### ISSUE TITLE
[BUG] Onboard screen does not fit

### ISSUE THREAD

**Issue by paulolima18** [Ivy-Apps/ivy-wallet#2688]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In smaller screens I cannot see the entire onboard page because it is not resizable or scrollable.

### To Reproduce

1. Open app with phone with smaller screen
2. Go into the designated onboarding page

### Expected behavior

I should be able to navigate in the entire screen.

### Screenshots

<img width="364" alt="Screenshot 2023-09-25 at 23 25 52" src="https://github.com/Ivy-Apps/ivy-wallet/assets/36114588/fcf7f35c-73bd-4da6-9b8e-66b98b5be9f5">

### Smartphone

Samsung Galaxy Nexus, Android 9

**Comment by paulolima18** [comment]
In case this issue is approved, I already have a solution for it

**Comment by ILIYANGERMANOV** [comment]
Awesome! A fix for that will be highly appreciated. Just put a screen recording on the PR so we can see the UI/UX
