### ISSUE TITLE
Loans Owed/Owe Total

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2691]
I think it'd be a slight improvement to add a Owed and Owe totals under the Loans title, something like this:

**Loans**
You owe: $XXX
You're owed: $XXX

or add a overall Debit/Credit amount somewhere in the app, maybe adding it under the total net worth![Screenshot_20230926_103313_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/cbcc3824-3e37-402b-9ad5-17ba0197dd97)

**Comment by vartult** [comment]
So we already have a percent here, maybe we can give an option in the settings to see toggle between percent & actual amount, which resolves half of the problem. that way user can see how much he have already paid. 
Though the problem still remains to see how much of the loan I owe as of current state. 
PS: Would like to work on this issue.

**Comment by ILIYANGERMANOV** [comment]
Sure. Assigned you ✅ When working on it make sure to not discard information that we already show. I don't use this feature but our goal is to make it as useful as possible for people that have/give loans

**Comment by vartult** [comment]
@ILIYANGERMANOV please mark this as duplicate as this will be covered in [2702](https://github.com/Ivy-Apps/ivy-wallet/issues/2702)

**Comment by ILIYANGERMANOV** [comment]
Duplicate will be resolved in #2702 . Conversion moved to #2702
