### ISSUE TITLE
Text aligned for long names[BUG]

### ISSUE THREAD

**Issue by vartult** [Ivy-Apps/ivy-wallet#2692]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The text is not properly aligned for long names on settings.

### To Reproduce

1. Go to the settings
2. Try Enter a very long name
3. See the text alignment is not correct at the end of name.

### Expected behavior

Margin should be consistent on both the start & end.

### Screenshots

![bug2](https://github.com/Ivy-Apps/ivy-wallet/assets/30458518/898f0879-6de2-4c1d-bc41-8e7f87e5f244)
![bug1](https://github.com/Ivy-Apps/ivy-wallet/assets/30458518/a36c6d70-18a0-4db4-a77f-5cf3da191802)

### Smartphone

Samsung S21 Plus, Android 13

**Comment by vartult** [comment]
I can pick this!

**Comment by vartult** [comment]
@ILIYANGERMANOV Can I pick this issue?

**Comment by ILIYANGERMANOV** [comment]
Ofc, take it - it's yours! ✅
