### ISSUE TITLE
[FEATURE] Add support for Multi-currency account. 

### ISSUE THREAD

**Issue by antonio-pedro99** [Ivy-Apps/ivy-wallet#2693]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to set up Multi-currency account like wise. 

### Why do you need it?

- Right now I have a Wise account, and I can hold any currency in my account. Instead of having Wise USD, Wise Euro, Wise CAD.

### How do you imagine it?

- It would be better to have an account Wise, and inside it have each currency

**Comment by ILIYANGERMANOV** [comment]
Depends on #2685

**Comment by antonio-pedro99** [comment]
I would like to work on this.

**Comment by ILIYANGERMANOV** [comment]
Nice! @antonio-pedro99 make sure to add a DB migration after changing the DB

**Comment by vartult** [comment]
@ILIYANGERMANOV @antonio-pedro99 just make sure we do the arithmetic operations keeping all txns in a single base currency and at the end just convert back to the user preferred one. A usecase where it will be required is total loan you owe/owed on the loan screen. Where user might end up adding multiple account's and apparently multi currency loan, but still wants to see the overall due amount.

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV @antonio-pedro99 just make sure we do the arithmetic operations keeping all txns in a single base currency and at the end just convert back to the user preferred one. A usecase where it will be required is total loan you owe/owed on the loan screen. Where user might end up adding multiple account's and apparently multi currency loan, but still wants to see the overall due amount.

Hey @vartult we need to support multi-currency transactions. We'll add conversion logic on the place where it's missing. Good call 👍

**Comment by forwardslashh** [comment]
yeah this is really annoying when I imported from Money Manager it halved the amount I have because I used multiple currencies with varying values
