### ISSUE TITLE
Multi-select Transactions

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2694]
Add the possibility to select multiple transactions by holding your finger on top of one and tapping, just like the gallery multi-selection feature

Off the top of my head I can think of these options after you selected the transactions:
- Delete them
- Change their date
- Change their account
- Change their category

The multi-selection could have a "select all" thingy that select all the transaction of that day, so you don't have to selected them one by one if there's too many<

**Comment by ILIYANGERMANOV** [comment]
That's a good one 👍

**Comment by teja1329** [comment]
can i work on this @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
> can i work on this @ILIYANGERMANOV

Sure - assigned to you. Keep in mind this is a tricky one and we'll merge it only if it doesn't crash and doesn't affect the transaction history performance.

**Comment by hiteshtib01** [comment]
![IMG_20231024_221819_400](https://github.com/Ivy-Apps/ivy-wallet/assets/99788416/5ec087a5-cea2-4f11-8cd9-21608b05ac62)
Multi - Select idea for total
