### ISSUE TITLE
Toggle to see percent vs amount on Loan[FEATURE] 

### ISSUE THREAD

**Issue by vartult** [Ivy-Apps/ivy-wallet#2702]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see the actual amount (with respect to the loan repaid percentage).

### Why do you need it?

- It can be pretty convenient to see how much total money I've spent on loan repayment.

### How do you imagine it?

So I see two option here-

1. Give an option to toggle b/w percent & actual amount on loan screen (As I see a lot of empty space there).
2. Go via settings and have a dedicated option for loans there. And we can toggle & control this scenario.

Pros with 1st- Quite convenient & user can easily toggle between the two options. It can be a good UX.
Pros with 2nd- We can incorporate more customisations with Loan Listing Experience. eg. [2691](https://github.com/Ivy-Apps/ivy-wallet/issues/2691)

**Comment by ILIYANGERMANOV** [comment]
Can't we just display both % and the actual amount?

**Comment by ILIYANGERMANOV** [comment]
I'm against adding too much customization Settings because:
- they add code complexity
- they're complex for the end user, too

**Comment by ILIYANGERMANOV** [comment]
Perf, assigned it to you
