### ISSUE TITLE
Fix Detekt deprecated style

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2705]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Fix warning:
```
Property 'style>OptionalWhenBraces' is deprecated. 
Same functionality is implemented in BracesOnWhenStatements.
```

Example of such log:
https://github.com/Ivy-Apps/ivy-wallet/actions/runs/6319023100

### Because...

- it's annoying 
- It confuses people who look at the Detekt error

### Description

It seems like in `config/detekt/config.yml` we use an outdated property. Migrate it to the new one.

### Success Criteria

- Detekt still works as expected. 
- The warning when running Detekt disappears
```
Property 'style>OptionalWhenBraces' is deprecated. Same functionality is implemented in BracesOnWhenStatements.
```

**Comment by priyatanu** [comment]
Hi, 
I would like to work on this issue, as i am new to the project

**Comment by ILIYANGERMANOV** [comment]
Thank you! Assigned to you

**Comment by priyatanu** [comment]
> Hi, I would like to work on this issue, as i am new to the project

Hi @ILIYANGERMANOV , I am an on holiday for the weekend. But i will look at it on Monday/Tuesday :)

**Comment by ILIYANGERMANOV** [comment]
Hey @priyatanu that's tine. Have a nice vacation :)
I'll temporarily unassign it from you in case someone can take it earlier. 
If not taken when you're back from vacation, please tag me and I'll assign it back to you.

**Comment by vishal2376** [comment]
Can i work on this issue ?

**Comment by ILIYANGERMANOV** [comment]
@vishal2376 ofc, assigned to you ✅

**Comment by ILIYANGERMANOV** [comment]
This issue is free, is someone wants to take it

**Comment by priyatanu** [comment]
> This issue is free, is someone wants to take it

Hi @ILIYANGERMANOV , 
I would like to take this as first issue, as something easy to start with

**Comment by ILIYANGERMANOV** [comment]
> > This issue is free, is someone wants to take it
> 
> Hi @ILIYANGERMANOV , I would like to take this as first issue, as something easy to start with

Assigned to you ✅
