### ISSUE TITLE
vanishing cursor when user tabs on screen

### ISSUE THREAD

**Issue by teja1329** [Ivy-Apps/ivy-wallet#2706]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

https://github.com/Ivy-Apps/ivy-wallet/assets/113032716/aa80a1fe-c941-42a1-b112-05cc6d9ba850

when the user enters something and tabs on screen then keyboard and cursor should vanish.

### Because...

1. Enhanced User Experience: Addressing the cursor behavior issue in "or in last year" number box improves user satisfaction, aligns with user preferences for a clutter-free interface, and reduces cognitive load.
2. The change prevents user errors by reducing the chance of accidental input changes, contributing to a smoother and error-free user interaction.

### Description

To Reproduce

After entering something on the "or in last year" number box, tap on the screen.

**Comment by teja1329** [comment]
what do you say @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
Seems like a valid UX problem that can be improved 👍 Thank you for creating it! @teja1329 would you like to work on it?

**Comment by teja1329** [comment]
@ILIYANGERMANOV sure i will work on that, thank you.
