### ISSUE TITLE
[FEATURE] Add a button to change the sign in the basic calculator

### ISSUE THREAD

**Issue by BlackDragonIX** [Ivy-Apps/ivy-wallet#2711]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to enter negative values in the account creation screen to start tracking credit accounts, and/or banking accounts currently in overdraft.

### Why do you need it?

Currently, entering a negative value is very inconvenient. Requiring you to enter the negative value as math in the advanced calculator.

The formula needs to be written as `0 - [value]`. Ultimately this complicates things for the end user and is not intuitive.

### How do you imagine it?

I imagine a button bring added to the basic calculator which looks like (+/-). Pressing this button would change the sign of the entered value.

The sign should remain negative while the user modifies the input (including -0). If the user decides they no longer wish to enter a negative value, they can press the (+/-) button again to change the sign yet again.

**This additional button should currently only appear in the account creation page.**

This means that it should only appear when the calculator is invoked with a flag, which if set, displays the (+/-) button.

**Comment by ILIYANGERMANOV** [comment]
Thank you @BlackDragonIX!! That's one well described issue - approved ✅

**Comment by ParthJain18** [comment]
Hello, I haven't made any contributions in the past. Can I try this?

**Comment by ILIYANGERMANOV** [comment]
Hi @ParthJain18 awesome! Assigned it to you :) Make sure to check our CONTRIBUTING.md
