### ISSUE TITLE
[BUG] Regression: Updated app icon missing themed/monochrome icon.

### ISSUE THREAD

**Issue by Aritzherrero4** [Ivy-Apps/ivy-wallet#2714]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The new icon doesn't have the themed/monochrome icon.

The previous version of the app, with the old icon had it.

### To Reproduce

1. Update the app.
2. Place the app on the home screen with themed icons activated.
3. Check that it doesn't get themed.

### Expected behavior

The icon should follow material you / android adaptive icon guidelines and follow the system theme color when the option is enabled.

### Screenshots

![Screenshot_20230927-202908](https://github.com/Ivy-Apps/ivy-wallet/assets/11832966/d865f775-fe9f-428a-9e45-b9c202405499)

### Smartphone

Pixel 7 Pro, Android 13

### Additional context

The culprit commit is ab19742df829755f65a384a6b03ba4e9475ee05a.

Previous implementation commit 1c3d9e6cf1b82bd0f272d5d90f7ea73a2f5b19c1.

Links with related information from android developer docs https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app

**Comment by ILIYANGERMANOV** [comment]
Thanks for raising this issue! Approved and marked as good first issue. Let's hope that someone will pick it soon 🤞

**Comment by paulolima18** [comment]
I'm on it!

**Comment by ILIYANGERMANOV** [comment]
> I'm on it!

Hey @paulolima18 thank you for your support! Unfortunately, that's not ready to be worked on cuz we're a missing an monochrome version from @stefanilijev97 (our designer) :/ I'll assign it @Aritzherrero4 cuz we already this in Telegram. Sorry, the organizational mess^

**Comment by alandrockwell** [comment]
The same issue - Pixel 6 Android 13
