### ISSUE TITLE
[BUG] It should not be possible to create negative transactions

### ISSUE THREAD

**Issue by BlackDragonIX** [Ivy-Apps/ivy-wallet#2718]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I am able to produce negative transfer, income, and expense transactions! — None of this should be possible as a negative income is an expense, a negative expense is income, and a negative transfer from A -> B, is a positive transfer from B -> A.

Negative transactions results in transaction types (income/expense/transfer) failing to be representative of their purpose, creating confusion.

### To Reproduce

1. Create a new transaction of your choosing, "Add Income", "Add Expense", or "Account Transfer"
2. When prompted to enter the value, open the calculator and type `0 - 75.20`
3. Press "Set"

You have now successfully entered a negative value of 75.20.

### Expected behavior

Whenever a Calculator formula would result in a negative value, the "Set" button should **instead**, create a warning along the lines of "Value cannot be negative".

### Screenshots

<img src="https://github.com/Ivy-Apps/ivy-wallet/assets/8507170/70c036ab-e66c-481f-8d7e-80627d954a45.png" width="33%">

<img src="https://github.com/Ivy-Apps/ivy-wallet/assets/8507170/d8321baf-5d7b-4467-b9b4-d9ea0e12d3f2.png" width="33%">

<img src="https://github.com/Ivy-Apps/ivy-wallet/assets/8507170/7a5f6e31-82df-477d-b8e9-abcc04fc3328.png" width="33%">

### Smartphone

Pixel 5

**Comment by ILIYANGERMANOV** [comment]
Ohh shit, we've messed up! Great catch @BlackDragonIX and thanks for the well-written bug report

**Comment by vishal2376** [comment]
Hey @ILIYANGERMANOV , I want to work on this issue. Please assign it to me.

**Comment by vishal2376** [comment]
Hey @ILIYANGERMANOV , I fixed the issue but how should i show error ?

**Comment by ILIYANGERMANOV** [comment]
> Hey @ILIYANGERMANOV , I fixed the issue but how should i show error ?

Hey @vishal2376 you can do the simplest thing possible. Maybe a toast?
