### ISSUE TITLE
[BUG] balance shows vertically when scrolling down.

### ISSUE THREAD

**Issue by uderbashi** [Ivy-Apps/ivy-wallet#2719]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The balance on the home screen gets compressed and appears vertical when scrolling down. It happens both if the balance is hidden and if it is shown.

Maybe it is because I have custom starting date thus longer month name.

### To Reproduce

1. Open the app
2. Scroll down 

### Expected behavior

The balance (or stars) should be displayed horizontally on one line. Maybe pushed down on the next line if it doesn't fit.

### Screenshots

![Screenshot_20230928_103826_Ivy Wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/32719218/7dbb2440-5877-4ec5-9fd3-d65a5b0285b0)

### Smartphone

Samsung Galaxy S20 FE

**Comment by ILIYANGERMANOV** [comment]
Thank you for reporting @uderbashi! Very well described bug report 👏

**Comment by Raghav1783** [comment]
hi, i am new to github i would like to contribute .. can you guide me in which file should i look for this issue

**Comment by ILIYANGERMANOV** [comment]
> hi, i am new to github i would like to contribute .. can you guide me in which file should i look for this issue

`HomeScreen` but first read our CONTRIBUTING markdown file for instructions on how to contribute to Ivy Wallet

**Comment by YatinGarg07** [comment]
Hi, i got the issue, I Would like to work on this issue, Please Assign it to me.

**Comment by Raghav1783** [comment]
yatin i am working on it

**Comment by ILIYANGERMANOV** [comment]
> Hi, i got the issue, I Would like to work on this issue, Please Assign it to me.

Hey @YatinGarg07, @Raghav1783 is already working on it - can you please pick a different one?

**Comment by YatinGarg07** [comment]
Sure, No problem

**Comment by Raghav1783** [comment]
I changed  the code a bit and made the currency and balance in 2 separate lines. 
![Screenshot_20231005-225523_Ivy Wallet Debug](https://github.com/Ivy-Apps/ivy-wallet/assets/134570234/ad62b614-40f2-4926-89de-ad8df181c5e4)

**Comment by Raghav1783** [comment]
hi @ILIYANGERMANOV  i wanted to know if i am going in the right direction... 
WHAT CHANGE I MADE:
In the file **BalanceRow**  
i made a new prameter  "overflow" of bool type in the function BalanceRowMini(line number 61) and made a if else block to display balance in next line if it is overflowing.Here is the link to the file [https://gist.github.com/Raghav1783/4d5f45ac34a821c4ce98de75cf5a3dab](url)
i added a if else block at line 114.
I wanted to ask if this is correct?

**Comment by ILIYANGERMANOV** [comment]
> hi @ILIYANGERMANOV i wanted to know if i am going in the right direction... WHAT CHANGE I MADE: In the file **BalanceRow** i made a new prameter "overflow" of bool type in the function BalanceRowMini(line number 61) and made a if else block to display balance in next line if it is overflowing.Here is the link to the file [https://gist.github.com/Raghav1783/4d5f45ac34a821c4ce98de75cf5a3dab](url) i added a if else block at line 114. I wanted to ask if this is correct?

Hey @Raghav1783 just raise a PR and I can give it a review 👀 Otherwise, it's hard to track what's changed. What I need is just a screen recoding to demo how it works
