### ISSUE TITLE
Loans Planned Payments

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2720]
I think it'd be nice to add **planned payments** that when executed automatically fill the **loan** of your choice, whether it was borrowed or lent. The reason for this suggestion is to be able to see these type of transactions on the "Upcoming" area. The Loans section should basically be treated as an account for this to work, by adding Loans to the accounts selection. There's a way to bypass this issue by creating an actual account called Loans without ever using the Loans feature but I'd rather see this implemented one day in the future

**Comment by keval-kanp-1011** [comment]
I'm interested to contribute on this feature.

**Comment by ILIYANGERMANOV** [comment]
Nice! Assigned to you @keval-kanp-1011 ✅
