### ISSUE TITLE
Setup code coverage CI check using Kover

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2722]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Be able to report code coverage on the changes of each PR
- Being able to get a code coverage report for the project

### Because...

- We need to be motivated to write more tests.
- We need to know which codepaths are tested.

### Description

Setup Kover.
Add Kover as a job that runs after successful unit tests.

### Success Criteria

- Reports code coverage 
- Script to be able to run locally 
- Uploads code coverage report
- Runs as a job after Unit tests (success)
- Excludes the Ui Composables from the code coverage check
- It's free and open-source 
- We're legally okay to use the tool for free

**Comment by SURAJ2600** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @SURAJ2600! 🎉
Issue #2722 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
> I'm on it

That's amazing!! Code coverage will be a big leap forward for the project 👍

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @SURAJ2600.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
