### ISSUE TITLE
[FEATURE] Implement new Home screen

### ISSUE THREAD

**Issue by ch3thanhs** [Ivy-Apps/ivy-wallet#2735]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

- Implement a home screen based on the following design - [Figma File](https://www.figma.com/file/AKBKXdkOtNED0BZeaz8NLu/Ivy-Home-Screen?type=design&node-id=0%3A1&mode=design&t=XpiT6LcCmEjgpaSb-1).
- Please follow typography guidelines from the [Ivy Design System](https://www.figma.com/file/kSwIa07jcHEHZXo6rzx7dn/Design-System?node-id=0%3A1&mode=dev) as the above design does not follow it.
- Icons are from - https://fonts.google.com/icons

P.S. Please do not judge the structure of the file, I have no idea what I'm doing.

**Comment by ILIYANGERMANOV** [comment]
## Success Criteria

- this Home version must be done in a separate module `:screen-home-chethans`
- we'll include a Setting for users to enable the new Home screen experience
- for implementation, we should use M3 components

**Comment by shreyas-kapse** [comment]
I'm interested to contribute on this feature.

**Comment by ILIYANGERMANOV** [comment]
> I'm interested to contribute on this feature.

Awesome!! Assigned to you. Just make sure to match the success criteria. Use `IvyFeatures` to make it a on/off setting.

**Comment by ch3thanhs** [comment]
@shreyas-kapse Are you still working on this?

**Comment by shreyas-kapse** [comment]
I was working on this, but due unavoidable reasons, I kept it on hold.
