### ISSUE TITLE
[BUG] Month can't be scrolled horizontally with gesture on Home Screen

### ISSUE THREAD

**Issue by nicolegeorgieva** [Ivy-Apps/ivy-wallet#2738]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Month in the outlined button in Home Screen on top of the screen is static and left-right or right-left gesture doesn't trigger a change (to display next/previous month instead of the current).

### To Reproduce

1. Open the app
2. Try to change the month with left-right or right-left gesture

### Expected behavior

The month on the Home Screen should change with left-right or right-left gesture resulting in displaying the next or previous month.

### Screenshots

![bug](https://github.com/Ivy-Apps/ivy-wallet/assets/93789076/581c1221-14f0-4a50-a4a6-219c5ced9105)

### Smartphone

Samsung Galaxy Note 20 Ultra, Android 11

**Comment by luispacheco-dev** [comment]
I'm on it

**Comment by Harshmhajn** [comment]
can i work on it

**Comment by ILIYANGERMANOV** [comment]
> can i work on it

Hey @Harshmhajn it's already taken by @luispacheco-dev. If he can't finish it in a few days, you can follow-up and we can re-assign it. I'd suggest looking for another issue or creating one on your own, if you have ideas for UI/UX or code improvements. For more info, refer to:
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md#contributing-rules
