### ISSUE TITLE
[BUG] Transactions screen bug

### ISSUE THREAD

**Issue by nicolegeorgieva** [Ivy-Apps/ivy-wallet#2739]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In Transactions Screen of Category a bug appears when you tap on the label of Category inside a transaction, then tap account label and then again Category label. Then a new screen appears with the title "Unspecified". Same thing when in Transactions Screen of an Account.

### To Reproduce

1. Open the app
2. Tap on one label from a transaction (Category for example).
3. You're now in Transactions Screen of Category.
4. When you tap on the label of Category inside a transaction, then tap account label and then again Category label. Then a new screen appears with the title "Unspecified". Same thing when in Transactions Screen of an Account.

### Expected behavior

When tapping on Category label of transaction - transactions screen of the category should appear and the same thing should happen for Account.

### Screenshots

Transactions screen | Unspecified
---|---
![bug2-1](https://github.com/Ivy-Apps/ivy-wallet/assets/93789076/a243b120-1632-4b2d-8d00-ac41d5aa0a05) | ![bug2](https://github.com/Ivy-Apps/ivy-wallet/assets/93789076/8801fc7f-f2cc-4f08-91fe-c803e46fd46c)

### Smartphone

Samsung Galaxy Note 20 Ultra, Android 11

**Comment by priyatanu** [comment]
Hi,
I would like to work on this issue

**Comment by ILIYANGERMANOV** [comment]
Hi @priyatanu assigned to you! Sorry for the late reply, I missed the GitHub notification

**Comment by priyatanu** [comment]
I am able to reproduce this issue, but I am going through the code

**Comment by MaratKhakim** [comment]
> I am able to reproduce this issue, but I am going through the code

Hi @priyatanu, are you working on that?

**Comment by ILIYANGERMANOV** [comment]
It's open 2 weeks have passed

**Comment by MaratKhakim** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @MaratKhakim! 🎉
Issue #2739 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by priyatanu** [comment]
Hi @MaratKhakim ,
yes you can go ahead. I was sick last 2 weeks. didnt get time to work on it
