### ISSUE TITLE
[FEATURE] Upgrade old-style date and time pickers

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2741]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user, I want the date/time picker to be styled with MD3. I will link the examples below.

### Why do you need it?

- The current pickers look very outdated and don't fit the design of the app
- On my side it's colored with a bright pink.. I wish I could change it because it makes the accents barely visible

### How do you imagine it?

Make them look like these: [DatePicker](https://m3.material.io/components/date-pickers/overview), [TimePicker](https://m3.material.io/components/time-pickers/overview).

**Comment by ILIYANGERMANOV** [comment]
Tha's a great one @nvllz! Feel free to pick it up if you want 💯

**Comment by ezhil56x** [comment]
I'm on it

**Comment by tajbaba999** [comment]
Hey, @ezhil56x have you completed this issue I want to work on this issue. @ILIYANGERMANOV can both at a time work on this issue?
