### ISSUE TITLE
[BUG] Digits diaplacement on the keyboard buttons

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2750]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I thought it was just an illusion, but it seems that the digits and other keyboard elements for the balance keyboard and calculator are not centered in the button outline. It's perfectly visible in the PR #2749 overview video. 

### To Reproduce

1. Add a transaction
2. Open a calculator

### Expected behavior

The numbers are correctly centered vertically and horizontally within the circle button outline.

### Screenshots

![](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/058fc5af-48d4-40b0-a0f0-0184edf67c73)

It's not that bad on my side, but some buttons still seem a little off.

![](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/5f1381a3-fe12-479a-92f4-05e8eb8db04f)
@

### Smartphone

Samsung Galaxy S20 Ultra

**Comment by ezhil56x** [comment]
Yeah, agreed. Text is not properly aligned wherever this style is used

**Comment by YatinGarg07** [comment]
I'm On it. Please Assign it to me.
