### ISSUE TITLE
[FEATURE] make calculator symbols more universal

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2751]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have the selected calculator symbols to match universal layout of the classic calculator.

### Why do you need it?

Almost every calculator layout looks like the one below, and it's the most universal way to display highlighted mathematical symbols.

### How do you imagine it?

Replace:
`/` with `÷`
`*` with `×`

![](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/1d72fc7c-e6f8-494e-9286-64732c617e50)

**Comment by amitYadavDev** [comment]
Hey @nvllz and @ILIYANGERMANOV I'm on it.
