### ISSUE TITLE
Data Layer: Transaction Repository

### ISSUE THREAD

**Issue by nicolegeorgieva** [Ivy-Apps/ivy-wallet#2762]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Implement the Data Layer for Ivy Wallet transactions
- TransactionRepository (interface + Impl)
- TrnsactionDataSource
- FakeTransactionRepository
- like the other Repositories 
- 100% code coverage requires 
- Implement it like AccountRepository and CategoryRepository

### Because...

- It's our new architecture.

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Im on it

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
This is one free to be taken

**Comment by ILIYANGERMANOV** [comment]
> Does this task also involve refactoring screens/features to use the repo or just the repo implementation for now? @ILIYANGERMANOV 

Hey @Rick-AB just repo impl, refactoring will be a separate one

**Comment by ivywallet** [comment]
Thank you for your interest @Rick-AB! 🎉
Issue #2762 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Rick-AB** [comment]
@ILIYANGERMANOV quick question. Seeing that this is part of a migration to a new architecture, should this implementation still work with the deprecated Transaction Model?

**Comment by Rick-AB** [comment]
> > @ILIYANGERMANOV quick question. Seeing that this is part of a migration to a new architecture, should this implementation still work with the deprecated Transaction Model?
> 
> Nope, only the new model with explicit types

Hmm, I see. And would these explicit types all have their own db table?

**Comment by ILIYANGERMANOV** [comment]
Hey @Rick-AB no tables created. You need to use the existing tables and apply mapping logic in the Repository. In the future, we'll migrate those tables. This will make stuff more complicated because:
- the legacy data model might contain invalid records
- invalid records must be filtered out by the repository

Check `CategoryRepository` and `AccountRepository`. Also, make sure to write unit tests. Unit tests are a must

**Comment by Rick-AB** [comment]
> > @ILIYANGERMANOV quick question. Seeing that this is part of a migration to a new architecture, should this implementation still work with the deprecated Transaction Model?
> 
> Nope, only the new model with explicit types

Hey @ILIYANGERMANOV coming back to this, there are functions like `findAll()` and many others in the transactionDao that return all transactions irrespective of type. What's the approach regarding this? Would these functions also be broken down to deal with explicit types as well? The implication being that higher level layers would be responsible for combining these transactions and also it means that every function in the repo (or at least 90%) would have three variants.

**Comment by ILIYANGERMANOV** [comment]
Hey @Rick-AB do as you see fit :) You can follow the pattern from the other Repositories but if something doesn't make sense, feel free to change it.

The goal for a Repository is to:
- be main-safe
- map.from Entity to domain
- save only valid domain data
- retrieve only valid domain data
- be covered with tests
- has fake impl.for testing purposes in the viewmodels

**Comment by Rick-AB** [comment]
Hey @ILIYANGERMANOV I see that the new transaction models have `recurringRuleId` and `loanRecordId` as non-nullable, I just want to confirm if this is a new requirement? If so can you please briefly explain why this is the case?

**Comment by ILIYANGERMANOV** [comment]
> Hey @ILIYANGERMANOV I see that the new transaction models have `recurringRuleId` and `loanRecordId` as non-nullable, I just want to confirm if this is a new requirement? If so can you please briefly explain why this is the case? 


They should be Nullable. It's a mistake - apologies. Please, make them nullable

**Comment by ILIYANGERMANOV** [comment]
cc @Rick-AB use https://github.com/Ivy-Apps/ivy-wallet/tree/data-layer-part-2 as a base - I started implementing it there and made some progress but abandonded the work

**Comment by Rick-AB** [comment]
> cc @Rick-AB use https://github.com/Ivy-Apps/ivy-wallet/tree/data-layer-part-2 as a base - I started implementing it there and made some progress but abandonded the work

do you mean I continue from where you stopped? cause I already finished the implementation.
sorry it took so long, sh*t happened
