### ISSUE TITLE
Class method ordering for consistent Dev Exp

### ISSUE THREAD

**Issue by vartult** [Ivy-Apps/ivy-wallet#2763]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Introduce Class method ordering using detekt so it can become mandatory for devs to follow consistent method ordering across app view model.

### Because...

Improves code readability.

### Description

for ref- https://detekt.dev/docs/rules/style#classordering

### Success Criteria

- For phase 1, make sure its consistent for new ComposeViewModel Arch.
- Identify way to introduce this to legacy code as well.

**Comment by ILIYANGERMANOV** [comment]
This is an excellent one @vartult !! Do you want to give it a try?

**Comment by vartult** [comment]
Sure, let me give it a try. Will keep posted here.
