### ISSUE TITLE
[FEATURE] CI automation test

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2768]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to

### Why do you need it?

-

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Issue #GitHubIssueNumber(value=2768) is not approved. @ILIYANGERMANOV must approve it first.

**Comment by ivywallet** [comment]
Issue #2768 is not approved. @ILIYANGERMANOV must approve it first.

**Comment by ivywallet** [comment]
This issue is not approved, yet. @ILIYANGERMANOV must approve it first.

**Comment by ivywallet** [comment]
⚠️ This issue is already taken by @nicolegeorgieva. Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

**Comment by ivywallet** [comment]
⚠️ This issue is already taken by @nicolegeorgieva. **Do not start working on it!** Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

**Comment by ILIYANGERMANOV** [comment]
Im on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! Assigned to you. You should work on it now ✅ If you don't want to work on it, please unassign yourself.

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉 Assigned to you. ✅ You can work on it now! If you don't want to work on it now, please unassign yourself so other contributors can take it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉 Assigned to you. You can work on it now ✅ If you don't want to work on it now, please unassign yourself so other contributors can take it.

**Comment by ILIYANGERMANOV** [comment]
Automation works!
