### ISSUE TITLE
Test ISSUE

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2773]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

ttes

### Because...

test

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #2773 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
