### ISSUE TITLE
Test issue 2

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2775]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

test

### Because...

test

**Comment by nicolegeorgieva** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @nicolegeorgieva! 🎉
Issue #2775 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
