### ISSUE TITLE
[BUG][Regression] Fix the Amount keyboard on large devices

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2776]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

![Screenshot_20231008_181158_Ivy Wallet Demo](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/3ace866c-bf68-41cc-83a7-5cbbb5df7ea5)

### To Reproduce

1. Use a large screen device
2. Open the Amount input/keyboard

### Expected behavior

The number keypad should be centered in the middle and with fixed margin between them.
The fix should also scale well for small devices.

### Smartphone

Fold4

**Comment by Raghav1783** [comment]
you want the keyboard to fit the screen on smaller devices and on bigger devices it should be centered right?

**Comment by Raghav1783** [comment]
why are we changing keyboard size i think the keyboard originally in the app looks pretty good

**Comment by Raghav1783** [comment]
yeah i am on it, also i wanted to ask what resources should i use learn android

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/resources

but first read CONTRIBUTING.MD and say the magic words to take the issue

**Comment by Raghav1783** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Raghav1783! 🎉
Issue #2776 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
