### ISSUE TITLE
[BUG] Problem Occurs While Typing Account Delete Confirmation 

### ISSUE THREAD

**Issue by SHYMOM** [Ivy-Apps/ivy-wallet#2778]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Account delete confirmation problem. The confirmation text is unable to write.

### To Reproduce

1. 

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/issues/2778#issuecomment-1752109153

### Smartphone

TCL 10 5G , Android 10

**Comment by ILIYANGERMANOV** [comment]
@SHYMOM can you include more details? Like a screen recording otherwise it's low a chance someone to understand and fix it

**Comment by SHYMOM** [comment]
https://github.com/Ivy-Apps/ivy-wallet/assets/130169485/6554bf32-c86e-4fa1-a99e-633bd8b13fde

**Comment by SHYMOM** [comment]
https://github.com/Ivy-Apps/ivy-wallet/assets/130169485/2e569ca2-1d86-4576-b452-27f45db12048

**Comment by chetan532** [comment]
@ILIYANGERMANOV I'm interested to contribute on this bug.

**Comment by ivywallet** [comment]
Thank you for your interest @chetan532! 🎉
Issue #2778 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
This one is open, if anyone wants to take it

**Comment by beradeep** [comment]
Hey @ILIYANGERMANOV and @SHYMOM , I was not able to reproduce this. In my case the confirmation text box works fine.

**Comment by MaratKhakim** [comment]
I was not able to reproduce it, either
