### ISSUE TITLE
I'd like to find a way to conceal, blur, or encrypt my income information from the home page.

### ISSUE THREAD

**Issue by moshiurhridoy11** [Ivy-Apps/ivy-wallet#2782]
Because There are some moments when I'm hesitant to open this app in certain places like front of colleges or family. I've noticed there's already an option for cash flow; I believe a similar feature could be implemented for income as well.

**Comment by luispacheco-dev** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @luispacheco-dev! 🎉
Issue #2782 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by venumanas87** [comment]
I'm on it
