### ISSUE TITLE
Improved Saving Goals

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2785]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

We need to improve the "Savings Goal" feature. We should be able to create savings Budgets for planned (yearly, semi-annual, etc...) expenses, that would work like a money box, or piggy bank. For example, if I have to pay every year $1200 for my car insurance, I'd like to virtually allocate $100 every month into a budget, so when that date comes I have saved enough to be able to pay

### Why do you need it?

- I need it on the app, because for now I rely on Excel and it's less practical

### How do you imagine it?

Savings Goal simply needs a "edit" button, that would open a page similiar or even identical to the already existing "Budgets" for monthly expenses. There would be a "Add Budget" there too, that let's you choose the cumulative amount you want to save. Then you could set the frenquency like once a month every 1st of the month, every week on Monday, etc... and maybe even add a date when the budget is going to end. It could also calculate the n of deposits you'd need and their value depending on the frequency you set. For example: today is Jan 1st 2024 and on April 10th 2024 I'll have to pay $300, and I want to deposit every 15th of each month. There would be three $100 deposits on Jan, Feb and March 15th, for a toal of $300.

I already do this for my yearly payment using formulas in Excel, i think it would be a powerful addition to the app

**Comment by ILIYANGERMANOV** [comment]
@atgfk you must set a feature title to the GitHub issue "[FEATURE]" isn't very descriptive and no one will want to open it
