### ISSUE TITLE
[FEATURE] Add image as part of a transaction

### ISSUE THREAD

**Issue by EmmaKnijn** [Ivy-Apps/ivy-wallet#2790]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to insert an image of a receipt associated with a transaction

### Why do you need it?

- I want to be able to check back on receipts whenever ai need to
- It helps to not have your receipts and transactions in seperate places

### How do you imagine it?

I'd imagine a field that shows an insert image button that opens the camera and inserts the taken picture into the transaction. Then the image would display when you open the transaction later on

**Comment by aryanA101a** [comment]
I'd like to work on it.

**Comment by ILIYANGERMANOV** [comment]
> I'd like to work on it.

Read CONTRIBUTING and say the magic words,  assignments are done only automatically @aryanA101a

**Comment by aryanA101a** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @aryanA101a! 🎉
Issue #2790 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Rajkdea123** [comment]
i'd like to work on it

**Comment by aryanA101a** [comment]
@ILIYANGERMANOV I was wondering where to specifically put the functions such as saveTransactionImage, createImageFile, createTransactionImageName, etc in the domain module?
Do I create a repository folder inside domain module and create a specific repository inside it?

**Comment by hexman1999** [comment]
I encourage adding such feature it'll be great!! And I think it is easy to add

**Comment by EmmaKnijn** [comment]
I think so too, I'm not experienced with programming android apps tho so I don't dare to
