### ISSUE TITLE
Time Period Bug

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2798]
In **Reports**, when you select a time range like September 1st to September 30th instead of directly selecting "September", it doesn't show the transaction happening on the last day (September 30th). In the screenshots below there's an expense on the 30th that shows up when I select September, but doesn't when I select the range. I noticed this bug when I wanted to see my expenses from March 1st to September 30th and one expense was missing, the one on the 30th. You can notice also how there are 20 and 21 transactions in the two cases, so there's 1 transaction missing.

I assume it has to be something related to timezones or something. Maybe when the last transaction was recorded it was already October 1st for the app. If that's the case, the app must follow the phone's time and date

![Screenshot_20231021_125319_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/e91a05b5-15e3-4856-aed4-ad722a1f4bea)

![Screenshot_20231021_124855_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/ac98e70e-ac06-491c-ac2d-762456974c7c)

![Screenshot_20231021_124824_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/4a7039a3-f830-4077-a429-bc2a781622bf)

![Screenshot_20231021_124840_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/cad04078-c2a6-4a27-a41c-bf69b990765a)

**Comment by MaratKhakim** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @MaratKhakim! 🎉
Issue #2798 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
