### ISSUE TITLE
Fix Account Tab UI

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [Ivy-Apps/ivy-wallet#2799]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Account Tab UI needs to be reverted back to the original padding values 

### Because...

Invalid Padding values makes the Account Tab cards bad

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @Vishwa-Raghavendra, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #2799 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
