### ISSUE TITLE
App for MAC OS 

### ISSUE THREAD

**Issue by 9harshit** [Ivy-Apps/ivy-wallet#280]
**What do you want to be added or improved?**
As a user I want to ...

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- This app currently exists for smartphones but having this app for laptops and computers will be great too. Because most of the Financial transactions and budget monitoring is done on laptops. So please port this application to MAC OS 

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- Convert this existing app for Mac OS using Xcode and make sure its backwards compatible with INTEL based Macs

**Comment by ILIYANGERMANOV** [comment]
Out of scope
