### ISSUE TITLE
Fix small Detekt error

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2810]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Fix the Detekt errors from this PR
https://github.com/Ivy-Apps/ivy-wallet/pull/2808

### Because...

- so we can merge the version update

### Description

See the Detekt error in https://github.com/Ivy-Apps/ivy-wallet/pull/2808 and fix it.
After your fix is merged we can merge the dependabot version update.

### Success Criteria

- The Detekt errors from https://github.com/Ivy-Apps/ivy-wallet/pull/2808 are resolved.

**Comment by priyatanu** [comment]
hi @ILIYANGERMANOV ,  i can take up the issue

**Comment by ILIYANGERMANOV** [comment]
Say the magic words so.it can be auto assigned to you

**Comment by priyatanu** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @priyatanu! 🎉
Issue #2810 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
