### ISSUE TITLE
[Money total sum customization] 

### ISSUE THREAD

**Issue by RoninZULU** [Ivy-Apps/ivy-wallet#2811]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Hello! I would like to suggest that the calculation of the total money in the "Accounts" section could be customized for which accounts we want to do the sum. I have 3 money accounts in liquid and one investment and for me it doesn't make much sense to add to the "total" the money I have in the investments because it change every day, but it would help me to see how much total money I have between the three liquid money accounts

### Why do you need it?

- I have several money accounts, but one of them being investments changes every day. It doesn't make sense that the total sum takes that number, since it is changing.

**Comment by ILIYANGERMANOV** [comment]
Hey @RoninZULU you can use "Include account" from the account edit modal to determine whether it should be included in the total balance? Does that work?

**Comment by CedricLindigkeit** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @CedricLindigkeit! 🎉
Issue #2811 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Aritzherrero4** [comment]
I don't really like this change. I think the account section should include all the accounts as it represents the real money you have. The "liquid" money is represented on the mail tab balance that already excludes hidden accounts.

I see the use case for the change though but it would be nice to make it optional. A new setting could be added to set if the excluded accounts should be taken into consideration on the "Account" tab.

I'm sorry for bringing this late to the table @CedricLindigkeit @ILIYANGERMANOV 

How do you guys see this proposal?

**Comment by ILIYANGERMANOV** [comment]
> I don't really like this change. I think the account section should include all the accounts as it represents the real money you have. The "liquid" money is represented on the mail tab balance that already excludes hidden accounts.
> 
> I see the use case for the change though but it would be nice to make it optional. A new setting could be added to set if the excluded accounts should be taken into consideration on the "Account" tab.
> 
> I'm sorry for bringing this late to the table @CedricLindigkeit @ILIYANGERMANOV 
> 
> How do you guys see this proposal?

Then, the UI should display both Liquid and Excluded. IMO, having both is the best. Wdyt?

**Comment by CedricLindigkeit** [comment]
I think this is a good suggestion, but I'm not sure where exactly I would put this option in the UI

**Comment by CedricLindigkeit** [comment]
I think this is a good suggestion, but I'm not sure where exactly I would put this option in the UI

**Comment by Aritzherrero4** [comment]
Maybe is the general app settings? Where the "hide balance" option is?

**Comment by ILIYANGERMANOV** [comment]
Why not just show both balances:
- better UX cuz more information available 
- less software complexity

**Comment by CedricLindigkeit** [comment]
That would be a valid possibility.

Would you allow the user to specify where the account is included (for example in Home too), or should this option really ONLY be for the account overview?

**Comment by Aritzherrero4** [comment]
I would keep it only for the accounts tab. The balance on the main page should only display the "useful" balance. It's what you need to quick check.
