### ISSUE TITLE
Balance After Planned Payments

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2812]
In the home, if you tap your balance, the app shows you the Balance After Planned Payments (let's call it BAPP), which is simply your balance after all the planned incomes and expenses of the current month. You can also check the following months and that's where we encounter a logical problem. The BAPP is calculated by adding to the Current Balance (CB) the Net Cash Flow (NCF) of that month, so we have:

BAPP¹ = CB¹ + NCF¹

The problem is that if I check the very next month, I expect my new BAPP to be calculated on the result of the equation before, right? So, it should be:

BAPP² = BAPP¹ + NCF²

BAPP³ = BAPP² + NCF³

Instead, what we have is:

BAPP² = CB¹ + NCF²

BAPP³ = CB¹ + NCF³

_(mind the little numbers)_

and so on, so it calculates the BAPP of any given month using today's current balance, which is illogical and most importantly useless. I think the point of checking future months is to have an idea of what my balance might look like after all the (planned) cash flows, so:

BAPP⁵ = CB¹ + NCF¹ + NCF² + NCF³ + NCF⁴ + NCF⁵

Lastly, you can also check previous months but it's pointless since all the planned incomes and expenses should have already been added to today's current balance. In case of overdue payments, they could be added to the NCF and eventually marked as overdue in the equation

**Comment by CedricLindigkeit** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @CedricLindigkeit! 🎉
Issue #2812 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
