### ISSUE TITLE
Translate the App into German

### ISSUE THREAD

**Issue by CedricLindigkeit** [Ivy-Apps/ivy-wallet#2825]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I would love to see a German translation in the app. German is quite a big language in central europe and i think i am not the only one who would like to change the language to German.

I have seen that there were issues created before (#429 & #1805) regarding a german translation, but they were closed without any comment. Is there a specific reason for that?

Anyhow, if this gets approved i might start translating today.

### Why do you need it?

- If the language can be changed to your native language, it is easier for many people to find their way around the app.

**Comment by CedricLindigkeit** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @CedricLindigkeit! 🎉
Issue #2825 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by kevinliao2003** [comment]
This issue particuarly interests me. As a polyglot myself, I also wonder if translating apps into various languages would be something I'm interested in. How would this work though? Is there a specific translation API, or would we have to do the translation ourselves?
