### ISSUE TITLE
Retain search query after opening transaction

### ISSUE THREAD

**Issue by ynshung** [Ivy-Apps/ivy-wallet#2828]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Currently if I search transactions, click into one of them and go back to the search page, the search will be reset. It would be more user friendly if the search query are retained to enable better bulk editing or other functions.

### Why do you need it?

- Ease the process of going to specific transactions with keywords and editing them
- Much more intuitive and user friendly as the user should be the one that resets the query after searching

**Comment by Angeloem** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Angeloem! 🎉
Issue #2828 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Angeloem** [comment]
I had gone to the holidays and forgot to work on it.

Let me give you the status on tomorrow 1900 GMT

**Comment by ynshung** [comment]
Hi @ILIYANGERMANOV would it be possible to reopen this issue so others can continue the work? Many thanks

**Comment by ILIYANGERMANOV** [comment]
It's open and ready to be taken

**Comment by Rick-AB** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Rick-AB! 🎉
Issue #2828 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
