### ISSUE TITLE
 [FEATURE] Tag transactions automatically by reading SMSs by using Regex.

### ISSUE THREAD

**Issue by thesurajkamble** [Ivy-Apps/ivy-wallet#2836]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to  keep track of all my credits and debits automatically (without having to manually add the expenses) 

### Why do you need it?

- It'll ease the use of the app as the user no more has to enter the transactions manually.
- user can choose to enter the transactions manually or automatically.
- reading transactions from SMS is much more easy.
- In India after the advent of UPI, small transactions are way too many and its impossible to keep track of all, reading all those SMSs and tagging the transactions with appropriate labels would help the user a lot. 

### How do you imagine it?

Ivy wallet reads the SMS using a regex pattern to figure out the nature of the transaction and updates the debited/credited amount.

**Comment by g-kartik** [comment]
This would be very helpful

**Comment by thesurajkamble** [comment]
> This would be very helpful

I'm Working on it.

**Comment by ILIYANGERMANOV** [comment]
@thesurajkamble say the magic words from the CONTRIBUTING.MD so the CI can assign it to you

**Comment by thesurajkamble** [comment]
@ILIYANGERMANOV  I'm on it

**Comment by thesurajkamble** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @thesurajkamble! 🎉
Issue #2836 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by GoodM4ven** [comment]
What about the case where there's a change in the SMS structure that you've written a Regex for...? I mean, what if it's a miss yet still half-a-match! Basically, can there be continuous logging to figure out similarities or something and then send a notification regarding that suspicious miss?

**Comment by g-kartik** [comment]
We just need to scan the transaction message to get the value of the unaccounted money and add it to the Ivy Wallet and then ask the user to tag the transaction manually.

For regex, I think the regex pattern should be configurable as different UPI apps and banks can have different sms formats and they may change over time. We can set the default patterns for some popular UPI apps and banks to make it easier for the user.
