### ISSUE TITLE
[FEATURE] Adding weekly in planned payments

### ISSUE THREAD

**Issue by anirban-1009** [Ivy-Apps/ivy-wallet#2838]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have weekly as a planned payment method

### Why do you need it?

- Weekly in th multiple times repeating planned payments

### How do you imagine it?

- In repears every block weekly shall be added where it's repeating every week i.e Monday - Friday
- Skipping Saturday and Sunday

**Comment by ILIYANGERMANOV** [comment]
That's a cool but unfortunately very hard to implement given our legacy data model
