### ISSUE TITLE
[FEATURE] Directly Open Google Drive When Clicking Backup

### ISSUE THREAD

**Issue by ariemay** [Ivy-Apps/ivy-wallet#2839]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to directly go to Google Drive when clicking backup data, so that I can store my backup without have to upload it manually

### Why do you need it?

- It will cut the process to save backup data in Drive
- No need to be afraid to lose backup data when the phone error

### How do you imagine it?

When clicking backup, there is a popup with option to store backup locally or in Google Drive. When clicking Google Drive, it will open existing GDrive app and save the backup in it

**Comment by ILIYANGERMANOV** [comment]
This feature should be implemented as a custom setting that's disabled by default. Some users have privacy and security concerns and wouldn't want that to happen automatically.
