### ISSUE TITLE
Some compose previews aren't showing

### ISSUE THREAD

**Issue by jgavir23** [Ivy-Apps/ivy-wallet#2848]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Be able to see compose previews

### Because...

- This will be useful to check the design changes without running it

### Description

When I tried to check the compose previews it doesn't show because it doesn't find the `IvyMaterial3Theme`. When the view is using the old `IvyWalletPreview` (ex: balance screen) it can be solved adding `implementation(projects.ivyDesign)` to the `build.gradle.kts`, but if the view is using the new `IvyPreview` (ex: Home tab screen) and the `implementation(projects.ivyDesign)` is added, it returns: `Failed to instantiate Composition Local`

### Success Criteria

- Be able to view all the compose previews in the project

**Comment by mokhtarmoustafa** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mokhtarmoustafa! 🎉
Issue #2848 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
