### ISSUE TITLE
[BUG] App starts on December 2023 instead of current month in 2024

### ISSUE THREAD

**Issue by ynshung** [Ivy-Apps/ivy-wallet#2853]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Happy new year 2024 everyone! There is a bug in 2024 where it will jump back and show transactions on December 2023 whenever the app is reopened.

### To Reproduce

1. Select month **January, 2024** at main screen
2. Close and reopen the app
3. The month will reset to **December** (2023)

### Expected behavior

The application should start with the current month (January, 2024) by default

### Smartphone

Android 13

**Comment by mokhtarmoustafa** [comment]
Im On It

**Comment by ivywallet** [comment]
⚠️ Hey @mokhtarmoustafa, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by mokhtarmoustafa** [comment]
OK Thanks

**Comment by ILIYANGERMANOV** [comment]
Approved @mokhtarmoustafa say the magic command again

**Comment by mokhtarmoustafa** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mokhtarmoustafa! 🎉
Issue #2853 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by mokhtarmoustafa** [comment]
@ynshung Could you please upload a video to give more details because i checked and everything is ok

**Comment by ynshung** [comment]
> @ynshung Could you please upload a video to give more details because i checked and everything is ok

Seems to be fixed by itself now, weird

I think this issue only happens for a while after going into the new year

Otherwise if the issue doesn't occur again after a few days, I'm closing the issue then

**Comment by ynshung** [comment]
Related to #3033
