### ISSUE TITLE
[BUG] Editing a category name from "Add planned payment form" screen does not work.

### ISSUE THREAD

**Issue by Subikesh** [Ivy-Apps/ivy-wallet#2855]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I'm not able to edit the category name when I'm trying to add a **planned payment** entry. Editing category works fine when done from other screens like adding income or expense. 

### To Reproduce

1. Open add planned payment screen. 
2. Add new income/expense
3. In choose category screen, long press any category to edit it. Make some changes and tap save.
4. The category name is not being updated after save.

### Expected behavior

The new category's name should be modified in place of old category. 

### Screenshots

![bug image before](https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/4ba6fd89-67dc-400e-bb08-ab08445344e5)
![bug image during](https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/989fe288-2b5e-49c0-8345-c9bbea135cee)
![Bug image after](https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/bdabc3d1-126b-4a47-a5f2-992bd842b96a)

### Smartphone

Pixel 6, Android 14

**Comment by Subikesh** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @Subikesh, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
approved

**Comment by Subikesh** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Subikesh! 🎉
Issue #2855 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
