### ISSUE TITLE
[BUG] The drop down/up arrow is inconsistent and upcoming expenses collapsible is confusing.

### ISSUE THREAD

**Issue by Subikesh** [Ivy-Apps/ivy-wallet#2858]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In the home page picture shown in the screenshots. the Upcoming expenses is collapsed with the up arrow. Whereas on top, where quick actions arrow is also collapsed but it is with down arrow. 

When I was using the app, I felt this was confusing. Especially because, the upcoming section has the up arrow and there was no distinction/divider between upcoming payments section and latest expenses section. So I often mistakenly read the latest expenses as upcoming expense.

Naturally if the view is collapsed, it should show down arrow (v). And if the view was expanded, it should show up arrow (^). 

This is just my suggestion. You can approve this if you feel the same.

### To Reproduce

1. Add some expenses and some planned payments.
2. After that observe the home page.

### Expected behavior

The upcoming expense arrow should point down(v) when collapsed. And it should point up(^) when expanded.

### Screenshots

![Arrows inconsistent bug](https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/22f6c4a2-282e-4f0c-8e81-625069f2d5d9)

### Smartphone

Pixel 6, Android 14

**Comment by beradeep** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @beradeep! 🎉
Issue #2858 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
