### ISSUE TITLE
[BUG] When clicking on back button in Privacy policy page it redirects the user to a repository. 

### ISSUE THREAD

**Issue by malirauf** [Ivy-Apps/ivy-wallet#2862]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

On the main screen, when you click on "Terms and Conditions" or "Privacy Policy," it opens a new screen displaying the respective policy. However, if you click the back button on this policy screen, it currently redirects you to the GitHub repository named "privacy-policies."

### To Reproduce

1. On main screen, click on privacy policy link.
2. On new screen click on back button.

### Expected behavior

 The expected behavior should be that it redirects the user back to the main screen from where they initially clicked on the "Privacy Policy" link.

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/59040625/c11c0e6f-a0ca-486f-8cc5-15b16f587a89

### Smartphone

Xiaomi Redmi Note 11, Android 12

**Comment by KMadhu479** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Clicking the "Privacy policy" opens the link in your default browser (app handling these types of links). In the case of the video that's the GitHub mobile app and effectively the GitHub app hijacks the "<" (Back) button. Thanks for the raising it!
