### ISSUE TITLE
[FEATURE] Tags

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [Ivy-Apps/ivy-wallet#2863]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to tag certain transactions to better manage my finances.

### Why do you need it?

Helps to segregate finances better. 

### How do you imagine it?

Phase 1
1) CRUD on Tag Entities
2) Ability to add multiple tags to transactions.
3) Report Filter Based on tags

Phase 2
1) Optional Separate screen for tags to view transactions associated with it quickly
2) Search based on tags

**Comment by Vishwa-Raghavendra** [comment]
I'm on it.

**Comment by ivywallet** [comment]
⚠️ Hey @Vishwa-Raghavendra, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Hey @Vishwa-Raghavendra if you're working on this say the magic words so the CI can assign it to you

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #2863 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Hey @Vishwa-Raghavendra feel free to open a draft PR so you can get feedback from the CI and at the same time, I'll be able to comment :)

**Comment by ILIYANGERMANOV** [comment]
Hey @Vishwa-Raghavendra any news on this one?

**Comment by Vishwa-Raghavendra** [comment]
Hey @nvllz 
Finding transactions based on tags is indeed possible (includes multi-tag search)
You can go to Reports -> Scroll to bottom and add the tags filter to find out about it
