### ISSUE TITLE
[BUG] The "Add payment" tile in quick settings does not work on android 14

### ISSUE THREAD

**Issue by mahdi-hosseinnion** [Ivy-Apps/ivy-wallet#2864]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In Android 14, when a user clicks on the "Add Payment" button in the quick settings the app will not be launched (nothing happens).

### To Reproduce

1. Run the app on a device or emulator running Android 14
2. Click on the "Add Payment" button in quick settings 

### Expected behavior

An instance of the app should be launched

### Smartphone

Pixel 7, Android 14

**Comment by mahdi-hosseinnion** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @mahdi-hosseinnion, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by mahdi-hosseinnion** [comment]
`startActivityAndCollapse(Intent)` function used in **PaymentTileService** to start **RootActivity** is deprecated and replaced with `startActivityAndCollapse(PendingIntent)`

**Comment by ILIYANGERMANOV** [comment]
Hey @mahdi-hosseinnion I approved the issue, comment the magic words and you can take it

**Comment by mahdi-hosseinnion** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mahdi-hosseinnion! 🎉
Issue #2864 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
