### ISSUE TITLE
Automatic backup to Google drive depending on frequency set by user[FEATURE] 

### ISSUE THREAD

**Issue by N1ghtmar6** [Ivy-Apps/ivy-wallet#2866]
### Please confirm the following:

- [x] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

A feature to login to your google drive account and app should be able to automatically backup data to gdrive. There should be an option to set the frequency of backup as well like daily, weekly, monthly etc

### Why do you need it?

- Manual backup to drive or to device is a tedious task
- This feature would make it easier for the user control the back up process

### How do you imagine it?

A feature to login to your google drive account and app should be able to automatically backup data to gdrive. There should be an option to set the frequency of backup as well like daily, weekly, monthly etc. Also an option to restore backup directly from gdrive if possible.

**Comment by mahdi-hosseinnion** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mahdi-hosseinnion! 🎉
Issue #2866 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Hey @mahdi-hosseinnion make sure to work with typed errors and you can get inspiration from this PR by https://github.com/Ivy-Apps/ivy-wallet/pull/2787

https://arrow-kt.io/learn/typed-errors/

**Comment by mahdi-hosseinnion** [comment]
Hey

I've been experiencing some unexpected delays due to a recent move. I'm currently in the process of unpacking and setting up my new home.

I know this isn't ideal, but I'm committed to complete this issue to the best of my ability.

I expect to have the issue done by the end of this weekend. I've already completed most of the work. I'll keep you updated on my progress.

Would it be possible to hold off on closing this issue until then?

Thank you for your understanding.

**Comment by emcee6798** [comment]
subscribing to updates here 
would love to take this up although time doesn't permit
would not mind paying a one time fee for this feature!

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

also make sure to read our developer guidelines

**Comment by ILIYANGERMANOV** [comment]
Duplicated of #2709
