### ISSUE TITLE
[FEATURE]  Schedule backup creation

### ISSUE THREAD

**Issue by victusforce** [Ivy-Apps/ivy-wallet#2868]
It would be great to a scheduled backup creation instead of manually creating backups. The frequency may be daily, weekly or monthly.

**Comment by Rex-0x7CB** [comment]
I would like to see this implemented as well. My workflow involves backing up data in a folder on my Android device which then auto-syncs to a remote backup server using Nextcloud. With this feature, I would only lose 1 day's worth of data in case the device is lost/stolen/corrupted.
Additionally, I won't have to put in the effort of manually backing up data.
