### ISSUE TITLE
Loans' missing date

### ISSUE THREAD

**Issue by atgfk** [Ivy-Apps/ivy-wallet#2869]
When creating a Loan, if you don't create a transaction associated with it, there's no way to tell when that loan was created

The solution would be to add the date of creation somewhere on the interface

![Screenshot_20240111_113818_Ivy Wallet.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/ccb3f859-c0e0-4d03-9bd1-9e1b55427571)

**Comment by beradeep** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @beradeep! 🎉
Issue #2869 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
