### ISSUE TITLE
[BUG] Import CSV from Bluecoins

### ISSUE THREAD

**Issue by singhgautam7** [Ivy-Apps/ivy-wallet#287]
**Describe the bug**
Bluecoins is not imported
![Screenshot_20211223-144726.jpg](https://user-images.githubusercontent.com/31505446/147218500-59a56f8e-2f79-4f03-a279-8a436a5fb47a.jpg)

**Comment by ILIYANGERMANOV** [comment]
Try "Manual CSV import"
