### ISSUE TITLE
[SUGGESTION] The save button for description in expense add screen is discrepant when adding and editing it.

### ISSUE THREAD

**Issue by Subikesh** [Ivy-Apps/ivy-wallet#2870]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I am adding an expense description initially when the field is empty, the button says **Add**. Whereas if I try to edit already entered description, then the button says **Save**. 

When I add a new description:
![adding description](https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/5d05d314-6fe6-4e1a-b659-e893d5c022a5)

When I edit already entered description:
![editing description](https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/f791103f-9bd6-443f-a700-7019ef3adc72)

I feel, when adding a description the button should say **Save** instead of **Add**. Because after adding the description, it only saves the description and routes back to form screen which says Add again.

### To Reproduce

1. Add an expense or edit already existing expense
2. Edit the description when it is empty and check the submit button
3. Edit the description when it is not empty and check the submit button

### Smartphone

Pixel 6

**Comment by ILIYANGERMANOV** [comment]
Having "+ Add" when there is no description and "Save" when there is one is the expected behavior by design
