### ISSUE TITLE
[FEATURE] Paid off loans visibility toggle

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2873]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have a simple toggle button in the loans screen. This way, the user could easily toggle between visibility of already paid off loans on the list.

### Why do you need it?

- Hide loans that have already been paid off
- A toggle on the bottom bar would provide easy access to the full loan history when needed

### How do you imagine it?

I imagine it as a toggle button next to the "Add Loan" button with an eye icon. This should be much easier to implement than a separate archive menu (https://github.com/Ivy-Apps/ivy-wallet/issues/2597), as we can use the `item.percentPaid` (which is a Double between 0 and 1) value to determine if the loan is already paid off, and check for it inside the for loop `for (item in state.loans)` in LoansScreen.kt.
I tried to implement it, but have problems with saving the current toggle state to memory.

**Comment by Vivekban** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vivekban! 🎉
Issue #2873 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
