### ISSUE TITLE
[BUG] title hitbox doesn't cover all-sized field

### ISSUE THREAD

**Issue by paajonk** [Ivy-Apps/ivy-wallet#2877]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Not sure that issue is a feauture-like, but is kinda annoying (title)

### To Reproduce

1. Make any transaction
2. Click on the right side of the field
3. Start going from right to left 

### Expected behavior

It should be clickable on all over this field, shouldn't it?

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/48648438/a68ebae4-6ba4-4370-9a0f-c35448f6a175

### Smartphone

Xiaomi Mi 11, Android 14

**Comment by pakka-papad** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @pakka-papad! 🎉
Issue #2877 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
