### ISSUE TITLE
[BUG] Top of the main screen (date) covers x3 place after changing date to view previous month 

### ISSUE THREAD

**Issue by backendan** [Ivy-Apps/ivy-wallet#2880]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I have attached the recording.
I pressed to change the date from current (January 2024) to December 2023
I went to home scree, starting to scroll down
And the date screen started to take x3 place
P.S. My phone is Oppo find x5, android version is 12

### To Reproduce

1. 

### Expected behavior

I should take same place as in January 2024

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/122120289/fe299e42-4f35-4a91-b69e-b9c38a6d0403

### Smartphone

Oppo find x5

**Comment by backendan** [comment]
I will regularly come check this issue to response to any comment or give any other information.

**Comment by ivywallet** [comment]
Thank you for your interest @nvllz! 🎉
Issue #2880 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
