### ISSUE TITLE
[FEATURE] Add a chart to view the overview expense

### ISSUE THREAD

**Issue by Devaraj10** [Ivy-Apps/ivy-wallet#2883]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to visualize the money flow including income and expense in app 

### Why do you need it?

- To know in which area I can cut down even more.
- To know the trending 

### How do you imagine it?

Like a piechart where for each category percentage is shown with respect to the net income.

**Comment by ILIYANGERMANOV** [comment]
Hey @Devaraj10 try clicking on your expense numbers - we already support pie charts. But more graphics are always welcome

**Comment by Devaraj10** [comment]
Hey @ILIYANGERMANOV I need a pie chart money spend on percentage with respect to the income for that particular month

**Comment by michalguspiel** [comment]
Hi, @Devaraj10 how would this work if your expenses exceed your income?
