### ISSUE TITLE
[BUG] Cards misalignment on the Categories screen

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2885]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Cards are not properly aligned. It's fine in the latest stable release.

### Screenshots

![f5ddc0eb-15e3-4922-a1e4-feee28ddc64b](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/5d0a8031-e50d-451f-bc6b-baccf7ed22cf)

### Smartphone

Galaxy S20+

**Comment by ILIYANGERMANOV** [comment]
Holy shit! That's very ugly 😬 Thanks for reporting! A bugfix will be greatly appreciated

**Comment by ivywallet** [comment]
Thank you for your interest @nvllz! 🎉
Issue #2885 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
