### ISSUE TITLE
Duplicate permission declaration in the AndroidManifest.xml file

### ISSUE THREAD

**Issue by malirauf** [Ivy-Apps/ivy-wallet#2888]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

"Duplicate permission declarations (android.permission.SET_ALARM and com.android.alarm.permission.SET_ALARM) in the AndroidManifest.xml file, indicating a potential redundancy or unnecessary inclusion."

### Expected behavior

To resolve the issue, remove the duplicate permission declaration (android.permission.SET_ALARM) to eliminate redundancy.

### Screenshots

![Screenshot 2024-01-23 100414](https://github.com/Ivy-Apps/ivy-wallet/assets/59040625/2e58df9d-e0cd-429b-b6c8-9ad68241c6d2)

### Smartphone

Samsung

**Comment by ILIYANGERMANOV** [comment]
@malirauf if this is still valid we can re-open it and you can submit a fix PR if you want

**Comment by malirauf** [comment]
Yes, it is still available. I accidentally closed it.

**Comment by malirauf** [comment]
Yes, please re-open it. I'll submit the PR.

**Comment by ILIYANGERMANOV** [comment]
Done, write the magic words and the CI will assist it to you

**Comment by malirauf** [comment]
I'm on it.

**Comment by malirauf** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @malirauf! 🎉
Issue #2888 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
