### ISSUE TITLE
[BUG] Loan Migration failure

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [Ivy-Apps/ivy-wallet#2891]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Loan Migration is failing.

### To Reproduce

1.  git reset  --hard 7e164455 
2. Add data with loans (a few transactions)
3. git pull (latest with main)
4. run

### Expected behavior

Migration should proceed Normally 

### Smartphone

AVD Pixel Android 10

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @Vishwa-Raghavendra, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
approved

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #2891 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
