### ISSUE TITLE
Image attachment

### ISSUE THREAD

**Issue by DeibisGM** [Ivy-Apps/ivy-wallet#2897]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

I would like the option to attach images to transactions. For instance, if I spend money at a restaurant, I want to be able to include a photo of the bill.

### Because...

I find it important to have the ability to attach images to transactions in my financial tracking. This feature would be especially useful for detailed record-keeping and verifying expenses. For example, attaching a photo of a restaurant bill not only helps me remember the specific occasion, but also serves as proof of the expense for budgeting and potential tax purposes. It adds a layer of transparency and accuracy to my financial management, making it easier to review and understand my spending habits over time.

**Comment by ivywallet** [comment]
Thank you @DeibisGM for raising Issue #2897! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by DeibisGM** [comment]
@ILIYANGERMANOV
