### ISSUE TITLE
[FEATURE] Show Budget in the catrgory screen

### ISSUE THREAD

**Issue by preet-hub** [Ivy-Apps/ivy-wallet#2898]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Can the budget progress bar be shown within the category anytime soon? We have to go all the way to the budget section to see the progress.

### How do you imagine it?

The progess to be tracked within the sub category.

**Comment by ivywallet** [comment]
Thank you @preet-hub for raising Issue #2898! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
