### ISSUE TITLE
[BUG] The "+" add button on the Home screen is missing

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2903]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Missing "+" on the Home tab.
Missing "+" on the Accounts tab.

### To Reproduce

1. Open the app.

### Expected behavior

The "+" button is shown.

### Smartphone

Samsung Fold4

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2903! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by YatinGarg07** [comment]
Hey @ILIYANGERMANOV I have solved this issue, please can i raise a new pr

**Comment by ILIYANGERMANOV** [comment]
Type the magic words so the CI can assign it and raise the PR
