### ISSUE TITLE
[FEATURE] Add the possibility to set accounts to a negative value when directly adjusting the current balance

### ISSUE THREAD

**Issue by Dantxo9** [Ivy-Apps/ivy-wallet#2907]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to treat some accounts as "Credit Card" accounts, which means they will have a negative balance. If I miss a couple expenses, it would be perfect to be able to directly set the balance of an account as a negative one to match the actual account balance. At the moment this can only be done adding an extra expense with the difference between Ivy Wallet balance and real balance. This involves doing maths separatedly, as the integrated calculator won´t allow the result to be a negative one either.

### Why do you need it?

- To have all accounts at hand, in my case I use 2 credit cards and 2 basic acounts. I usually pay daily expenses with the credit cards, which means they are always in credit or "negative". If I missed some expenses and I want to directly change the balance of an Ivy Wallet account to my real account amount, Ideally I would add this new value as a negative value, as it is credit. At the moment this cannot be done.

### How do you imagine it?

I guess adding a "-" button on the keyboard to add amounts, but I understand this may bring some issues to the actual expenses, as this means you´d be able to create "negative" expenses or negative incomes.
Maybe the accounts can be set as Basic Account or Credit Account, which means credit accounts are always shown as negative?

**Comment by ivywallet** [comment]
Thank you @Dantxo9 for raising Issue #2907! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by YatinGarg07** [comment]
I'm on it. Assign this issue to me.

**Comment by ivywallet** [comment]
Thank you for your interest @YatinGarg07! 🎉
Issue #2907 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
> I cannot run compose preview with ivy design system. can anyone tell me how can i use compose preview with this project?
> 
> Getting this error Render problem: java.lang.ClassNotFoundException: com.ivy.design.system.IvyMaterial3ThemeKt

Yeah, it's broken - can you try to fix it? It's probably some missing CompositionLocal

**Comment by YatinGarg07** [comment]
@ILIYANGERMANOV can you provide me some documentation on how to work with custom design systems

**Comment by ILIYANGERMANOV** [comment]
@YatinGarg07 idk, search on Google or ask ChatGPT they'll be more helpful than me 😄

**Comment by tomriddle25** [comment]
@YatinGarg07 @ILIYANGERMANOV is this issue still being worked upon?

**Comment by Jack-Works** [comment]
this is possible today, I think this can be closed
