### ISSUE TITLE
Bring Budget option on the home screen 

### ISSUE THREAD

**Issue by rounit-k-verma** [Ivy-Apps/ivy-wallet#2908]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want budget option on the home screen. It will increase the visibility of the budget.

### Why do you need it?

It will increase the visibility of budgets.

### How do you imagine it?

Add budget icon  at the bottom.

**Comment by ivywallet** [comment]
Thank you @rounit-k-verma for raising Issue #2908! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Must be controlled by a on/off setting in Settings because not all users might want this. Use `Features` from our `ivy-domain` module and make this setting by default off.

**Comment by rounit-k-verma** [comment]
Thanks a lot

**Comment by Vivekban** [comment]
@ILIYANGERMANOV I having difficulty in understanding what UI changes are required. In the bottom bar right now there are 3 buttons, If we add one more it will change dynamic of the bottom bar as there is a plus button in the center. Let me know how you visualise it.

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV I having difficulty in understanding what UI changes are required. In the bottom bar right now there are 3 buttons, If we add one more it will change dynamic of the bottom bar as there is a plus button in the center. Let me know how you visualise it. 

I imagine adding some special time of card like the customer journey ones but for budget. And by default it should be disabled (show this only if the user specifically enables it)

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV I having difficulty in understanding what UI changes are required. In the bottom bar right now there are 3 buttons, If we add one more it will change dynamic of the bottom bar as there is a plus button in the center. Let me know how you visualise it. 

I imagine adding some special time of card like the customer journey ones but for budget. And by default it should be disabled (show this only if the user specifically enables it)

**Comment by Vivekban** [comment]
@ILIYANGERMANOV Can you please let me know what should be title, description, background
```
CustomerJourneyCardModel(
            id = "budget",
            condition = { trnCount, _, _ ->
               // if enabled right?
            },
            title = ?,
            description = ?
            cta = ?
            background = Gradient.solid(Red3) or anything else,
            hasDismiss = true,
            onAction = { _, _, ivyActivity ->
                ivyActivity.goToBudget()
            }
        )
```

**Comment by ILIYANGERMANOV** [comment]
No idea @Vivekban, I think we should ask @rounit-k-verma what he expects from this task? Also, please don't use the CustomerJourney cuz it's a legacy code with the purpose for dismissable temporary cards. I think @rounit-k-verma was looking for a performanent bugets entrypoint on the Home screen.

I think it might be a better idea to jump on some other better defined issue (idk if such exists) I usually blindly approve GitHub Issues that are well-formatted 😅

**Comment by ILIYANGERMANOV** [comment]
@Vivekban this one is well defined https://github.com/Ivy-Apps/ivy-wallet/issues/2923
