### ISSUE TITLE
[BUG] Incorrect addition on account transfer

### ISSUE THREAD

**Issue by pravissw** [Ivy-Apps/ivy-wallet#2910]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

One of my accounts had a balance of 32.45€. I transferred 167.55€ from another account to make it 200€. Adding this on ivy wallet somehow results in ivy showing a balance of 199€ in the first account.

I modified the amount of the account transfer on ivy wallet to observe some funny results, pfa some screenshots. The same error is also there if I change the amount to 67,55 (the total should be 100€ but it shows 99€)

### To Reproduce

Add an account transfer to make the balance a multiple of 100

### Expected behavior

The new balance should be exact

### Screenshots

![Screenshot_2024-02-02-10-23-50-84_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/40398726/7491a4dc-5221-4721-a9a2-150fff701036)
![Screenshot_2024-02-02-10-23-40-33_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/40398726/56a0e98a-9245-4ebb-99c0-185c3f459630)
![Screenshot_2024-02-02-10-16-43-13_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/40398726/8b24bbb7-a671-4733-872f-a63d0117a8b6)
![Screenshot_2024-02-02-10-16-28-93_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/40398726/0739fc04-e121-4c95-814b-cea6ca5e9701)
![Screenshot_2024-02-02-10-16-14-58_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/40398726/3da79241-edf5-4188-89f7-cfc02e63ad08)
![Screenshot_2024-02-02-10-16-07-47_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/40398726/da679408-6eb7-4793-8380-77c266e9c819)

### Smartphone

OnePlus Nord CE 2

**Comment by ivywallet** [comment]
Thank you @pravissw for raising Issue #2910! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Vishwa-Raghavendra** [comment]
Hey @ILIYANGERMANOV 
I would like to work on this but this would result in re-write of calculation methods 
As we have a lot of deprecated methods / Act for it

Acceptable for re-work?

**Comment by ILIYANGERMANOV** [comment]
> Hey @ILIYANGERMANOV 
> I would like to work on this but this would result in re-write of calculation methods 
> As we have a lot of deprecated methods / Act for it
> 
> Acceptable for re-work?

Hey @Vishwa-Raghavendra, ideally, we should rewrite them in `:shared:domain` as use-cases + unit tests and having the new domain model.

You can also fix the old ones if you wish but at one point they'll be thrown away

**Comment by ILIYANGERMANOV** [comment]
@Vishwa-Raghavendra that's perfect! The old ones are garbage, just make sure that the new are:
- type-safe
- do **not** throw exceptions, use `Either`
- make them type-safe
- simple
- main-safe (computations happen on a background thread)

Also check #2990

**Comment by Vishwa-Raghavendra** [comment]
Sure @ILIYANGERMANOV

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #2910 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Hey @Vishwa-Raghavendra did you find anything about this one? I'm considering if we can release the current GitHub version to Beta
