### ISSUE TITLE
[BUG] Balance row text alignment

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2927]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Just tried a recent nightly build and the first thing I noticed was a slight value misplacement for the balancerow strings.

### Expected behavior

Vertically align the value and currency code in the BalanceRow.

### Screenshots

![67b8a09c-8a89-45df-9234-dd5fc586a335](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/2fc06aff-5ca1-4cc1-a849-8bc5178b0695)

### Smartphone

Galaxy S23

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #2927! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by sandeepjak2007** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @sandeepjak2007! 🎉
Issue #2927 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by sandeepjak2007** [comment]
![Screenshot_20240208_121821](https://github.com/Ivy-Apps/ivy-wallet/assets/16497904/0f1cf010-34c4-42b5-8289-a771f6cd50dc)

@nvllz is this page or the content you are pointing to change?

If not can you suggest the correct page or the steps to reproduce?

**Comment by sandeepjak2007** [comment]
@nvllz **Is this a correct solution?** 

_Am I getting you the right?_

If not can you or someone elaborate on this so that I can work on it and give the correct result?

![ivy-2](https://github.com/Ivy-Apps/ivy-wallet/assets/16497904/cdbfe617-33a9-4513-9855-c6487066e971)

**Comment by ILIYANGERMANOV** [comment]
> @nvllz **Is this a correct solution?**
> 
> _Am I getting you the right?_
> 
> If not can you or someone elaborate on this so that I can work on it and give the correct result?
> 
> ![ivy-2](https://private-user-images.githubusercontent.com/16497904/303315099-cdbfe617-33a9-4513-9855-c6487066e971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTM3NTcsIm5iZiI6MTcwNzM5MzQ1NywicGF0aCI6Ii8xNjQ5NzkwNC8zMDMzMTUwOTktY2RiZmU2MTctMzNhOS00NTEzLTk4NTUtYzY0ODcwNjZlOTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDExNTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ODEzOGYxODUwYTU5NTdkOTk1NDVkODc1MmQyN2MwZDM5NGViY2VmZDZjNzI4ZmU2NzE5ZDkzNzJiMjFkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GlJVYuvCQKCCk5Vqlca1vqknQHRN2zRHKFNMYvw7JBU)

@sandeepjak2007 I think @nvllz is referring that the currency "USD" is not aligned well with the 1.00 number (baselines of the text aren't aligned) but what you've built loos good actually - you can submit a PR.with it 👍

**Comment by sandeepjak2007** [comment]
@ILIYANGERMANOV Haven’t pushed yet the code.

Can I create another?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV Haven’t pushed yet the code.
> 
> Can I create another?

Ofc, feel free to do so!
