### ISSUE TITLE
Implement the `FakeAccountDao` 

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2931]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Implement the `FakeAccountDao` to mirror 1:1 the real behavior of `AccountDao` and `WriteAccountDao`.

### Because...

- Enable use the `AccountRepository` in Unit tests.

### Description

1. Implement the methods in the fake dao
2. Look the real SQL queries and try to mirror the behavior.
3. Cover the fake dao with unit tests.

### Success Criteria

- The fake dao is implemented and behaves like the real SQL dao.
- The fake dao is covered with unit tests.

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2931! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Rick-AB** [comment]
@ILIYANGERMANOV don't we have these already or am I missing something?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV don't we have these already or am I missing something?

Yeah, I created it before seeing your changes 😀 Do we have unit tests for the fake dao? Maybe that can be the last missing bit @Rick-AB

**Comment by Rick-AB** [comment]
> > @ILIYANGERMANOV don't we have these already or am I missing something?
> 
> Yeah, I created it before seeing your changes 😀 Do we have unit tests for the fake dao? Maybe that can be the last missing bit @Rick-AB

oh yh, there are no tests for any of the faka dao

**Comment by Rick-AB** [comment]
@ILIYANGERMANOV where should the tests be placed? I'm looking to pick this up

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV where should the tests be placed? I'm looking to pick this up

Where the repository tests are in the `:shared:data` test source set

**Comment by Rick-AB** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Rick-AB! 🎉
Issue #2931 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
