### ISSUE TITLE
Implement `FakeCategoryDao`

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2932]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Implement the `FakeCategoryDao` to mirror 1:1 the real behavior of `CategoryDao` and `WriteCategoryDao`.

### Because...

- Enable use of the `CategoryRepository` in Unit tests.

### Description

1. Implement the methods in the fake dao.
2. Look at the real SQL queries and try to mirror the behavior.
3. Write unit tests for the fake dao.

### Success Criteria

- The fake dao is implemented and behaves like the real SQL dao.
- The fake dao is covered with unit tests.

**Comment by Rick-AB** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Rick-AB! 🎉
Issue #2932 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
