### ISSUE TITLE
Implement `FakeTransactionDao`

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2933]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Implement the `FakeTransactionDao` to mirror 1:1 the real behavior of `TransactionDao` and `WriteTransactionDao`.

### Because...

- Enable use of the `TransactionRepository` in Unit tests.

### Description

1. Implement the methods in the fake dao.
2. Look at the real SQL queries and try to mirror the behavior.
3. Cover the fake dao with unit tests.

### Success Criteria

- The fake dao is implemented and behaves like the real SQL dao.
- The fake dao is covered with unit tests.

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2933! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Rick-AB** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Rick-AB! 🎉
Issue #2933 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by AMHaroun** [comment]
Hey @Rick-AB do you mind if I take over this issue? I'd like to get more experience writing tests. If you've already done some work please don't hesitate to say no.

**Comment by Rick-AB** [comment]
Hi @AMHaroun I'm already finished with the tests, but I'm sure you can pick up whichever one comes up next
