### ISSUE TITLE
[FEATURE] Remembering the scroll position for Accounts and Categories screens

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2938]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I want the Accounts and Categories screens to retain the scroll position when I go back from the Details dialog. 

Now both screens don't preserve the list position (when going back the list is scrolled to the top):

https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/104d7669-f762-45ac-a92c-00a9015926d8

### Why do you need it?

It would be much more intuitive to have these menus work this way. Especially if one's got a long list of items.

### How do you imagine it?

I want it to work the same way as in the dashboard screen, so when I go back from the transaction details dialog, the list position is preserved.

https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/46416377-e953-4f01-8d0d-7d2e693a8749

**Comment by anuraganandwork** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @anuraganandwork! 🎉
Issue #2938 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by madhavbhavsar** [comment]
Hey, Did you found anything? @anuraganandwork . I found this but its not working 

        val listState = rememberScrollPositionListState(
            key = "home_lazy_column",
            initialFirstVisibleItemIndex = ivyContext.transactionsListState
                ?.firstVisibleItemIndex ?: 0,
            initialFirstVisibleItemScrollOffset = ivyContext.transactionsListState
                ?.firstVisibleItemScrollOffset ?: 0
        )

I tried to change the key, and context.liststate, and then setted it to lazycolumn's state, but its not working.

**Comment by madhavbhavsar** [comment]
Hey @ILIYANGERMANOV , I solved the above issue like this.

```
  var listState = rememberLazyListState()
    if (!state.accountsData.isEmpty()){
        listState = rememberScrollPositionListState(
            key = "accounts_lazy_column",
            initialFirstVisibleItemIndex = ivyContext.accountsListState?.firstVisibleItemIndex ?: 0,
            initialFirstVisibleItemScrollOffset = ivyContext.accountsListState?.firstVisibleItemScrollOffset ?: 0
        )
    }

  LazyColumn(
        modifier = Modifier
            .fillMaxSize(),
            state = listState,
    ) { }
```
I'm not able to find another way.

**Comment by ILIYANGERMANOV** [comment]
> Hey @ILIYANGERMANOV , I solved the above issue like this.
> 
> ```
>   var listState = rememberLazyListState()
>     if (!state.accountsData.isEmpty()){
>         listState = rememberScrollPositionListState(
>             key = "accounts_lazy_column",
>             initialFirstVisibleItemIndex = ivyContext.accountsListState?.firstVisibleItemIndex ?: 0,
>             initialFirstVisibleItemScrollOffset = ivyContext.accountsListState?.firstVisibleItemScrollOffset ?: 0
>         )
>     }
> 
>   LazyColumn(
>         modifier = Modifier
>             .fillMaxSize(),
>             state = listState,
>     ) { }
> ```
> I'm not able to find another way.

Hey @madhavbhavsar that should be fine. Submit a PR, and I'll review you it

**Comment by madhavbhavsar** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @madhavbhavsar, this issue is already taken by @anuraganandwork.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@madhavbhavsar say the magic words again

**Comment by madhavbhavsar** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @madhavbhavsar! 🎉
Issue #2938 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
