### ISSUE TITLE
[BUG] Theme switching in the Quick Access menu doesn't work

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2939]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Quick access theme switch does not work.

### Expected behavior

Tapping the switch should toggle between the Auto/Light/Dark theme options.

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/7c5ae417-70fd-4589-8315-431df9ddd760

### Smartphone

Galaxy s20+

### Additional context

Works well in the latest stable release.

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #2939! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by michalguspiel** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @michalguspiel! 🎉
Issue #2939 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
