### ISSUE TITLE
Region Aware Display Of Amounts

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#294]
Amounts displayed should be region aware. For eg, In India we call 100 thousand as 1lakh,  and 1 million as 10lakhs, 10million as 1crore and so on. The numbers are also displayed differently. For eg: In US one will write 100 thousand as 100,000. In since 100k is called 1lakh, we write it as 1,00,000. 

Similarly I am sure other regions will have their onw way and terms to use with numbers. It would be great if Ivy could display the numbers specific to their native region.

**Comment by prince737** [comment]
Below is a javascript example of what I am looking for:
```
const event = 100000;
console.log(event.toLocaleString('en-IN'));
//OP: "1,00,000"
```

In-app this should convert from `209.62k` to something like `2.0962l`
