### ISSUE TITLE
[BUG] Sorting categories by balance amount works incorrectly

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2940]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Sorting by balance amount in the Categories list screen with negative balances can result in the wrong order. Currently, the app seems to ignore whether the value is positive or negative and sorts by the absolute value, which is not intended in this case.

### To Reproduce

Reproduce the screenshot state with sorting by balance in the Categories screen.

### Expected behavior

In this case, the negative values should appear at the bottom of the list in reverse order, so that the list looks like this:
Shopping
Clothes
Investments
Car
Groceries
...

### Screenshots

![3936fabe-1fe9-437f-b7a3-2b2cd682339b](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/5111d854-0a0c-4e69-abe9-556ce721c355)

### Smartphone

Galaxy s20+

### Additional context

It's worth noting that in this scenario each category has only one entry, which is equal to the displayed value.

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #2940! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by madhavbhavsar** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @madhavbhavsar! 🎉
Issue #2940 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
