### ISSUE TITLE
[BUG] Change savings goal has no effect

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2941]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

It's not possible to change the Savings goal value.

### To Reproduce

Expand the top menu and try changing the Savings goal value.

### Expected behavior

Savings should be updated when confirmed.

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/d102553d-a45f-466d-87fd-256a8ee2a08a

### Smartphone

Galaxy s20+

### Additional context

Works well in the latest stable release.

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #2941! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by sandeepjak2007** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @sandeepjak2007! 🎉
Issue #2941 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
