### ISSUE TITLE
[BUG] Crash when trying to edit loan main transaction details

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2942]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When trying to edit the Main Transaction details (associated with a loan), the app crashes.

### To Reproduce

1. Create a loan record with 'Main Transaction' checked
2. Go back to the dashboard and tap on the transaction to open the detail screen
3. Attempt to edit the name/description

### Smartphone

Galaxy s20+

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #2942! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by sandeepjak2007** [comment]
Hi @nvllz & @ILIYANGERMANOV 

It's related to the version issue of compose-material3. When I changed the compose-material3 version from 1.1.2 to 1.2.0, this issue may have been fixed. Please find the related video as attached. 

https://github.com/Ivy-Apps/ivy-wallet/assets/16497904/0d0a4997-ccfc-41a9-abe1-16a52cb473bd

issue Supported article: https://stackoverflow.com/questions/77877363/no-virtual-method-atljava-lang-objectilandroidx-compose-animation-core-keyfra

As it's related to version. can I create a pr or it

**Comment by sandeepjak2007** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @sandeepjak2007! 🎉
Issue #2942 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by sandeepjak2007** [comment]
@nvllz, kindly review and confirm if this issue has been resolved. Additionally, please verify if the fix has not impacted any other functionalities. Your feedback is appreciated.
