### ISSUE TITLE
SMS parsing for keeping track of transactions 

### ISSUE THREAD

**Issue by just-jhanvi** [Ivy-Apps/ivy-wallet#2945]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to let the SMS parsing feature read my sms and automatically register the transactions that took place. Then according to distribute the transactions to either income or expense 

### Why do you need it?

- Manually adding entries is a hassles and a lot of tiny transactions are missed

**Comment by ivywallet** [comment]
Thank you @just-jhanvi for raising Issue #2945! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by g-kartik** [comment]
Yes it is difficult to track small and frequent transactions manually. This feature is very useful.
