### ISSUE TITLE
[BUG] Read me file issue

### ISSUE THREAD

**Issue by sandeepjak2007** [Ivy-Apps/ivy-wallet#2946]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Some contents in read-me file are not loading

### To Reproduce

1. Go to ivy-wallet read-me file.
2. Under the creative contributor's wall some items are not loading. 

### Screenshots

<img width="801" alt="Screenshot 2024-02-11 at 2 23 55 PM" src="https://github.com/Ivy-Apps/ivy-wallet/assets/16497904/64ca5c31-2d81-4612-ac68-a4af899b2a88">

### Smartphone

Any phone

**Comment by ivywallet** [comment]
Thank you @sandeepjak2007 for raising Issue #2946! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by sandeepjak2007** [comment]
I am on it.

**Comment by ivywallet** [comment]
Thank you for your interest @sandeepjak2007! 🎉
Issue #2946 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
