### ISSUE TITLE
[FEATURE] Add Budget Time Frames

### ISSUE THREAD

**Issue by JaviMuller** [Ivy-Apps/ivy-wallet#2954]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to set a time frame for a budget. I want to be able to make weekly, monthly, anual  or custom time frame budgets, maintaining the options already available.

### Why do you need it?

- I make my general budget annually with anual goals.
- When I do voyages that may span multiple weeks, I would like to be able to set the budget for the trip even if it is the last week of the month and the first week of the new one.
- Being able to budget in advance for expenses that are expected in coming months

### How do you imagine it?

In the budget page, being able to select a start and end date to show the budgets that are either contained or that contain that time frame (probably the second would make more sense).

When adding a new budget, making it a monthly budget by default (to keep current user experience), but being able to alter both the start and the end date of that budget entry.

Adding some visual representation (e.g. lower transparency or text color) to show when a budget due date has already been surpassed.

**Comment by ivywallet** [comment]
Thank you @JaviMuller for raising Issue #2954! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
