### ISSUE TITLE
[Data Layer] Migrate the code to use the new the `CategoryRepository`

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2962]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Utilize `CategoryRepository` for data manipulation operations
- Transition from direct `CategoryDao` and `WriteCategoryDao` interactions to using the repository

### Because...

- To phase out the old data management system
- To maintain uniformity in our architectural approach
- To enhance safety and facilitate ease of future extensions

### Success Criteria

- Comprehensive unit testing
- Seamless operation of existing functionalities without regressions
- Stable application functionality with the integrated new data layer

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2962! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by diasmashikov** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @diasmashikov! 🎉
Issue #2962 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by priyatanu** [comment]
I would like to work on it

**Comment by priyatanu** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @priyatanu! 🎉
Issue #2962 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@priyatanu are all usages of CategoryDao and WriteCategoryDao outside the data layer migrated to the repo?
