### ISSUE TITLE
[Performance] Fix Unstable composables

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2965]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Ivy Wallet is full of unstable composables that make the app slow.
- We should fix that by making the unstable parameters - stable.

### Because...

- The app slow and lags when scrolling (losing frames) or animating.

### Description

1. Remove the unstable Composables baseline from https://github.com/Ivy-Apps/ivy-wallet/blob/main/ci-actions/compose-stability/ivy-compose-stability-baseline.txt
2. Submit a draft PR so the "Compose stability" CI can execute and fail
3. See the failure in the Compose Stability workflow - it'll show you which composable is unstable and what parameters cause that.

**Fixing unstable composable**
1. Identify unstable parameters (the Compose Stability action will tell you)
2. Fixing an unstbale parameter: (best to worse)
- Replace it with a primitive (e.g. String, Int, Double, ...)
- Replace `List` / `Set` with `ImmutableList` / `ImmutableSet` from kotlinx Immutable collections
- Explicitly mark as `@Immutable` or `@Stable` for classes

Read this https://developer.android.com/jetpack/compose/performance/stability.

Fix stability issues guide: https://developer.android.com/jetpack/compose/performance/stability/fix

### Success Criteria

- Compose Stability CI action passes.
- You have fixed at least three unstable Composables.
- The app works as expected and doesn't crash.

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2965! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Note: Even if you fix 2 Composables it's still very helpful! But... in general the more you can fix the better 😄

**Comment by AMHaroun** [comment]
im on it

**Comment by AMHaroun** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Thank you @AMHaroun for fixing some composables! 🙌 I re-opened the issue since there are more. Help is still wanted and much appreciated. I'll keep re-opening until we fix all composables and completely remove the baseline

**Comment by ILIYANGERMANOV** [comment]
Bonus points: if we can prioritize the transactions list that's used on the Home screen. It's about replacing `BigDecimal` -> `Double` in the viewStates and the ViewModel + replacing `LocalDateTime` -> `String` and doing the date formatting in the ViewModel. It's a bigger change but this is the way to fix the scrolling performance

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

**Comment by ILIYANGERMANOV** [comment]
No longer needed after K2 enables Stong Skipping
