### ISSUE TITLE
[Data Layer] Re-work `SyncExchangeRatesAct` to repository and use-case

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2966]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- This legacy class https://github.com/Ivy-Apps/ivy-wallet/blob/main/temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/exchange/SyncExchangeRatesAct.kt refactored to UseCase, Repository, DataSource
- The above covered with unit tests 
- The above covered wirh integration tests (androidTest)
- The above being type-safe and using Arrow Typed-Erroea

### Because...

- getting rid of legacy code
- safety, stability and maintainability
- migration to our new architecture

### Description

1. Check https://github.com/Ivy-Apps/ivy-wallet/blob/main/temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/exchange/SyncExchangeRatesAct.kt
2. In `:shared-data` create `ExchangeRatesRepository` that:
- Fetches exchange rates from a `RemoteExchangeRatesDataSource` (the Ktor request)
- Can save exchange rates locally in room using directly the daos that we already have
- Can save exchange rates overrides
- Can read exchange rates
- It should map DB exchange rates entity to a new domain model that is - type-safe and explicitly defined! (see our `data.model` package)
3. In `:shared-domain` create `SyncExchangeRatesUseCase` without inherenting anything and simply adding some `suspend fun sync()` method (does the same as https://github.com/Ivy-Apps/ivy-wallet/blob/main/temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/exchange/SyncExchangeRatesAct.kt)
4. Cover the above with unit tests
5. Cover the use-case with integration tests
6. Migrate https://github.com/Ivy-Apps/ivy-wallet/blob/main/temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/exchange/SyncExchangeRatesAct.kt usages and delete it.

### Success Criteria

- Read https://arrow-kt.io/learn/typed-errors/working-with-typed-errors/ and make sure to work with typed-errors. **Do NOT throw exceptions, use Either from Arrow**
- Cover all classes written with unit tests using given-when-then styling (see existing tests)
- Cover the use case with an integration test (see how androidTest is setup in `:shared:data` + you must update the Integration Test GitHub Action workflow because currently it runs integration tests only for `:shared:data`)
- The legacy code about exchange rates is deleted and the app works as before but using `SyncExchangeRatesUseCase` and the `ExchangeRatesRepository`

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2966! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by AMHaroun** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @AMHaroun! 🎉
Issue #2966 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
