### ISSUE TITLE
[FEATURE] Allow adding categories to Transfers

### ISSUE THREAD

**Issue by ankitjavalkar** [Ivy-Apps/ivy-wallet#2971]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to add Categories to Account Transfers.

Note: I notice several older issues for such a feature, but the feature is not live or available in the app. 

### Why do you need it?

- It is a useful feature to differentiate between different transfer transactions
- This features makes this app pretty much a drop in replacement for Financisto

**Comment by ivywallet** [comment]
Thank you @ankitjavalkar for raising Issue #2971! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by diasmashikov** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @diasmashikov! 🎉
Issue #2971 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
