### ISSUE TITLE
[BUG] Loans payment left to pay balance left incorrect using latest demo

### ISSUE THREAD

**Issue by technificentConsulting** [Ivy-Apps/ivy-wallet#2973]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Create loan with balance of $500. Create  main transaction increases left to pay remains the same should be $300 now.

### To Reproduce

1. Create loan with balance of $500. Create  main transaction increase of $50.  Add main transaction interest $200.  Add main transaction decrease $200.  
Left to pay says $200 but should be $250.
Add another main transaction increase of $50 left to pay remains tge same should be $300 now.

### Expected behavior

 Left to pay should be $300 now

### Screenshots

![Screenshot_20240219_122758_Ivy Wallet Demo](https://github.com/Ivy-Apps/ivy-wallet/assets/24426012/c1ca5715-939f-4eea-b4eb-aa245e2d15bf)
[](url)
![Screenshot_20240219_122119_Ivy Wallet Demo](https://github.com/Ivy-Apps/ivy-wallet/assets/24426012/75402118-09fc-4e5c-8f26-f37159795e92)

### Smartphone

Samsung ZFold3

**Comment by ivywallet** [comment]
Thank you @technificentConsulting for raising Issue #2973! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by sandeepjak2007** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @sandeepjak2007! 🎉
Issue #2973 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #2973 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
