### ISSUE TITLE
 Ledger In loans (Add Debit/Credit Transaction) in loan Section 

### ISSUE THREAD

**Issue by mightythor2019** [Ivy-Apps/ivy-wallet#2975]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

1.  Please add a feature of adding multiple Debit or Credit transaction in a single loan account.

### Because...

Because Some time or most of the time we need to give or borrow some amount from the same person once again without Clearing the previous balance.

For an example: If we Lent some Amount (₹500) to person 'A' and after some time for some situations again we need to Lent some amount let say (₹200) to them.

In this case in total we Lent them ₹700 in two transactions or events.

But in the existing features of the ivy wallet there no option to add this type of transactions.
It does not allow to add another debit transaction to a existing lending loan Account.

If I want to add a second lending transaction to the same person it s
Does not allow me to add on the same loan account perviously made.

All I need to make a new Loan account of the same person which makes a lot of confusion.

### Description

I thought if this Feature added to the ivy wallet it will be 1 step closer to become a complete budget application.

### Success Criteria

I am not a coder or app developer

All I am is a heavy user of the ivy wallet.

I can suggest to add features to enhance the productivity of the app.

If the app work on the suggestions I made... Definitely will will become the no 1 app for the personal Finance.

**Comment by ivywallet** [comment]
Thank you @mightythor2019 for raising Issue #2975! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
