### ISSUE TITLE
[BUG in Adding transaction in Loan Account] 

### ISSUE THREAD

**Issue by mightythor2019** [Ivy-Apps/ivy-wallet#2981]
### Please confirm the following

- [x] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Hello, there is a bug in the Demo version 4.5.0(150) of the Ivy wallet.

When adding a loan account, for example, lending $500 to a person from an account in the app and marking it as a main transaction, it correctly shows as an expense on the main page.

However, if we increase the loan amount by lending $200 more to the same person without clearing the previous balance and mark it as a main transaction, the app incorrectly categorizes it as an income transaction on the main and account pages. It should be recognized as an expense, as we are lending more money. Currently, the amount increases instead of decreasing.

Please fix this issue.

### To Reproduce

1.) I lended $400 to a person 'A' with my bank 'ABC'
 And when I see this transaction in the bank 'ABC' ledger in the Account section . It shows as this transaction as an expense (debit) transaction. And it is good and expected output.

2.)  But If I again add $100 as **Increase** in lending amount,  it means I have given more money to the same person. 

This time also the amount in the bank account from where I have given the amount to that person should be decreased.

But when we check the transaction in the bank section we find the amount got increased instead of decreasing.

### Expected behavior

Expected behaviour

The amount in the main bank account from where we have lended the person once again that transaction should also be marked as debit transaction (expenses Transaction)

### Screenshots

![Screenshot_20240223-011003](https://github.com/Ivy-Apps/ivy-wallet/assets/160373272/9d82bb1b-21e0-41e8-afe3-0e0bb3d4ae1b)
![Screenshot_20240223-012004](https://github.com/Ivy-Apps/ivy-wallet/assets/160373272/62ce8a95-3713-4031-9e27-da78ad4781fb)
![Screenshot_20240223-012024](https://github.com/Ivy-Apps/ivy-wallet/assets/160373272/75e0d219-a563-400a-8c28-167a7ce97faa)

### Smartphone

Pixel 6a

**Comment by ivywallet** [comment]
Thank you @mightythor2019 for raising Issue #2981! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by mightythor2019** [comment]
Any update on this issue??? @ILIYANGERMANOV @ivywallet

**Comment by ILIYANGERMANOV** [comment]
> Any update on this issue??? @ILIYANGERMANOV @ivywallet

Nope, I don't see contributors expressed interest to fix it

**Comment by Vishwa-Raghavendra** [comment]
I'm on it.

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #2981 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
