### ISSUE TITLE
[FEATURE] German Language Support

### ISSUE THREAD

**Issue by jh4097** [Ivy-Apps/ivy-wallet#2983]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to use the app through German.

### Why do you need it?

- it would expand the potential userbase

### How do you imagine it?

It would be all the English UI elements translated into German.

**Comment by jh4097** [comment]
I'm on it

**Comment by jh4097** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
@jh4097 say the magic words again 😀

**Comment by jh4097** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @jh4097! 🎉
Issue #2983 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by jh4097** [comment]
I've translated the strings.xml file and am trying to build an APK in android studio to test it as per the contributing guidelines, but cannot get it to work. I have never used android studio before so have no clue what I'm doing. Is there any easier way for me to test it?

**Comment by ILIYANGERMANOV** [comment]
@jh4097 submit a draft PR and let the CI build one APK for you

**Comment by ov3rk1ll** [comment]
@jh4097 are you still working on this?

Otherwise I'd happy to continue work on your PR to add the missing translations.

**Comment by jh4097** [comment]
@ov3rk1ll apologies no, I am not and have forgotten to unassign myself. I will comment the file with my already completed translations and unassign myself momentarily. (It should be pretty much finished, but of course feel free to read over it and make changes where needed)

**Comment by jh4097** [comment]
In order to upload it here, I've converted my .xml file to a .txt .
[strings.txt](https://github.com/Ivy-Apps/ivy-wallet/files/14885502/strings.txt)

**Comment by jh4097** [comment]
Having just read over it I thing the only issue with those translations is "Kosten" for expenses could more commonly be translated with the synonym "Ausgeben", however there may be one or two smaller details

**Comment by ov3rk1ll** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ov3rk1ll! 🎉
Issue #2983 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
