### ISSUE TITLE
[BUG] No paddings between Accounts when creating a transaction

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2986]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

![Screenshot_20240225_002402_Ivy Wallet Demo](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/321bf0c0-c7eb-4bda-952c-d2381c02e7c5)

### To Reproduce

1. Tap the "+"
2. Add expense

### Expected behavior

There's `8dp` padding between the accounts

### Smartphone

Doesn't matter

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2986! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by narojunagaraju** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @narojunagaraju! 🎉
Issue #2986 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
