### ISSUE TITLE
[FEATURE] Add Missing Feedback for Unselected 'To' Account in Account Transfer

### ISSUE THREAD

**Issue by diasmashikov** [Ivy-Apps/ivy-wallet#2987]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have feedback if I have not selected to which account I am sending my money 

Attaching the video of the issue:

https://github.com/Ivy-Apps/ivy-wallet/assets/50723693/a6204f2e-f446-4f85-a109-c901ed20002d

### Why do you need it?

- When I first used the application, I wanted to test its functionality, so I attempted to transfer money. However, it didn't work. Initially, I thought it might be a bug, but then I realized that I had forgotten to specify the destination account for the transfer. This experience made me think that new users might encounter similar issues.

- Furthermore, users who frequently transfer money might automatically assume they are sending funds to their usual account. They could end up confused when pressing the "Add Account" transfer button does not initiate the transfer, not realizing immediately that they have not selected an account to transfer the funds to.

- Acknowledging that users might make such oversights, implementing feedback mechanisms to guide and prevent them from making these mistakes could significantly enhance the user experience.

### How do you imagine it?

I see two ways:
1. Popping out the alert dialog that will say what to do to the user
2. Having some red text appear around the Row of Account to transfer to

Which one do you think will be better?

**Comment by ivywallet** [comment]
Thank you @diasmashikov for raising Issue #2987! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
