### ISSUE TITLE
[Optimization] Loading balances

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2990]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Make the Home screen load fast
- Make the Accounts tab load fast

### Because...

- it's lame and annoying to wait

### Description

1. Memoize the Accounts in the `AccountRepository` using `MutableMap<AccountId, Account>
- Update the memo in-memory cache when an Account is updated
- Remove the account from the memo when it's deleted or flagged as deleted
- Populate the memo on each read/write operation

2. Memoize the Category in the `CategoryRepository` using the same strategy

3. Cache Account's balance calculations
Add a new `AccountBalanceSnapshitEntity` in Room DB. It must have:
- (primary key) accountId: UUID
- balance: Double
- currency: String
- timestamp: Instant

Algorithm:
1. Check for a cached balance snapshot
2. Retrieve the transactions only after the cached timestamp from the DB
3. Sum the cached balance + the sum of the retrieved trns
4. Save a new cached balance snapshot 
5. Return the calculated result.

---

4. Create a `DataLayerObserver` class that exposes `Flow<DataChangeEvent>`
- the `DataChangeEvent` is a sealed interface (SUM type) that can be AccountChange, TransactionChange etc.
- Emit such change events when writing stuff in the DB

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #2990! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #2990 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
If someone is up for a challenge and understands exactly what needs to be done, feel free to take over this one 🚀

**Comment by ILIYANGERMANOV** [comment]
Nvm, I'll give it a try 😄 Not sure if I'll finish the whole thing - I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #2990 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
This #2993 should be done for the `CategoryRepository`

**Comment by diasmashikov** [comment]
I'm on it (working on the Category Repository)

**Comment by ivywallet** [comment]
Thank you for your interest @diasmashikov! 🎉
Issue #2990 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by diasmashikov** [comment]
Starting to work on balance calculation optimization

**Comment by ILIYANGERMANOV** [comment]
@diasmashikov assign it to yourself
