### ISSUE TITLE
[FEATURE] Implement "Carry Forward" Balance Option

### ISSUE THREAD

**Issue by theabhishekbhujang** [Ivy-Apps/ivy-wallet#2996]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [x] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Add a "carry forward" balance feature to Ivy Wallet, allowing users to retain their remaining balance from the previous month into the current month. This improvement will enhance accuracy, usability, and user satisfaction by providing a more realistic representation of their financial status and transaction history.

### Why do you need it?

The feature of "carry forward" or "carry on" balance is needed to improve the accuracy and usability of Ivy Wallet. Currently, the system resets the balance to zero at the beginning of each month. By implementing this feature, users will have the option to carry forward their remaining balance from the previous month, providing a more realistic representation of their financial status. This enhancement aligns the platform with common financial practices and improves user satisfaction and retention.

### How do you imagine it?

- Users should have the option to enable or disable the "carry forward" feature.
- If enabled, the system will automatically carry forward the remaining balance from the previous month to the current month.
- The carried-forward balance should be clearly indicated in the user interface to maintain transparency.
- Users should be able to view their transaction history with both the carried-forward balance and the current month's transactions.
- Automatic Balance Transfer: At the beginning of each month, the system would automatically transfer any remaining balance from the previous month to the current month. This transfer would occur seamlessly in the background, without requiring any manual intervention from the user.

- Visible Balance: The carried-forward balance would be prominently displayed in the user's account overview, alongside the current month's balance. This visibility ensures that users are aware of their total available funds, including those carried forward from previous months.

- Accurate Financial Tracking: By incorporating the carried-forward balance into transaction histories and budgeting tools, Ivy Wallet provides users with a more accurate representation of their financial status. Users can track their spending and saving habits over time, accounting for fluctuations in their balance from month to month.

- Improved Financial Planning: The "carry forward" feature empowers users to better plan and manage their finances. They can make informed decisions based on their actual available funds, rather than starting each month with a clean slate. This leads to more effective budgeting and greater financial stability in the long run.

Overall, the "carry forward" balance feature enhances the usability of Ivy Wallet by aligning with real-life financial practices and providing users with a more comprehensive view of their financial health. It promotes better financial planning, tracking, and decision-making, ultimately contributing to increased user satisfaction and loyalty.

**Comment by theabhishekbhujang** [comment]
yes. agreed

**Comment by krzema12** [comment]
As a new user of Ivy Wallet, I'm surprised this behavior isn't the default one. I'd expect resetting the balances to 0 to be an opt-in feature because I see it as an action done by the app that the user doesn't necessarily want.

**Comment by devsarahgeo** [comment]
I would like to work on this. Could i work on this feature if nobody is working on it? @ivywallet
