### ISSUE TITLE
[BUG] Text for TransactionsScreen does not fit the rounded box

### ISSUE THREAD

**Issue by diasmashikov** [Ivy-Apps/ivy-wallet#2997]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

It is quite simple: just a disproportion of the text within the IncomeExpensesCards across all Transaction Cards. 

I intend to solve it by decreasing the text size and minimizing the horizontal padding a little. 

However, what do you think about the size?

### To Reproduce

1. Just go to the CategoriesScreen and click to one of the Categories or Accounts

### Screenshots

<div style="display: flex;">
How it is now:
  <img src="https://github.com/Ivy-Apps/ivy-wallet/assets/50723693/32c30871-15f5-4a92-8675-d13ccc117411" height="400" />
  How I imagine it:
  <img src="https://github.com/Ivy-Apps/ivy-wallet/assets/50723693/17e87fab-3852-4cde-945c-8b48ba2e4449" height="400" />
</div>

### Smartphone

Samsung S9

**Comment by ivywallet** [comment]
Thank you @diasmashikov for raising Issue #2997! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
