### ISSUE TITLE
[BUG] App crashes on Account module when viewing transaction of type “Account Transfer” having “To” and “From” set to the same account

### ISSUE THREAD

**Issue by xplo1t-sec** [Ivy-Apps/ivy-wallet#3001]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When there is a transaction of type "Account Transfer" that has the "From" and "To" accounts set to the same account, the app will crash when that transaction appears while scrolling on that particular account's page and the transaction appears on screen.

### To Reproduce

1. Create a transaction of type “Account Transfer” and select the same account for both the “From” and “To” fields.
2. Go to the account page and scroll down until the self-transfer transaction is visible on the screen.
3. Observe that the app crashes.

### Expected behavior

- The app should not crash when displaying a self-transfer transaction.
- The app should either prevent creating a self-transfer transaction.

### Smartphone

Google Pixel 6a, Android 14

### Additional context

I had mistakenly made an account transfer transaction with both "From" and "To" values set to the same account. Due to this, my account balance was having inconsistencies in my account. To analyse the cause of the inconsistencies, I tried checking the transactions for that particular account. Scrolling through the transactions, the app crashed every time that particular transaction appeared on the screen.

Also, if JFYI, I have set INR as currency if it helps!

**Comment by ivywallet** [comment]
Thank you @xplo1t-sec for raising Issue #3001! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Both:
- The app should not crash on self transfer 
- Self transfers should not be allowed (stop them on repository level)

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3001 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
