### ISSUE TITLE
[BUG] [VISUAL] The divide button in calculator looks differnt to the other buttons

### ISSUE THREAD

**Issue by uderbashi** [Ivy-Apps/ivy-wallet#3003]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In the calculator menu, there is a 4*5 grid. In the lower 4*4, the rightmost buttons are a bit squished to give more space to other buttons. However, in the top row, that is not the case, making the UI a bit inconsistent. (See screenshot).

### To Reproduce

1. Add transaction
2. Hit the calculator button

### Expected behavior

All rightmost buttons should look one way or another.

### Screenshots

![Screenshot_20240301_111834_Ivy Wallet Demo](https://github.com/Ivy-Apps/ivy-wallet/assets/32719218/2b7fd2ae-dbbd-4553-9b17-5903fd985bbe)

### Smartphone

Samsung S20FE, Android 13

**Comment by ivywallet** [comment]
Thank you @uderbashi for raising Issue #3003! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
The divide button is looking properly. The other button are broken because it isn't scaling well. 

Ww should make buttons smaller on smaller devices

**Comment by narojunagaraju** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @narojunagaraju! 🎉
Issue #3003 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
