### ISSUE TITLE
[FEATURE] Change the backup file name date format

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3006]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I think it would be more universal to use the ISO 8601 date format for naming backup files, so instead of "Ivy Wallet 11 Mar 02_21.zip" make it "Ivy Wallet 20240311_0221.zip".

### Why do you need it?

It would be more useful if you have multiple backups, especially if you sort a list of files by name. Now it's a bit confusing when I see 01 Mar and 01 Jan listed at the top in this case.

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3006! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Natzee** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Natzee! 🎉
Issue #3006 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
