### ISSUE TITLE
[BUG] Search View Clear button is Gone upon long query text

### ISSUE THREAD

**Issue by Natzee** [Ivy-Apps/ivy-wallet#3011]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When user searches in search view if that search query is to long, clear button is gone

### To Reproduce

1. Go to search screen
2. search long  query text
3. observe clear button is now gone

### Expected behavior

Clear button should always visible irrespective of query length

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/68009703/536ef0a4-b5b0-49d2-bc26-a378dbb05b42

### Smartphone

Samsung S23

### Additional context

Have fixed this

**Comment by Natzee** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you @Natzee for raising Issue #3011! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Can be fixed by using `Modifier.weight`

**Comment by Natzee** [comment]
Yes I too fixed in same way

**Comment by teja1329** [comment]
@ILIYANGERMANOV can i resolve this issue

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

**Comment by Natzee** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
> @teja1329 I have already completed work item.
> 
> @ILIYANGERMANOV Should search bar should expand because other application search bar only scrolls horizontally, shall I make it single line..? making singleline true..?

@Natzee idk, going on multiple lines is fine too because the user can see the enrire search query - whatever feels like the bettee UX
