### ISSUE TITLE
[FEATURE] Expenses by category (in a percentage format)

### ISSUE THREAD

**Issue by Sim4n6** [Ivy-Apps/ivy-wallet#3016]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to view the expenses by category as a percentage. 

I mean something like :

![GIJdcZiXYAAfis-](https://github.com/Ivy-Apps/ivy-wallet/assets/13036531/9da22692-2746-4667-b3b5-a45d218674e1)

### Why do you need it?

- it is much easier to track that percentages ... 

### How do you imagine it?

![GIJdcZiXYAAfis-](https://github.com/Ivy-Apps/ivy-wallet/assets/13036531/397dd49a-7a0c-455b-b96a-6407a7c7baec)

**Comment by ivywallet** [comment]
Thank you @Sim4n6 for raising Issue #3016! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey, have you seen our piebchart by clicking the expense box on your home screen?

**Comment by Sim4n6** [comment]
nope sorry , never mind thanks
