### ISSUE TITLE
CSV format specification

### ISSUE THREAD

**Issue by palapapa** [Ivy-Apps/ivy-wallet#3019]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Add a specification about the CSV format used by the import function.

### Because...

So people can more easily support the import feature for more apps.

**Comment by ivywallet** [comment]
Thank you @palapapa for raising Issue #3019! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Other apps should probably import from the Backup JSON and not the CSV. The csv is missing information while the backup json exports the entire database

**Comment by palapapa** [comment]
I think you misunderstood. What I meant was if there were a specification of the format of the CSV Ivy accepts, then other people can easily add more apps that Ivy can import from. I was not talking about the format of the CSV exported from Ivy.
But since Ivy internally actually uses JSON, I guess what we need is its schema.
The reason I want to know that is I might try to figure out the structure of the export file of another app called Daily Budget. It's in a binary format, so if I know the schema, I might be able to convert from that file to a JSON file that Ivy accepts.
