### ISSUE TITLE
[FEATURE] Expand remembering the scroll position for other screens

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3021]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Unfortunately I forgot to mention all the places affected by this problem. This request covers the same feature as described in https://github.com/Ivy-Apps/ivy-wallet/issues/2938, but for the Loans, Planned Payments, and Reports screens. If possible, also consider

### How do you imagine it?

This was successfully resolved by @madhavbhavsar with https://github.com/Ivy-Apps/ivy-wallet/pull/2977, but we definitely need it to work this way also for screens mentioned above. Shouldn't be hard to apply this code.

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3021! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by madhavbhavsar** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @madhavbhavsar! 🎉
Issue #3021 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
