### ISSUE TITLE
[BUG] Account tab balance for some accounts it is not correct 

### ISSUE THREAD

**Issue by Aritzherrero4** [Ivy-Apps/ivy-wallet#3025]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Data imported from the production application (v4.5.0) is not displayed correctly in the calculation of the balance of each account and the total.

Although the data import appears 100% correct and the transactions can be found in the history, the account does not include them and the value is incorrect.

The issue is related to empty fields on the backup file. I have verified that if an empty "description" filed is present on the json (see the example below) the transaction won't get added.

This might occur with other fields too but not checked.
[BugBackupFile.zip](https://github.com/Ivy-Apps/ivy-wallet/files/14643337/BugBackupFile.zip)

### To Reproduce

1. Create a transaction and click the description box. Exit that field without entering text.
2. Export the data and import it on the GitHub apk.
3. Check that the transaction is missing.
4. Check the backup file. The problematic transaction has an empty description field:
```json

{
         "accountId":"f5a6ecb3-6fb2-4fbf-ae66-4bd0e7e99aa9",
         "type":"EXPENSE",
         "amount":60.0,
         "toAmount":60.0,
         "description":"",
         "dateTime":1710801631309,
         "categoryId":"ae92e17a-5cbd-47ab-bd2a-6f9d4f13744b",
         "id":"22744a09-1dbb-460c-a740-ca2cb194f32f"
      },
```

### Expected behavior

The balance of each account and the total balance should be calculated correctly. Taking every transaction into account.

### Screenshots

![Stable](https://github.com/Ivy-Apps/ivy-wallet/assets/11832966/57ae3f77-67f1-495e-b8b7-49d6b5976f0a)

![GitHub apk](https://github.com/Ivy-Apps/ivy-wallet/assets/11832966/40b716b8-ec71-4553-b705-1ddf2676f8f7)

### Smartphone

Pixel 7 Pro, Android 14
OnePlus 9, Android 13/14

### Additional context
The exported backup json with the issue example:
[BugBackupFile.zip](https://github.com/Ivy-Apps/ivy-wallet/files/14643349/BugBackupFile.zip)

**Comment by ivywallet** [comment]
Thank you @Aritzherrero4 for raising Issue #3025! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Can someone try this fix?
```kotlin
description?.let(NotBlankTrimmedString::from)
```

The transaction's description must be optional, check `TransactionMapper`

**Comment by Aritzherrero4** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Aritzherrero4! 🎉
Issue #3025 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
