### ISSUE TITLE
Sync of exchange rates not saving to db

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [Ivy-Apps/ivy-wallet#3035]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The Syncing of exchange rates are not working if an account of different currency is used

### To Reproduce

1. Create an Account with a different Currency which is not the same as base currency 
2. add expense and income transactions 
3. balance is broken

### Smartphone

Pixel 7a (Emulator)

**Comment by ivywallet** [comment]
Thank you @Vishwa-Raghavendra for raising Issue #3035! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
