### ISSUE TITLE
Can't create an account with InitialBalance

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [Ivy-Apps/ivy-wallet#3037]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When creating an account, the initial balance entered is not being taken into account
We need to create an account and then manually go to the accounts page and enter initial balance to get the account with initial balance working

### To Reproduce

1. Create an Account with Initial balance
2. Go to Home tab  
(Account Initial Balance Transaction not seen)

### Expected behavior

Initial Balance Transaction should be seen

### Smartphone

Pixel 7a (Emulator)

**Comment by ivywallet** [comment]
Thank you @Vishwa-Raghavendra for raising Issue #3037! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
