### ISSUE TITLE
[BUG] Wrong amount position

### ISSUE THREAD

**Issue by Okazakee** [Ivy-Apps/ivy-wallet#3043]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When displaying the total amount in homescreen or account view, the number is offsetted to the bottom and not centered relative to the currency label.

### To Reproduce

1. Open the app and/or open account detail page

### Expected behavior

Total amount number should be centered relative to the currency label

### Screenshots

![5771466289909449192_121](https://github.com/Ivy-Apps/ivy-wallet/assets/17621558/b5e2ac50-6c55-4305-babb-fd2a9022d3bf)

### Smartphone

Pixel 8 Pro

**Comment by ivywallet** [comment]
Thank you @Okazakee for raising Issue #3043! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
![IMG_20240326_201836_908](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/0127c64d-b70f-4cf6-ad30-e023f8a28a9d)

**Comment by nkhar** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @nkhar! 🎉
Issue #3043 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@nkhar can you rework the component be a single `Text()` that contains both the "$balance $currency" (ofc keeping the current formatting logic)

**Comment by nkhar** [comment]
@ILIYANGERMANOV thanks for the advice I will do as you have proposed.
I am new to the codebase was reading the source. **BalanceRow** composable is aligned with: `verticalAlignment = Alignment.CenterVertically`. Despite the alignment parameter the currency and balance texts seem to be misaligned. I am not sure what causes this, maybe formatting, maybe fontWeight, maybe something else.

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV thanks for the advice I will do as you have proposed. I am new to the codebase was reading the source. **BalanceRow** composable is aligned with: `verticalAlignment = Alignment.CenterVertically`. Despite the alignment parameter the currency and balance texts seem to be misaligned. I am not sure what causes this, maybe formatting, maybe fontWeight, maybe something else.

It's because of the different fonts. Just merge them into one `Text`. Make sure to include screenshots and screen recordings in your PR
