### ISSUE TITLE
Select account should be vertically not horizontally

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3044]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

it's very pain to select account currently (I have more than 10). you need to scroll horizontally and you can only see 2~3 on the screen at the same time.

### Because...

it's pain
![IMG_20240327_091718_988](https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/c95e95d4-2002-4017-9aa1-a6bb96af480e)

### Description

I hope select account in this screen can have a button ie something else so I can select it in full screen with vertical scroll. that will improve my experience a lot thanks!

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3044! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Usually people have only few accounts. It should remain horizontal but also have a button as item index 0 to expand a vertical account picker

**Comment by Jack-Works** [comment]
> Usually people have only few accounts. It should remain horizontal but also have a button as item index 0 to expand a vertical account picker

I have 27 accounts in the software. Some of them are multi-currency credit cards (each currency has one account), and some are like Line (a chat service) balance.

**Comment by ILIYANGERMANOV** [comment]
@Jack-Works Yeah our UX isn't great for use-case. The proper fix would be:
1. Support multi-currencies accounts - one account, transactions in multiple currencies
2. Keep the horizontal scrolling
3. Add a small expand button as first to the horizontal account scrolling thing

**Comment by Jack-Works** [comment]
not stale, can you reopen this?

**Comment by Jack-Works** [comment]
still not stale, can you reopen this? thanks!

**Comment by Jack-Works** [comment]
still not stale, can you reopen this? thanks!
