### ISSUE TITLE
[BUG] Wrong text label is shown on category elimination

### ISSUE THREAD

**Issue by Okazakee** [Ivy-Apps/ivy-wallet#3046]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When deleting a category, the wrong text label is shown as I can type "Alimentari" (see screenshot) and delete button can be pressed.

### To Reproduce

1. Try to delete a category.

### Expected behavior

Correct label is shown upon category deletion modal.

### Screenshots

![5773798027654447756_121](https://github.com/Ivy-Apps/ivy-wallet/assets/17621558/0b58ec83-7fba-495f-ba06-552c9b49f73f)

### Smartphone

Pixel 8 Pro

**Comment by ivywallet** [comment]
Thank you @Okazakee for raising Issue #3046! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Okazakee** [comment]
> Do you mean that the confirmation text doesn't support your language(which I guess is Italian) ?

Haven't tried other langs honestly, if it repeats the behaviour, there must be some chars escaping in the code

**Comment by ILIYANGERMANOV** [comment]
The solution is to use `NotBlankTrimmedString.value`

**Comment by ivywallet** [comment]
Thank you for your interest @beradeep! 🎉
Issue #3046 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
