### ISSUE TITLE
[BUG] Categories cannot be deleted

### ISSUE THREAD

**Issue by Okazakee** [Ivy-Apps/ivy-wallet#3048]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When trying to delete a category, nothing happens.

### To Reproduce

1. Try to delete a category.

### Expected behavior

Category is deleted after pressing the button.

### Smartphone

Any

**Comment by ivywallet** [comment]
Thank you @Okazakee for raising Issue #3048! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ivywallet** [comment]
Thank you for your interest @beradeep! 🎉
Issue #3048 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
