### ISSUE TITLE
[BUG] Account deletion input box responsiveness

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3051]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

It's difficult to type in the input box of the account deletion confirmation dialog box. You also can't move the cursor or select text.

### Expected behavior

The account confirmation dialog input box is as responsive as any other.

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/dbdfa398-32cb-4589-b733-389dca844369

Please notice the keyboard suggestion bar getting buggy too.

### Smartphone

Galaxy s20+

### Additional context

The input box content should probably not be checked this way (every 50 ms), because it can cause problems with some keyboard apps, like HeliBoard. Making the Clear button clickable instead (always enabled) and checking the input box validity on button tap may solve the problem.

[Related PR](https://github.com/Ivy-Apps/ivy-wallet/pull/2641)

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3051! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by muray52** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @muray52! 🎉
Issue #3051 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by muray52** [comment]
Hi @nvllz , I will do bugfix also for category delete confirmation
