### ISSUE TITLE
[BUG] Button content misalignment

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3054]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The text for the "+/-" button in the initial balance dialog looks very off.

### To Reproduce

1. On the Accounts tab, tap a "+" icon
2. Tap on the "ENTER ACCOUNT BALANCE" section below

### Expected behavior

The button content should be centered like other icons in the row.

### Screenshots

![](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/724ae532-5a05-4222-b094-93a0010bd4f5)

### Smartphone

Galaxy S20+

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3054! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3054 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
