### ISSUE TITLE
[BUG][Onboarding] When the user clicks "Skip-Skip" default categories aren't added

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3056]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Default categories during onboarding aren't added. 

### To Reproduce

1. Clear data (open fresh install)
2. Click Offline Account
3. Click Start Fresh
4. Skip
5. Skip
6. Open the categories screen

### Expected behavior

After clicking "Skip" - "Skip" the default categories should be added.

### Smartphone

Doesn't matter

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3056! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3056 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
