### ISSUE TITLE
[BUG] Some strings aren't localized

### ISSUE THREAD

**Issue by code-a1** [Ivy-Apps/ivy-wallet#3058]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Some strings aren't localized

### To Reproduce

1. Try to create or manage a loan

### Expected behavior

The strings should be localized

### Smartphone

Every smartphone

**Comment by code-a1** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you @code-a1 for raising Issue #3058! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by code-a1** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @code-a1, this issue is already taken by @code-a1.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
