### ISSUE TITLE
[FEATURE] Option to use currency symbols

### ISSUE THREAD

**Issue by andrewpwade** [Ivy-Apps/ivy-wallet#3063]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues. (the ones I found were closed as 'completed', without comment)
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see e.g. "£" instead of "GBP" consistently across the UI (except when picking a currency, where the symbol and the name could be shown, for clarity).

This would also ensure a consistent display, as in the UI there is a mixture of `GBP 1.00`, `1.00 GBP` and `1.00 British Pound` formats

### Why do you need it?

- save precious real estate in widgets 
- use a more familiar identifier of currency (in every day use, it's uncommon to use currency names such as GBP, USD, TRY etc)
- consistent formatting of currency makes it easier to read

### How do you imagine it?

Anywhere the currency name is used, the symbol would be used instead. E.g instead of `GBP -100.99`, show `-£100.99`

In the large widget, the header would show `-£100.99`

The minus symbol prefix matches Excel's default style.

I think it could be worth discussing making it the default, too.

**Comment by ivywallet** [comment]
Thank you @andrewpwade for raising Issue #3063! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by andrewpwade** [comment]
I'm a developer with a bit of Kotlin experience (not Android though). I'd be interested in making this change, if there is interest.

And thanks for the app! It's awesome, exactly what I was looking :)

**Comment by shamim-emon** [comment]
@andrewpwade to to assign the issue to yourself
![Capture](https://github.com/Ivy-Apps/ivy-wallet/assets/60817041/b54a5786-800e-4a1b-88fb-1d8033fede61)

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md
