### ISSUE TITLE
[BUG] CSV export is broken

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3079]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Exporting to CSV is broken.

### To Reproduce

1. Export to CSV
2. Open the exported CSV

### Expected behavior

The exported CSV is formatted as expected - columns match the data.

### App version

4.6.0 from GitHub

### Smartphone

Doesn't matter

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3079! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @FreedomChuks! 🎉
Issue #3079 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Hey @FreedomChuks I took that issue yesterday but for some reason the automation didn't work. Can you pick a different one?

**Comment by FreedomChuks** [comment]
Sure

**Comment by ILIYANGERMANOV** [comment]
Fix merged
