### ISSUE TITLE
[FEATURE] Vietnamese Language Support

### ISSUE THREAD

**Issue by isaacnguyen0809** [Ivy-Apps/ivy-wallet#3087]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want a version that supports Vietnamese

### Why do you need it?

Expand the scope of users because I have seen on Google Play Store that there are requests for the Vietnamese version

### How do you imagine it?

All text in the app will have a Vietnamese version, i will take care of the transaltion

**Comment by ivywallet** [comment]
Thank you @isaacnguyen0809 for raising Issue #3087! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3087 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
