### ISSUE TITLE
To show a balance along the list of single transaction's done[FEATURE] 

### ISSUE THREAD

**Issue by mitzl02** [Ivy-Apps/ivy-wallet#3088]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to 
Idk if there's anything which can help me 

I note transaction's however sometimes i note down 1 week worth of transaction in one go

Now i get amount mismatch 
I tried to check where i got wrong but i am not able to find it.

So as a feedback while we note the transaction can we also show the current balance in the transaction list while make a note of that single transaction (as statement does say you had this much balance while doing this xyz amount) so it can be easy to find where did i go wrong/on which date....

Right now i had the backup of last month where i checked with the bank statement and it does show the correct balance

So now i cloned the app
One with current data
One with previous month data
And now i am adding it again one by one (by matching it with bank statement pdf)....🥲

### Why do you need it?

Easy to find where the amount balance started to mismatch

### How do you imagine it?

Easy for users to track and solve the transaction issue.

**Comment by ivywallet** [comment]
Thank you @mitzl02 for raising Issue #3088! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ASriDatta** [comment]
Please release this feature fastly I'm also facing similar issue when I tried to check where the mistake had taken place
