### ISSUE TITLE
[FEATURE] Time range - picker sliding window around current time

### ISSUE THREAD

**Issue by smalldevshima** [Ivy-Apps/ivy-wallet#3090]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be meaningfully informed about upcoming transactions based on how close they are, for example "the next two weeks" or "the next 30 days".

### Why do you need it?

- i am currently unable to see an upcoming transaction for the first day of the next period after the "firstDayOfMonth", even though it is tomorrow i.e. very soon
- i want to see expenses as they are happening and not "be surprised" when the "firstDayOfMonth" changes over and suddenly the entire next month of expenses is listed

### How do you imagine it?

*UI Aspect*
New setting for the inclusion time interval for the "Upcoming" view, that has a scalar part and a unit part, such as ("1", "month") or ("3", "weeks").

*UX Aspect*
The above setting influences the time range calculation logic for the "Upcoming" view.

*Considerations*
(The following could be considered a different feature and need a new issue according to the ORPGI rule.)
Perhaps different "modes" could be supported as is currently available for the transaction time range selection. The current behaviour could be the "now until next firstDayOfMonth" interval mode and another mode could be the "now plus interval" mode, to allow for users to choose between behaviours.

**Comment by ivywallet** [comment]
Thank you @smalldevshima for raising Issue #3090! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@smalldevshima upcoming includes the time range that you've selected from the date picker. If you select "April" you'll see the upcoming only for April. I haven't read the entire issue but having more customization is welcome

**Comment by smalldevshima** [comment]
@ILIYANGERMANOV Perhaps it would fit more in line with the current experience to extend the time selection to not only be able to select the "last X weeks" but also "next X weeks"? Like a sliding window selection surrounding the current date.

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV Perhaps it would fit more in line with the current experience to extend the time selection to not only be able to select the "last X weeks" but also "next X weeks"? Like a sliding window selection surrounding the current date.

Yeah, that makes good sense! I like the idea of a sliding window around the current time 💯 At somw point we should rework how our time range picker works
