### ISSUE TITLE
Latest release 

### ISSUE THREAD

**Issue by Sim4n6** [Ivy-Apps/ivy-wallet#3094]
How to download the latest version on Android, please?

**Comment by ivywallet** [comment]
Thank you @Sim4n6 for raising Issue #3094! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
> How to download the latest version on Android, please?

Google Play for a stable one. Or the latest APK from https://github.com/Ivy-Apps/ivy-wallet/actions/workflows/apk.yml?query=branch%3Amain which will likely contain bugs
