### ISSUE TITLE
[BUG] Fix memoization issues

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3097]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Memorization is broken when:
- Deleting all data
- Importing data

### To Reproduce

1. 

### Expected behavior

Memorization should work.

### App version

4.6.3 Google Play

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3097! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
