### ISSUE TITLE
[BUG] Incorrect balance after 4.6.2 update

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3104]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

After updating app from Google Playstore i have encountered the bug in change of balance on 3 accounts out of 6 accounts. Balance of the account was 10484.34 after update balance is 11494.34 On one account. On another account there is difference of 315

### To Reproduce

1. 

### Expected behavior

Account balance should be displayed as correctly as previous 

### App version

4.6.0 (160) From Google Playstore

### Smartphone

OnePlus Nord CE 2 5G 

### Additional context

Pervious balance was correct and now is wrong
- Not using the "Transfers as income & expense"
- You checked with your real accounts and verify that it's wrong
_No response_

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3104! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@Kishore263 please provide more info. Also the title "[BUG]" isn't good - change it sth like "[BUG] Incorrect balance after 4.6.2 update"

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by lhervier** [comment]
OK, my bad... Still problems with the balance of one of my accounts. But it seems to be my fault... Let me try to explain.

When using Budgets, i found that only expenses are used to compute the budget. Incomes are ignored (I haven't tried to see if it's something that have changed). So to avoid adding incomes to the categories that are part of my budgets, I "hacked" the calculator : If you try to compute an expense value using the calculator, and compute "0 - the income", and press "Set" before pressing "equal", Ivy will create an expense with a negative amount...

It used to work until now. But now, my balance is off by the exact amount of the sum of all my negative expenses. I will have to change them by hand i suppose...

**Comment by ILIYANGERMANOV** [comment]
> OK, my bad... Still problems with the balance of one of my accounts. But it seems to be my fault... Let me try to explain.
> 
> When using Budgets, i found that only expenses are used to compute the budget. Incomes are ignored (I haven't tried to see if it's something that have changed). So to avoid adding incomes to the categories that are part of my budgets, I "hacked" the calculator : If you try to compute an expense value using the calculator, and compute "0 - the income", and press "Set" before pressing "equal", Ivy will create an expense with a negative amount...
> 
> It used to work until now. But now, my balance is off by the exact amount of the sum of all my negative expenses. I will have to change them by hand i suppose...

Hey @lhervier negative expenses and incomes are not allowed. Our new domain model expects all transactions to have positive amounts and differ only by transaction type. For example, a negative expense is essentially an income

**Comment by lucasresck** [comment]
> When using Budgets, i found that only expenses are used to compute the budget. Incomes are ignored

Hi there, any suggestion to overcome this?

I need my budgets to consider category incomes so that expenses that are posteriorly refunded don't count in budgets. I could remove the category from the transactions, but sometimes refunds are partial (e.g., I paid the full value of something and my friend refunded me half of it).

Thanks!
