### ISSUE TITLE
[BUG] After update Calculator Starting from "0.00"

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3105]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

After the update Calculator on ivy wallet starting from "0.00" instead of empty. After entry some value it goes behind on the decimals like we entering "48" means its goes like "0.0048"

### To Reproduce

1. 

### Expected behavior

Calculator should be empty 

### Screenshots

![Screenshot_2024-04-08-07-06-00-10_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/166375674/32622700-c1ae-4cfb-abad-6e6bdee94e64)

### App version

4.6.0 (160) From Google Playstore

### Smartphone

OnePlus Nord CE 2 5G

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3105! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3105 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
