### ISSUE TITLE
[BUG] After the update Balance widget is Broken

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3106]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I have encountered the bug that is app widget is not showing any value 

### To Reproduce

1. 

### Expected behavior

Widget should show the value

### Screenshots

![Screenshot_2024-04-08-14-13-01-06_b783bf344239542886fee7b48fa4b892](https://github.com/Ivy-Apps/ivy-wallet/assets/166375674/575fa765-8453-4489-be20-536a54464fd8)

### App version

4.6.0 (160) From Google Playstore

### Smartphone

OnePlus Nord CE 2 5G

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3106! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3106 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
