### ISSUE TITLE
[FEATURE]  Keyboard Should be in less space

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3108]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to keyboard of the app should be in less spaces to access the number easily

### Why do you need it?

- To access the numbers of the keyboard more easily with one hand also

### How do you imagine it?

Like we can reduce the space between the rows

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3108! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Upload screenshots, otherwise I can't approve it

**Comment by Kishore263** [comment]
![Uploading Screenshot_2024-04-08-21-22-17-06_5e9f1c73c4ea0ad7b9937a61f977427e.jpg…]()

**Comment by Kishore263** [comment]
![Screenshot_2024-04-08-21-22-17-06_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/166375674/15c8381f-a754-4cb7-9c4c-7263eb67eaa1)

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3108 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
