### ISSUE TITLE
[BUG] Wallet Balance widget UI being cut

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3116]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Actually the buttons on the widget is cutting slightly. It cut the bottom

### To Reproduce

1. 

### Expected behavior

Want to display button fully

### Screenshots

![Screenshot_2024-04-10-21-14-30-92_b783bf344239542886fee7b48fa4b892](https://github.com/Ivy-Apps/ivy-wallet/assets/166375674/5f980c1c-4959-439e-b85d-a5aaea7ea55e)

### App version

4.6.2  From Google Playstore

### Smartphone

OnePlus Nord CE 2 5G

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3116! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@Kishore263 try 4.6.3 from the playstore

**Comment by ILIYANGERMANOV** [comment]
Also where's the crash? Attach a screen recording - that's an UI glitch only

**Comment by Kishore263** [comment]
> Also where's the crash? Attach a screen recording - that's an UI glitch only

Yea its UI glitch sorry for my bad English

**Comment by ILIYANGERMANOV** [comment]
No worries, updated it

**Comment by ILIYANGERMANOV** [comment]
**Fix:** reduce the spacings (margins/paddings) in the balance widget impl. Make sure to attach screenshots and that it still looks good

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3116 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Kishore263** [comment]
> **Fix:** reduce the spacings (margins/paddings) in the balance widget impl. Make sure to attach screenshots and that it still looks good

Actually after adjusting Margin the buttons are good

**Comment by Kishore263** [comment]
![Screenshot_2024-04-11-22-00-29-49_b783bf344239542886fee7b48fa4b892](https://github.com/Ivy-Apps/ivy-wallet/assets/166375674/6523a26c-7e61-4d5c-bd9a-d7ab9b06dc2a)
