### ISSUE TITLE
[FEATURE] Select All Time on Settings

### ISSUE THREAD

**Issue by paul222008** [Ivy-Apps/ivy-wallet#3117]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I wanted to have an option to enable/disable "Select All Time" by default on Settings. 

![IMG_20240411_004008_536](https://github.com/Ivy-Apps/ivy-wallet/assets/159406776/37901cbe-1585-41c4-b490-0c3f22164585)

### Why do you need it?

• This way user can track overall expenses easily 

• User have an option to choose wether to enable or disable "Select All Time"

**Comment by ivywallet** [comment]
Thank you @paul222008 for raising Issue #3117! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This new setting should be disabled (off) by default for all users. Only users that enable it should see "Select all time" by default.
