### ISSUE TITLE
Adjust balance bug

### ISSUE THREAD

**Issue by Aman-Yanni** [Ivy-Apps/ivy-wallet#3119]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I wanted to adjust balance by going to my account clicking edit and setting a new value but it updated it to a seeminglyrandom value. I wanted to update it from 3664.11 to 3954.15 and it added 265,708.84. and it added different amount based on those two values

### To Reproduce

1. Go to accounts
2. Click Edit
3. Enter a new balance
4. Save

### Expected behavior

It should create a new transaction for adjusting the balance with a different value than the difference in change

### App version

4.6m3 from Google play

### Smartphone

Samsung s23 ultra

**Comment by ivywallet** [comment]
Thank you @Aman-Yanni for raising Issue #3119! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #3119 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
**Fix:** Make all logic use the `TransactionRepository` instead of `TransactionDao`. To fix the bug fix the adjust balance code to use the `TransactionRepository`

**Comment by Aman-Yanni** [comment]
@ILIYANGERMANOV Please update on when the release for this fix is
