### ISSUE TITLE
[BUG] TagSelection Not Working 

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [Ivy-Apps/ivy-wallet#3126]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Unable to Deselect a tag after its associated with a  transaction

### To Reproduce

1. 

### App version

4.6.3

### Smartphone

Pixel 8a

**Comment by ivywallet** [comment]
Thank you @Vishwa-Raghavendra for raising Issue #3126! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
