### ISSUE TITLE
[FEATURE]  Investment option to record amount invested and amount returned

### ISSUE THREAD

**Issue by PulkitLavaniya** [Ivy-Apps/ivy-wallet#3129]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to request the developers of Ivy Wallet to add a feature to the same regarding the investments. I suggest the developers to add a section under the name "investments" which will track the amount of money invested and the amount got as returns. It will be even better if it tells the exact profit or loss by calculating the difference between invested amount and returned amount. 
Thanks for creating such a useful app

### Why do you need it?

-  The Feature mentioned will help any user who have any small or big amount invested in Equities, Mutual Funds, commodities and might be in cryptocurrencies also.
- It will help the user to calculate total net loss or profit for the amount invested by the user

### How do you imagine it?

A section named with "Investments" inside which there will be options available to choose from different investment options like equties, mutual funds, foreign currency, commodities, crytocurrencies etc. with the option to create and name a custom section available. In that the "amount invested" and "amount returned" input space shall be provided with total net profit or loss calculator

**Comment by ivywallet** [comment]
Thank you @PulkitLavaniya for raising Issue #3129! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
