### ISSUE TITLE
[BUG] "iIvy" typo in Spanish

### ISSUE THREAD

**Issue by LindsayPinto** [Ivy-Apps/ivy-wallet#3130]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The first one is a typo in the link to access the GitHub repository, it says 'iIvy' instead of 'Ivy'. The other issue is that when the user doesn't have an internet connection and tries to access a feature that requires it, it redirects to the browser or the app without checking the connection first.

### To Reproduce

1. Clicking on any feature that requires internet redirection.

### Expected behavior

I would expect to be informed beforehand that the connection was lost and that I should try again later.

### App version

4.6.3

**Comment by ivywallet** [comment]
Thank you @LindsayPinto for raising Issue #3130! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Redirecting to the browser app is expected. Can you please specify where's the typo so we can fix it? The browser behave should stay as it is.

**Comment by LindsayPinto** [comment]
The typo is in the spanish version in the settings, in the GitHub link that says "iIvy wallet es de código abierto!" instead of "Ivy wallet es de código abierto."

**Comment by ILIYANGERMANOV** [comment]
Got it. Thank you!

**Comment by sandeepjak2007** [comment]
I am on it
