### ISSUE TITLE
Migrate `TransactionDao` calls to `TransactionRepository`

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3132]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Migrate all `TransactionDao` calls to `TransactionRepository` (if the repo method is missing, you need to create it and add tests for it)
- Migrate all `WriteTransactionDao` calls to `TransactionRepository

### Because...

- Use the new Data layer that's single source of truth.
- Fixes bugs ans inconsistencies.

### Success Criteria

- You've tested each change manually.
- The code is covered with tests.
- The code is consistent with the other stuff in `:shared:data`.
- The code is following the Ivy Wallet's Developer Guidelines

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3132! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by rishi2062** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @rishi2062! 🎉
Issue #3132 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
