### ISSUE TITLE
Fix typos in the Developer Guidelines

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3133]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Read our Dev guidelines and its pages. Fix any typos and mistakes. 
https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md

### Because...

- Better dev docs

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3133! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by adersh1996** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @adersh1996! 🎉
Issue #3133 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by biplab1** [comment]
@adersh1996 I noticed you are assigned to this issue. If you are not currently working on it, would it be okay if I take over? I'd be happy to help.

**Comment by ILIYANGERMANOV** [comment]
@biplab1 I unassigned it, it's from April. Type the magic words to take over

**Comment by biplab1** [comment]
@ILIYANGERMANOV Thank you! I'll take over this issue now.

**Comment by biplab1** [comment]
i'm on it

**Comment by biplab1** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @biplab1! 🎉
Issue #3133 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by biplab1** [comment]
"I'm on it"

**Comment by ivywallet** [comment]
⚠️ Hey @biplab1, this issue is already taken by @biplab1.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
