### ISSUE TITLE
Customizable font and item size on the interface

### ISSUE THREAD

**Issue by Bryn102** [Ivy-Apps/ivy-wallet#3136]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I want to be abme to change the interface menu, font and other item sizes. 

### Why do you need it?

Things appear too big for my eyes

### How do you imagine it?

A display settings menu in the settings to customize the interface size

**Comment by ivywallet** [comment]
Thank you @Bryn102 for raising Issue #3136! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
