### ISSUE TITLE
[BUG] Unspecified Category missing on the latest update  (4.6.3)

### ISSUE THREAD

**Issue by adrianndirangu** [Ivy-Apps/ivy-wallet#3137]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The default **Unspecified** category that existed before under the Income and Expenses tabs is missing. However, the Unspecified category can still be viewed under categories when generating reports. 

### To Reproduce

1. Open the Ivy Wallet App
2. On the Home Screen,  tap on the Income or Expenses tabs.
3. Unspecified category is missing for transactions that have not been categorized.

### Expected behavior

I should see an Unspecified category for the transactions that have not be manually placed into any of the available categories that exist for my account.

### App version

4.6.3 (163)  from Google Play Store

### Smartphone

Nokia 4.2, Android 11

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3137 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
