### ISSUE TITLE
[Domain] Build the `AccountBalanceUseCase`

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3143]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Build the `AccountBalanceUseCase`.
- Use the `AccountStatsUseCase` and the `TransactionRepository`

```kotlin
class AccountBalanceUseCase @Inject constructor(...) {
   fun calculate(account: AccountId): Map<AssetCode, NonZeroDouble>
}
```

- Build the `NonZeroDouble` following the pattern to the `PositiveDouble`
- We neee NonZeroDouble to handle the case of negative balances (credits to @Vishwa-Raghavendra)

### Because...

- Proper domain logic following the architecture and having unit + property-based tests.

### Success Criteria

- Follows all dev guidelines (this is a critical code so expect Requests for changes on your PR)
- Property-based tests
- Unit tests

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3143! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by priyanshuborole** [comment]
"I'm on it"

**Comment by ivywallet** [comment]
Thank you for your interest @priyanshuborole! 🎉
Issue #3143 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by rishi2062** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Hey @rishi2062 any updates on this? If not you can unassign yourself so someone else can take it

**Comment by rishi2062** [comment]
Sure, although i started but not getting time lately.🥲

**Comment by rishi2062** [comment]
@ILIYANGERMANOV can you help me with the unassign code.

**Comment by rodrigoliveirac** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @rodrigoliveirac! 🎉
Issue #3143 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
