### ISSUE TITLE
[BUG] DATE PROBLEM

### ISSUE THREAD

**Issue by hkjansonchan** [Ivy-Apps/ivy-wallet#3145]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I just input the date & time eg 18 May 7.00am 
But after I confirmed the date become 17 May and I press in it, It was 18 May 7.00am
That's weird 

### To Reproduce

1. 

### App version

4.6.3(163) from Play Store

### Smartphone

Samsung Galaxy A54

**Comment by ivywallet** [comment]
Thank you @hkjansonchan for raising Issue #3145! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
It's a timezone issue. Set your device to GMT+8 or some big difference from UTC and it'll break.

We need to work everywhere with `Instant` (UTC) and convert to LocalDateTime only in the UI layer when we format `Instant -> String`.

**Comment by palapapa** [comment]
Same problem. The transaction history screen seems to be using the GMT+0 timezone no matter what.

**Comment by rishi2062** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @rishi2062! 🎉
Issue #3145 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by rishi2062** [comment]
@ILIYANGERMANOV is this issue still open after my merge
?
