### ISSUE TITLE
[FEATURE] Subgroup or Subcategory

### ISSUE THREAD

**Issue by KavinFelixSK** [Ivy-Apps/ivy-wallet#3146]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to able to add subcategories under main category

### Why do you need it?

- Category is a broader term, inaddition to that having subgroup will help in narrowing down the spends across categories

**Comment by ivywallet** [comment]
Thank you @KavinFelixSK for raising Issue #3146! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
