### ISSUE TITLE
Add BaselineProfile For Performance Improvements

### ISSUE THREAD

**Issue by parvinder8** [Ivy-Apps/ivy-wallet#3147]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Startup time
- Other Components

### Because...

- baseline profile improve app performance by atleast 20%

**Comment by parvinder8** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you @parvinder8 for raising Issue #3147! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
