### ISSUE TITLE
[FEATURE] Desktop App for Linux

### ISSUE THREAD

**Issue by rezatester94** [Ivy-Apps/ivy-wallet#3154]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have Ivy wallet in Linux Desktop

### Why do you need it?

- in desktop, will be easier to manage

### How do you imagine it?

I have no idea about coding, but your app is awesome. If you can bring it in to Desktop, at least with the same feature, it will be great. Once again good job guys, very well done.

**Comment by ivywallet** [comment]
Thank you @rezatester94 for raising Issue #3154! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
We can do this someday when KMP supports our Android techstack. Unfortunately, that's not feasible right now
