### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by toothsy** [Ivy-Apps/ivy-wallet#3156]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I followed the flow that is mentioned in steps to reproduce, the app crashes everytime i follow it.
I click on a transaction in report, it should show me which transaction add upto that much amount.

### To Reproduce

 The flow is defined as below. 
1. Create a account transfer from Source A to source B.
2. Navigate to accounts. 
3. Choose source A.
4. Click on expenses card. 
5. Choose the cross account transaction.

### Expected behavior

Mention the transactions that add upto the total mentioned in the account transfer transaction.

### App version

4.6.3

### Smartphone

Samsung s21 fe and Android 14

### Additional context

Clearing app cache does not seem to mitigate the app crash

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3156 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
