### ISSUE TITLE
Show a pie 🥧 of 50/30/20 rule 

### ISSUE THREAD

**Issue by Sim4n6** [Ivy-Apps/ivy-wallet#3159]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to see in a form of a pie chart categories grouped into 50/30/20 budgeting rule. 

### Why do you need it?

- to simplify my monthly Overview and do better analysis of my income /expense issues.
- 

### How do you imagine it?

Something like either a pie chart explained OR a three bars budget chart where I can see if the categories that I grouped into the 50 essentials are respected and the 30 wants are also in respect with my planning, finally the savings are within the 20 rule.

**Comment by ivywallet** [comment]
Thank you @Sim4n6 for raising Issue #3159! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This should be a new screen and not affect the current pie-chart that we have

**Comment by Sim4n6** [comment]
Definitely

**Comment by Sim4n6** [comment]
Does this mean I can expect this feature please?
