### ISSUE TITLE
[FEATURE] dynamic goals, custom and with all functionalities like transfer, topics, pay scheduled...

### ISSUE THREAD

**Issue by DanielDevDu** [Ivy-Apps/ivy-wallet#3162]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to plan speific goals 

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @DanielDevDu for raising Issue #3162! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey @DanielDevDu we need more info. Explain in detail how do you imagine it? I'll likely be soms new screen with this functionality inside it. But make sure to specify it properly so it can bs implemented
