### ISSUE TITLE
[FEATURE]  Foreign Currency input

### ISSUE THREAD

**Issue by hkjansonchan** [Ivy-Apps/ivy-wallet#3164]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add a area to turn the foreign currency to the account setting

### Why do you need it?

- It's inconvenient that every time travel to other countries need to open a new account for their currency.

### How do you imagine it?

![Screenshot_20240427_111820_Ivy Wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/91411747/c9e5e580-589c-42de-9d0f-82c890e00f3f)
As the photo I want the 'HKD' can be changed to other currencies and also have a online offline exchange rate

**Comment by ivywallet** [comment]
Thank you @hkjansonchan for raising Issue #3164! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
