### ISSUE TITLE
[FEATURE] sub category 

### ISSUE THREAD

**Issue by Rhaycee** [Ivy-Apps/ivy-wallet#3165]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to subcategories for categories 

### Why do you need it?

- to have more organizations 

### How do you imagine it?

![Screenshot_2024-04-27-20-25-10-70_286634920e44507b7c2cb0ae7579ffaf](https://github.com/Ivy-Apps/ivy-wallet/assets/132153247/0c54d26f-0f94-4ab4-ae17-25acb48676bf)

**Comment by ivywallet** [comment]
Thank you @Rhaycee for raising Issue #3165! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by daaniikusnanta** [comment]
Isnt this the same as #3146?
