### ISSUE TITLE
[BUG] Incorrect balance after Adjust balance

### ISSUE THREAD

**Issue by zatsepinvl** [Ivy-Apps/ivy-wallet#3166]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When clicked on existing balance and adjusted it in place, the resulting value is incorrect.
The account exists for more than 1 year and contains hundreds transactions.
Default currency is EUR.

### To Reproduce

1. Click on the account balance RSD  105,500.00
2. Change value to 105,000.00
3. Save
4. Balance is 151,643.18
5. Transaction added 46,143.18

### Expected behavior

Balance to be 105,000.00
Transaction to be 500

### App version

4.6.3

### Smartphone

Xiomi mi 14

### Additional context

Observed behaviour:
1. Works OK with new account created.
2. Does not work (as described) with existing accounts
3. Setting exchange rate manually doesn't make any effect.

**Comment by ivywallet** [comment]
Thank you @zatsepinvl for raising Issue #3166! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by zatsepinvl** [comment]
UPD 
Found out, that the same happens even with just change the account name: random transaction with strange amount appears.

**Comment by ILIYANGERMANOV** [comment]
@zatsepinvl can you test if this happens with the latest GitHub Release? 🙏

**Comment by zatsepinvl** [comment]
@ILIYANGERMANOV 
Fixed! 🎉 
Checked with the latest version Release v2024.07.21-191. All good now. Many thanks.
