### ISSUE TITLE
On a Mac, I needed to install git lfs before i could checkout a branch. Instructions do not mention this

### ISSUE THREAD

**Issue by stetimi** [Ivy-Apps/ivy-wallet#3169]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Developer onboarding

### Because...

I got an error because git lfs was not installed on my Mac. Took a google search and a few minutes to resolve, but it'd be nicer if the developers' guide had a warning.

### Description

The developers' guide could mention git lfs is needed before cloning the fork:

I got this error on my Mac when cloning my fork of the repo:
```
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
```
Installing lfs fixed it. 
```
brew install git-lfs
git lfs install
```

**Comment by ivywallet** [comment]
Thank you @stetimi for raising Issue #3169! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@stetimi good catch! Can you such instructions in the README and/or the contribution guidelines?

**Comment by stetimi** [comment]
I'm on it
