### ISSUE TITLE
[BUG] Description multiline gets duplicated

### ISSUE THREAD

**Issue by biagio11** [Ivy-Apps/ivy-wallet#3171]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In the latest build (29 apr app-demo.apk) on my phone with Android 13 as OS I noticed that when writing in the description field and entering a new line (enter) the text in the previous line gets duplicated in the next line.

### To Reproduce

1. open expense or income or transfer
2. enter the description
3. press enter
4. the previous line gets duplicated

### Expected behavior

I expect the line to not be repeated when I go to a newline.

### App version

4.6.3 (163) from GitHub

### Smartphone

Samsung Galaxy S20FE, Android 13

**Comment by ivywallet** [comment]
Thank you @biagio11 for raising Issue #3171! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey @biagio11 does that happen on the Google PlayStore version, too?

**Comment by Anshu-Bijarnia** [comment]
Can i look into this issue ?

**Comment by ILIYANGERMANOV** [comment]
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

**Comment by biagio11** [comment]
> Hey @biagio11 does that happen on the Google PlayStore version, too?

I confirm it is an open issue also in the Google PlayStore 4.6.3 version.

**Comment by biagio11** [comment]
I briefly reviewed the code and I think the issue might be related to a redundant `clickable` modifier inside the Description.kt. Removing it may help resolve the duplication issue.

I think the issue is because the `DescriptionText` composable is wrapped inside a `PrimaryAttributeColumn` which itself is clickable, so adding the `clickable` modifier to the Text composable inside `DescriptionText` may be redundant.

Removing the  `.clickable{onClick()}` like so in the Description.kt might solve the issue.

```
private fun DescriptionText(  
    description: String,  
    onClick: () -> Unit,  
) {  
    PrimaryAttributeColumn(  
        icon = R.drawable.ic_description,  
        title = stringResource(R.string.description),  
        onClick = onClick  
    ) {  
  Spacer(Modifier.height(12.dp))  
  
        Text(  
            modifier = Modifier  
                .padding(horizontal = 24.dp)  
                .testTag("trn_description"),  
            text = description,  
            style = UI.typo.nB2.style(  
                textAlign = TextAlign.Left  
  ),  
        )  
  
        Spacer(Modifier.height(20.dp))  
    }  
}
```

I'm not 100% sure but I'm open to discuss about it.

**Comment by ILIYANGERMANOV** [comment]
If it fixes it, feel free to https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

**Comment by biagio11** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @biagio11! 🎉
Issue #3171 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
