### ISSUE TITLE
sync, import and export data

### ISSUE THREAD

**Issue by ghost** [Ivy-Apps/ivy-wallet#3172]

**Comment by ILIYANGERMANOV** [comment]
@lucasnuic if that doesn't disrupt the existing functionality feel free to give a shot. Also:
- this new features should not change `:shared` module
- It must be off by default 
- Only users who decide to opt-in into explicitly from the Settings screen will receive it

Can you provide more details how it'll work technically? Ivy Wallet currently do backup by dumping the local Room database into one big JSON file. I guess you'd like to sync this JSON backup file on some trigger (e.g. write in db/app close or open)

**Comment by ILIYANGERMANOV** [comment]
- Pricing: What does it cost? Is it free for commercial use?
- Legal - what can go wrong?

**Comment by ILIYANGERMANOV** [comment]
Sounds like this feature is more complex and will require time investment from my side. Even if you develop it successfully it'll require maintenance and customer support afterwards which I can't do.
https://t.me/c/1647280565/8173/19608

Feel free to build it in your own fork and release an Ivy Wallet clone. If the feature is safe enough we can consider releasing it in the main app

**Comment by daaniikusnanta** [comment]
Hey @lucasnuic if you need some help on this feature, (maybe) I can help! Online sync I think is also very important. Cashew already has it, so it might be the tipping point for some people.
