### ISSUE TITLE
[FEATURE] Ability to expand and collapse transactions 

### ISSUE THREAD

**Issue by pavankonjarla** [Ivy-Apps/ivy-wallet#3173]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to
Be able to expand and collapse the transactions so that I can see more number of rows in a page. 
By default the view should have all the details including the transaction type, category, amount and date etc... but if I collapse, it should only show the amount details 

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @pavankonjarla for raising Issue #3173! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
