### ISSUE TITLE
[FEATURE] Swipe gestures on home screen 

### ISSUE THREAD

**Issue by pavankonjarla** [Ivy-Apps/ivy-wallet#3174]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to swipe on the home screen to go to next or previous months transactions. This is very user friendly instead of selecting the month from top right corner. 

### Why do you need it?

-  improvement in accessing the future and past transactions with simple swipe guesture

**Comment by ivywallet** [comment]
Thank you @pavankonjarla for raising Issue #3174! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey @pavankonjarla try swiping on the month button at the top. It does exactly what you describe. Test it and lmk what you think

**Comment by pavankonjarla** [comment]
Excellent. That's already working. Thank you very much.
Any possibility to swap this feature with accounts swipe guesture. Not a big deal anyway.

**Comment by ILIYANGERMANOV** [comment]
For now we'll keep the current swiping  behavior because users are used to it for checking their accounts
