### ISSUE TITLE
List/ Notepad

### ISSUE THREAD

**Issue by DemonsEye208** [Ivy-Apps/ivy-wallet#3178]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want toYou can add a list feature/ notepad so that we can have list of items we have to buy

### Why do you need it?

- i keep finding myself making lists but i have to use another app for that 
- it would be nice to have some list feature or a notepad so that we can set reminders for shopping lists or some other expenses 

### How do you imagine it?

I would like a notepad kind of tab in which we can write anything but it also includes a list tab with a few columns that can be like item, quantity, expected price, actual price etc,
I would really love this feature to be added

**Comment by ivywallet** [comment]
Thank you @DemonsEye208 for raising Issue #3178! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
