### ISSUE TITLE
Ability to exclude amount in selected accounts from total balance 

### ISSUE THREAD

**Issue by JoyFrancs** [Ivy-Apps/ivy-wallet#3179]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have total balance excluding the required accounts

### Why do you need it?

- To exclude the amount I wish to save from the total balance 
- To help user save more and avoid spending the saved money

**Comment by ivywallet** [comment]
Thank you @JoyFrancs for raising Issue #3179! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey @JoyFrancs I think we already have that. Click "Edit" in one of your accounts and uncheck "Include in Balance"
