### ISSUE TITLE
[FEATURE]  Add confirm dialogue box

### ISSUE THREAD

**Issue by pavankonjarla** [Ivy-Apps/ivy-wallet#3180]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to
To able to have a confirmation dialogue box if I accidentally click "Skip all" in overdue transactions. 

### Why do you need it?

-  Because it is very tedious to identify all the skipped transactions if a user clicks skip all button by mistake.

**Comment by ivywallet** [comment]
Thank you @pavankonjarla for raising Issue #3180! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
