### ISSUE TITLE
[BUG] Quick Settings Tile Small Icon

### ISSUE THREAD

**Issue by ynshung** [Ivy-Apps/ivy-wallet#3181]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In Xiaomi's Android 13, the Quick Settings Tile is smaller than usual compared with other tiles.

### To Reproduce

1. Edit the quick settings section and see the Ivy Wallet tile.

### Expected behavior

Ivy wallet icon in the quick settings tile should be bigger with the same size with the other tiles

### Screenshots

![Screenshot_2024-05-02-18-34-43-412_com ivy wallet-edit](https://github.com/Ivy-Apps/ivy-wallet/assets/61302840/90300e52-a94f-4d54-922d-5b87bd8a2e89)

### App version

4.6.3 from Google Play

### Smartphone

Poco F3, Android 13, Xiaomi HyperOS 1.0.2.0.TKHMIXIM

**Comment by 09karankr** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @09karankr! 🎉
Issue #3181 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by SK3180** [comment]
i have started working on this issue..

**Comment by SK3180** [comment]
I have Fixed the issue

**Comment by suyash01** [comment]
@ILIYANGERMANOV this issue needs to be closed as the fix has already been merged.
