### ISSUE TITLE
Budget categorie tied to a percentage of the income

### ISSUE THREAD

**Issue by Sim4n6** [Ivy-Apps/ivy-wallet#3182]
is there a way to set a budget tied to a percentage of the income value, please ? 

I mean if the income is 1000 and I set the budget to 30% , the upper limit would be 300. but if the income becomes 2000 , the upper limit of that budget would be 600.

**Comment by ivywallet** [comment]
Thank you @Sim4n6 for raising Issue #3182! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
