### ISSUE TITLE
[FEATURE] Add repeat until for planned payments

### ISSUE THREAD

**Issue by pavankonjarla** [Ivy-Apps/ivy-wallet#3185]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to
Be able to limit the planned payments till a specific date

### Why do you need it?

- Some planned payments will end on perticular day. So I should have an option to stop the payments.

### How do you imagine it?

Having a selection for "repeat until " when adding planning payments

**Comment by ivywallet** [comment]
Thank you @pavankonjarla for raising Issue #3185! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
