### ISSUE TITLE
sub-category

### ISSUE THREAD

**Issue by i2414977** [Ivy-Apps/ivy-wallet#3188]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

it could be usefull add possibility to add sub-category.

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @i2414977 for raising Issue #3188! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
