### ISSUE TITLE
[TRANSLATION] Brazilian Portuguese

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#319]

**Comment by ruanitto** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @ruanitto, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@ruanitto type the magic words again

**Comment by ruanitto** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ruanitto! 🎉
Issue #319 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
