### ISSUE TITLE
Wallet sharing

### ISSUE THREAD

**Issue by Eeshay82** [Ivy-Apps/ivy-wallet#3191]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to share my wallet with someone who also uses Ivy Wallet. A feature in which I can make a wallet in which both I and other people can make expenses, add income etc.

### Why do you need it?

- For example when someone living with someone, some expenses are shared with them, like your roommate or spouse. With a shared wallet we will know how much money we have left in our shared wallet, and can add expenses to that. This will make it easier to track the expenses for groceries or rent together. 

### How do you imagine it?

- Being able to share the wallet with one or more people
- Everyone being allowed to edit the wallet by adding income and expenses

**Comment by ivywallet** [comment]
Thank you @Eeshay82 for raising Issue #3191! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This feature require cloud sync which isn't feasible right now

**Comment by igrowing** [comment]
Another vote for this feature request. Having cloud sync open also other opportunities, like online backup/restore. Maybe [this](https://developer.android.com/training/sync-adapters/creating-sync-adapter) can convert `can't do` into `approved` ;)
By the same chance, I want to say "Huge thank you" to the developers for the idea of awesome user-fiendly app. (Positive review in the app store is left already).

**Comment by ILIYANGERMANOV** [comment]
@igrowing didn't check the details but if this enables "free" cloud sync w/o legal or security risks - someone can feel free to give it a shot
