### ISSUE TITLE
CMC api support

### ISSUE THREAD

**Issue by viduxsh** [Ivy-Apps/ivy-wallet#3194]
It would be very useful to be able to add the coinmarketcap api key so you can add updated currencies and conversion rates through it

**Comment by ivywallet** [comment]
Thank you @viduxsh for raising Issue #3194! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
