### ISSUE TITLE
[FEATURE] auto backup data

### ISSUE THREAD

**Issue by FozuX** [Ivy-Apps/ivy-wallet#3196]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to Back up data automatically, it's up to you whether you want to use a third party or just auto backup locally

### Why do you need it?

- I often forget to do backups
- I have 2 cellphones 
- makes it easy to back up so you don't need to do it manually

### How do you imagine it?

auto backup files every few days, using Google sync, GitHub, or email. Backup locally or online using Google Drive or other software

**Comment by ivywallet** [comment]
Thank you @FozuX for raising Issue #3196! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
