### ISSUE TITLE
[FEATURE]  Reimbursement of Expenses 

### ISSUE THREAD

**Issue by subinps** [Ivy-Apps/ivy-wallet#3197]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

It would be better if the team can add an option for reimbursement of expenses.
For example , lets say If i met an expense of ₹1000 and the money is deducted from my balance. 
Now among that 1000 , i will be getyung the reimbursement of 50 % say for example if the expense was of for food among friends and later they split and pay.
In that case it would be good if we can adjust the credit amount as reimbursement for previous expense that was entered , so the net amount will be actual expense.

### Why do you need it?

-  Many a times there is cases of splitibg expenses 
- At preset there is no option other than manual adjustment to previously recorded expeses, if if we do so, there is no track for the reimbursement.

**Comment by ivywallet** [comment]
Thank you @subinps for raising Issue #3197! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
