### ISSUE TITLE
[FEATURE] Specialized saving objectives

### ISSUE THREAD

**Issue by Pedromax13** [Ivy-Apps/ivy-wallet#3199]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to divide my saving objectives, let's say I want to save for a car, or for a trip, I want to be able to set that goal and to be able to allocate x amounts in percentages or fixed amounts to that goal.

### Why do you need it?

- It would make the experience of saving for something more visual, like a bar filling up with time.
- It would also incentivize saving behavior by making it more visual.
- It would make it easier to allocate certain amounts of every income to specific objectives.
- It could also work to assign funds like emergency funds or travel funds.

### How do you imagine it?

Similar to the budgeting feature just instead of selecting categories you select accounts (or incomes) and a specific amount of every account (or income), either in percentage or fixed.

The funds or savings fund could be renameable, and customizable, with icon and color.

Optionally, but remarkably, an option to automatically allocate what was not spent from a budget at the end of the month to a savings fund would be awesome.

**Comment by ivywallet** [comment]
Thank you @Pedromax13 for raising Issue #3199! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
