### ISSUE TITLE
[IMPORT] Walnut: Expense Tracker (com.daamitt.walnut.app)

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#320]
### Google PlayStore URL to the app from which you want to import

https://play.google.com/store/apps/details?id=com.daamitt.walnut.app

### Developer/Contributor Notes

- Checkout this **[Sample Commit](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/323ed68343a0904ee33f226480716a30368fd646)** to see how import CSV works in Ivy Wallet
- Make sure that the imported dates of the transactions are correct"

**Comment by HiteshRohira** [comment]
Is it possible to get an ETA on this. I have been using walnut for a while now and have a lot of transaction but want to move to your app. If this feature was present I would move in today.

Also is it at all possible that I can start using IVY now and when this feature comes all my old transactions will get imported and the new ones I recorded will remain too??

**Comment by ILIYANGERMANOV** [comment]
1) ETA - no, can't promise you anything. 

2) Yes, you can use Ivy even for years and still import old transactions from another app.
