### ISSUE TITLE
App doesn't keep chosen date [BUG] 

### ISSUE THREAD

**Issue by Moyohyu** [Ivy-Apps/ivy-wallet#3202]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I enter new expense and choose the date, the app changes it for today's date instead of chosen date.

### To Reproduce

1. Enter new expense
2. Save it using any date but today
3. Review it, it will show today's date instead of the one you chose.

### App version

4.6.2 google play

### Smartphone

Samsung galaxy z flip 5

**Comment by ivywallet** [comment]
Thank you @Moyohyu for raising Issue #3202! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by suyash01** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @suyash01! 🎉
Issue #3202 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
