### ISSUE TITLE
[FEATURE] Very useful features 

### ISSUE THREAD

**Issue by Rnold35** [Ivy-Apps/ivy-wallet#3205]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to set a automatically repeated income/expense on set date. Example i want to set may payroll income every 15th and 29th of month. 

### Why do you need it?

- This way i don't have to put my payroll income every time i got it.

- Or it will automatically deduct my expenses every month on the set date. 

### How do you imagine it?

I imagine it has income and expenses and you can set weekly, monthly or annually.

For weekly they need to set day, the options are - mon, tues, weds, thu, fri, sat or sun. Example they click expense - > weekly - > Monday, and enter the amount 100 dollars. This way, it will automatically deduct 100 dollars every monday.

For month they need to set number date. Example they click income - > monthly - > 15th day and enter 2000 dollars. This way, it will automatically add 2000 dollars every 15th day of month. Very useful for payroll

Lastly for annually they need to choose which month and day. Example they click expense - > annually - > March 12 and enter 500 dollars. This way it will automatically deduct 500 dollars every match 12.

**Comment by ivywallet** [comment]
Thank you @Rnold35 for raising Issue #3205! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
