### ISSUE TITLE
Unspecified category not shown in expense pie[BUG] 

### ISSUE THREAD

**Issue by Ibmflash** [Ivy-Apps/ivy-wallet#3207]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

**Expenses not under any specific category (i.e unspecified) have stopped showing up in the expenses pie chart.** They are shown everywhere else.

Also individual categories dont add upto the total on the top ont he pie chart page as this unspecified category is not shown.

### To Reproduce

1. Add some expense without a category
2. Check that months expense pie chart
3. Find out its not shown

### Screenshots

![Screenshot_20240522_055643_Ivy Wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/170481247/54383263-e593-423a-a0a3-3b34c9c92ee0)

# **Above:**
3 example expenses for this month. 2 in categories and one unspecified.

# **Below:**
Expenses pie chart page shows total correctly but no **unspecified** category in the pie or list. Percentages of other expenses are also out of order because of this. 

![Screenshot_20240522_055655_Ivy Wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/170481247/31624fbb-daa2-4dc2-b0ef-82920d7dae65)

### App version

4.6.3 from google play store

### Smartphone

Samsung galaxy S20 plus, android 13

**Comment by ivywallet** [comment]
Thank you @Ibmflash for raising Issue #3207! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by adrianndirangu** [comment]
This bug was already submitted as issue #3137 and closed as issue #3160.
