### ISSUE TITLE
[FEATURE] Add  a $MONTH variable to ta reccuring monthly payment

### ISSUE THREAD

**Issue by Sim4n6** [Ivy-Apps/ivy-wallet#3209]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user, I want to add the current $month to a monthly recurring payment description or title.

### Why do you need it?

I mean sometimes I pay a monthly bill before its time and it corresponds to the next month with a brand new variable like $MONTH that would be perfect. the variable $MONTH would track the corresponding month even though if I pay before or after .... 

### How do you imagine it?

something like a specific text `$MONTH` for instance.

It can only mentioned in the title & description of an expense in a recurring payment. When the user mention it, it would somehow be replaced with the tracked month. 

If a recurring payment is a monthly telephone bill. Its use would show `Bill Phone $MONTH` => `Bill Phone May` or `Bill Phone Juin` ... 

Voilà

**Comment by ivywallet** [comment]
Thank you @Sim4n6 for raising Issue #3209! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by rishi2062** [comment]
To Confirm this issue, if the payment category is Planned Payments , and here if user don't provide any title, we should add a $Month variable untill it is modified by user
<img width="417" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/72225636/1125a008-d332-469e-8f95-6dedaa33de77">

 or 
 
<img width="417" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/72225636/5809e0a2-cdb1-4a0c-9314-c13f9f9d74e4">

say here the 50 INR transaction that i made, was for June Month in planned payment, so here we should show
as : the month exclusively for recursive payments, and is it a good idea to add a category card for planned payment as how it is for Transport, Food and drinks with a little title, describing which planned payment it was for as Netflix subscription or else?

**Comment by rishi2062** [comment]
<img width="417" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/72225636/b2841c57-e025-46ba-90dc-03a84ed6e253">

Here i made the recurring daily payment for different dates of june and july, but while showing transaction history there is no detail, that the payment made was for which day,
or when user clicks on each card, we can show the detail in title, if it is not modified by user.

**Comment by Sim4n6** [comment]
a bit lost in details, thank you

**Comment by rishi2062** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @rishi2062, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by rishi2062** [comment]
I'm on it
