### ISSUE TITLE
Budget Restart / Expenditure Restart

### ISSUE THREAD

**Issue by NKBudget** [Ivy-Apps/ivy-wallet#3214]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to restart my balances to zero. I'd like for this to include all expenses, income, budget categories etc. This would be useful for at the end of the month or payday when I am using a set allowance, instead of carrying over from the previous month. Currently I am struggling and either restarting everything, or adding new categories to disregard like "End of Month" as a note.

### Why do you need it?

- useful for the end of the month period
- budgeting monthly
- not carrying over previous allowances
- more efficient than restarting this month

**Comment by ivywallet** [comment]
Thank you @NKBudget for raising Issue #3214! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
