### ISSUE TITLE
[BUG] Time Change Date Change

### ISSUE THREAD

**Issue by Melo076** [Ivy-Apps/ivy-wallet#3216]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

If you change the time for an expense/income after setting a date, the date changes to the day before, sometimes 2 days earlier

### To Reproduce

1. Change time to an early morning time of the same date/later date

### Expected behavior

If time is changed after date has been set, date does not change

### App version

4.6.2

### Smartphone

Samsung A13 5G

**Comment by ivywallet** [comment]
Thank you @Melo076 for raising Issue #3216! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Fixed in https://github.com/Ivy-Apps/ivy-wallet/pull/3224
