### ISSUE TITLE
[BUG] Exchange between accounts 

### ISSUE THREAD

**Issue by Melo076** [Ivy-Apps/ivy-wallet#3217]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

If an exchange between accounts has been beleted, the "money" does not stay in the original account
ex.
Bank: 500
Transfer from Bank to Savings: 300
Bank: 200
Savings: 300
*delete transfer* 
Bank: 200
Savings: 300

### To Reproduce

1. "transfer" to another account
2. delete the "transfer"

### Expected behavior

original money of the bank account returns
ex.
Bank: 500
Transfer from Bank to Savings: 300
Bank: 200
Savings: 300
*delete transfer* 
Bank: 500

### App version

4.6.2

### Smartphone

Samsung A13 5G

**Comment by ivywallet** [comment]
Thank you @Melo076 for raising Issue #3217! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by suyash01** [comment]
@Melo076 I am not able to reproduce this issue on the latest version of the app on the play store. If you are still facing this issue could you please povide more information in the format of a screen recording or step by step screenshot.
