### ISSUE TITLE
[FEATURE]  add option for categorising loans screen and filtering

### ISSUE THREAD

**Issue by hexman1999** [Ivy-Apps/ivy-wallet#3219]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to categorize my loans borrowed and lent and adding option for search or view filter what i want and what not

I think also it will be great to have an archive space for finished ones instead of deleting the finished ones for personal documentation purposes

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @hexman1999 for raising Issue #3219! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by msaeedsaeedi** [comment]
I really appreciate, if we get this feature. We are waiting for it.
