### ISSUE TITLE
Sub-Category [FEATURE] 

### ISSUE THREAD

**Issue by KingMJ2** [Ivy-Apps/ivy-wallet#3223]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to create sub-categories of Accounts & Spend Areas.

### Why do you need it?

By being able to create sub-categories within major categories, the no. of main categories would be reduced, making data entry "Add Category" & "From" clutter-free.

Better Analyses can be dobe for personal finance & budget based on major spend areas overall and a particular higher area within a category.

### How do you imagine it?

For Accounts, 
1. Banks should be sub-categorizable to a particular bank BOB, SBI, CBI, etc.
2. Cards should be sub-categorizable to ICICI, Flipkart, SC, etc.
3. Investments should be sub-categorizable to Stocks, Mutual funds, etc.

For Spend areas,
1. Food shall be sub-categorizable to Breakfast, Lunch, Dinner, Snacks, Beverages, etc.
2. Household shall be sub-categorizable to Water, Gas, Electricity , etc.

**Comment by ivywallet** [comment]
Thank you @KingMJ2 for raising Issue #3223! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by vraj152** [comment]
@ILIYANGERMANOV - I think this is quite hot FR, I've seen at least 5/6 FRs (#3188 , #3165 ...) 

Tbh, this feature makes sense too. Do you think we could re-open this?

Thanks,
Vraj
