### ISSUE TITLE
Sub wallets

### ISSUE THREAD

**Issue by viduxsh** [Ivy-Apps/ivy-wallet#3227]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have the ability to create sub wallets so you can give different currencies to the sub wallets and group them into one wallet with a standard currency

### Why do you need it?

- it is useful if we plan to keep track of a service such as Exchange, where the main currency is fiat and we have many small accounts with other fiat or cryptocurrencies

**Comment by ivywallet** [comment]
Thank you @viduxsh for raising Issue #3227! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
