### ISSUE TITLE
[FEATURE] Transaction fees

### ISSUE THREAD

**Issue by Cyanhead** [Ivy-Apps/ivy-wallet#3229]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to enter an optional transaction fee for all kinds of transactions.

### Why do you need it?

- There are fees sometimes when I transfer between my accounts (due to local bank policies), and I currently enter these fees as new entries.
  - For example; I own accounts A and B. Account A sends $10 to account B.  A fee of $0.05 is deducted, putting the total expense to $10.05. Account B however, only receives $10. I now have to create a new entry to account for the $0.05.
- To save a little bit more time and for better accuracy.

### How do you imagine it?

- When entering a transaction, the user can toggle an optional fee checkbox that reveals an input field where they can either set the exact fee amount, or a percentage of the main transaction amount.
- On the home screen, the fee can be show in smaller text just below the transaction amount of each transaction that has a fee.
- (Optionally, the feature would persist on recurring transactions as well)

**Comment by ivywallet** [comment]
Thank you @Cyanhead for raising Issue #3229! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
