### ISSUE TITLE
[FEATURE] Transaction time on home

### ISSUE THREAD

**Issue by Cyanhead** [Ivy-Apps/ivy-wallet#3230]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see the entry time of each transaction on the home screen without first clicking on the transaction.

### Why do you need it?

- To be able to tell the time of any transaction at first glance, without the need to open the transaction to view.

### How do you imagine it?

- At the bottom right of each transaction on the home screen, a simple 24 hour time format (23:45) of the transaction is shown.
- This feature can be toggled in the settings so the UI is remains decluttered for users that prefer.

**Comment by ivywallet** [comment]
Thank you @Cyanhead for raising Issue #3230! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This should be a setting that's disabled by default. Use `IvyFeatures.kt`
