### ISSUE TITLE
I have a problem with adding entry past 12.00 AM and before 07.00 AM

### ISSUE THREAD

**Issue by natashadjayaputera** [Ivy-Apps/ivy-wallet#3236]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

For context,

I live in a place that use GMT+7 for their timezone.

Every time I tried to add an entry that has time in between 12.00 AM to 07.00 AM it's saved as yesterday's entry, and everytime I tried to change the time out of that range, the date automatically changed to the day before. Also, if my phone time is in between 12.00 AM to 07.00 AM even though I've changed date already, yesterday's date is still called "TODAY"

### To Reproduce

Entry saved as yesterday's entry:
1. Make sure you are in GMT+7 timezone
2. Add a new entry
3. Choose time value in between 12:00 AM to 07:00 AM
4. Save
5. You can see that the entry is saved as yesterday's date. 

Entry date changed when I changed the time:
1. Open the entry that you saved earlier.
2. Change the time to be above 07:00 AM
3. You can see the date is changed to yesterday's date.

Yesterday's date is called "Today":
1. Have your phone time in between 12:00AM to 07:00AM
2. Open Ivy wallet apps
3. Look at the main transaction history page and see that yesterday's date is still called Today.

### Expected behavior

1. Entry saved between 12:00 AM to 07:00 AM should be saved under correct date in main transaction history page 
2. Changing time should not changed any date.
3. If the phone's date already changed, the app should also changed accordingly.

### Screenshots

Please look at the current time on top left. It's 03:23 on 13 June

Here you can see that I'm trying to add an entry for 13 June 03:23.
![Screenshot_20240613-032315](https://github.com/Ivy-Apps/ivy-wallet/assets/89530293/f03586d3-260d-42af-b01b-231ae8bba69a)

But in the main transaction history page, it's saved under 12 June, and it's still called "TODAY" even though it's already 13 June for me.
![Screenshot_20240613-032318](https://github.com/Ivy-Apps/ivy-wallet/assets/89530293/2d49c2ac-66b7-4877-832a-5ad2544f3dbf)

So I tried to change the time to 08.27 AM.
![Screenshot_20240613-032342](https://github.com/Ivy-Apps/ivy-wallet/assets/89530293/4da87a03-87b6-44f1-9186-c7e5e4db4b4d)

But after I pressed the OK button, the date immediately changed to 12 June.
![Screenshot_20240613-032346](https://github.com/Ivy-Apps/ivy-wallet/assets/89530293/edaf9352-f9ec-47ee-92f0-3b7fd9f383d6)

So I changed it to 13 June and it's saved correctly under 13 June on main transaction history page.
![Screenshot_20240613-032352](https://github.com/Ivy-Apps/ivy-wallet/assets/89530293/a0540dba-5490-41ec-8612-7bca890913dd)

### App version

4.6.3 (163)

### Smartphone

Infinix Note 30 Pro, Android Version 13

**Comment by ivywallet** [comment]
Thank you @natashadjayaputera for raising Issue #3236! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hi @natashadjayaputera can you try the latest APK from GitHub?

**Comment by natashadjayaputera** [comment]
> Hi @natashadjayaputera can you try the latest APK from GitHub?
> 
> https://t.me/c/1647280565/16118

Hello I've tried the latest Ivy Wallet Demo APK shared on Telegram
![Screenshot_20240613-170708.jpg](https://github.com/Ivy-Apps/ivy-wallet/assets/89530293/0aa76303-f273-4b91-8056-4418a1d6e59a)

And it's still showing the same bugs

**Comment by ynshung** [comment]
Related to #3033

**Comment by suyash01** [comment]
@natashadjayaputera there was a fix done related to this issue. Please try the latest APK from Telegram and confirm if this issue persists.

**Comment by natashadjayaputera** [comment]
@suyash01 yup, I think it has been fixed!
