### ISSUE TITLE
[FEATURE] Recent incomes and expenses widget 

### ISSUE THREAD

**Issue by Merouane692** [Ivy-Apps/ivy-wallet#3237]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have recent incomes and expenses on the large size widget (4x4 or 4x2)  
![Screenshot_20240613_124212_One UI Home](https://github.com/Ivy-Apps/ivy-wallet/assets/172429141/cd1b0e32-aba1-4477-8d4d-12e557ba00ed)

### Why do you need it?

- to quick check my latest expenses

### How do you imagine it?

In the blank area

**Comment by amandeepsinghjamwal** [comment]
Good day @Merouane692. I want to work on it, just one suggestion I want from you, will showing last 5 transactions be enough?

**Comment by ILIYANGERMANOV** [comment]
@amandeepsinghjamwal that feature should be a setting disabled by default (some users might find it a privacy problem). Use `IvyFeatures` to create one

**Comment by Merouane692** [comment]
Hi good morning. Yes 5 should be perfect.Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Amandeep Singh ***@***.***> Date : 18/06/2024  13:08  (GMT+01:00) À : Ivy-Apps/ivy-wallet ***@***.***> Cc : Merouane692 ***@***.***>, Mention ***@***.***> Objet : Re: [Ivy-Apps/ivy-wallet] [FEATURE] Recent incomes and expenses widget  (Issue #3237) 
Good day @Merouane692. I want to work on it, just one suggestion I want from you, will showing last 5 transactions be enough?
