### ISSUE TITLE
[FEATURE] Graphs

### ISSUE THREAD

**Issue by bharathkumar019** [Ivy-Apps/ivy-wallet#3239]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to improve my tracking so for that i need statistical report (by pie chart graphics and analysing my tracking in a single graph) 

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @bharathkumar019 for raising Issue #3239! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
There's a Pie chart if you click your expense on the home screen
