### ISSUE TITLE
[FEATURE] Archiving loans after marking as paid

### ISSUE THREAD

**Issue by Aman-Yanni** [Ivy-Apps/ivy-wallet#3242]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to mark loans as complete to remove them from the list without affecting the transactions 

### Why do you need it?

- The current implementation has all loans in a single list which can become quite long and deleting the loan removes the transaction associated with it

### How do you imagine it?

We have an option in the loan object that allows us to mark as complete and that move it into a separate archives/completed list tab with in the loans screen

**Comment by ivywallet** [comment]
Thank you @Aman-Yanni for raising Issue #3242! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
