### ISSUE TITLE
Migrate Paparazzi to Compose Preview Screenshot testing

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3243]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Get rid of Paparazzi in favor of https://developer.android.com/studio/preview/compose-screenshot-testing

### Because...

- Screenshot tests + previews at the same time
- Supported and maintained by the Compose team

### Description

1. Setup Compose Screenshot testing
2. Migrating existing Paparazzi tests to it
3. Get rid of Paparazzi
4. Update the `scripts` (if any Paparazzi related)
5. Update the docs and the CI Troubleshooting guide
6. Update the screenshot test CI check

### Success Criteria

- Everything works like now but with https://developer.android.com/studio/preview/compose-screenshot-testing
- Docs is updated
- CI is updated

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3243! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3243 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
