### ISSUE TITLE
[BUG] Transaction UI doesn't fit for long category names

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3244]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In Transaction log when a longer account name goes shrunk and account name not displayed fully

### To Reproduce

1. 

### Expected behavior

When a longer account name comes it should flow on second line

### Screenshots

![Screenshot_2024-06-14-07-17-01-26_5e9f1c73c4ea0ad7b9937a61f977427e](https://github.com/Ivy-Apps/ivy-wallet/assets/166375674/1401d6db-5f13-47c0-820d-f8c004f68ce3)

### App version

4.6.3  Google Playstore

### Smartphone

OnePlus Nord CE 2 5G

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3244! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by giuseppe2028** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @giuseppe2028! 🎉
Issue #3244 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@giuseppe2028 use https://developer.android.com/develop/ui/compose/layouts/flow to make the Account go on a 2nd row if needed
