### ISSUE TITLE
[BUG] Incorrect time for existing and new transaction

### ISSUE THREAD

**Issue by ynshung** [Ivy-Apps/ivy-wallet#3249]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

This is quite a major issue: I added a transaction such as follows:

![Screenshot_2024-06-23-15-48-55-747_com ivy wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/61302840/82257ac9-9d75-4c98-840d-d16cb53f3db4)

Then when I clicked on the transaction again, the transaction time is now 8 hours behind (which is my time zone GMT+8):

![Screenshot_2024-06-23-15-48-59-380_com ivy wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/61302840/2f863ad7-8019-4633-9d82-0de5335f4ae1)

This bug occurs on existing transaction where all transactions that I checked now became 8 hours earlier.

Hopefully this is something that will be fixed alongside with the existing one.

### To Reproduce

1. Make sure device time zone is set to non UTC (GMT+0) time zone
2. Create a transaction and note the time
3. Click on the newly created transaction
4. The transaction time is incorrect (a few hours earlier or later depending on the timezone set)

### Expected behavior

New and existing transaction time is correct

### App version

4.6.5 from Google Play (Beta Testing)

### Smartphone

Poco F3, Xiaomi Hyper OS 1.0.2.0, Android 13

**Comment by ivywallet** [comment]
Thank you @ynshung for raising Issue #3249! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by mahmoodharis88** [comment]
I'm on it

**Comment by mahmoodharis88** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mahmoodharis88! 🎉
Issue #3249 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
