### ISSUE TITLE
Tags don't work properly

### ISSUE THREAD

**Issue by MPrinzis** [Ivy-Apps/ivy-wallet#3250]
The tags don't show it they are selected and they can't be deleted

**Comment by ivywallet** [comment]
Thank you @MPrinzis for raising Issue #3250! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Which app version? Also this issue does not follow the bug reporting template

**Comment by ILIYANGERMANOV** [comment]
Open a new one following the template, please
