### ISSUE TITLE
Adding the time zone based on the users' places.

### ISSUE THREAD

**Issue by ShiCheng0923** [Ivy-Apps/ivy-wallet#3258]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to list down the things I paid in the apps. But the apps time zone is in USA, which follow the UTC time. But I'm a Malaysian, I use GMT, so I hope there will be a new features for the users to choose their time zone, so no need to keep adjusting the timing, thanks. 

### Why do you need it?

- I can't list down my things accordingly to my time zone. 
- I don't want to keep adjusting the time, I want to make it in my time zone, GMT.
- I used this apps nearly 3 years, I hope my request can be done. Thanks.

**Comment by ivywallet** [comment]
Thank you @ShiCheng0923 for raising Issue #3258! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by giuseppe2028** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
The app should detect the user's device time zone automatically. We have a datetime issues because the data in the DB isn't saved in UTC.

@giuseppe2028 to fix it:
- make sure all transactions are saved in UTC `Instant`
- only in the UI layer when displaying the UTC `Instant` is converted and formatted in local time
