### ISSUE TITLE
Select Time Zone

### ISSUE THREAD

**Issue by hkjansonchan** [Ivy-Apps/ivy-wallet#3260]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have a time zone selector at the setting

### Why do you need it?

- I found that some issues appear as the root cause is the time zone

**Comment by ivywallet** [comment]
Thank you @hkjansonchan for raising Issue #3260! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by zzjjaayy** [comment]
"I'm on it"

**Comment by ivywallet** [comment]
Thank you for your interest @zzjjaayy! 🎉
Issue #3260 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by zzjjaayy** [comment]
@ILIYANGERMANOV I just noticed that this issue is very interconnected with [IvyIssue-3258](https://github.com/Ivy-Apps/ivy-wallet/issues/3258). I suggest both of them to be handled together.

**Comment by giuseppe2028** [comment]
I see that this issue is interconnected with #3258  as well. Therefore, I am trying to create a new settings section to manage the user's timezone.

**Comment by giuseppe2028** [comment]
we can work on it together, if you want

**Comment by zzjjaayy** [comment]
@giuseppe2028 Absolutely! text me on any of my socials on my profile. Would have done that but could not find any way to contact.
