### ISSUE TITLE
Android Smartwatch Support 

### ISSUE THREAD

**Issue by CE-Yazeed** [Ivy-Apps/ivy-wallet#3261]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to use my watch to add expenses/income 

### Why do you need it?

It is a very repetitive task that can be made less tedious 

### How do you imagine it?

A simple app

**Comment by ivywallet** [comment]
Thank you @CE-Yazeed for raising Issue #3261! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by rkd-me** [comment]
Hmmm, list of upcoming payments would be super cool to see on the watch.
