### ISSUE TITLE
[FEATURE] Connect the wallet to a Google Account.

### ISSUE THREAD

**Issue by AbhishekKing-176** [Ivy-Apps/ivy-wallet#3266]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to connect my Google account with the wallet. So requesting a feature where I can link my Google account with my Ivy Wallet

### Why do you need it?

- To have a backup of my wallet expenses in my Google cloud servers.
- Quick sign in using Google account.

### How do you imagine it?

Give us an option while starting the app, where we can choose to have an offline account or an online account. Under online account give us the access to connect our wallets to our Google account and have a backup.

**Comment by ivywallet** [comment]
Thank you @AbhishekKing-176 for raising Issue #3266! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by AbhishekKing-176** [comment]
@ILIYANGERMANOV Please do the needful.

**Comment by ILIYANGERMANOV** [comment]
Hey @AbhishekKing-176 sorry, we don't have the capacity to implement it. It also comes with some legal and privacy risks

**Comment by rkd-me** [comment]
@ILIYANGERMANOV i think you imagined it in a wrong way.

The way I see this could be implemented without any legal issues is to simply backup the IVY Wallet (all data like wallets and transactions) to Google Drive, so user can have a backup in case of device failure.

IMO legal issues could come up while connecting Google Wallet Service to automatically download transactions from Google to IVY, but simple backup of IVY data to Google Drive or actually any other Cloud Drive shouldn't pose any threat.

**Comment by AbhishekKing-176** [comment]
@ILIYANGERMANOV @rkd-me Yes. That would be a better implementation. Please let me know how I can backup the data to my cloud since there is no option to do it.

**Comment by rkd-me** [comment]
I think the only option at the moment is to manually backup data and then upload the archive to your cloud of choice.

**Comment by suyash01** [comment]
For this I think we should implement an auto backup solution to a specific folder and then the user can use their backup app of choice to sync to the cloud.

**Comment by rkd-me** [comment]
Yeah, this could work and would be way easier to implement than making an api connection script for every avaliable cloud.

The choice of backup frequency would be welcome.

**Comment by suyash01** [comment]
IMO we should not have any sort of API integration at all. Just notmal backup that we have happen at fixed interval. It will be up to the user to backup that backup.

**Comment by ILIYANGERMANOV** [comment]
> IMO we should not have any sort of API integration at all. Just notmal backup that we have, happen at fixed interval. It will be up to the user to backup that backup.

I like that! Some users however prefer having some form of cloud backup in case their device breaks

**Comment by suyash01** [comment]
> > IMO we should not have any sort of API integration at all. Just notmal backup that we have, happen at fixed interval. It will be up to the user to backup that backup.
> 
> I like that! Some users however prefer having some form of cloud backup in case their device breaks

In that case, we can integrate google drive backups, which I think backup the entire app data to a location on google drive which has it's own separate section and not editable. On new app launch we can fetch the backup just like what WhatsApp does for its backup. I am not sure about any legal issue that can come up.
