### ISSUE TITLE
Fix typos and mistakes in the Contributions Guidelines

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3270]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

These are Ivy Wallet's contribution guidelines:
https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

Fix typos, mistakes and in general make them easier to understand and follow.

### Because...

- make the contribution process easier
- motivate more developers to contribute

### Success Criteria

- The guidelines are easier to read after your changes.
- The guidelines are easier to understand. 
- Grammar/typos is improved.

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3270! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by CodinGeo** [comment]
Could You assign me this issue?

**Comment by ILIYANGERMANOV** [comment]
@code-a1 you can do it yourself - read https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

There's an automation for that

**Comment by CodinGeo** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @CodinGeo! 🎉
Issue #3270 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Hey @CodinGeo a fee notes:
1. Git LFS is no longer needed and can be removed from the guidelines.
2. We can mention that the automation takes ~2min to assign the issue

In general the better the contributor experience, the better

**Comment by CodinGeo** [comment]
Sure, I'm going to make it as simple and easy to use as I can, so it will be a great help for fresh contributors like myself.
