### ISSUE TITLE
[BUG] 4 decimal is not enough for crypto

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3287]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

<img width="320" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/9d9ef76f-1e20-41b3-b79a-e60ae7014128">

The exchange rate cannot have more than 4 decimals, so when exchanging JPY for BTC (1 JPY = 0.00000011 BTC), it cannot work correctly.

### App version

2024.07.06 (181)

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3287! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by suyash01** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @suyash01! 🎉
Issue #3287 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by suyash01** [comment]
@ILIYANGERMANOV just changing the decimal place will change it for every currency and usually crypto like ETH can have upto 18 decimal places. So, I was thinking to maintain 2 decimal places - one for crypto and one for normal currency.
However, we don't store the type of currency in either account or exchange rate table. what are your thoughts on this?

**Comment by ILIYANGERMANOV** [comment]
Hey @suyash01 we have an `IvyCurrency` class that can differentiate between those. Just create a `Set` of all supported crypto in Ivy Wallet and if the currency is in that set => use crypto decimals. Also, the UI won't properly display 18 places 😬

**Comment by suyash01** [comment]
Ok, from UI perspective I am putting the exchange rate to a new line to prevent wrapping.

**Comment by Jack-Works** [comment]
hi! I'm afraid this issue is not solved. When you edit the exchange rate, you're still being limited to 4 decimals. Please reopen this thank you! cc @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
@suyash01 can you have a look when editing exchange rates?
