### ISSUE TITLE
[BUG] 0 balance after a 2147483647 income transaction

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3288]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

<img width="318" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/df1f8a28-0bb7-4b3a-ab14-b0d06fc8b072">

<img width="372" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/21c27550-acc7-44c0-8b22-7a0c55e67503">

### App version

v2024.07.06 (181)

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3288! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by suyash01** [comment]
Did we fix this? I am not able to reproduce on the latest code base.
@Jack-Works can you check this on your end as well?

**Comment by Jack-Works** [comment]
version 188 is what I said. I found 189 fixes the problem, thanks!

**Comment by suyash01** [comment]
@ILIYANGERMANOV this can be closed.

**Comment by Jack-Works** [comment]
oh I checked this again, this is actually #3327
