### ISSUE TITLE
[FEATURE] Improve Currency exchange: Change the target currency amount

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3292]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Change the amount by specifying the target currency

<img width="313" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/ff75a1d6-c516-44fa-a797-f4943a8ced5c">

In the screenshot above, it will be hard if I want to exchange for 20 Euros because I can only change the amount of USD.

**Comment by Jack-Works** [comment]
I found I described 4 features in this issue. I'll split them and leave the first one in this issue.

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3292! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
