### ISSUE TITLE
[FEATURE] Improve Currency exchange: Reverse the exchange rate

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3293]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

<img width="313" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/c392a6ab-61ec-4bb8-9f9f-71ecb6995f98">

In the screenshot above, the BTC-USD rate is well-known (easy to Google, it's 57154.80 now) but I have no way to set it. I have to use the reverse rate USD-BTC (0.000017) and it's hard to set. (this also triggers bug #3287).

I hope I can specify the reverse exchange rate in this case.

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3293! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
The exchange rates are created from the POV of your base currency. We need to add an additional UI allowing to set the reverse as you suggested

**Comment by Jack-Works** [comment]
Hi, Can you keep this open? thanks!
