### ISSUE TITLE
[FEATURE] Improve Currency exchange: Calculated exchange rate from manually input of source and target currency

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3294]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Let's say we're trading USD-EUR in a bank app.

The bank app tells you, you're spending 1000 USD and getting 918 EUR (it's 921.35 by Google).

It's annoying to do the calculation to get the bank exchange rate.

It will be good if I can input 1000 USD and get 918 EUR and leave the exchange rate calculated.

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3294! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Jack-Works** [comment]
Hi, Can you keep this open? thanks!
