### ISSUE TITLE
[FEATURE] Improve Currency exchange: Trading fee

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3295]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

In many cases, trading between different currencies has a trading fee. If I can record the fee without making 2 transactions manually, that will be great.

The fee might be charged in source currency, target currency, or both.

e.g.

- 1000 USD-EUR with a 3 USD fee
- 1000 USD-EUR with a 2.5 EUR fee
- 1000 USD-EUR with a 1.5 USD and a 1 EUR fee

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3295! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Jack-Works** [comment]
Hi, Can you keep this open? thanks!
