### ISSUE TITLE
[FEATURE] Large screen support

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3298]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

<img width="845" alt="image" src="https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/e11cb98d-a3ed-40ad-b3e7-0321ac38847b">

Thank you, this app is great! I think it will be better if it follows the Android Large Screen guide <https://developer.android.com/guide/topics/large-screens> to improve for tablets and foldable screens.

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3298! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Jack-Works** [comment]
hmm Hello? Can you keep this open? thanks!
