### ISSUE TITLE
Report feature is not working as expected 

### ISSUE THREAD

**Issue by 0smic** [Ivy-Apps/ivy-wallet#3308]

**Comment by ivywallet** [comment]
Thank you @0smic for raising Issue #3308! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey @0smic we need more info, preferably with screen recording to be able to fix this
