### ISSUE TITLE
Disable Firebase Crashlytics for development builds

### ISSUE THREAD

**Issue by suyash01** [Ivy-Apps/ivy-wallet#3309]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Disable crashlytics for developemt builds

### Because...

- It will make development builds faster
- prevents unnecessary data being send to firebase

**Comment by ivywallet** [comment]
Thank you @suyash01 for raising Issue #3309! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@suyash01 check the Contribution Guidelines - this issue isn't yet assigned to you. So follow the process to take it

**Comment by suyash01** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @suyash01! 🎉
Issue #3309 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ahsanishaq721** [comment]
@ILIYANGERMANOV As I understand, nothing should be sent to firebase crashlytics and its dependencies and code should be commented or removed? am I right?

**Comment by ahsanishaq721** [comment]
@ILIYANGERMANOV i have completed my task and created PR. You have marked it ready to merge.

**Comment by suyash01** [comment]
Before removing firebase/crashlytics we can make change where whenever a crash occurs the application will display the trace on the screen and allow the user to copy and report it.

However it's a manual process and the logs are basically lost if the user closes the app. Also there is a gap where the crash happens due to something on the reporting page itself.

Applications like [Mihon](https://github.com/mihonapp/mihon) use this type of crash reporting, which we can look into in case we plan to remove firebase/crashlytics.

**Comment by ILIYANGERMANOV** [comment]
That's an alternative. For now, let's keep Crashlytics for Google PlayStore. Many crahses happen on app open => they can't report it

**Comment by ILIYANGERMANOV** [comment]
I'll close this one for now
