### ISSUE TITLE
Add Scrolls or use multiple lines in category display.

### ISSUE THREAD

**Issue by KrishModi-Hub** [Ivy-Apps/ivy-wallet#3311]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see the complete category and accounts affected in the transactions displayed in homescreen of this application.
![Screenshot_20240709_172927](https://github.com/Ivy-Apps/ivy-wallet/assets/136954955/560acf73-2958-47d1-80f9-e9b5db14572b)

As we can see here.. whenever the category name is large.. it hides the remaining details.. 

### Why do you need it?

- I need it to have more better information of my transactions in the home screen itself

### How do you imagine it?

We can have scrolling or support using multiple lines for displaying large categories.

**Comment by ivywallet** [comment]
Thank you @KrishModi-Hub for raising Issue #3311! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@KrishModi-Hub can you test the latest version from GitHub? It should fix that problem - look at the latest GitHub Release for an APK

**Comment by KrishModi-Hub** [comment]
> @KrishModi-Hub can you test the latest version from GitHub? It should fix that problem - look at the latest GitHub Release for an APK

Yep it is good and it is fixed !!
Thanks!
One more thing... I wanna ask.. when will this changes be reflected in the Google play app?

**Comment by KrishModi-Hub** [comment]
> @KrishModi-Hub can you test the latest version from GitHub? It should fix that problem - look at the latest GitHub Release for an APK

Yep it is good and it is fixed !!
Thanks!
One more thing... I wanna ask.. when will this changes be reflected in the Google play app?
