### ISSUE TITLE
Descriptions in accounts and categories

### ISSUE THREAD

**Issue by KrishModi-Hub** [Ivy-Apps/ivy-wallet#3312]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to have descriptions in accounts and categories that I assign in the application. 
![Screenshot_20240709_173744](https://github.com/Ivy-Apps/ivy-wallet/assets/136954955/ed2f5aed-a1b1-49d0-b885-883439161c96)

Whenever We make a new category all we can do is assign a name, a symbol and a colour to it. We should also be able to save a description of that category.

### Why do you need it?

- Let's assume we have a long list of categories and we save the name of the person in it. We might forget about the identity of the person with that name sometimes.. so we should be able to add description of these categories as well, it's an important component of accounting.
- Having description also helps when having common names for persons, assets, etc.. that we mention as categories.

### How do you imagine it?

![Screenshot_20240709_173744](https://github.com/Ivy-Apps/ivy-wallet/assets/136954955/c89335b5-ad67-41d9-8085-378495219e10)
When we add a new category, have an optional field "description" below name.

![Screenshot_20240709_174356](https://github.com/Ivy-Apps/ivy-wallet/assets/136954955/161e8ade-a205-4a60-bcd4-038ba20c3660)
This description we add should also be visible somewhere in our category screen here.
I recommend below or above the "income/expenses columns".

**Comment by ivywallet** [comment]
Thank you @KrishModi-Hub for raising Issue #3312! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
