### ISSUE TITLE
Change UX of PR template

### ISSUE THREAD

**Issue by CodinGeo** [Ivy-Apps/ivy-wallet#3313]
### Please confirm the following

- [x] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Make process of making PR easier and more pleasant for eye
- Help standardize all future PRs
- Overall enhance UX of using this template

### Because...

- Easier process of reviewing PRs
- Better experience for developers

**Comment by CodinGeo** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @CodinGeo, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
Thank you @CodinGeo for raising Issue #3313! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hey @CodinGeo just approved it. Btw, don't change it. Considering simplifying it here and there. Make sure to highlight that the PR maker must have tested the PR and attach proof that their code works. Thanks for taking the initiative about making our dev-exp better 👏

**Comment by ILIYANGERMANOV** [comment]
comment - I'm on it again 😅

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #3313 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by CodinGeo** [comment]
@ILIYANGERMANOV Should the checklist position of screen recording stay like it is, or should I change it to be about screen recording OR screenshots? Also, there isn't a requirement for every box to be checked for the PR to be considered, right?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV Should the checklist position of screen recording stay like it is, or should I change it to be about screen recording OR screenshots? Also, there isn't a requirement for every box to be checked for the PR to be considered, right?

- All boxes that are applicable must be checked (for example your PR can't have a screen recording)
- Keep it to screen recording, screenshots aren't sufficient because often people's code crashes when you interact with it

**Comment by ILIYANGERMANOV** [comment]
Hey @CodinGeo it would be awesome if you can also reduce the noise from the PR template. I find it annoying when reviewing PRs

![Screenshot_20240710_011050_Chrome~2](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/e527876e-35b9-475e-91ea-4b0243bb86a3)

![Screenshot_20240710_011146_Chrome~2](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/65ef5dfc-7395-4aad-a6cc-8cd644cfe97e)
