### ISSUE TITLE
Remove code related to google sign in

### ISSUE THREAD

**Issue by suyash01** [Ivy-Apps/ivy-wallet#3314]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- remove code related to google sign in as we are not using it anymore

### Because...

- makes code cleaner

### Description

Couple places which I think can be removed
- `loginWithGoogle` method in `OnboardingViewModel`
- `googleSignInLauncher` method in `RootActivity`

**Comment by ivywallet** [comment]
Thank you @suyash01 for raising Issue #3314! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
That's an awesome initiative!

**Comment by ahsanishaq721** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ahsanishaq721! 🎉
Issue #3314 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ahsanishaq721** [comment]
@ILIYANGERMANOV please check my PR.
Thanks
