### ISSUE TITLE
Transactions are automatically being placed under the wrong date on the homescreen [BUG] 

### ISSUE THREAD

**Issue by RheaRamjohn** [Ivy-Apps/ivy-wallet#3315]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Sometimes when I add income or expenses, the date on the home page isn't aligned with the date I set. When I look under the respective transaction account, everything looks normal but when I go to the overall home page, the date for some of the transactions are set as the day before what I actually have it as.

### To Reproduce

1. Add an income or expense on a particular date (eg June 25th).
2. What actually happens is that that transaction is added on June 26th instead on the HOME SCREEN, despite trying to change it again, but on my accounts the date is correct.

### Expected behavior

I expect that the home screen would accurately reflect my transaction dates

### Screenshots

This is in the home page. All the transactions seem to fall under june 25th when the only transaction I had put in for that date is the first one listed
![IMG_20240709_110023_615](https://github.com/Ivy-Apps/ivy-wallet/assets/143855137/9d505818-19aa-43fd-aaa3-443c1d69ef75)
However, when I go to my specific cash transaction wallet, it's done correctly
![IMG_20240709_110027_871](https://github.com/Ivy-Apps/ivy-wallet/assets/143855137/fcb4ded4-2c66-4cf5-9c52-635ec3ef6b47)

### App version

v4.6.3 (163)

### Smartphone

Samsung Galaxy S10e

**Comment by ivywallet** [comment]
Thank you @RheaRamjohn for raising Issue #3315! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by mahmoodharis88** [comment]
@RheaRamjohn can you please make a video on this?

**Comment by suyash01** [comment]
Related to below issues
#3236 
#3303

**Comment by RheaRamjohn** [comment]
> @RheaRamjohn can you please make a video on this?


Uploading Screen_Recording_20240709_235329_Ivy Wallet.mp4…

**Comment by RheaRamjohn** [comment]
> @RheaRamjohn can you please make a video on this?


https://github.com/Ivy-Apps/ivy-wallet/assets/143855137/06317163-6fa3-4688-9255-441e0793640b

**Comment by mahmoodharis88** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mahmoodharis88! 🎉
Issue #3315 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
