### ISSUE TITLE
Attachment for Transaction 

### ISSUE THREAD

**Issue by may-96** [Ivy-Apps/ivy-wallet#3316]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to attach receipt with the transaction (income, expense, transfer or loan). 

### Why do you need it?

- This will be a proof of payment 

### How do you imagine it?

At the time of adding or editing a transaction if user want to attach a receipt of transaction then user will click an attachment button, which will allow them to either take the picture using mobile camera or select an image or pdf file from file manager.

**Comment by ivywallet** [comment]
Thank you @may-96 for raising Issue #3316! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
I just don't like the proof part. Don't use Ivy Wallet for such purposes, it's an open-source money manager that's full of bugs

**Comment by may-96** [comment]
Yeah we don't us it for a proof but still having a receipt with a transaction is quite useful.
