### ISSUE TITLE
[Feature] View recently added transactions

### ISSUE THREAD

**Issue by supunTE** [Ivy-Apps/ivy-wallet#3318]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user, I would like to be able to view the most recently added transactions. This does not mean recent transactions, but rather the most recently added ones. 

### Why do you need it?

Every month, I fill in any missing transaction records. When doing so, I have to input an older date and then add the transaction. However, there are times when I mistakenly enter the wrong date. This means I have to sift through numerous transactions to locate the incorrect one and then update the date again. It would be very helpful if there was a list of the few last added transactions available.

### How do you imagine it?

A list of recently added transactions.

**Comment by ivywallet** [comment]
Thank you @supunTE for raising Issue #3318! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
