### ISSUE TITLE
[FEATURE]  More Options for categories

### ISSUE THREAD

**Issue by GhjuliaM** [Ivy-Apps/ivy-wallet#3320]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have more options to define categories and be able to instantly recognize what it is at first glance. Predefined color options are nowhere near varied enough. I would also like to either have more and more varied type of icons or an option to customize, so it can reflect all possible categories and needs for everyone. 

### Why do you need it?

- I need this type of customization because I have a very well organized and categorized wallet (coming from another app) that has over 20 categories + providers/sellers identification and the current icon options in Ivy do not apply or correspond in a few cases. 

- As for colors, I need to be able to find and/or instantly recognize what an expense is (I personally use the shop or brand color scheme or main color but that's just me) but currently it is limited in numbers and shades.

### How do you imagine it?

Any type of added variety in categories color options would be great, but a color picker would answer all my needs. As for icons, being able to import images or icons from packs would do the same. Thank you for considering it!

**Comment by ivywallet** [comment]
Thank you @GhjuliaM for raising Issue #3320! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by rkd-me** [comment]
One extra button at the end of shades with `+` to add custom color via RGB or any other color picker would be great.

I use one color as category (crypto, banks, etc) and often I'm short of them.

**Comment by ILIYANGERMANOV** [comment]
Sounds good!

**Comment by GhjuliaM** [comment]
Thank you! :)

**Comment by Rex-0x7CB** [comment]
I think having the choice to pick icons would be much more helpful than just RGB colors.

**Comment by akashs056** [comment]
@ILIYANGERMANOV  can we add third party library for RCB custom color picker ?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV can we add third party library for RCB custom color picker ?

Lets not add 3rd panties preferably. Is there an Android/Google one?

**Comment by akashs056** [comment]
I have searched but did not find an official Android or Google library specifically for RGB color picking.
