### ISSUE TITLE
Add tonchain crypto currency

### ISSUE THREAD

**Issue by rkd-me** [Ivy-Apps/ivy-wallet#3321]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I would like to be able to add $ton blockchain as wallet.

### Why do you need it?

It happens to skyrocket in popularity and lots of projects are based on it, so I would like to track expenses related to it.

### How do you imagine it?

It's simple, just another currency to support.

**Comment by ivywallet** [comment]
Thank you @rkd-me for raising Issue #3321! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by vk92257** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @vk92257! 🎉
Issue #3321 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@vk92257 because you're not using our PR description template now I have to close this manually 😬 I'll add CI check that requires proper PR description before merging

**Comment by ILIYANGERMANOV** [comment]
@CodinGeo your improvement of the template is good but I see a few more things we can do:
- too many blank lines
- when I use the template I get confused what is a comment and what is not

For example, I started typing in "I fixed..." and it turned out to be a comment. Can you improve that as well?

The experience when previewing the markdown is good but the experience when creating the markdown is bad. 

@vk92257 can you give us some feedback about our PR template? In general, why you're not using it. We're trying to make the dev experience better so any thoughts/comment would be appreciated

**Comment by CodinGeo** [comment]
@ILIYANGERMANOV I think the main problem is that while creating PR, there isn't any text styling in code view (comments included), and I didn't take that into account while making this template. I will erase all not completely necessary empty lines, leave example of "what's changed" with table uncommented and end every Tip comment with another 💡, so it will be more visible that the comment ends here. At least these are my ideas for now, maybe they'll change. I'm gonna make an issue and start working on it either later today or tomorrow.

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV I think the main problem is that while creating PR, there isn't any text styling in code view (comments included), and I didn't take that into account while making this template. I will erase all not completely necessary empty lines, leave example of "what's changed" with table uncommented and end every Tip comment with another 💡, so it will be more visible that the comment ends here. At least these are my ideas for now, maybe they'll change. I'm gonna make an issue and start working on it either later today or tomorrow.

Sgtm!
