### ISSUE TITLE
Transactions don't be reflected in the amount until time edited

### ISSUE THREAD

**Issue by Jack-Works** [Ivy-Apps/ivy-wallet#3327]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

https://github.com/Ivy-Apps/ivy-wallet/assets/5390719/f8a0a9c5-984d-44e5-ab59-307d8fc4a625

### To Reproduce

1. Set your time zone to Japan (UTC+9)
2. Set time to 5 pm (17:00 +9 = 2 am next day)
3. Add a transaction

### App version

2024.07.06(181)

### Additional context

I think it is treating the local time as UTC+0 or somewhere else, so when you're in 5 pm in Japan, it reads 5 pm in UTC+0, then it convert the time back to UTC+9 and you get 2 am next day.

**Comment by ivywallet** [comment]
Thank you @Jack-Works for raising Issue #3327! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Only transactions that have happened (i.e. before now) are reflected

**Comment by Jack-Works** [comment]
> Only transactions that have happened (i.e. before now) are reflected 

yeah, but newly added transactions are marked as happening in future (as you can see in the video)

**Comment by ILIYANGERMANOV** [comment]
> > Only transactions that have happened (i.e. before now) are reflected
> 
> yeah, but newly added transactions are marked as happening in future (as you can see in the video)

Technically it's not on the timeline. My concern is that counting such transactions will prevent us from optimizing the account balances using caching. Also, some users are used to this behavior and might be using it as a feature. Let's think about the implications before changing it

**Comment by suyash01** [comment]
> > Only transactions that have happened (i.e. before now) are reflected
> 
> yeah, but newly added transactions are marked as happening in future (as you can see in the video)

That is an issue related to UTC conversion.
Related to #3236

**Comment by ILIYANGERMANOV** [comment]
We neee to fix the timezone issues once and forall but migrating existing data won't be trivial

**Comment by suyash01** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @suyash01! 🎉
Issue #3327 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
