### ISSUE TITLE
[RELEASE BLOCKER] Remove Foreground service permissions

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3328]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Unblock Google Play Release

### Because...

- We can't update the app

### Description

![Screenshot_20240711_122352_Chrome](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/3bb8860e-ba17-4089-840b-067108eab5da)
![Screenshot_20240711_122404_Chrome](https://github.com/Ivy-Apps/ivy-wallet/assets/5564499/db5383fe-1d15-4cd0-83e6-02db57245cac)

### Success Criteria

- The foreground service permissions are removed 
- We can release the app to Google PlayStore
- The app is still working as expected

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3328! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@vk92257 please read this https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md

You need to assign the to yourself before working on it

**Comment by vk92257** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @vk92257! 🎉
Issue #3328 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
