### ISSUE TITLE
Fix PR template code view

### ISSUE THREAD

**Issue by CodinGeo** [Ivy-Apps/ivy-wallet#3335]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Remove any not required blank lines
- Make tips and other comments more stand out from main body of PR

### Because...

- For better developer experience

**Comment by CodinGeo** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @CodinGeo! 🎉
Issue #3335 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@CodinGeo can you also remove the "Based to `main` branch` checkbox? It's always based on `main`  by default
