### ISSUE TITLE
Finding good feature from other alternatives

### ISSUE THREAD

**Issue by n3rfy** [Ivy-Apps/ivy-wallet#3339]
### What do you want to be added or improved?

I want to switch from [Zenmoney](https://play.google.com/store/apps/details?id=ru.zenmoney.androidsub&hl=en) to Ivy Wallet, but for a comfortable switch I lack the list of features that are described below. If we need more detailed information on any of the features, then I am ready to provide it.

**Accounts**:
- Ability to automatically synchronize transactions via SMS sent by systems (banks, crypto exchanges).
- Ability to automatically synchronize transactions through integrations/plugins that allow you to authorize in to other systems (banks, crypto exchanges). For example, thanks to the plugin in Zenmoney, you can synchronize transactions using a specified crypto-address. 
   <img src="https://github.com/user-attachments/assets/bdbadd3a-abd6-49f8-8555-49321d8e1eac" width="100">

- Ability to group accounts. For example, in Zenmoney there is a group “Savings”, into which you can group all your savings accounts, and then work with the group in analytics dashboard.
   <img src="https://github.com/user-attachments/assets/c8e782c0-7d58-4670-b4c0-40a55df2b768" width="100">
- Ability to determine what share in the capital each currency has.
   <img src="https://github.com/user-attachments/assets/9b9db2f4-7ce1-41ce-b293-aee60a581013" width="100">

**Transactions**:
- Ability to classify transaction into fixed and flexible, and then work with the classify in analytics dashboard.

**Categories**:
- Ability to assign parent categories, and then work with the categories in analytics dashboard.

**Monthly analytics**:
Most often we analyze finances within the current month, so Zenmoney has a separate section for this.
- Ability to compare income and expenses on a chart for the current month.
- Ability to see planned (future) expenses and income on a graph the current month.
   <img src="https://github.com/user-attachments/assets/e91ac356-5cef-4c01-9fa5-13cb159e7a5d" width="100">
- Ability to view in detail current expenses and income the current month.
   <img src="https://github.com/user-attachments/assets/3a385850-854b-4189-8f2c-e9e7611b15cd" width="100">

**Global analytics**:
This section is for more detailed analytics.
- The ability to track/forecast capital over different periods in the form of graphs.
   <img src="https://github.com/user-attachments/assets/4430949e-7136-454f-84e0-536bb368f10c" width="100">

### Why do you need it?

Why do I want to change Zenmoney?
> Because it is not open-source. Finances are a very personal thing that should be kept safe.

**Comment by ivywallet** [comment]
Thank you @n3rfy for raising Issue #3339! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Please split the feature requests into multiple issues. SMS parsing and automation is out of scope due to legal and privacy issues
