### ISSUE TITLE
Google account backup for datas[FEATURE] 

### ISSUE THREAD

**Issue by jaibyjose77** [Ivy-Apps/ivy-wallet#3341]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add feature of Google account sync for data. So that it can access while we lost and reconfigure in new phone. 

### Why do you need it?

- need data to be safe and secure

### How do you imagine it?

Sync with Google account.

**Comment by ivywallet** [comment]
Thank you @jaibyjose77 for raising Issue #3341! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
We can't guarantee reliability on the cloud sync feature. It's out of scope for now, sorry!
