### ISSUE TITLE
[FEATURE] Add option to create duplicate of an expense or income

### ISSUE THREAD

**Issue by snehageorge25** [Ivy-Apps/ivy-wallet#3342]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to create a duplicate of an expense. This will avoid the hassle of refilling the details like category or date. Sometimes I have the same expense which has the same amount and falls into the same category but the transactions occur on different dates. But to add each transaction, I have to fill in all details. Having a duplicate option would make it simpler.

### Why do you need it?
To make it easier to add similar expenses without having to refill all details
- 

### How do you imagine it?
Each transaction can have a button to duplicate the transaction, and when that new transaction is created, there can be a temporary button which gives edit option.
_No response_

**Comment by ivywallet** [comment]
Thank you @snehageorge25 for raising Issue #3342! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
**Spec**
- The duplicate button should be in the transaction details screen (when you open the transaction)
- Put the duplicate button on the left to the "Delete" one
- It should duplicate everything expect the date and time (they should be current time)
- When the duplicate button is clicked, the transaction detail screen will close and the transaction will be duplicated

**Comment by LexLeontiev** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @LexLeontiev! 🎉
Issue #3342 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by LexLeontiev** [comment]
> **Spec**
> 
> * The duplicate button should be in the transaction details screen (when you open the transaction)
> * Put the duplicate button on the left to the "Delete" one
> * It should duplicate everything expect the date and time (they should be current time)
> * When the duplicate button is clicked, the transaction detail screen will close and the transaction will be duplicated

@ILIYANGERMANOV Hi! This is my first issue on this project. It doesn't seem difficult, but I'm not sure what to do about the design part of it. Where can I get an icon for this button?

**Comment by ILIYANGERMANOV** [comment]
@LexLeontiev you use a material icon from `Icons.` and the standard ones that Compose have
