### ISSUE TITLE
[FEATURE] Change the keypad layout

### ISSUE THREAD

**Issue by Sakchamn** [Ivy-Apps/ivy-wallet#3343]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [x] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I've entered the wrong amount while entering the amount for the transactions, as i have been using the traditional android number keypad for a long time, it's hard to adjust to the layout of the application

### Why do you need it?

- So that whenever a user enters a transaction, they does not enter a wrong transaction in a haste ( for eg, 780 instead of 120)

### How do you imagine it?

Change the layout form 
![IMG_20240714_234705](https://github.com/user-attachments/assets/ee721456-22f8-43ce-aadb-4b96f016754b)
to 
![IMG_20240714_234724](https://github.com/user-attachments/assets/baef1e56-8924-4bab-9665-790387cd1998)

**Comment by ivywallet** [comment]
Thank you @Sakchamn for raising Issue #3343! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
There's no standard for this. We changed it a few times back and forth. For now, we follow the pattern on Samsung

![Screenshot_20240714_213122_Calculator](https://github.com/user-attachments/assets/0be83bf4-efa4-4093-abb9-1444e3c508d0)

**Comment by ILIYANGERMANOV** [comment]
As a alternative we can have a Settings using the `IvyFeatures` class for which type of keyboard to show

**Comment by Sakchamn** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Sakchamn! 🎉
Issue #3343 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@Sakchamn make sure that by default Ivy Wallet uses its current keypad format. Only when the setting that you add is enabled then the keypad will change to your proposal. It might be the simplest to create 2 versions of the keypad composable.

**Comment by ILIYANGERMANOV** [comment]
> hey @ILIYANGERMANOV , i've edited the amount modal function, which now takes a boolean parameter to tell whether to use the default keypad format or not, can you guide me how to create settings for the same ? I've tried doing it my self, but got stuck.

@Sakchamn see the `IvyFeatures` class and add a new called `contactsKeypadEnabled` or some better name
