### ISSUE TITLE
[FEATURE] Transaction Fee

### ISSUE THREAD

**Issue by yuvraj-timalsina** [Ivy-Apps/ivy-wallet#3345]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to add transaction fees if I keep record of money transfers.

### Why do you need it?

Providers charges certain fee while transfers are made between accounts, and the amount is low. Its hectic to add separate record for low amount, so it will be beneficial if charge could be added along with amount for transfers.

### How do you imagine it?

I should be able to add trabsaction fee if I transfer amount.

**Comment by ivywallet** [comment]
Thank you @yuvraj-timalsina for raising Issue #3345! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
