### ISSUE TITLE
[FEATURE] Set Initial Balance to zero (0) or add note on first entry of Loan.

### ISSUE THREAD

**Issue by yuvraj-timalsina** [Ivy-Apps/ivy-wallet#3347]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to have note for my first entry in Loan or create a zero account and add loan records later.
![IMG_20240717_084810](https://github.com/user-attachments/assets/3ca9847b-ef75-4152-a888-2568167ef365)

### Why do you need it?

- To track what the initial loan was for.

### How do you imagine it?

It is good to select wallet and add note for first entry or create zero entry and start adding loan records as it occurs.

**Comment by ivywallet** [comment]
Thank you @yuvraj-timalsina for raising Issue #3347! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
![WhatsApp Image 2024-07-23 at 14 57 55_edf2df1a](https://github.com/user-attachments/assets/fbb40356-1e24-43e2-85cb-2e4070a5fcb7)

@yuvraj-timalsina Are you expecting your UI to look like this ?

**Comment by yuvraj-timalsina** [comment]
@akashs056 Yes, and it would be better if that Starting record could also be selectable by user. 🫡

**Comment by akashs056** [comment]
> @akashs056 Yes, and it would be better if that Starting record could also be selectable by user. 🫡

So apart from starting record, what all tags you prefer

**Comment by yuvraj-timalsina** [comment]
I mean the ability to select category in loans as well by user.

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3347 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
