### ISSUE TITLE
Unlimited repeats in Planned payments Screen hide "Time Component"

### ISSUE THREAD

**Issue by MudassarStd** [Ivy-Apps/ivy-wallet#3349]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In **planned payments** repeat section, there are unlimited repeats for (day, week, month or year) and as we keeping entering numbers, "repeats every" box keeps on stretching across screen which ultimately pushes time (day, week, month or year) button off screen.

### To Reproduce

1. Go to planned payments screen
2. Select multiple times
3. Keep on adding "repeats every" number

### Expected behavior

In my opinion, there should be multi-line feature for large numbers so that time button stays visible OR there should be a limit of repeats corresponding to time (Day, Week, Month or Year).

### Screenshots

![Screenshot_20240717-181045_Ivy Wallet](https://github.com/user-attachments/assets/ddba6ce0-8690-4414-a5f1-34fb6f24f5d7)
![Screenshot_20240717-181056_Ivy Wallet](https://github.com/user-attachments/assets/acc221e5-0b64-464a-a290-966e5a15b04b)

### App version

4.6.3 (163) 

### Smartphone

Samsung Galaxy A12, Android 12

**Comment by ivywallet** [comment]
Thank you @MudassarStd for raising Issue #3349! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by MudassarStd** [comment]
Another suggestion is to implement scrolling text so that "repeats every" box retains its width without pushing "time button" off screen.

**Comment by MudassarStd** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @MudassarStd! 🎉
Issue #3349 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by akashs056** [comment]
@ILIYANGERMANOV it's been more than 7 days but the assignee didn't resolve this issue .please unasign him. I would i like to take on this issue

**Comment by ILIYANGERMANOV** [comment]
@akashs056 you can take it, type the magic words

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3349 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
