### ISSUE TITLE
[BUG] Calculator allowing garbage equations

### ISSUE THREAD

**Issue by vraj152** [Ivy-Apps/ivy-wallet#3357]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The app allows users to enter equations like -> `10+-*/20` - and gives nothing (which is expected) - hence, it'd be better if we just sanitize inputs from user. 

### To Reproduce

1. 

### App version

4.6.3 (163)

### Smartphone

Google Pixel 6 Pro

**Comment by ivywallet** [comment]
Thank you @vraj152 for raising Issue #3357! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3357 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
#3359
