### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Rex-0x7CB** [Ivy-Apps/ivy-wallet#3361]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The "Demo" in the APK's name looks strange when using the app. It gives a feeling as if the product is not quite ready to be used or is designed only for the sales team. It's an amazing application with tons of feature and the name doesn't do justice to it. So, can we remove "Demo" from the application's name.

### To Reproduce

1. Install the application from the APK.
2. Read the name of the installed application.

### Expected behavior

The application name on the Android's application drawer should not contain "Demo"

### App version

Release v2024.07.21-191 from GitHub

### Smartphone

Samsung M33

**Comment by ivywallet** [comment]
Thank you @Rex-0x7CB for raising Issue #3361! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @akashs056, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by akashs056** [comment]
hey @Rex-0x7CB  where can i find the APK

**Comment by Rex-0x7CB** [comment]
@akashs056 It's on GitHub release section. Here: https://github.com/Ivy-Apps/ivy-wallet/releases/tag/v2024.07.21-191

**Comment by akashs056** [comment]
> @akashs056 It's on GitHub release section. Here: https://github.com/Ivy-Apps/ivy-wallet/releases/tag/v2024.07.21-191

Thanks

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3361 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
