### ISSUE TITLE
[FEATURE] Re-design "Categories" view 

### ISSUE THREAD

**Issue by vraj152** [Ivy-Apps/ivy-wallet#3364]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

_Note:_ Similar concern for different view has been raised here - #3297 

Most if not all, categories will have "expense" (not income) - Consider this screenshot. The space here is mostly wasted.

![SS](https://github.com/user-attachments/assets/8970c7b9-332e-4272-939f-7539ff8b134b)

**Comment by ivywallet** [comment]
Thank you @vraj152 for raising Issue #3364! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ivywallet** [comment]
Thank you for your interest @rodrigomatosc! 🎉
Issue #3364 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by rodrigomatosc** [comment]
@ILIYANGERMANOV, what are your thoughts on this redesign?

<img width="393" alt="Screenshot 2024-08-23 at 14 07 56" src="https://github.com/user-attachments/assets/3f57c5c8-5b40-4aff-999a-0df2c18dace0">

<img width="393" alt="Screenshot 2024-08-23 at 14 07 42" src="https://github.com/user-attachments/assets/8ad7a559-f1af-4b00-a760-22ce72aba4b7">

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV, what are your thoughts on this redesign?
> 
> <img alt="Screenshot 2024-08-23 at 14 07 56" width="393" src="https://private-user-images.githubusercontent.com/22649983/360936884-3f57c5c8-5b40-4aff-999a-0df2c18dace0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTg4MzQsIm5iZiI6MTcyNDQxODUzNCwicGF0aCI6Ii8yMjY0OTk4My8zNjA5MzY4ODQtM2Y1N2M1YzgtNWI0MC00YWZmLTk5OWEtMGRmMmMxOGRhY2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEzMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MTY0ODgzZDU1ZDRmZWFjMDAzY2UzZWQyMDI4ZmM3NzNhZTcwZjkyOTBiZWUxMTVmMmE4MTRlZTQwY2JiNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.08P6ynxuTD5MvPih4xq8R7rjl_mgdKmignzVoo7ouwE"> <img alt="Screenshot 2024-08-23 at 14 07 42" width="393" src="https://private-user-images.githubusercontent.com/22649983/360936890-8ad7a559-f1af-4b00-a760-22ce72aba4b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTg4MzQsIm5iZiI6MTcyNDQxODUzNCwicGF0aCI6Ii8yMjY0OTk4My8zNjA5MzY4OTAtOGFkN2E1NTktZjFhZi00YjAwLWE3NjAtMjJjZTcyYWJhNGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEzMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmOGE5YjY5ODU1OTM1NDQ2YTQ0OGVhZTY1NjE0NTQ2ZTc2Nzc5Y2MwYWFiYjM1NmM0ZjEzMjY0MTIxNDVjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_jCyio_rB6gIgLs5wRIYzc9jK4zBK5JQssb_qHwfeE">

Misses information about which account is excluded. Also make sure to gate it via `IvyFeatures`. The compact design should be disabled by default. 

My feedback:
- Reduce spacing between accounts
- Make the Balance bigge
- Support base currency equivalent (e.g. accounts that are not in base currency)

@stefanilijev97 for design feedback

**Comment by ILIYANGERMANOV** [comment]
Looks compact 💯 These are categories (forget about excluded accounts) I thought you were redesigning the Accounts tab (which btw can look similarly)
