### ISSUE TITLE
[TOTAL REMAINING BUDGET] 

### ISSUE THREAD

**Issue by Magediluc** [Ivy-Apps/ivy-wallet#3365]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to know how much my budget left, not only the summary of my planned budget.

### Why do you need it?

A. From there I can find out how much my budget left straightly, no need to summarize it manually anymore
B. And so from there I can find out whether the remaining budget exceeds the total remaining money or not

### How do you imagine it?

The total remaining budget will be shown beneath the budget info, described as "Total Remaining Budget"

**Comment by ivywallet** [comment]
Thank you @Magediluc for raising Issue #3365! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3365 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by akashs056** [comment]
@Magediluc The total remaining budget, which is being calculated. is from the categorized budget. or from the app budget, because if we make any expense, it will show in the app budget. And if expenses categorized, then it will be in categorized budget. We can't include both Because the categorized budget will also fall in app budget also with will lead to miscalculation. So what is your perspective? And how do you think of it

**Comment by akashs056** [comment]
![WhatsApp Image 2024-07-25 at 15 21 51_f1752caf](https://github.com/user-attachments/assets/a4bd5704-cb35-4001-8713-49268cf35507)
@Magediluc  This is what I have done. I have calculated the total remaining budget by the logic that if the app budget is present, then the calculation will be done. How much budget is left in the app budget? If it is not present, then we will sum all the category left budget and summit up and show it. So what's your opinion?

**Comment by akashs056** [comment]
@ILIYANGERMANOV  what's your opinion on this

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV what's your opinion on this

I don't use this feature so feel free to ask in the Telegram community
