### ISSUE TITLE
Invoice / receipts fotos

### ISSUE THREAD

**Issue by NuromenPt** [Ivy-Apps/ivy-wallet#3367]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to...

Hello.

It wold be a nice addon the ability to take a foto of our expenses receipts/invoices and attach it no our expences movements. 

I know that I have this feature of my online account s but I prefer to have it all centralized on Ivy Wallet.

### Why do you need it?

- have full info of expences movements on app
- be able to use Ivy for a digital copy of my invoices/receipts.

### How do you imagine it?

On the adding the expence movement screen, a field/button to photograph ATM or add picture from gallery.

**Comment by ivywallet** [comment]
Thank you @NuromenPt for raising Issue #3367! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
