### ISSUE TITLE
[BUG] Implement pagination for the "Contributors" screen

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3370]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Currently we show only the Top 100 contributors within the "Contributors" screen. 

### To Reproduce

1. Open the Contributors scree from Settings
2. Observe only 100 contributors are shown.

### Expected behavior

All GitHub contributors are displayed and the correct number is visible in the toplbar.
Note: do **not** add new libraries to the project. You might need to implement a new GitHub API request to fetch the exact number of contributors.

### App version

any version

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3370! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by rodrigoliveirac** [comment]
`I'm on it`

**Comment by ivywallet** [comment]
Thank you for your interest @rodrigoliveirac! 🎉
Issue #3370 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
