### ISSUE TITLE
[FEATURE]  Please add the feature of sharing the expenses with the family

### ISSUE THREAD

**Issue by archanpagedar** [Ivy-Apps/ivy-wallet#3372]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to share this expense reporting with my family.

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @archanpagedar for raising Issue #3372! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
We don't have the capacity to maintain online cloud sync
