### ISSUE TITLE
[BUG] Fix the Internal Release Telegram announcement message

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3374]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

There's a `\n\n` that isn't displaying properly. Let's replace it with just spaces

![Screenshot_20240728_131624_Telegram](https://github.com/user-attachments/assets/52da999a-20af-4528-87d8-71447f0c58ec)

Look into the "internal_release.yml" workflow

### To Reproduce

1. Wait for an internal release
2. Observe the Telegram announcement

### App version

n/a

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3374! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3374 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by akashs056** [comment]
![image](https://github.com/user-attachments/assets/72d6f867-0121-4ed2-bfd6-1d9051103783)
@ILIYANGERMANOV  will this do ? I have just replaced the \n\n with 2 spaces . I hope i dont get a detekt failure error...

**Comment by ILIYANGERMANOV** [comment]
> ![image](https://private-user-images.githubusercontent.com/152642367/352807425-72d6f867-0121-4ed2-bfd6-1d9051103783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjgxMzUsIm5iZiI6MTcyMjE2NzgzNSwicGF0aCI6Ii8xNTI2NDIzNjcvMzUyODA3NDI1LTcyZDZmODY3LTAxMjEtNGVkMi1iZmQ2LTFkOTA1MTEwMzc4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMTU3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTcxYTVjMGZkZmRiZDhhNDExYWE3ZmEwMTFiZTdlMjVhZjU2N2RhMzE4NTZkNTM2YTViNWNiZmMzMzQ5OWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OwddIPEKI9AaZwsE6y2f9yvQ4lBXY7yhG2Kl6j7SSRQ) @ILIYANGERMANOV will this do ? I have just replaced the \n\n with 2 spaces . I hope i dont get a detekt failure error...

Looks good, Detekt is only for Kt files
