### ISSUE TITLE
[FEATURE] Add option to hide budget adjustment

### ISSUE THREAD

**Issue by Kreuger** [Ivy-Apps/ivy-wallet#3376]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have the option to hide budget adjustments from the main screen.

### Why do you need it?

- I dont have any desire to see it. Im not sure why but it has been wrong 3 times with just one month of entries.

### How do you imagine it?

Add a check box setting like the ones for hide balance and income.

**Comment by ivywallet** [comment]
Thank you @Kreuger for raising Issue #3376! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
@Kreuger 
can you provide a screenshot of what should be hidden 
'hide budget adjustments from the main screen'
