### ISSUE TITLE
Speed improvement and feature request

### ISSUE THREAD

**Issue by ibrahimgem** [Ivy-Apps/ivy-wallet#3379]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to express Ivy Wallet is an excellent app for managing finances, with an intuitive interface and robust features that make tracking expenses a breeze. However, a speed improvement would enhance the user experience, making it even more efficient and enjoyable to use.
https://github.com/user-attachments/assets/4cc82f7f-2f95-46b7-ac55-b2a61c2f351c

Additionally, including an effective balance (mentioned as {Effective balance}) on every transaction card would further improve its functionality.

![IMG_20240729_161944](https://github.com/user-attachments/assets/51cb5d7b-8353-47a2-a5b6-8b8841bb279b)

### Why do you need it?

-  Apps will take lesser time while doing any transaction entry for user ease.
- It will show the current balance after every transaction for better user experience.

### How do you imagine it?

I have already mentioned as {Effective balance} in attached photo for help.
![IMG_20240729_161944](https://github.com/user-attachments/assets/f33f7d70-88a9-43f8-8fdc-b3441abdbc8b)

**Comment by ivywallet** [comment]
Thank you @ibrahimgem for raising Issue #3379! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3379 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
