### ISSUE TITLE
Report of excluding a tag

### ISSUE THREAD

**Issue by hkjansonchan** [Ivy-Apps/ivy-wallet#3382]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add a function that can filter out a tag

### Why do you need it?

- I usually use the tag to mark which is non important expanses for me.

### How do you imagine it?

In the report, the tag can have a exclude button.

**Comment by ivywallet** [comment]
Thank you @hkjansonchan for raising Issue #3382! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by rodrigoliveirac** [comment]
@ILIYANGERMANOV For this case, I thought about adding a 'Filter Preferences' item to the Settings screen, where the user can choose multiple tags or just one. The system will then display only the transactions with the selected tags. What you think?
