### ISSUE TITLE
[FEATURE] Allow showing predicted balance on home screen

### ISSUE THREAD

**Issue by Thibugs** [Ivy-Apps/ivy-wallet#3384]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to see the planned balance at the end of the month instead of the current balance.
As of right now you can only see the planned balance by clicking on the current balance.

### Why do you need it?

- Allow to see the real available balance at a glance

### How do you imagine it?

A setting to switch between the too options or a long press to switch between (The latest would be less obvious to users)

**Comment by ivywallet** [comment]
Thank you @Thibugs for raising Issue #3384! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
I think the home screen will get too information heavy and expensive if we deicide to show it
