### ISSUE TITLE
Make the "Features" screen visible as a button in Settings

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3386]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

We have the `IvyFeatures` class which manages features gated behind a feature flag. Add a button in Settings to navigate to the "Features" screen where users can control those features. 

### Because...

- Each user have different taste and we must give them an easy way to turn on/off different features. 
- A centralized way for developers to add new features that aren't enabled by default.

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3386! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@letsaguiar you need to type the magic words from the Contribution Guidelines so this issue will get assigned to you by the CI
