### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by akshayrajan07** [Ivy-Apps/ivy-wallet#3387]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Account balance not update properly. when i enter expence it cannot show the current balance

### To Reproduce

1. 

### App version

Latest version 

### Smartphone

Samsung galaxy a30

**Comment by ivywallet** [comment]
Thank you @akshayrajan07 for raising Issue #3387! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by mahmoodharis88** [comment]
@akshayrajan07 can you please share video?

**Comment by suyash01** [comment]
@akshayrajan07 please try with the latest demo apk and post a video or screenshot if the issue still exists.

**Comment by akshayrajan07** [comment]
Uploading SM-A305F_20240803225113.mp4…

Sir please check screenrecord. I reinstall your app and save my income and expence dummy but not reflect closing balance correctly please take any solution for this problem

**Comment by akashs056** [comment]
> Uploading SM-A305F_20240803225113.mp4…
> 
> Sir please check screenrecord. I reinstall your app and save my income and expence dummy but not reflect closing balance correctly please take any solution for this problem

@akshayrajan07  from where you are installing the app and also i cant access your recording

**Comment by akashs056** [comment]
In my testing, after the latest pr this issue has been solved

**Comment by suyash01** [comment]
@akshayrajan07 you have to let the video upload and it will convert to a github link, then only others can access. Please download the latest demo apk from Telegram and check.

**Comment by ILIYANGERMANOV** [comment]
Should be fixed by https://github.com/Ivy-Apps/ivy-wallet/pull/3390
