### ISSUE TITLE
Fix Integration Test Workflow

### ISSUE THREAD

**Issue by suyash01** [Ivy-Apps/ivy-wallet#3391]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Integration test workflow is stuck

### Because...

- Improves code quality and reliability

### Description

Integration test workflow is stuck with below repeated error
```
 /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed
 adb: device 'emulator-5554' not found
 The process '/usr/local/lib/android/sdk/platform-tools/adb' failed with exit code 1
 /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed
 adb: device 'emulator-5554' not found
 The process '/usr/local/lib/android/sdk/platform-tools/adb' failed with exit code 1
 /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed
 adb: device 'emulator-5554' not found
 The process '/usr/local/lib/android/sdk/platform-tools/adb' failed with exit code 1
```

### Success Criteria

- Integration test workflow completes successfully

**Comment by ivywallet** [comment]
Thank you @suyash01 for raising Issue #3391! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Thank you! 🙏

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #3391 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
