### ISSUE TITLE
[BUG] Time Picker Issue

### ISSUE THREAD

**Issue by suyash01** [Ivy-Apps/ivy-wallet#3394]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Time picker is not displaying correct value once a different time has been selected and it is opened again, also it does not switch to 24 hour mode.

### To Reproduce

1. Go to add an expense
2. Edit time and ok - displays 12 hour picker irrespective of system settings
3. Click on time again - displays current time instead of previously selected time

### Expected behavior

- Time picker should display time which was previously selected
- Time picker should show 12/24 hour format depending on system settings

### App version

v2024.07.28 (192)

### Additional context

If possible please try to move the pickers to new compose components.

**Comment by ivywallet** [comment]
Thank you @suyash01 for raising Issue #3394! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3394 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
