### ISSUE TITLE
Google Drive integration

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#34]
Google Drive integration is crucial for two things:
- attach Receipts files to transactions (#6)
- automatic backups for offline accounts (#35)

## Goal
- create "Ivy Wallet" folder in user's Google Drive
- create "Ivy Wallet/attachments" directory for uploading attachments (receipts, invoices, etc

## Success Criteria
- create `:google-drive` module
- implement `GoogleDrive` interface supporting:
  - creating & writing files
  - reading files
  - deleting files
- your Google Drive abstraction can accomplish the things from [Goal](##Goal)

**Comment by MohitMandalia** [comment]
for this feature did you configure the app to use the Drive API?
 if not please include the same

**Comment by ILIYANGERMANOV** [comment]
Hi @MohitMandalia can't we implement it in a way where each user can backup in their own personal GDrive? This way we won't need centralized Ivy configuration, right?

**Comment by MohitMandalia** [comment]
yes correct I am currently looking into what ways can be implemented for drive integration.

and I can see you already have attachment URL in the transaction data class so I think it is not in use currently because i dont see any way to attach a file when adding a trancastion.

Please correct me if I am wrong.

**Comment by MohitMandalia** [comment]
> Hi @MohitMandalia can't we implement it in a way where each user can backup in their own personal GDrive? This way we won't need centralized Ivy configuration, right?

I am also checking on the same.

**Comment by MohitMandalia** [comment]
So regarding this I have made few changes so when we open Activity for result for the flag open document we get option to upload from storage or drive so I think that works if user has allowed files to be shared from drive.

Does this sound good for the attachment part?

**Comment by ILIYANGERMANOV** [comment]
Hi, @MohitMandalia that sounds good! My only concern is that the user might choose the wrong Google Drive folder for their attachment. And btw, great research :)

Q: Is possible to upload via code (w/o stating an Activity) using Google Drive's API?

**Comment by MohitMandalia** [comment]
let me get something clear here this is not related to user saving a backup. This is just the first case where for each transactions user will select a file and attach it to the transaction itself.  What exactly is in your mind can you elaborate both behaviours?

**Comment by MohitMandalia** [comment]
> Hi, @MohitMandalia that sounds good! My only concern is that the user might choose the wrong Google Drive folder for their attachment. And btw, great research :)
> 
> Q: Is possible to upload via code (w/o stating an Activity) using Google Drive's API?

I think you are referring to backup here.

**Comment by ILIYANGERMANOV** [comment]
Yes, I was referring the backup. But your proposal for attaching images to transactions is perfect! Feel free to proceed with it 🚀

**Comment by ILIYANGERMANOV** [comment]
Perfect, thank you @MohitMandalia!

**Comment by ILIYANGERMANOV** [comment]
@MohitMandalia ask for permission after the user clicks the button for attaching/uploading image. We don't need to ask for a permission before we actually need it. Does that answer your question?

**Comment by MohitMandalia** [comment]
> @MohitMandalia ask for permission after the user clicks the button for attaching/uploading image. We don't need to ask for a permission before we actually need it. Does that answer your question?

Yes Thanks as we need to show the attachment filename and we are not saving that name to the transaction table we need to fetch that when Edit transaction screen is initiated let me know your thoughts.

**Comment by ILIYANGERMANOV** [comment]
@MohitMandalia can't we simply generate UUID and use it for attachment name? 

Algorithm:
1. Generate UUID
2. Save the attachment with this UUID as name
3. Set attachmentUrl

I don't understand why do we need attachment name in transaction's table?

**Comment by MohitMandalia** [comment]
Since we dont have a UI for attachment I made one which looks like this :

<img src="https://user-images.githubusercontent.com/36087806/163333299-55275b98-f030-4a07-843c-dde96802bfc0.png" height="700"></img>

No need to save the name but to get name as a user edits it from the URI we need permission if user has not provided it on initiating the screen.

Please suggest if any alternative was is there or if any change in the screen.

**Comment by ILIYANGERMANOV** [comment]
Hi @MohitMandalia your UI is good. I'd suggest:

1) If the attachment is an image to display the image as a picture using Glide.

2) The same applies for videos, if possible? There must be a library for displaying videos.

3) If it's a file: when clicked you should be able to open it.

And thanks for your work! Great job, it would be a killer feature 🚀

**Comment by MohitMandalia** [comment]
sure I will check on it but my concern was just asking permission on load of edit transaction instead of on click because if user opens existing transaction he would need permission to see the attachment. what do you suggest for this.

and this feature will take a bit longer as there is a lot of work involved let me know if that's okay

**Comment by ILIYANGERMANOV** [comment]
I understand now. Well, let's make it as simple as possible for version 1 of the feature then. We can always improve it later.

It is mandatory that if you click the attachment you should be able to see it. When in doubt about the right UI/UX decision just imagine what you'd like best as an user.

Ask yourself what the ideal would do in that situation :)

**Comment by MohitMandalia** [comment]
Yes I was gonna make it such that we can see the attachment my only concern was permission.

Ui was not a doubt actually because as you said had thought as a user to give best UI experience to the user.

**Comment by MMannanAkmal** [comment]
Hi @MohitMandalia @ILIYANGERMANOV, are we done implementing this? If not, I would like to join you guys in completing the feature. Guessing from the thread, @MohitMandalia is working on the Issue #6. I can work on #35. Please let me know what you guys think.

**Comment by ILIYANGERMANOV** [comment]
Hi @MMannanAkmal, nope. And we really need it! It's critical. We need a new `:google-drive` module with simple `GoogleDrive` interface having write, read, delete files methods.

Haven't heard from @MohitMandalia either so feel free to work on it 👍

**Comment by MohitMandalia** [comment]
I wanted but couldn't complete it yet please feel free to pick it up. Sorry man @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
No worries @MohitMandalia 👍 Thanks for participating and helping us!

**Comment by MohitMandalia** [comment]
If @MMannanAkmal couldn't complete it i would like to pick it up again. Thanks

**Comment by ILIYANGERMANOV** [comment]
We managed to complete a fully-working prototype of the Google Drive integration! 🎊 🎆 Special thanks to @MohitMandalia and @CyberSirius for making it possible 👏
