### ISSUE TITLE
CALENDAR | GOALS

### ISSUE THREAD

**Issue by Gclaude33** [Ivy-Apps/ivy-wallet#3400]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see the expenses I will face on the calendar and have a list of savings goals

### Why do you need it?

- Improved clarity of how far I am from the goal
- Improved expenditure planning

**Comment by ivywallet** [comment]
Thank you @Gclaude33 for raising Issue #3400! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
