### ISSUE TITLE
[FEATURE] Layered Transactions

### ISSUE THREAD

**Issue by ItzYeho** [Ivy-Apps/ivy-wallet#3407]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to list multiple "transaction items" within a single transaction. I can give two very clear examples:

Amazon/eBay/other online shopping:
When you pay in those kinds of stores, you are charged for your whole cart, plus shipping and taxes. It would be cool if Ivy Wallet could represent this as one transaction, that includes sub transactions that are representative as "items" in a shopping cart.

For instance, you could have, say, a Water Bottle from Category A and a Shipping cost from Category B, and it would be all layered in the same main transaction that might be called "Bottle from Amazon".

Another example I have is for instance a group order of food with friends. Say you go to a restaurant, or order food on Uber, and you are the sole person paying. If later on your friends send you money, either physically or to your bank account, you can add this as an income sub transaction, which would automatically deduct from the initial value. This would also keep a clean record history.

### Why do you need it?

- Better organization of financial records 
- Easy and convenient way to remember exactly why, say, I spent "$100" on Amazon, listed into items I bought.
- Good intermediate way to manage debts with group purchases (not perfect, but still good nonetheless)

### How do you imagine it?

I imagine it looking sort of like TickTick's subtasks (a todo list management app).

You would have the main transaction (that would be either income or outcome). The main transactions would at first have an account associated with it. However, once you add sub transactions, those sub transactions would have their own accounts associated with them, and the main transaction will have a **list of accounts** associated with it.

To better imagine it, currently you have the category pill for the transaction, and then the account pill. You would have multiple account pills that are scrollable sideways (if that many accounts participated).

If you then open the main transaction, you would see at the top the accounts associated listed top to bottom, with each account having a sum of money taken in/out, in place of the "Pay with" prompt (or in some other way, not fully sure how to integrate it quite yet).

You could then add another sub transaction, and it will ask for details, bank account, etc. And of course those sub transactions could have sub transactions as well, which is imo the "correct" way to code it.

Lastly, in the accounts screen where every transaction associated with the account is shown, it would show any sub transactions associated with the account, along with a "part of [Main Transaction]"

**Comment by ivywallet** [comment]
Thank you @ItzYeho for raising Issue #3407! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ItzYeho** [comment]
I guess I can do it. It'll take me a good while though, my first rodeo in Android development. If nobody else wants this task I'll take it, but again it will take lots of time :)
