### ISSUE TITLE
[FEATURE] An option to directly choose the currency while adding income or expence

### ISSUE THREAD

**Issue by Aswin-avj** [Ivy-Apps/ivy-wallet#3410]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to switch between multiple currencies while adding the income and expences. But it should reflect in a single currency in the income expense dashboard. ie, when I add an expance in a different currency than my default, it should convert it in the background and and ultimately reflet it in the dashboard.

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @Aswin-avj for raising Issue #3410! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
