### ISSUE TITLE
[FEATURE]  add planned transfers

### ISSUE THREAD

**Issue by sammukhgupta** [Ivy-Apps/ivy-wallet#3414]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add scheduled / planned transfers.

### Why do you need it?

- currently only planned expenses are available. Planned transfers will enable a way to manage recurring deposits, SIPs. I have added RD and MF SIPs as separate accounts. Being able to schedule transfers every month from bank to these accounts will make it efficient.

### How do you imagine it?

Similar to the cureently available planned expenses, feature ahould let user add planned transfers recurring every week, month, year, etc.

**Comment by ivywallet** [comment]
Thank you @sammukhgupta for raising Issue #3414! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
