### ISSUE TITLE
[FEATURE] add an option to change the size of UI

### ISSUE THREAD

**Issue by Anvith280** [Ivy-Apps/ivy-wallet#3417]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add an option to increase or decrease the size of the User interface into possibly Small, Medium and Large to be able to see more than a couple transactions/transfers on my screen.

### Why do you need it?

- It would be easier to find a transfer when multiple of them could be viewed at once. It could help visualise the amount of money the person is spending or earning 

### How do you imagine it?

Adding a GUI Scale option in the settings to change the size from "Small, Medium and Large".
1. Small would show a list of transactions while showing minimal information which could possibly include only the money spent/earned, date and the account
2. Medium could use bigger tiles with more information like the category
3. Large could be the current UI

**Comment by ivywallet** [comment]
Thank you @Anvith280 for raising Issue #3417! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
