### ISSUE TITLE
[FEATURE] Sub Tags 

### ISSUE THREAD

**Issue by Krystal7kane** [Ivy-Apps/ivy-wallet#3419]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to categorise a sub tag under a tag
For example, under the category food and snacks, I would further like to categorise it as takeout, groceries, snacks,drinks etc

### Why do you need it?

a) it will make it easier to categorise properly
b) It will help me understand where i need to make changes in my spending behaviour
c) It will help me organise properly

### How do you imagine it?

After i add a tag, a sub tag option would be there under it

**Comment by ivywallet** [comment]
Thank you @Krystal7kane for raising Issue #3419! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
