### ISSUE TITLE
[TRANSLATION] All wanted languages

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#342]
User Request to translate app in different languages includes these:

* #179
* #319
* #353
* #370
* #394
* #397
* #429
* #442
* #447
* #489
* #525
* #798
* #802

**Comment by MohitMandalia** [comment]
@ILIYANGERMANOV 

User Request to translate app in different languages includes these :

- Spanish #277
- Polish  #370
- German #429 
- Romania #525 
- Indonesian #632 
- Arabic #618 

Other duplicate issues : 

- #374 
- #382
- #419 
- #652

**Comment by ILIYANGERMANOV** [comment]
Thank you for the great summary @MohitMandalia!
