### ISSUE TITLE
[FEATURE] ability to edit from PC

### ISSUE THREAD

**Issue by kemekelen** [Ivy-Apps/ivy-wallet#3420]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to edit from PC that connected from USB or local network, while connected, the screen on Android should be paused/blocked.

### Why do you need it?

Sometime I need to make quicker and lot of data at once it become uncomfortable to do from phone interface.

### How do you imagine it?

When connected to the same wifi, on Android I can push a button to enable the feature, the screen then goes dark and showing an ip address for the web interface, then I type it on desktop/laptop browser to open that address, enter pin then edit the wallet.

**Comment by ivywallet** [comment]
Thank you @kemekelen for raising Issue #3420! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
