### ISSUE TITLE
[FEATURE] Auto read SMS message

### ISSUE THREAD

**Issue by selvamsivakumar** [Ivy-Apps/ivy-wallet#3421]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to the app to automatically read the SMS and ask to add it to the expense or income. 

### Why do you need it?

I usually use whatever I buy to make payments through the tap & pay option (NFC), even for a small amount. So I will have many transactions in a day. This is more useful for people like me who want to make more transactions using cards, NFC, UPI, etc.

### How do you imagine it?

- Auto read SMS (should have option to configure what to read from the SMS text content)
- Pop up to ask the user permission to add the information from SMS.

**Comment by ivywallet** [comment]
Thank you @selvamsivakumar for raising Issue #3421! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
