### ISSUE TITLE
[BUG] Incorrect time shown in exported csv file

### ISSUE THREAD

**Issue by SaarthakSinghal** [Ivy-Apps/ivy-wallet#3422]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

This is a transaction in the Ivy Wallet app
[Image 1]
And this is the same transaction in the csv file. 
[Image 2]
I think this issue might be related to #3402 

### To Reproduce

1. Go to settings
2. Export CSV File
3. Some transactions have incorrect time.

### Image 1
![WhatsApp Image 2024-08-23 at 13 30 49_590b7206](https://github.com/user-attachments/assets/07b230fc-b312-44ae-a9e1-f669f55d36d8)
### Image 2
![image](https://github.com/user-attachments/assets/367c0e84-7192-4da7-8895-8bd03f4a296f)

### App version

v2024.07.28(194) from Google Play

### Smartphone

Poco F3 GT, Android 13

**Comment by ivywallet** [comment]
Thank you @SaarthakSinghal for raising Issue #3422! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3422 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
