### ISSUE TITLE
[FEATURE] To include tags in the exported json / csv

### ISSUE THREAD

**Issue by mr-lanholmes** [Ivy-Apps/ivy-wallet#3423]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have the expense tags to be exported together in the json / csv file.

### Why do you need it?

- being able to get 100% details of my expenses exported.

### How do you imagine it?

When exporting csv / json, it will include the tags information as well.
For JSON it should be in array format (i.e. "tags": [ "tag1", "tag2", "tag3" ]
While in CSV format it can be comma separated (i.e. "tag1,tag2,tag3") 

Alternatively, there can be a tags dictionary with UUID as the identifier, which can be exported together

**Comment by ivywallet** [comment]
Thank you @mr-lanholmes for raising Issue #3423! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
