### ISSUE TITLE
Transfer money from one account to another account

### ISSUE THREAD

**Issue by observerabhishek** [Ivy-Apps/ivy-wallet#3429]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to 

### Why do you need it?

- let i have cash money account and paytm money account and i transfer money from cash to paytm but in this situation i have expenses in cash money and add income in paytm so that a very easy when u add a feature of transfer from one account to another

**Comment by ivywallet** [comment]
Thank you @observerabhishek for raising Issue #3429! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Ivy Wallet support logging transfer transactions. Just for context, Ivy Wallet doesn't work with real money - it's just an expense tracker app

**Comment by ILIYANGERMANOV** [comment]
Click "+" and then Transfer
