### ISSUE TITLE
[FEATURE] Allow adding tags to scheduled transactions

### ISSUE THREAD

**Issue by zebrapurring** [Ivy-Apps/ivy-wallet#3437]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

At the moment it is only possible to add tags to past transactions. It would be really helpful if scheduled transactions can also be tagged.

**Comment by ivywallet** [comment]
Thank you @zebrapurring for raising Issue #3437! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
