### ISSUE TITLE
[BUG] Updating a transaction from a report does not get reflected

### ISSUE THREAD

**Issue by zebrapurring** [Ivy-Apps/ivy-wallet#3438]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

After creating a report, when clicking in one transaction and updating it, the report view does not get updated.

### To Reproduce

1. Create a report and add relevant filters
2. Select transaction
3. Make updates to the transaction and save it
4. The report view is still displaying the outdated transaction

This is also reproducible by creating a report, leaving the report activity, updating a transaction and returning to the Reports activity.

### Expected behavior

The report should be updated when any transaction is changed

### App version

v2024.08.25 from Google Play

**Comment by ivywallet** [comment]
Thank you @zebrapurring for raising Issue #3438! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3438 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
