### ISSUE TITLE
Bad Debts features 

### ISSUE THREAD

**Issue by Rajeel-Ali** [Ivy-Apps/ivy-wallet#3439]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to request a new feature for IVY Wallet called "Bad Debts." This feature will allow users to hide or archive debts that are no longer likely to be repaid, such as dormant or uncollectible loans. Similar to how the app already hides zero balance loans, this option would keep these bad debts out of view, helping users better manage their active financial obligations while keeping their records clean and organized. This addition would make IVWallet even more useful for long-term financial management.

### Why do you need it?

 I need the "Bad Debts" feature because, over time, I accumulate loans that have become dormant or unlikely to be repaid. Keeping these visible alongside active loans clutters the interface and makes it harder to focus on the debts that are still relevant. By being able to hide or archive these bad debts, I can better organize my finances and keep my dashboard cleaner, showing only active obligations.

### How do you imagine it?

I imagine this feature working similarly to how zero balance loans are hidden – with a simple toggle or option to archive specific debts, making them invisible on the main interface but still accessible in a separate section if needed for future reference.

**Comment by ivywallet** [comment]
Thank you @Rajeel-Ali for raising Issue #3439! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
