### ISSUE TITLE
[BUG] App crashes when viewing expanded categories in expense or income section

### ISSUE THREAD

**Issue by asadmash** [Ivy-Apps/ivy-wallet#3440]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The app crashes when trying to view any expanded category in both the expense and income sections. The issue occurs with the following steps:
1.Open the app and navigate to one of my accounts.
2.Go to the "Expense" or "Income" section.
3.Click on any of the categories (e.g., "Medicines" in Expense or "Salary" in Income).
4.The app freezes and then crashes.

Note: This crash occurs during any action related to viewing a category's transactions, such as reports, income, expenses, or tapping on a category to view its transactions.

https://github.com/user-attachments/assets/f6ada91f-7840-4d42-a133-e03794926d1f

### To Reproduce

1. Go to any account.
2. Navigate to the "Expense" or "Income" section.
3. Click on any category to expand it.
4. Observe that the app freezes and then crashes.

### Expected behavior

Expected Behavior: The app should display the expanded category view without freezing or crashing.

Actual Behavior: The app freezes and crashes when an expanded category view is accessed in either the expense or income sections.

### App version

Latest demo APK from Telegram (TG).

### Smartphone

Symphony z40 Android 10

**Comment by ivywallet** [comment]
Thank you @asadmash for raising Issue #3440! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3440 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
