### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by refinedleopard** [Ivy-Apps/ivy-wallet#3441]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I want to use this app on multiple devices with a central repository so that my family members can add expenses from their individual devices and the data will be synced to all devices. Currently, I do this manually by exporting data from the last used device and importing the same on other devices. For this I have created a shared folder in my Google Drive where the exported data file gets saved and the other users can import data from that shared folder. What I would like as a new feature in Ivy Wallet is that it can automatically import data from the shared Google Drive folder upon launching the app and export data on exit. This will ensure data is synchronised on all devices within my family.

### Why do you need it?

- To allow family members to add expenses from their individual devices

### How do you imagine it?

Allow configuring the app to automatically export data to a user specified folder (Dropbox or Google Drive) everytime on exit and import the same upon launching the app.

**Comment by ivywallet** [comment]
Thank you @refinedleopard for raising Issue #3441! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
