### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by soumyajits2000** [Ivy-Apps/ivy-wallet#3443]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to make sure that I have different account and there is an option that says if inwant to keep the unit of currency as INR or Euro. Multiple people who use it as euro and inr basically foreign nationals need it. 

### Why do you need it?

-

**Comment by ivywallet** [comment]
Thank you @soumyajits2000 for raising Issue #3443! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
@soumyajits2000 please add a title to the GitHub issue
