### ISSUE TITLE
Backup loose tag

### ISSUE THREAD

**Issue by viduxsh** [Ivy-Apps/ivy-wallet#3445]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I am trying to move the backup to another device. All data seems to be retained except tags.

### To Reproduce

1. 

### App version

2024.08.11 (194)

**Comment by ivywallet** [comment]
Thank you @viduxsh for raising Issue #3445! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Vishwa-Raghavendra** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #3445 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by asadmash** [comment]
No tags were restored. I also tested an old backup file @ILIYANGERMANOV @Vishwa-Raghavendra

**Comment by Vishwa-Raghavendra** [comment]
Hi @asadmash 
Thanks for following up on the bug 

The issue was that for old backups the tag data was entirely missing and not backed up at all 
hence you weren't able to restore it because it was never backed up 

you can get a fresh backup and restore that to see the results
