### ISSUE TITLE
[BUG] Manual time entry during transaction reverts 6 hours earlier

### ISSUE THREAD

**Issue by asadmash** [Ivy-Apps/ivy-wallet#3451]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When manually entering a time while adding a transaction, the time reverts to 6 hours earlier than the intended entry. Automatic time picking works correctly, and the issue is specific to manual time entry for transactions.

### To Reproduce

1. Set the device to UTC (+06:00) BST time zone.
2. Add a transaction and enter a specific time manually.
3. Observe that the time shifts 6 hours earlier than the entered time.

### Expected behavior

The manually entered time for a transaction should match the intended time without any time shift.

### App version

Latest demo APK from TG

### Smartphone

Symphony Z40 Android 10

### Additional context

Time Zone: UTC (+06:00) BST

**Comment by ivywallet** [comment]
Thank you @asadmash for raising Issue #3451! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #3451 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
Should be fixed in #3453

**Comment by jamilxt** [comment]
It's not happening in Emulator, rather in real device. I've debugged it, found out, the method updateDateTime() is called, the date is converting it to UTC which is causing the date to set previous date than selcted date.

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/7c8e95a6-7f1b-495f-9b68-2052e3e15646">

May I know, why are you converting the datetime to UTC?

**Comment by ILIYANGERMANOV** [comment]
> It's not happening in Emulator, rather in real device. I've debugged it, found out, the method updateDateTime() is called, the date is converting it to UTC which is causing the date to set previous date than selcted date.
> 
> <img alt="image" width="1364" src="https://private-user-images.githubusercontent.com/18072164/372269534-7c8e95a6-7f1b-495f-9b68-2052e3e15646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MzY4NzUsIm5iZiI6MTcyNzczNjU3NSwicGF0aCI6Ii8xODA3MjE2NC8zNzIyNjk1MzQtN2M4ZTk1YTYtN2YxYi00OTVmLTliNjgtMjA1MmUzZTE1NjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIyNDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MjQ2MjhkNmVkNzc5ZTM5OGQyZTBiNDVlYWI2ZDc0MDIzNTBlMzcwYWQzYWUwNTI3OWZiNjMxNmE5ZTkwYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wYBl-_tZAvYerJIMPAOfLxI1UaT9KcVryCPcf3DEzkQ">
> May I know, why are you converting the datetime to UTC?

All records in the DB should be in UTC so they are timezone agnostic. Can you test the latest version? It should fix this issue

**Comment by jamilxt** [comment]
The screenshot is taken after running the latest code from the "main" branch. 
Unable to produce the bug on the emulator. But, it's happening in my physical device.

**Comment by jamilxt** [comment]
My suggestion will be - to convert dateTime in UTC in Repository layer while saving the data, rather than in viewModel. After retriving from DB, we can convert it to user's timezone. We can utilize Room's TypeConverter feature for that?

**Comment by jamilxt** [comment]
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/f521bdc6-25cf-4aa3-872b-44c475ce0274">

Handling this centrally will improve maintainability, as it eliminates the need to manually implement it everywhere, reducing errors.

**Comment by ILIYANGERMANOV** [comment]
@jamilxt yes it should be centralized but we have a lot of legacy code that works with `LocalDateTime`. A good solution would be:
- Always work with `Instant` (UTC)
- Firmat this Instant to String (timezone) included before displaying it in the UI

Having LocalDateTime in the UI is terrible for a few reasons:
- It's inefficient: formatting being done in the Compsable and repeated on each recomposition
- It also makes composables unstable 
- The timezone bugs that we have 

However, I don't have the time to migrate all legacy code so tried to hotfix it with back and forth time conversions. My point is that if we make everything Instant there will be no need for conversions
