### ISSUE TITLE
[BUG] Transaction not showing in correct month

### ISSUE THREAD

**Issue by VISVIN** [Ivy-Apps/ivy-wallet#3452]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I added a transaction on Aug 31 but the transaction is showing in September. Even the transaction time also incorrect
![Screenshot_20240831_202433_Ivy Wallet](https://github.com/user-attachments/assets/7e29c721-59dd-4365-83f9-4007b1de41f4)

### To Reproduce

1. Add a expense transaction on Aug 31.
2. Go to the main screen and you will not see yhe transaction in Aug. It will be visible under September. 

### Expected behavior

It should be under September

### Screenshots

![Screenshot_20240831_202433_Ivy Wallet](https://github.com/user-attachments/assets/5ce9f88d-e8cc-466e-bfe2-d85b563d4335)

### App version

Release v2024.08.25-195

### Smartphone

Samsung A52s 5G

**Comment by ivywallet** [comment]
Thank you @VISVIN for raising Issue #3452! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Sennin2222** [comment]
Me too
![Screenshot_20240831_224916_com_ivy_wallet_RootActivity](https://github.com/user-attachments/assets/7ffaea23-fe3b-46ef-80c7-af0d2d717fcb)


V.2024.08.25-195
Smartphone: Honor 90 5g

**Comment by karsh-kay** [comment]
Same issue as #3451, It seems the app is considering the local time as 6hrs behind the actual time. I can see that transaction times have been recently updated.

**Comment by TDYQ-Liu** [comment]
[me too](https://github.com/Ivy-Apps/ivy-wallet/issues/3448)

**Comment by ILIYANGERMANOV** [comment]
Can you retest with v2024.09.01 (latest from PlayStore) and close the issue if it's fixed?

**Comment by VISVIN** [comment]
Thanks Iliyan
