### ISSUE TITLE
[BUG] Incorrect balance & default time captured for transactions.

### ISSUE THREAD

**Issue by anikets349** [Ivy-Apps/ivy-wallet#3457]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

By default when a transaction is being added, the captured time used to be the current time earlier. Now that does not happen, it is set to some other time that is also disturbing the order of transactions. 
Second, about account transfers particularly, it does not reflect the correct balance of the account to which money has been transferred.

### To Reproduce

1. Add a transaction - account transfer 
2. Check if the captured time is current time
3. Check if the balance of both accounts are updated correctly

### Expected behavior

If I add a transaction now, the time by default should be the current time.
Second, the balances of the account(s) must be correctly updated.

### App version

v2024.08.25 (195)

### Smartphone

OnePlus 12

**Comment by ivywallet** [comment]
Thank you @anikets349 for raising Issue #3457! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by harsh5424** [comment]
I noticed that the timestamps on all of the transactions changed, and moved back by five and a half hours.
It seems to be a time zone issue, because I'm in India, and that my time zone is +0530, matches perfectly with the time offset on the transaction.

Hope that helps!

**Comment by ILIYANGERMANOV** [comment]
@harsh5424 can you try the latest release from GitHub?

**Comment by harsh5424** [comment]
All my time stamps seem to be fixed, and adding new transactions gives it the correct time stamp!
That was really quick, thanks guys!
