### ISSUE TITLE
[FEATURE] Reports by Excluding Tags

### ISSUE THREAD

**Issue by mr-lanholmes** [Ivy-Apps/ivy-wallet#3459]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.

### What do you want to be added or improved?

As a user I want to have the capabilities to generate expense report by excluding certain tags.

### Why do you need it?

- Most of user expenses doesn't have tags
- User only add tags for certain use case

### How do you imagine it?

Under the report filter, there's a section to Exclude Tags of choice

**Comment by ivywallet** [comment]
Thank you @mr-lanholmes for raising Issue #3459! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3459 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
