### ISSUE TITLE
[FEATURE] Add option to not display titles suggestions

### ISSUE THREAD

**Issue by Saksow** [Ivy-Apps/ivy-wallet#3460]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want the option to not show the suggested transaction titles from my history when adding a new transaction.

### Why do you need it?

- The list is rarely relevant, I use categories and that is enough to explain what the expense is
- The list hides all my screen so I have to scroll to the more important parts like date and time
- I regretted using titles and now I have to see them every time I add an expense

### How do you imagine it?

I go to Settings > Advanced Features, I see a toggle "Show previous titles suggestions ON/OFF"

**Comment by ivywallet** [comment]
Thank you @Saksow for raising Issue #3460! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3460 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
