### ISSUE TITLE
[BUG] Date & Time are white in dark team

### ISSUE THREAD

**Issue by A-MushtaqAli** [Ivy-Apps/ivy-wallet#3465]
### Please confirm the following

- [ ] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

After updating to latest version date and time picker are showing in white while using dark theme. 

### To Reproduce

1. Just tap on  date or time picker. 

### Screenshots

![Screenshot_20240902-160453](https://github.com/user-attachments/assets/bbb85e9a-bc47-4f57-b615-62b2a5ba53a8)

### App version

2024.09.01

### Smartphone

Google Pixel 3

**Comment by ivywallet** [comment]
Thank you @A-MushtaqAli for raising Issue #3465! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shubhang-d** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shubhang-d! 🎉
Issue #3465 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by oguzsout** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @oguzsout! 🎉
Issue #3465 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
