### ISSUE TITLE
[BUG] Categories Icon Section - Text Showing in Black for Dark Mode also

### ISSUE THREAD

**Issue by VISVIN** [Ivy-Apps/ivy-wallet#3469]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In Transaction Categories, If I want to change the ICON of the Categories like Icon for Fuel, Icon for Grocery.
In the UI I see Text in Black for the Categories Icon Page. Screenshots attached FYR.

### To Reproduce

1. Go to Home Screen of the App
2. Click on Top Right Arrrow
3. Select Categories, click on any category
4. On the top, click on the category name
5. Click the icon right side of category name
6. You will see list of icons.
7. Scroll down to see the Category Name like IVY, Brands, Building etc. 
8. The Text is showing in Black even if the App UI is switched to Dark Mode.

### Expected behavior

The text should be white / any light colour which is readable in the dark background.

### Screenshots

![Screenshot_3](https://github.com/user-attachments/assets/45f09a42-193b-4889-be8d-cc31c47f486b)
![Screenshot_2](https://github.com/user-attachments/assets/2cc0926e-41cc-45db-80a2-e1f8f149dfe1)
![Screenshot_1](https://github.com/user-attachments/assets/bbf8394d-1197-4da4-8fa7-84da1406a082)

### App version

v2024.09.01-196

### Smartphone

Samsung A52s 5G

**Comment by ivywallet** [comment]
Thank you @VISVIN for raising Issue #3469! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3469 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
