### ISSUE TITLE
[FEATURE] Adding a Profile picture to the account. 

### ISSUE THREAD

**Issue by VISVIN** [Ivy-Apps/ivy-wallet#3470]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have a profile picture beside my name in the settings
![Screenshot_20240902_234816_Ivy Wallet](https://github.com/user-attachments/assets/cadbebdf-c819-4d3b-a6ad-9a1a78155f81)

### Why do you need it?

- Its good to have a profile picture on your profile. A personalized touch and good feature.

**Comment by ivywallet** [comment]
Thank you @VISVIN for raising Issue #3470! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
