### ISSUE TITLE
[FEATURE] In the Home Screen. I want to not show the account balance.

### ISSUE THREAD

**Issue by VISVIN** [Ivy-Apps/ivy-wallet#3471]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to completely not show the account balance.
I know there is aoption to hide the balance but it shows **asterisk** .
I want the balance to be completely hidden.
![Screenshot_20240902_234901_Ivy Wallet](https://github.com/user-attachments/assets/1e89716a-1554-4302-a791-efb69a03e3f2)
![Screenshot_20240902_234848_Ivy Wallet](https://github.com/user-attachments/assets/27e8ee99-0111-43d0-ae87-5cd7a5716763)
![Screenshot_20240902_234915_Ivy Wallet](https://github.com/user-attachments/assets/9ad98ca4-a24e-4da0-8509-ddcf9ab984a8)

### Why do you need it?

- Sometimes its just not a good idea to show the balance or the Star Symbols. 
- Balance should be in a reports when user wants to see.

### How do you imagine it?

![Screenshot_20240902_234915_Ivy Wallet1](https://github.com/user-attachments/assets/b49f0afa-c2ca-438b-a6f8-c26f4d43f78b)

**Comment by ivywallet** [comment]
Thank you @VISVIN for raising Issue #3471! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by prathmeshkc** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @prathmeshkc, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
