### ISSUE TITLE
[FEATURE]  Redesign Currency Converter Screen

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3473]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to have a improved UI/UX for currency converter screen.
![photo_6253483322713949870_y](https://github.com/user-attachments/assets/a45db565-3ab1-43db-859a-39c418b8738a)

### Why do you need it?

-  Ease of use and better look & feel

### How do you imagine it?

- We can have a better looking currency column.
-  We can re-position the add rate floating action button.
- We can provide improved floating action button design.

**Comment by ivywallet** [comment]
Thank you @shamim-emon for raising Issue #3473! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
That's a nice one!

**Comment by rodrigomatosc** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @rodrigomatosc! 🎉
Issue #3473 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
