### ISSUE TITLE
[FEATURE] Setting to hide balances from the "Accounts" tab

### ISSUE THREAD

**Issue by paulolima18** [Ivy-Apps/ivy-wallet#3475]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to hide the total balance and total balance(excluded) inside the accounts screen like in the home screen

### Why do you need it?

- It is more private, as I want to use the whole app and I don't mind showing some accounts amount of cash, but showing my global total balance is more private.
- I have several accounts so I can sort them to have more privacy

### How do you imagine it?

Like in the homescreen with the asterisks

**Comment by ivywallet** [comment]
Thank you @paulolima18 for raising Issue #3475! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by paulolima18** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @paulolima18! 🎉
Issue #3475 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
@paulolima18 use IvyFeatures for this one, it should be disabled by default
