### ISSUE TITLE
[BUG] App crash bug when an anonymous contributor is clicked in Contributor Screen 

### ISSUE THREAD

**Issue by akashs056** [Ivy-Apps/ivy-wallet#3479]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

App crash bug when an anonymous contributor is clicked in Contributor Screen 

### To Reproduce

1.  Navigate to Contributors screen from settings
2. Click on any Anonymous one 
3. The app will crash

https://github.com/user-attachments/assets/9a015289-4b25-40d9-8503-06a248e0ae72

### Expected behavior

The app should not open their profile....

### App version

in both the versions the bug is there Playstore and Github 

### Smartphone

Realme 8 Android 11

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you @akashs056 for raising Issue #3479! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
