### ISSUE TITLE
[BUG] Time Not Applied Correctly in Loans – Set Time Behind by 1 Hour (-1h)

### ISSUE THREAD

**Issue by zi3dAouidene** [Ivy-Apps/ivy-wallet#3481]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In the loans section, the time is consistently behind by one hour (-1h) from the set value. This bug results in incorrect time being displayed for all loan entries.

### To Reproduce

1. Navigate to the loans section.
2. Set a specific time for a loan.
3. Observe that the displayed time is consistently behind by 1 hour from the time that was set.

### Expected behavior

The time should match the exact value set for the loan.

### Screenshots

https://github.com/user-attachments/assets/3c9db962-9367-45ef-9cfb-7990cded3126

### App version

v2024.09.01

### Smartphone

Xiaomi redmi 10, Android 11

### Additional context

Please check the attached video for a more detailed demonstration of the issue.

**Comment by ivywallet** [comment]
Thank you @zi3dAouidene for raising Issue #3481! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
To fix it use:
- TimeConverter
- TimeProvider
- DeviceDateTimePicker
- TimeFormatter

these are the proper new classes that are tested and work

**Comment by akashs056** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @akashs056! 🎉
Issue #3481 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
