### ISSUE TITLE
[BUG] Transaction copy does not copy tags

### ISSUE THREAD

**Issue by viduxsh** [Ivy-Apps/ivy-wallet#3484]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When uso the copy function in a transaction, tags are not copied

### To Reproduce

1. 

### App version

2024.09.01 (196)

**Comment by ivywallet** [comment]
Thank you @viduxsh for raising Issue #3484! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by priyatanu** [comment]
I am on it

**Comment by ivywallet** [comment]
Thank you for your interest @priyatanu! 🎉
Issue #3484 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by priyatanu** [comment]
Hi @viduxsh , can you please mention steps or screenshots ?

**Comment by viduxsh** [comment]
Hi @priyatanu to reproduce:
- open a transaction you have already registered with a tag
- press the copy button to create a copy
- verify that the copy has no tag
Thank you

**Comment by viduxsh** [comment]
Hi @priyatanu , is there any news?

**Comment by priyatanu** [comment]
> Hi @priyatanu , is there any news?

I am on it, I was debugging last week but due to sickness I could not proceed further

**Comment by ivywallet** [comment]
⚠️ Hey @priyatanu, this issue is already taken by @priyatanu.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by viduxsh** [comment]
Ok, don't worry and I hope you're better now
