### ISSUE TITLE
[FEATURE] Dynamic Color

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3487]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Right now we have 3 theme option 
i.Dark
ii.Light
iii.Automatic
As a user I want to have fourth option  for theme
with [ dynamic color scheme](https://developer.android.com/develop/ui/compose/designsystems/material3#dynamic_color_schemes) feature where custom colors are generated from device wall paper for supported device.

### Why do you need it?

- It's a new material 3 feature which would make this app better looking

### How do you imagine it?

User would be able to switch to dynamic color theme from settings/quick access menu along side other theme options.

**Comment by ivywallet** [comment]
Thank you @shamim-emon for raising Issue #3487! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by stefanilijev97** [comment]
In order to solve this request, we’ll need:
1. Improve the current design color system to support this options (1 week of work)
2. Introduce UI with color scheme picker with simple and advanced options (0.5-1 week of work)

**Total time needed - 2 WEEKS
Severity - LOW
Level of engagement (from main designer) - HIGH**
