### ISSUE TITLE
[FEATURE] Category Search Bar 

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3488]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

In Category Screen as a user I want to have a search functionality via search bar
[
![category_screen](https://github.com/user-attachments/assets/d71d54f1-ffdd-436d-b759-99888e274999)
](url)

### Why do you need it?

- We have good number of categories and user can add custom categories. Therefore the list may get longer. So it'd be best to have a search option , so one can easily find desired category in the screen.

### How do you imagine it?

In category screen we can have a search bar. This bar will be hidden by default. User can make it visible  from settings.

**Comment by ivywallet** [comment]
Thank you @shamim-emon for raising Issue #3488! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @shamim-emon, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
⚠️ Hey @shamim-emon, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
approved

**Comment by shamim-emon** [comment]
@ILIYANGERMANOV added additional requirement ` This bar will be hidden by default. User can make it visible from settings.` Please let me know if that's alright.

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3488 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
