### ISSUE TITLE
Add Separate Tabs for Pending and Completed Loans in the Loan Section

### ISSUE THREAD

**Issue by Muthuraj5107220** [Ivy-Apps/ivy-wallet#3490]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

It would be helpful to introduce two distinct tabs in the loan section for improved organization and clarity.
Pending Loans: A tab that lists loans that are still active or in progress.
Completed Loans: A tab that lists loans that have been fully paid off or closed.
This feature would help users easily differentiate between their current obligations and those that have been completed. By having these two tabs, it would make the loan section more user-friendly and improve overall navigation.

### Why do you need it?

Proposed Solution:
Add two separate tabs within the loan section:
Pending Loans: For loans that are ongoing or still require payments.
Completed Loans: For loans that have been fully paid off or closed.

This way, users can easily view and manage their ongoing loans without having to filter through completed ones.

Benefits:
Improved clarity: Users can quickly identify which loans are active.
Easier tracking: Allows users to focus on the loans that require attention.
Organized interface: Reduces clutter and improves usability.

**Comment by ivywallet** [comment]
Thank you @Muthuraj5107220 for raising Issue #3490! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3490 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Muthuraj5107220** [comment]
I recently discovered that the eye button located at the bottom of the loan section is designed to hide completed loans from view. In the event that we decide to split the loan section into two separate categories—pending and completed loans—it's important to ensure that the functionality of the eye button is correctly implemented to accommodate this change. This will ensure that users can still easily toggle the visibility of completed loans, even with the new structure in place.
