### ISSUE TITLE
[BUG] Pie Chart Screen Scroll Position Lost

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3492]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When you Go to Pie Chart Screen(Expense/Income) scroll down to bottom and click on income/expense, upon coming back scroll state is lost

### To Reproduce

1. Select Account Tab
2. Tap Any account that has transactions & arrive on Account Details Page
3. In Account Details Page, click on Income/Expense card & arrive on Pie Chart Screen
4. In Pie chart screen scroll down and tap on any transaction & arrive on transaction details screen.
5. Navigate back to Pie chart screen & you will see Pie Chart Screen has lost scroll position.

### Expected behavior

Pie Chart Screen shouldn't loose scroll position.

### Screenshots

![photo_6274060785906990851_y](https://github.com/user-attachments/assets/60824631-b8e7-4a3e-8408-5227b697bae1)

### App version

v2024.09.08(197)

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3492 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
