### ISSUE TITLE
Account interface when adding entries

### ISSUE THREAD

**Issue by FerMario** [Ivy-Apps/ivy-wallet#3494]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to see all accounts on top of the amount when adding an entry in the wallet 

### Why do you need it?

- Makes it much easier and faster to select the relevant account
- Easier to locate the relevant account 
![Screenshot_20240911-215722](https://github.com/user-attachments/assets/ad5d10dd-cd7d-4631-b4b5-fd5e4100be07)

### How do you imagine it?

Arrange the accounts in an array and make the individual icons smaller so that it could maybe fit 3 accounts per row.
This will make it much easier than having to scroll right until you find the relevant account

**Comment by ivywallet** [comment]
Thank you @FerMario for raising Issue #3494! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This must be a setting via `IvyFeatures` that is disabled by default

**Comment by FerMario** [comment]
How can it be enabled?
