### ISSUE TITLE
Automatic CSV backups for offline accounts

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#35]
Backup transactions CSV automatically for offline accounts in Google Drive every N day.

**DEPENDS ON:**
- Google Drive integration (#34)

**Comment by iwitz** [comment]
Would those backups need to be to a Google Drive / OneDrive cloud, or would we be able to perform a backup to the filesystem ?
Thank you !

**Comment by ILIYANGERMANOV** [comment]
Only online GitHub backups
