### ISSUE TITLE
[FEATURE] Navigation Back Button In Exchange Rates  

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3504]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Currently, in` Exchange Rates` Screen we don't have any navigation back button. So, user needs to use device back button to navigate back from this screen. I'd be better if we add a `back button` to this screen to maintain look and feel consistency.

![photo_6280589419664752113_y](https://github.com/user-attachments/assets/e9e34e98-9953-4761-8d83-868e88b55279)

### Why do you need it?

-  To maintain consistent look and feel across application.

### How do you imagine it?

Like common navigation button in other screens.

**Comment by ivywallet** [comment]
Thank you @shamim-emon for raising Issue #3504! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3504 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
