### ISSUE TITLE
[Refactor] HomeViewModel: use `by` delegation for mutable states

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3505]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Rework `val x = mutableStateOf()` and `x.value` to `x by mutableStateOf()` and `x`.

### Because...

It's more convenient to use and the code becomes simpler to read.

### Success Criteria

- No functional changes
- The app works as expected

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3505! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by prathmeshkc** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @prathmeshkc! 🎉
Issue #3505 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
