### ISSUE TITLE
Automatically Detect Transactions From SMS

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#351]
Detect transactions automatically based on the incoming messages from the banks. Both incoming and outgoing money can be tracked with automatic categorisation based on where it was spent. Walnut is a great example app.

**Comment by zadn** [comment]
Another example I can cite here is SMS Organizer from Microsoft. It's not a finance management application, but still I can use it as a finance manager just with this one feature, where they categorize according to each account/cards and does a pretty good job at listing each transaction. This feature is missing from most of the finance management apps and would love to see this implemented in Ivy Wallet.
![image](https://user-images.githubusercontent.com/32202869/147954751-f06ebc1d-c7b0-4204-93d1-2a633ebb821d.png)

**Comment by ILIYANGERMANOV** [comment]
Thanks for the suggestion @zadn! We'll investigate how it can be done and start coding when I have time to do so. Unfortunately, I'm a solo Android developer with lots of features/improvements for the app. But me and my co-founder (the designer) do our best.
