### ISSUE TITLE
[BUG] Exchange Rate Clear Text Visibility Issue

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3515]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In Exchange Rate Screen the clear text icon in search bar is always visible.

### Expected behavior

Clear text button/icon would only be visible when there is any text in search bar

### Screenshots

![photo_6285267721381855240_y](https://github.com/user-attachments/assets/9d613753-c984-4ab9-8f59-a8c88e0e60bf)

### App version

v2024.09.05(198)

**Comment by ivywallet** [comment]
Thank you @shamim-emon for raising Issue #3515! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by mohsin363** [comment]
I'm on it.

**Comment by ivywallet** [comment]
⚠️ Hey @mohsin363, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by mohsin363** [comment]
I'm on it.

**Comment by ivywallet** [comment]
Thank you for your interest @mohsin363! 🎉
Issue #3515 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
