### ISSUE TITLE
[FEATURE] Amoled friendly Dark mode

### ISSUE THREAD

**Issue by MehrabShawon** [Ivy-Apps/ivy-wallet#3518]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to request an AMOLED-friendly dark mode. The current dark mode isn't pitch black, and it's uncomfortable for my eyes since I've been using a pitch-black theme for years. It would be great if you could add an AMOLED-friendly dark mode that features a true pitch-black background.

### Why do you need it?

- Comfortable for the eyes for some people (including me).
- Looks better, in my opinion.
- Consumes slightly less battery on phones with OLED/AMOLED displays.

### How do you imagine it?

I'm looking for an AMOLED dark mode where the background is pitch black instead of gray.

**Comment by ivywallet** [comment]
Thank you @MehrabShawon for raising Issue #3518! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by paulolima18** [comment]
Changing the default black in the object `IvyColors` from this `val Black = Color(0xFF09090A)` to this `val Black = Color(0xFF000000)` is enought I think, does this work or maybe we should create a new Theme? @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
We should create a new theme. Otherwise, we'll break our original dark mode that most users like

**Comment by paulolima18** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @paulolima18! 🎉
Issue #3518 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
