### ISSUE TITLE
[BUG] Search Transactions Clear Text Icon Visibility Issue

### ISSUE THREAD

**Issue by mohsin363** [Ivy-Apps/ivy-wallet#3535]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

On search transactions on the Home Screen, the clear text icon in the search bar is always visible.

### To Reproduce

1. 

### Expected behavior

Clear text button/icon would only be visible when there is any text in the search bar

### Screenshots

![WhatsApp Image 2024-09-16 at 16 49 44](https://github.com/user-attachments/assets/5e3697b5-8ee6-42ee-8d24-01388bb92421)

### App version

v2024.09.05(198)

**Comment by ivywallet** [comment]
Thank you @mohsin363 for raising Issue #3535! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by mohsin363** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @mohsin363! 🎉
Issue #3535 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
