### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by cmatthew-s** [Ivy-Apps/ivy-wallet#3536]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to built a live tracking dashboard regarding my financial performance, for this purposes I hope that Ivy Wallet will have atleast a feature to connect to an existing google sheets, on where I couls connect to a customizable dashboard  using any BI Software. From here I could make a better decision regarding my financials.

### Why do you need it?

- To make a better decision with my financials performance
- To be able to evaluate my financial performance
- To be able to make a dynamic forecast Year End Prediction about my savings
- To be able to perform a better financial planning

### How do you imagine it?

Just a simple button to connect to any existing datasource, whether its postgres, mysql or google sheet. I would suggest google sheets, due to its simplicity

**Comment by ivywallet** [comment]
Thank you @cmatthew-s for raising Issue #3536! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
