### ISSUE TITLE
IMPORTANT! Join https://discord.gg/gruppe

### ISSUE THREAD

**Issue by cfer4nanderzH** [Ivy-Apps/ivy-wallet#3537]
Hey there!
Please join our Discord server, we have to tell you something important.

https://discord.gg/gruppe

**Comment by ivywallet** [comment]
Thank you @cfer4nanderzH for raising Issue #3537! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Spam
