### ISSUE TITLE
[Refactor] Simplify the Loans screen by making the Tabular UI the default one

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#3541]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

See https://github.com/Ivy-Apps/ivy-wallet/pull/3539#discussion_r1764537363

After the change only the Tabular UI code should be left and everything else cleaned up.

### Because...

- Simpler code

### Success Criteria

- Loans work as expected

**Comment by ivywallet** [comment]
Thank you @ILIYANGERMANOV for raising Issue #3541! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3541 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
