### ISSUE TITLE
[FEATURE] Add color to accounts labels in transactions list.

### ISSUE THREAD

**Issue by DrwOOx** [Ivy-Apps/ivy-wallet#3545]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Would it be possible for that "label" to appear in the color of the account instead of black... Like it happens with the categories in all transactions list.

### Why do you need it?

It would provide more clarity to know to which account each record belongs with a quick query to the transaction list.

![image](https://github.com/user-attachments/assets/19e117ce-fc30-4fa7-859e-8647d7106efa)

### How do you imagine it?

It would be similar to how the categories label is shown in the transaction list but for the accounts label, showing the color that these have defined in their setting in the accounts section.

**Comment by ivywallet** [comment]
Thank you @DrwOOx for raising Issue #3545! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This should be an `IvyFeatures` setting that's disabled by default

**Comment by DrwOOx** [comment]
> This should be an `IvyFeatures` setting that's disabled by default

Would it be possible to add the advanced configuration setting to be able to activate it? Thank you.

Regards.

**Comment by ILIYANGERMANOV** [comment]
That's the idea - an advanced setting. The reason why it'll be off by default is because the UI will look too colorful with both categories and accounts => it'll be a distraction. But there's no problem having it as a setting

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3545 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
