### ISSUE TITLE
[Bug] Loan transactions disappears

### ISSUE THREAD

**Issue by Muthuraj5107220** [Ivy-Apps/ivy-wallet#3546]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I noticed something unusual with the demo APK released for #3490 Tabular Loan UI. The change works as expected, showing the loan in the completed tab once it is finished. However, after adding a new record, the entire loan disappears from both the pending and completed tabs.

I've attached the screen recording for reference. Please feel free to reach out if you have any questions or need further clarification regarding the test.

### To Reproduce

1. Add a loan entry.
2. Repay the loan, as it will show in the completed loans tab.
3. After that add a new record in the same load, the entire loan disappears from both pending and completed loans.

### Expected behavior

It should be displayed in the completed loans tab.

### App version

v2024.09.15-198

### Smartphone

Realme GT Neo 3T, Android 14

**Comment by Muthuraj5107220** [comment]
https://github.com/user-attachments/assets/365f3430-c186-4732-b984-4621ee011fb2

**Comment by ivywallet** [comment]
Thank you @Muthuraj5107220 for raising Issue #3546! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3546 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Muthuraj5107220** [comment]
I have tested the latest apk but the same problem exists.

**Comment by Muthuraj5107220** [comment]
@ILIYANGERMANOV @nvllz I am sorry for that, It is working great as expected.
