### ISSUE TITLE
[BUG] Inconsistent icons size in Settings

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3549]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

There's visible inconsistency in Settings icons – Language and Theme icons are much larger than the others, and some are much smaller. 

### Expected behavior

Make all the icons the same size.

### Screenshots

![f82c8272-72f5-4065-9bd1-f37f0a4baa88](https://github.com/user-attachments/assets/efbd5b07-e5b4-458e-bf22-78f2fd8330fe)

### App version

Latest action build

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3549! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ivywallet** [comment]
Thank you for your interest @nvllz! 🎉
Issue #3549 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
