### ISSUE TITLE
Home page Summary by Category 

### ISSUE THREAD

**Issue by kins4fred** [Ivy-Apps/ivy-wallet#3555]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see a summary by Cash, Bank, Debit Card, Credit Card, investment. So each account will have a category to aid the summary function. 

### Why do you need it?

- At a glance, you can see your Credit card summary. Bank accounts balance, investment balance. 

### How do you imagine it?

All Savings and Checking account will be treated as Bank Account. With this function, you can modify Credit cards to have a limit entry so that when you spend, it can show your percentage utilization, limit and current balance. While in the home page Credit  card summary will be showing total of all credit limits  utilization and current balance.

**Comment by ivywallet** [comment]
Thank you @kins4fred for raising Issue #3555! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
