### ISSUE TITLE
[FEATURE] Advanced features grouping

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3559]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Advanced Features screen is a bit.. random.

![9b862492-9807-4949-8289-6af63762f88b](https://github.com/user-attachments/assets/5a7236d6-e5e2-4ccd-a0fe-cfc6199aa9db)

These tweaks could be grouped and labeled as "Accounts tab", "Categories" and "Transactions".

### Why do you need it?

- better user experience, as it's easier to recognize specific settings
- as this section keeps growing, it will become a bit clattered very soon

### How do you imagine it?

Maybe like the Settings screen group labeling, but more compact.

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3559! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Introduce a nullable `group: FeatureGroup?` which is `enum FeatureGroup`

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3559 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by shamim-emon** [comment]
> @shamim-emon would it be possible to apply this switch style for advanced features? It would make the design more consistent.
> 
> ![fffd5e5a-9732-4ca7-9a0d-b7a0f0ce8353](https://private-user-images.githubusercontent.com/110673332/370817640-7d5daa95-a6a4-4379-be42-8012273a24f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTQzNTIsIm5iZiI6MTcyNzMxNDA1MiwicGF0aCI6Ii8xMTA2NzMzMzIvMzcwODE3NjQwLTdkNWRhYTk1LWE2YTQtNDM3OS1iZTQyLTgwMTIyNzNhMjRmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwMTI3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjkzN2E1OGIzNGRiYTY1YmY4Mjc1MTY3OWZmNTg2YTAzYWFiMTkyY2UzNzVhNTFkY2M5YjA5MjRkZTJmMGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mWhZNdGN6biclUVskV3nP4OHs95mpRcwvuNakpM4d1s)

Sure!
