### ISSUE TITLE
[Subcategory] & [Split Budget]

### ISSUE THREAD

**Issue by Rudra0123** [Ivy-Apps/ivy-wallet#3560]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add Subcategory in expense and income category & I want to add a Split Budget (For Room Partners  or family). 

### Why do you need it?

- To Add detailed Finance and  Split the budget with others

**Comment by ivywallet** [comment]
Thank you @Rudra0123 for raising Issue #3560! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
This issue should be split into two separate ones so contributors can work on if parallel
