### ISSUE TITLE
[FEATURE]Hide upcoming income 

### ISSUE THREAD

**Issue by abdelrahman267** [Ivy-Apps/ivy-wallet#3561]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to be able to select If I want to hide or show upcoming payments( income)

### Why do you need it?

Because the interface is very disturbing and not oranganized

**Comment by ivywallet** [comment]
Thank you @abdelrahman267 for raising Issue #3561! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
