### ISSUE TITLE
[TRANSLATION] Galician

### ISSUE THREAD

**Issue by ikergcalvino** [Ivy-Apps/ivy-wallet#3565]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to add the Galician translation.

### Why do you need it?

- It is a somewhat undervalued language that not many apps include, and I would like to contribute to the project.

**Comment by ivywallet** [comment]
Thank you @ikergcalvino for raising Issue #3565! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ikergcalvino** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ikergcalvino! 🎉
Issue #3565 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
