### ISSUE TITLE
[BUG] reading higher expenses 

### ISSUE THREAD

**Issue by abdelrahman267** [Ivy-Apps/ivy-wallet#3566]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The application is reading much higher expenses than actual expense 

### To Reproduce

1. 

### App version

V2024.09.22(199)

**Comment by ivywallet** [comment]
Thank you @abdelrahman267 for raising Issue #3566! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Not enough info to reproduce
