### ISSUE TITLE
Auto Backup Data

### ISSUE THREAD

**Issue by jovian-parco** [Ivy-Apps/ivy-wallet#3586]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to auto backup settings and data, a plus if cloud storage is possible

### Why do you need it?

- if device is lost or broken data is lost forever 
- possible to use cross device syncing 

### How do you imagine it?

Maybe auto backup first to device store next future is to cloud storage.

**Comment by ivywallet** [comment]
Thank you @jovian-parco for raising Issue #3586! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_
