### ISSUE TITLE
[FEATURE] Loan screen horizontal swipe gesture

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3589]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to seamlessly move between Pending/Completed cards on the Loans screen using a horizontal swipe gesture.

### Why do you need it?

- to improve user experience

### How do you imagine it?

The same way it works in the main screen:

https://github.com/user-attachments/assets/70d5a904-57e6-471c-b101-aec96e1aae65

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3589! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by p42rthicle** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @p42rthicle! 🎉
Issue #3589 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
