### ISSUE TITLE
[BUG] UI is being cut on loan section

### ISSUE THREAD

**Issue by Kishore263** [Ivy-Apps/ivy-wallet#3593]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

On the loan section we can see the last loan ui are being cut in both pending and finished loans

### To Reproduce

1. 

### Expected behavior

Add spacer in bottom of the loan section 

### Screenshots

![IMG_20241008_161508_532](https://github.com/user-attachments/assets/8b79320d-b87d-4543-b951-a14161fbda05)

### App version

v2024.09.29

### Smartphone

OnePlus Nord CE 2 5G

**Comment by ivywallet** [comment]
Thank you @Kishore263 for raising Issue #3593! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it
