### ISSUE TITLE
[FEATURE] Improve the "Hide total balance" ivyfeature

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#3597]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

Currently, the "Hide total balance" setting turns total balances into asterisks. You can't reveal them like other hidden balance rows, and this static way is a total waste of space. I see there are two options:
1. Instead of masking balances, hide this section completely
2. Make these asterisks "tap to reveal"

### Why do you need it?

- better user experience
- in case of implementation the 1st way: cleaner UI, the other way: usability of the section

**Comment by ivywallet** [comment]
Thank you @nvllz for raising Issue #3597! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3597 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
