### ISSUE TITLE
[FEATURE] Option to reverse number pad (similar to phone dialer)

### ISSUE THREAD

**Issue by arafatamim** [Ivy-Apps/ivy-wallet#3598]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

An option to reverse the layout of the number pad in the application.

### Why do you need it?

To align with the user's muscle memory from phone dial pads, improving usability and reducing input errors.

### How do you imagine it?

- A toggle in the settings menu to switch between standard and reversed layouts
- When reversed, the number pad layout would mirror a phone dial pad:
```
1 2 3
4 5 6
7 8 9
. 0 ⌫
```

**Comment by ivywallet** [comment]
Thank you @arafatamim for raising Issue #3598! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Dev notes: use `IvyFeatures` to implement such advanced setting

**Comment by p42rthicle** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @p42rthicle! 🎉
Issue #3598 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
