### ISSUE TITLE
[BUG] The time circle has a non-centralized position

### ISSUE THREAD

**Issue by adanyl0v** [Ivy-Apps/ivy-wallet#3599]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When you add a new entry, when you specify a timestamp, the time circle is closer to the left edge of the screen. Is it supposed to be like that?

### To Reproduce

1. Click on '+'
2. Go to 'Add income/expense/transfer'
3. Click on 'Created on' field 

### Screenshots

![Screenshot_20241010-080654](https://github.com/user-attachments/assets/9ac1a3d4-503e-485d-9823-86ea5254955d)

### App version

v2024.10.06-201 from Google Play

### Smartphone

Google Pixel 6a

**Comment by ivywallet** [comment]
Thank you @adanyl0v for raising Issue #3599! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by p42rthicle** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @p42rthicle! 🎉
Issue #3599 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
