### ISSUE TITLE
[BUG] report are all zero  

### ISSUE THREAD

**Issue by Acevoligit** [Ivy-Apps/ivy-wallet#3613]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The report page everything is zero even if I have a lot of in and out  

### To Reproduce

1. Just go to report page and everything is zero 

### Expected behavior

I expected to see graphic report and charts 

### Screenshots

![Screenshot_2024-10-13-19-40-13-994_com ivy wallet](https://github.com/user-attachments/assets/ab1d73f9-aef3-4004-b4d9-ed61abe9552f)
![Screenshot_2024-10-13-19-40-35-792_com ivy wallet](https://github.com/user-attachments/assets/01f0378c-e800-4900-8a16-b1affc33b456)

### App version

V2024. 09.29 from Google play

### Smartphone

Xiaomi Redmi note 10 pro 

### Additional context

2024.09.29 from playstore

**Comment by ivywallet** [comment]
Thank you @Acevoligit for raising Issue #3613! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
You need to first set a filter
