### ISSUE TITLE
[BUG] Delete Dialog Incorrectly reappears

### ISSUE THREAD

**Issue by p42rthicle** [Ivy-Apps/ivy-wallet#3616]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The delete dialog is incorrectly reappearing upon deleting an account and then clicking  another account's card item in the Accounts List Screen.

### To Reproduce

1. Create a sample Account in the Accounts Screen (optional - just to see this behaviour)
2. Click on an existing account card from the list of accounts and in there, click on delete icon (top right)
3. Confirm deletion
4. Upon successful deletion you will be returned to the accounts list again
5. Click on any other account card and you should see delete dialog reappearing

### Expected behavior

The delete dialog should not reappear

### Screenshots

https://github.com/user-attachments/assets/262db800-ce7f-4076-836a-5a2ee8613427

### App version

v2024.10.13 (202)

### Smartphone

Samsung Galaxy S23

**Comment by p42rthicle** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @p42rthicle! 🎉
Issue #3616 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
