### ISSUE TITLE
[BUG] Should not be able to select past date for planned payments

### ISSUE THREAD

**Issue by p42rthicle** [Ivy-Apps/ivy-wallet#3617]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

As the title suggests, we should not be able to select past dates for planned payments (or so I think). If this is intended behaviour then we can close this issue

### To Reproduce

1. Create a new planned payment
2. Select any date in the past.

### Expected behavior

We should not be able to select past dates

### Screenshots

https://github.com/user-attachments/assets/fb8a8295-273f-40a9-bd38-1ff2d6a7107f

### App version

v2024.10.13 (202)

### Smartphone

Samsung Galaxy S23

**Comment by ivywallet** [comment]
Thank you @p42rthicle for raising Issue #3617! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment]
Hi, this is intended there are cases where the user might want to enter a past subscription with delay

**Comment by p42rthicle** [comment]
Got it, thanks!
