### ISSUE TITLE
[BUG] Add Default Values For Ivy Features

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3630]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Some IvyFeatures ( sortCategoriesAscending, compactAccountsMode, compactCategoriesMode) are missing default values.
Provide Default values for them.

### To Reproduce

N/A

### Expected behavior

For mentioned ivy features provide false default values explicitly

### App version

2024.10.13(202)

**Comment by ivywallet** [comment]
Thank you @shamim-emon for raising Issue #3630! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3630 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
