### ISSUE TITLE
Add Support For Large  Number

### ISSUE THREAD

**Issue by shamim-emon** [Ivy-Apps/ivy-wallet#3633]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

In [FormatMoneyUseCase](https://github.com/Ivy-Apps/ivy-wallet/blob/main/shared/ui/core/src/main/java/com/ivy/ui/FormatMoneyUseCase.kt) add support for large number in a way so
we can present millions and billions as xM and xB. Ex : 1000000 = 1M.

### Because...

This class will be used centrally to format double to string across entire application and centralizing all money formatting logic in this class would be great.

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @shamim-emon, this issue is **not approved**, yet.
@ILIYANGERMANOV must approve it first.

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by shamim-emon** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @shamim-emon! 🎉
Issue #3633 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
