### ISSUE TITLE
[FEATURE] Add color to transfer label in transaction list

### ISSUE THREAD

**Issue by shinebrillant** [Ivy-Apps/ivy-wallet#3637]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

[Feature] Added color to accounts labels in transactions list Behind IvyFeatureToggle #3628
Accounts and categories have added colors, and transfers are also required.

### Why do you need it?

Easy to identify.

![556+456nsmail-1](https://github.com/user-attachments/assets/3a8ae4c8-e535-4cbc-8666-cc52d9a2162c)

**Comment by ivywallet** [comment]
Thank you @shinebrillant for raising Issue #3637! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by viratde** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @viratde! 🎉
Issue #3637 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by viratde** [comment]
Hey @ILIYANGERMANOV, then what is this feature request about?

**Comment by ILIYANGERMANOV** [comment]
@viratde it's about adding color to the transfers and it should be disabled by default. Most users prefer not having colored accounts. @shinebrillant can confirm if I understand it correctly

**Comment by viratde** [comment]
Hey @shinebrillant , if you could attach a video or image, that would be really helpful

**Comment by shinebrillant** [comment]
Enable advanced features to show account colors, transfers will not show colors.

**Comment by viratde** [comment]
Hey @ILIYANGERMANOV, I have added account specific colors in transfercard but ci is failing because of a constant that i have used. I am not able to figure out how to manage that constant effectively. if you could help me

**Comment by viratde** [comment]
Hey @ILIYANGERMANOV, Could you please review the pr attached?
