### ISSUE TITLE
[BUG] Some Spanish translations are missing at Setting screen

### ISSUE THREAD

**Issue by Mj-br** [Ivy-Apps/ivy-wallet#3654]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When we have the application in Spanish and go to the settings screen, some titles and descriptions are not translated correctly.

### To Reproduce

1. Go to "Settings"
2. Language
3. Set language to Spanish
4. Go to "Ajustes" (Settings in English)

### Expected behavior

All titles and descriptions should be in Spanish.

### Screenshots

<details><summary>Screenshots</summary>
<p>

![Bug screen 1](https://github.com/user-attachments/assets/f3976d2b-af07-462f-86cf-678c21a658f0)
![Bug screen 2](https://github.com/user-attachments/assets/819f7284-c60c-4c33-963f-67f14c212124)
![Bug screen 3](https://github.com/user-attachments/assets/b8eaecee-4b91-48f2-8986-c806c190c72a)
![Bug screen 4](https://github.com/user-attachments/assets/bdac932c-e0ed-4edc-8ed3-0d009ee028af)

</p>
</details> 

### App version

v2024.10.20 (204) from Google Play

### Smartphone

One Plus 11 5G, Android 14

### Additional context

Hi @ILIYANGERMANOV!

I've already developed the solution for this adding the missing labels at `es/strings.xml` and also I have the screenshots of the fixed version.

Could you please, if possible, assign me the task once it’s accepted? Thanks in advance.

**Comment by ivywallet** [comment]
Thank you @Mj-br for raising Issue #3654! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Mj-br** [comment]
I'm on it

**Comment by Mj-br** [comment]
Waiting for @ILIYANGERMANOV for review & approval

**Comment by Mj-br** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @Mj-br! 🎉
Issue #3654 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
