### ISSUE TITLE
[BUG] Wrong balance after new expense

### ISSUE THREAD

**Issue by gataahaythem** [Ivy-Apps/ivy-wallet#426]
**Describe the bug**
I added an expense, substracting 0.7 from 21, the result was 21.3

**To Reproduce**
1. Go to 'New expense'
2. Add the expense
3. Save the expense
4. Find a wrong final balance

**Expected behavior**
When my balance is 21, and I add an expense that costs .7, my new balance should be 20.3

**Screenshots**
Before
![Screenshot_20220112-093345_Ivy Wallet](https://user-images.githubusercontent.com/82048300/149097993-152e0016-3b29-435c-a707-e2905cb1fc6b.jpg)
After
![Screenshot_20220112-093336_Ivy Wallet](https://user-images.githubusercontent.com/82048300/149098022-f03e5443-4095-4f8d-be98-916f6a08654e.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S21
 - OS: Android 11

https://user-images.githubusercontent.com/82048300/149098273-e0d0c762-7868-4067-b13b-9988a0412aa6.mp4

**Comment by KikiManjaro** [comment]
Hi @gataahaythem,
Seems weird, how can you have 21.30 TND with 1,200.40 TND of income and 984.45 TND of expenses ?

You should normaly have your balance equals to your cashflow (215.95):
![Screenshot_1642026853](https://user-images.githubusercontent.com/59285425/149234073-e67c7ae4-bdfb-4559-a731-1c0197aa68b6.png)

And then adding 0.70 TND of expenses (215.25):
![Screenshot_1642026864](https://user-images.githubusercontent.com/59285425/149234161-bc42fd37-093d-43e6-b9a4-4dd137bfd8b0.png)

Seems to work fine for me, how did you get to have different TND from cashflow ?

**Comment by gataahaythem** [comment]
I have accounts that are exluded from the total balance.

**Comment by Aditya137x** [comment]
I tried reproduce the issue several times yet I am not seeing any issue in the latest release, so closing the issue.
