### ISSUE TITLE
Make transaction detail cards smaller in height

### ISSUE THREAD

**Issue by deep5050** [Ivy-Apps/ivy-wallet#428]
**What do you want to be added or improved?**
As a user I want the transaction details card on the main pag to be smaller in height. If possible use icon instead of icon+label on account used for the transaction.
**If possible make the UI more compact. Atleast these cards**

Otherwise a great UI i have migrated to this app recently. Waiting for other features. 

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [ ] No, it's a new issue.
- [x] I'm not sure but I've checked.
![Screenshot_20220112-183445_Ivy Wallet](https://user-images.githubusercontent.com/27947066/149145800-ee31b2b7-4ab7-4714-8144-84336ec8abba.png)

**Comment by ILIYANGERMANOV** [comment]
That's planned we'll fix it if we ever manage to deliver the new design
