### ISSUE TITLE
On Home Screen There Should Be Option To Show Income From Different Currency Accounts

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#434]
To explain it if i have added 2 income account for pkr currency , 2 for usd currecny and one from crypto, so there should be an option where instead of showing all the income total from all accounts , i should have an option to show incomes of different categories at home screen like:
A box for INCOME IN PKR 
A BOX FOR INCOME IN USD
A BOX FOR INCOME IN CRYPTO

Vice versa foe the expenses

**Comment by Aditya137x** [comment]
You can do this in reports section.
