### ISSUE TITLE
Bluecoins import - wrong account balance

### ISSUE THREAD

**Issue by singhgautam7** [Ivy-Apps/ivy-wallet#441]
I imported data from my bluecoins, i keep doing it once in a while. So i found that the import calculation is way off the charts. I am attaching the screenshots for the reference.

Ivy wallet account balance (incorrect)
![Screenshot_20220119-223605](https://user-images.githubusercontent.com/31505446/150179690-4fe9cfb9-d51d-4a3d-96fc-cef4423e1d8a.jpg)

Bluecoins account wallet (correct)
![Screenshot_20220119-223616](https://user-images.githubusercontent.com/31505446/150179703-96f5c45c-2081-4cbc-bbe6-b0d12a135601.jpg)

Also attaching the bluecoins csv for the same.
[transactions_list_table.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/7899160/transactions_list_table.csv)

**Comment by ILIYANGERMANOV** [comment]
Use Manual CSV import
