### ISSUE TITLE
[FEATURES] Add Transaction Shortcut On App Icon

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#462]
Android shortcut directly into add Expense/Income/Transfer transaction screen

**Comment by jevo160296** [comment]
I'm working on it

**Comment by ILIYANGERMANOV** [comment]
Brilliant! Much appreciated 👍

**Comment by rubenquadros** [comment]
I think this can be closed?

**Comment by ILIYANGERMANOV** [comment]
It must be re-implemented in `dev`
