### ISSUE TITLE
[INSIGHTS] Graphs & Charts 📊📉

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#47]
Display beautiful **Bar Charts & Line Charts** for:
- available balance
- expenses
- income

**by:**

- accounts
- categories

**for:**

- 12 months
- 6 months
- or any selected user time period

**Comment by SnjezanTwin** [comment]
Hi,

I know that you have been working on improvements 
on Ivy wallet alot. I did some research and found an app that already have different charts. I'm sending you pictures of charts, just as an idea how could it look in Ive wallet. 

Keep doing the great job 👍

**Comment by ILIYANGERMANOV** [comment]
Hi @SnjezanTwin, thank you for your screenshots! It's helpful :) We have something in mind, it's just a matter of time to implement. We do our best.

**Comment by SnjezanTwin** [comment]
Hi, 
Is there going to be any updates?

**Comment by StarHamster** [comment]
@SnjezanTwin, we got closer to the goal. Thanks to #660

**Comment by SnjezanTwin** [comment]
Great job, great team 👍

**Comment by Ansem93** [comment]
Any hope for this update? I wanted to move to a new wallet app and was in doubt between ivy and the other app with vertical graph

**Comment by ILIYANGERMANOV** [comment]
> Any hope for this update? I wanted to move to a new wallet app and was in doubt between ivy and the other app with vertical graph

No promises, we have not enough contributors atm and I have other priorities :/
