### ISSUE TITLE
CSV export broken on locales using comma as decimal separator

### ISSUE THREAD

**Issue by Soukyuu** [Ivy-Apps/ivy-wallet#520]
So I've just ran into this bug on my new device which I don't want to root, hence no way to transfer all the data from an offline account:

Exporting the CSV in i.e. German locale will mess up all the figures. 118,59€ turns into 11859,00€ etc.
As a workaround, you can change the phone language to English, restart the app and run the export.

Importing does not seem to be affected by locale, so importing a CSV exported in English locale on a device in German locale imports the figures correctly.

**Comment by ILIYANGERMANOV** [comment]
Thsnks for reporting!

**Comment by ILIYANGERMANOV** [comment]
Must be fixed in `prod` branch

**Comment by Tiihi** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Nice!! Make sure to send PR to `prod` and base your PR on `prod`
