### ISSUE TITLE
[BUG] Crashing while viewing a spend

### ISSUE THREAD

**Issue by ravikaant** [Ivy-Apps/ivy-wallet#552]
**Describe the bug**
App crashed on when I tried to view a spend whose description has only markdown text.

**To Reproduce**
1. Create a spend
2. In the spend, put the description as only markdown. Like below (remove the quotes)
"--------------
|A|B|C|D|E|
|-|-|-|-|-|
|1|F|G|H|I|
|2|J|K|L|M|
|3|N|O|P|Q|
|4|R|S|T|U|
|5|V|W|X|Y|
|6|Z|1|2|3|"

3. Save the spend.
4. Go back and try to view the same spend again.
5. App crashed
6. Can't even delete the spend 

**Expected behavior**
Should've opened the spend correctly

**Screenshots**
![1](https://user-images.githubusercontent.com/32794377/155359272-31a2ca0c-2402-4d36-975d-3ce7b23944f3.jpeg)
Clicking in the 1st spend on 22nd Feb will crash the app, but clicking on the second spend behaves normal because it contains markdown as well as normal text
![2](https://user-images.githubusercontent.com/32794377/155359061-2367398c-4f9f-43d6-8576-9cd657237653.jpeg)
![3](https://user-images.githubusercontent.com/32794377/155359304-86b38ae9-2721-48a5-af62-bf8b78c02718.jpeg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 11

**Additional context**

**Comment by Vishwa-Raghavendra** [comment]
I am not even able to save the transaction, it crashes as soon as i press save 😅

Android 10
Device Redmi note 7 pro

**Comment by david-oh-git** [comment]
This issue is from compose-mardown library.

**Comment by Aditya137x** [comment]
I tried reproducing the issue multiple times in the latest release. Looks like the issue is resolved.
