### ISSUE TITLE
Add A Little Donate Option In Settings, Under 'Other'

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#556]

**Comment by Aditya137x** [comment]
Added

**Comment by devops-scrutiny** [comment]
Can you please describe where the donate option is implemented?
I could not find it in my version 4.5.

**Comment by ILIYANGERMANOV** [comment]
> Can you please describe where the donate option is implemented? I could not find it in my version 4.5.

It was recently removed because we no longer want to have it
