### ISSUE TITLE
Pick a random color automatically

### ISSUE THREAD

**Issue by edsnchz** [Ivy-Apps/ivy-wallet#576]
**What do you want to be added or improved?**
As a user I want to ... have the option to pick a random color automatically, when I create categories, accounts, etc. Preferably an unused color

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- Just a "Random" or "Pick for me" option when the color picker show off
- If possible the chosen color should be one that is not in use

**Comment by TharunBalaji2004** [comment]
This one sounds pretty good feature. I'm interested to work on it, can you able to assign it for me

**Comment by ILIYANGERMANOV** [comment]
Awesome. Assigned. Can you try to implement also this part:

> If possible the chosen color should be one that is not in use

We can start with the random part. Also make sure to read our CONTRIBUTING.md and Architecture guidelines. Thank you for your interest 🎉

**Comment by TharunBalaji2004** [comment]
> If possible the chosen color should be one that is not in use

Yeah sure I will come up with the logic part for that
