### ISSUE TITLE
Numbers on transaction panel are not centered

### ISSUE THREAD

**Issue by edsnchz** [Ivy-Apps/ivy-wallet#579]
**What do you want to be added or improved?**
As a user I want to ... fix the numbers in the transaction panel. They are slightly shifted up

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- My OCD is killing me

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**

![Captura de pantalla 2022-03-06 185559](https://user-images.githubusercontent.com/52385674/156948060-770e90d7-47a8-45da-be98-24327a2e2417.jpg)

**Comment by Sagar19RaoRane** [comment]
can i take this issue?

**Comment by ILIYANGERMANOV** [comment]
Assigned to you
