### ISSUE TITLE
Add some UI themes (solid colors only)

### ISSUE THREAD

**Issue by edsnchz** [Ivy-Apps/ivy-wallet#580]
**What do you want to be added or improved?**
As a user I want to ... have the ability to change the theme of the interface.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [x] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- Personally I think that solid colors are the best option instead of gradients
- Some people will prefer gradients, so better to have more than one option

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- For my part I would like only solid colors, not gradients
- I also think it is necessary to unify some elements. For example, everything related to expenses must always be red, and everything related to income must always be green.
- The current look is not bad, the application is beautiful, but having varieties of themes could improve

Here is a photoshopped example:
![Screenshot_2022-03-06-19-17-44-239_com ivy wallet](https://user-images.githubusercontent.com/52385674/156950938-de16bb69-60b0-41cf-842a-9fd29bd9911e.jpg)

**Comment by ILIYANGERMANOV** [comment]
Out of scope
