### ISSUE TITLE
Bank To Cash Transfer

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#589]
Withdrawing money from bank and adding it to Cash, please add a feature for this transfer bank to cash

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by Aditya137x** [comment]
You can create a account named Cash and transfer the amount from the account named Bank to account named Cash whenever you withdraw amount from Bank.
