### ISSUE TITLE
Attach Receipts/Files to transactions

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#6]
As a user I want to be able to attach one or multiple files to a transaction.
- IMAGE
- PDF
- DOC
- SHEET

Max file size 10mb.

DEPENDS ON:
- Google Drive integration (#34)

**Comment by ILIYANGERMANOV** [comment]
Local save (mandatory) + GDrive (optional)


If your GDrive isn't connected, nothing will be saved there

**Comment by mhm13dev** [comment]
Hi @ILIYANGERMANOV 
What's the update on  this?
