### ISSUE TITLE
[BUG] OnboardingSplashLogin doesn't scroll

### ISSUE THREAD

**Issue by timmyCoder** [Ivy-Apps/ivy-wallet#63]
**Describe the bug**
The OnboardingSplashLogin Screen doesn't scroll on my device, I can not access the offline access button
**To Reproduce**
1. Launch the app on a larger device

**Expected behavior**
The OnboardingSplashLogin screen should be scrollable

**Screenshots**

![home](https://user-images.githubusercontent.com/36578083/140814378-e83c96f3-89cf-4157-bde6-117a358dc07d.jpeg)
**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A21s
 - OS: Android 11

**Additional context**
A fix and better scaling across device should be considered

**Comment by ILIYANGERMANOV** [comment]
Thanks for reporting! Have you turned on screen zoom or large text from Settings?

Anyway the screen should be scrollable.

**Comment by timmyCoder** [comment]
on it

**Comment by rubenquadros** [comment]
Not sure if this issue is still valid? The code has been commented out.

**Comment by ILIYANGERMANOV** [comment]
Obsolete
