### ISSUE TITLE
[BUG] Backspace Removes Entire Balance if 3+ Decimal Places Used

### ISSUE THREAD

**Issue by GovindKrishnan** [Ivy-Apps/ivy-wallet#636]
**Describe the bug**

If the wallet balance amount entered has **more than 3 decimal places**, backspace button clears the entire amount. For example, if I enter 0.4567 BTC & click backspace button to erase "7", it removes the whole amount.

**To Reproduce**
1. Go to Wallets & Add One
2. Select BTC
3. Enter Balance as 1.9876
4. Press Backspace
5. See error

**Expected behavior**
Expects to erase only last digit as Crypto can normally have more than 3 decimal places.

**Screenshots**
https://user-images.githubusercontent.com/74248475/159622563-406fc275-e394-423d-90c7-d2188c9473c5.mp4

**Smartphone (please complete the following information):**
 - Device: Realme 7
 - OS: Android 11

**Additional context**

High priced cryptos like BTC would always have more than 3 decimal places.

**Comment by MohitMandalia** [comment]
Check for the issue and yes when you enter more than 3 decimal values and press it make amount as 0.
