### ISSUE TITLE
Transfert Money

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#655]
Why when a transfer money from account 1 to account 2, it does not appear in 'income this month' ?

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by Aditya137x** [comment]
Ability to mark transfer as Income added
