### ISSUE TITLE
Add more ways of adding transactions like telling google assistant to record a payment

### ISSUE THREAD

**Issue by SscSPs** [Ivy-Apps/ivy-wallet#666]
**Allow Google Assistant to add transactions**
As a user I want to be able to make the transactions adding a bit easier, I wanna keep things more spontaneous, I want to be able to just tell google assistant to "record a transaction of 500 from cash towards clothes" or even smaller, like "Record a 500 cash payment"

In a case where all info required to record a transaction is not present, we can keep it in a draft state, with txn time and other available info filled in, and later can be completed by user properly.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- draft transactions
- google assistant/other assistant support
- possibly support for plugins which can read transactions from different sources and save them

**Comment by SscSPs** [comment]
I'll see if I can add a draft transaction support first over the weekend, but before I start on it, I wanted to know if you would be willing to add this to the app?
I want to ask your view on this whole thing, Draft transactions, and add support for 3rd party apps to create transactions.

**Comment by ILIYANGERMANOV** [comment]
Hi @SscSPs that feature would be cool! I like the idea :)

**Comment by SscSPs** [comment]
Great, I'll see what I can make and would love to discuss this in more detail.
I haven't gone through the code yet, will do it tomorrow and see what is present and what I should add.

**Comment by ILIYANGERMANOV** [comment]
Awesome! I'm here to support you and great idea, btw! We can also parse Revolut notifications if possible.

**Comment by SscSPs** [comment]
I haven't used Revolut, I suppose it's not available where I live.
I was thinking we can have such apps and other format parsing as plugins, so we(or the community) can easily add support for newer options.
So, I think exposing such API would be the first step.

But, lets me not get ahead of myself, I'll see the sourcecode before I commit to anything 😅

**Comment by ILIYANGERMANOV** [comment]
Currently, out of scope
