### ISSUE TITLE
Removal of Maldivian Rupee (MVP) Currency

### ISSUE THREAD

**Issue by mohamed-azhar** [Ivy-Apps/ivy-wallet#670]
**What do you want to be added or improved?**
From the currency select list during the initial application setup, I can see 2 currencies for the Maldives which are:
- Maldivian Rupee (MVP)
- Maldivian Rufiyaa (MVR)

The official currency for the Maldives is Maldivian Rufiyaa (MVR) not Maldivian Rupee (MVP) which also doesn't exist. 
So would like to suggest removing the MVP currency as it is useless.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Comment by rakib10rr3** [comment]
I don't see MVP in the currency list. There is only Maldivian Rufiyaa (MVR)

**Comment by mohamed-azhar** [comment]
> I don't see MVP in the currency list. There is only Maldivian Rufiyaa (MVR)

I just did a fresh installation from Google Play Store and was able to see it.

version: 3.0.1-universe 

![Screenshot_20220407-153437_Ivy Wallet.jpg](https://user-images.githubusercontent.com/17266828/162180458-834792e3-22de-4b1d-8a99-7bb2a3984aaf.jpg)

**Comment by ILIYANGERMANOV** [comment]
We use a currency API - not under our control
