### ISSUE TITLE
Wrong calculations

### ISSUE THREAD

**Issue by Pkcarreno** [Ivy-Apps/ivy-wallet#685]
**Describe the bug**
I realized while doing "balance adjustment" the final calculation was wrong (I attach evidence)

The amounts are always calculated in the same way since it always returns the same results under the same input data.

I usually do this type of operations and the first time I notice this error, maybe it's since version 3.0.1

**To Reproduce**
1. Make transfer between accounts of different currencies (I don't know if this influences but that's how it worked for me)
2. After I have a *.91$ balance left, I proceed to go to the usd wallet and press the wallet amount, then I round the amount to the nearest higher
3. So it puts me an amount of 5$ difference instead of 0.09 which should be the difference

**Expected behavior**
The calculations are always given in the same way no matter how many times you repeat the process, I assume that the operation does not throw random numbers

**Screenshots**

https://user-images.githubusercontent.com/34664891/161896332-ae7643f2-7be4-499c-8d78-207971c477d5.mp4

note: xiaomi has a weird way of dealing with dark mode in apps, ignore that.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 9S
 - OS: Android 11

**Additional context**
I use the function of transferring between accounts of different currencies a lot, with version 3.1 there is another bug that I am going to report that does not let me edit the value of the exchange rate, I see that it has 4 digits after the comma, I think so keep a larger number of digits can alter the final result, this is only an assumption

**Comment by Pkcarreno** [comment]
I still have this problem in 4.1.1

In recent tests I discovered that this is not a calculation error in general, it only happens when an expense or income is made and the sum of that amount plus the existing one in the wallet generates a new round number (***.00), then the calculation goes wrong.

For example: I have 465.89$ and I make a deposit of 0.11$, that sum should give me 466.00$, however, it shows me 465.00$

**Comment by Pkcarreno** [comment]
I have not presented this error again so I will close this issue

**Comment by jdleval** [comment]
Yeah, it seems to happen whenever I adjust the balance manually by selecting the balance amount and editing it. It throws it off a dollar somehow

**Comment by Pkcarreno** [comment]
hi @jdleval!
I haven't had this error in a while so I closed the thread, I'll reopen it in case it helps

**Comment by ILIYANGERMANOV** [comment]
Thank you @Pkcarreno! It's an issue with "Double" rounding - reassure you that balance is correct, just displayed incorrectly. We'll fix thar after the BIG performance rework - the truth is that our app is very laggy and inefficient in its current state :)

**Comment by jdleval** [comment]
Thank you so much, I'm an aspiring programmer, maybe one of these days I can contribute

Jeremy Leval
Assistant Manager
Pizza Parma
Pittsburgh, Pa
Cell: 412-897-4330
________________________________

**Comment by Pkcarreno** [comment]
Thanks @ILIYANGERMANOV for all the hard work, I'm learning kotlin in my free time so I can help more soon 💪

**Comment by ILIYANGERMANOV** [comment]
Fixed by https://github.com/Ivy-Apps/ivy-wallet/pull/2715
