### ISSUE TITLE
In light mode is hard to read the numbers on the budget squares, it should be in a darker color.

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#695]

**Comment by Aditya137x** [comment]
When the Budget bar is slightly filled the color of the changes from dark to light and its hard to read.

![image](https://user-images.githubusercontent.com/111834313/186399500-37d4dc52-f176-411a-8587-05eec6a804c0.png)

![image](https://user-images.githubusercontent.com/111834313/186399564-bbd3eaea-7b93-4929-9400-6210e0580811.png)
