### ISSUE TITLE
Subcategories (category groups/folders)

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#7]
As an user I want to be able to:
- group categories in folders
- see grouped categories as one part in PieChart
- go level deeper wheb clicking category folder in PieChart

**IMPORTANT:** Only one category (not folder) can be assigned to a transaction.

**Comment by 8227846265** [comment]
In regard to the implementation of categories and sub-categories. Wallet by BudgetBaker has the best UI/UX currently, Ivy Wallet can use this as a reference.

- https://play.google.com/store/apps/details?id=com.droid4you.application.wallet&hl=en&gl=US

Hopefully the planned sub-categories on Ivy resembles or has a better UI/UX than Wallet.

It would be nice to drill down expenses under categories such as `Food & Drinks` into
- Breakfast
- Lunch
- Dinner
- Snacks

To see food expenses by situation.

**Comment by ILIYANGERMANOV** [comment]
Implemented in the new Ivy Wallet.

**Comment by devops-scrutiny** [comment]
I've migrated from Money Manager to Ivy Wallet.
Can you please let me know where is the subcategories feature implemented in the app?

_Version: 4.5.0_

https://github.com/Ivy-Apps/ivy-wallet/assets/143527216/10afc915-13d1-42b5-8dd5-527d4b949429

**Comment by ILIYANGERMANOV** [comment]
> I've migrated from Money Manager to Ivy Wallet. Can you please let me know where is the subcategories feature implemented in the app?
> 
> _Version: 4.5.0_
> 
>  Screen_Recording_20230930_114906_Ivy.Wallet.mp4

Hey unfortunately, Ivy Wallet doesn't have Subcategories

**Comment by devops-scrutiny** [comment]
> > I've migrated from Money Manager to Ivy Wallet. Can you please let me know where is the subcategories feature implemented in the app?
> > _Version: 4.5.0_
> > Screen_Recording_20230930_114906_Ivy.Wallet.mp4
> 
> Hey unfortunately, Ivy Wallet doesn't have Subcategories

Is it planned to be implemented?

**Comment by ILIYANGERMANOV** [comment]
It's planned but I have no idea when this will happen 😀 Reopened it
