### ISSUE TITLE
Cannot edit exchange rate

### ISSUE THREAD

**Issue by Vivekpj** [Ivy-Apps/ivy-wallet#711]
While transferring money from AED to INR the exchange rate edit feild is not working, please fix.

**Comment by tasken** [comment]
Please fix. Calculation button is also not working. It would be great to be able to specify both currencies and the app to calculate exchange rate.

**Comment by ILIYANGERMANOV** [comment]
@Vishwa-Raghavendra can you have a look at that? I can confirm that when trying to make a transfer between BGN and ADA, I can't enter exchange rate.

**Comment by tasken** [comment]
Same happens between ARS to USD

**Comment by ILIYANGERMANOV** [comment]
I noticed that this bug is already fixed, we just didn't released a new app's version. Expect a new release soon!

**Comment by Vishwa-Raghavendra** [comment]
Hi @ILIYANGERMANOV it has been fixed  as you have mentioned it, 
if it is still recurring do let me i will take a look as i am  able to edit it 

What @tasken mentioned can also be added to improve the UX

**Comment by tasken** [comment]
Please count me in for other UX improvements

**Comment by ILIYANGERMANOV** [comment]
Stale
