### ISSUE TITLE
Implement Notification System

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#76]
**What do you want to be added or improved?**
Implement Notification System which support adding different notifications, displayed in different conditions similar to the CustomerJourneyLogic.kt

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
No

**Explain with bullets why do you need it**
- Notify users of upcoming planned payments
- Notify users for overdue planned payments
- Notify users for exceeding a budget
- Implement a contextual notification customer journey to make the app more useful

**Comment by ILIYANGERMANOV** [comment]
Not a priority

**Comment by technificentConsulting** [comment]
I see this is no longer on the todo list but do notifications work at all?  I'm looking at the source and looks like it's a deprecated  feature but a setting still exists.  I'm trying to figure out where to call testNow to verify if the deprecated function call works and just needs to be reintegrated or if it doesn't work at all.
