### ISSUE TITLE
Custom Font/System font.

### ISSUE THREAD

**Issue by parzival-cmd** [Ivy-Apps/ivy-wallet#760]
**What do you want to be added or improved?**
As a user I want to see the app in my native font or also you can add some open source pre installed fonts in the app itself or even both options.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [×] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
