### ISSUE TITLE
[TRANSLATION] Russian

### ISSUE THREAD

**Issue by silentiumNoxe** [Ivy-Apps/ivy-wallet#802]
**What do you want to be added or improved?**
Add Rus localization.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- By starting using the app all categories in English
- User experience

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
- I can suggest for you use Weblate for kv translating

**Comment by llama-0** [comment]
I'm on it
