### ISSUE TITLE
Ivy Wallet iOS app

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#81]
**What do you want to be added or improved?**
Start implementing the Ivy Wallet app for iOS from scratch.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
No

**Explain with bullets why do you need it**
- Ivy Wallet is available only for Android
- Many people have asked for an iOS vesrion
- With iOS we can implement Sharing between Couples/Families
- Contributors who're interested in iOS will be able to implement interesting stuff

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
As a project owner I want to:
- To create a iOS copy of the current Ivy Wallet android vesrion
- Initiate iOS project in this repository

**Technical Spec**
- Swift
- SwiftUI
- Clean code
- Ivy Design System
- Mirrors the Android app behavior

# Call to Discussion
- Comments
- Ideas
- Thoughts

### Question: What are your thoughts on Kotlin multiplatform?

**Comment by Harizaki** [comment]
I would love an iOS version as well. I will actually soon have to switch to an iPhone and I really hope Ivy Wallet gets an iOS version cuz its simply the best budget/expense tracker that meets my requirements so far.

**Comment by paulnunezm** [comment]
What do you think about starting this with KMM?

**Comment by muzafakar** [comment]
agree on KMM!. First step should be extracting logics from current app to KMM modules.

**Comment by myounus96** [comment]
Any update on this? @ILIYANGERMANOV

**Comment by patrickteng** [comment]
Switching to an iPhone soon as well, hopefully this gets implemented!

**Comment by ILIYANGERMANOV** [comment]
Out of scope
