### ISSUE TITLE
[FEATURE] Month to date, year to date button

### ISSUE THREAD

**Issue by Jai-mTm** [Ivy-Apps/ivy-wallet#840]
### Please confirm the following

- [x] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

In the date picker,choose month could you add:
Month to date (MTD) and year to date (YTD) buttons?
(Rather than manually setting date)

### Why do you need it?

- efficiency

### How do you imagine it?

As a button

**Comment by ILIYANGERMANOV** [comment]
Need more info

**Comment by ILIYANGERMANOV** [comment]
> Month to date (MTD) is the period starting from the beginning of the current month up until the present date.
> 
> Year to Date (YTD) is used in reference to determining the period of time from a start date to the current date of current calendar year.
> 
> But I think this may be a rarely used feature.

Thank you for clarifying @TharunBalaji2004 ! Tbh, I might use the YTD option. If this feature is hidden behind a setting in `Features` is Settings - it makes sense. Show those 2 buttons only if enabled. However, we might need to re-work the UI so it's scalable.
