### ISSUE TITLE
(BUG) Adding new recurring transactions

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#845]
When adding new recurring transactions with a description. The descriptions aren't being saved, i had to edit the recurring payments & add the description again for it to be saved

**Comment by husseinaltaaf** [comment]
Actually it doesn't autofill on Edit but actually saves whatever i input.
So if i added a recurring payment with a certain description and saves it. It is saved. But next time i click on the recurring payment to edit it, the description disappear
