### ISSUE TITLE
[BUG] Wrong today's date on the transaction list

### ISSUE THREAD

**Issue by muzafakar** [Ivy-Apps/ivy-wallet#846]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

Transaction created for today's date is identified as tomorrow's transaction in the home screen

### To Reproduce

1. Create new transaction without choosing date through date picker (as it will chose today's date by default) then save the transaction
2. Observe the list of transaction in the home screen, you'll find that transaction is marked as yesterday's transaction and wrong today's date

### Expected behavior

created transaction should be marked as today's transaction with correct today's date

### Screenshots

![image](https://user-images.githubusercontent.com/27369892/166675512-53d2beb8-2061-4613-8e39-f6cdead2fd39.png)
![image](https://user-images.githubusercontent.com/27369892/166675541-b55a53a5-0ed4-4372-8601-c8a57df5d2fd.png)

### Smartphone

Samsung Galaxy A50s (Android 11)

### Additional context

I created the transaction around 7AM on May 4 in GMT+8 timezone

**Comment by ilya-rb** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Done
