### ISSUE TITLE
[TRANSLATION] Introduce plurals for better UX

### ISSUE THREAD

**Issue by llama-0** [Ivy-Apps/ivy-wallet#855]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

Add plurals.

### Why do you need it?

- Different languages have different rules for grammatical agreement with quantity. So in order to translate app to different languages we need to add support for this quantity strings.
Example:
En - 1 day, 4 days, 5 days
Ru - 1 день, 4 дня, 5 дней
- With this feature we'll achieve better UX

### How do you imagine it?

Here is a [sample project](https://github.com/llama-0/StarCounter) for En-Ru to highlight what plurals are and how to work with them. Anyone can use it as a reference.
Here are [official docs](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals)
I'll attach a list of candidates for plurals from the Ivy Wallet project later, based on Russian translation. Feel free to check it for other languages and add your suggestions.

**Comment by Pkcarreno** [comment]
the project currently contains plural words

for example:
> https://github.com/ILIYANGERMANOV/ivy-wallet/blob/00f595181648f782ec88c9d7f6e18f8145d21fcd/app/src/main/res/values/strings.xml#L419
> https://github.com/ILIYANGERMANOV/ivy-wallet/blob/00f595181648f782ec88c9d7f6e18f8145d21fcd/app/src/main/res/values/strings.xml#L418

and others more.

but I don't understand if you mean the implementation of these, which I'm not very aware of.

**Comment by llama-0** [comment]
Hi, @Pkcarreno! It's not about words itself, it's about different representation of such words in different languages. For some languages there are more than 2 words for single and multiple.
Look at the example below
[.../values/strings.xml](https://github.com/llama-0/StarCounter/blob/master/app/src/main/res/values/strings.xml)
[.../values-ru/strings.xml](https://github.com/llama-0/StarCounter/blob/master/app/src/main/res/values-ru/strings.xml)
So, for example, for a word "day" ("день") it would be:

- English
   * 1 day
   * many (2, 5, 10, 100000, etc) days
- Russian
   * 1 день
   * 2..4 дня
   * 5 дней
   * 51 день (notice, the end of the number is 1, so the representation is recurring)
   * 52 дня (same here for 2..4)
   * 105 дней (same here for 5+)
   etc.

If you follow the link to official documentation, the issue should be clear. If not, please leave a comment, and we'll discuss it in more details, and I'll dig up some linguistic terminology.

**Comment by ILIYANGERMANOV** [comment]
Stale
