### ISSUE TITLE
[FEATURE] Configure if "left to spend" should take into account the budget and upcoming expenses 

### ISSUE THREAD

**Issue by jevo160296** [Ivy-Apps/ivy-wallet#858]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

Add an option in the configuration to change the calculation of "left to spend", currently is being calculated by
- "current balance" - "savings goal" 

But it would be nice if it can be calculated as 
- "Current balance" - "savings" - "budget" - "upcoming".

### Why do you need it?

- I can keep track of the money I can expend without compromising the planned payments, budget and savings goal.

### How do you imagine it?

In the part where I can edit the "savings goal" there is a configuration button, when I tap it, there is a list off switches I can turn on or off depending on what amount to take into account:
- Budget
- Upcoming

**Comment by ILIYANGERMANOV** [comment]
Nice! Thank you @jevo160296! That'll help us design our Savings Goals feature

**Comment by ILIYANGERMANOV** [comment]
Out of scope
