### ISSUE TITLE
Bug -when Export , A Lot Of Bugs In Csv, I See ##### Inplace Of Date

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#873]

**Comment by StarHamster** [comment]
Excel shows ##### when the date does not fit into the cell. In fact, the date is still there. So, it seems to me that this is not a bug.

**Comment by jdwarraich** [comment]
I think tha we should seperate coloumns for date and time during export. And can we add option to export as pdf ?
