### ISSUE TITLE
Icons weirdly scaled

### ISSUE THREAD

**Issue by xoudoesthings** [Ivy-Apps/ivy-wallet#880]
The new icons for categories have a weird scaling issue. They appear larger than the original Ivy ones.
![Screenshot_20220509-165008_Ivy Wallet.png](https://user-images.githubusercontent.com/97404131/167436456-9e1fd8e0-21dc-4fb8-a83f-b1a0187d6691.png)
![Screenshot_20220509-165020_Ivy Wallet.png](https://user-images.githubusercontent.com/97404131/167436464-7434fdf0-3425-4536-b7dc-935c5628df42.png)

**Comment by ILIYANGERMANOV** [comment]
Thanks for reporting! We'll fix that 👌

**Comment by code-a1** [comment]
Fixed
