### ISSUE TITLE
[WIDGET] Accounts Widget

### ISSUE THREAD

**Issue by Cosmiika** [Ivy-Apps/ivy-wallet#882]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to be able to use a widget where I can quickly see a list of my accounts and their balances. [+ possibly the same three buttons from the pre-existing one]

### Why do you need it?

-  This would make my effiency alot more easier, considering i can quickly check my balance before making a purchase for example.

### How do you imagine it?

A scrollable list similar to the accounts page in the app, and the three buttons at the side (optional)

**Comment by baruma** [comment]
I'm on it

**Comment by baruma** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Someone can work on that using Glance
