### ISSUE TITLE
Get data from notification

### ISSUE THREAD

**Issue by xoudoesthings** [Ivy-Apps/ivy-wallet#889]
### Please confirm the following

- [x] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

I have an idea for an advanced feature. My banking app gives me notifications for transactions, and from that i can get basic data like price and name.

### Why do you need it?

- would make logging more automated and easier
- remove the possibility of miscalculations and forgetting to log something

### How do you imagine it?

I think the way it would work is by having an editor, where we can edit the structure of the notification

for example, the bank gives this notification:
"You've paid 5430HUF to Shop"

we could input it like:
"You've paid \<price> to \<name>"

The words would be ignored, and this way we can filter only the stuff we need. \<price> would obviously be the price and \<name> the name.

there would also need to be options for multiple messages. ivy would recognize which one it is by the words we add.
so, for example i have a notification for expenses, that looks something like this:
"You've paid 1345HUF to PayPal inc."
but i also have one for income, that looks something like this:
"🎉 You got 5000HUF from Microsoft refund"

we could add multiple options, and by the words we add (so not \<income> and \<name>) ivy would recognize and automatically add it.

edit: for each account, we could add one or more app to check the notifications of. so if someone has paypal and their bank as separate accounts, then they could separate them, but if someone has one account for all, then they can input multiple app's notifications into it (altough it might be weird for example with paypal, so maybe limiting to one app per account would be better)

edit 2: instead of 1000HUF being \<price> we could also do \<price>\<currency>

**Comment by StarHamster** [comment]
Hello, @xoudoesthings. It's very similar to #351, isn't it?

**Comment by xoudoesthings** [comment]
> Hello, @xoudoesthings. It's very similar to #351, isn't it?

i guess you're right, i didnt find it because i searched "message" and "notification" 
altough i think i went into more detail than that one
