### ISSUE TITLE
Monedas 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#906]
Diferentes tipos de monedas en la misma billetera, por ejemplo, tengo una billetera de Cryptos pero diferentes monedas en la misma pero aquí solo puedo agregar una moneda por pilletera quisiera agregar almenos 5 tipos de Crypto monedas por billetera

**Comment by Pkcarreno** [comment]
He talks about an account model where under the same account you can have different currencies, he raises it from the perspective of cryptocurrencies, it occurs to me that perhaps he is talking about a Binance-type or wallet-type structure that in your account you can have several different currencies.

I think it is the same as creating different accounts each with a currency, in this way confusion would be avoided

**Comment by ILIYANGERMANOV** [comment]
Thanks for the info @Pkcarreno!
