### ISSUE TITLE
[FEATURES] Improve the feature request form in the app

### ISSUE THREAD

**Issue by Pkcarreno** [Ivy-Apps/ivy-wallet#911]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

I think that the feature request form could be improved and requests made directly from the app would be better classified

### Why do you need it?

- I see that requests for features coming from the app are often repeated and take a little longer to be classified to their original thread (if they exist).
- I think that with a couple more inputs it can be profiled much better and thus reduce the redundancy of the issues faster
- Helps people who contribute to the project go directly to the issues they know they can contribute

### How do you imagine it?

In addition to the description and title that currently exists in the app, I think that classifiers could be added, such as:

- **Language of the request**: with which the contributor who knows the selected language will be able to attend and make a translation of the intentions of the request
- **Type of request**: If it is to report a bug or request a feature
- **Request category**: for example: Translations, csv import/export, finance functions, etc.

without complicating the structure of the form too much, I think that with some select type inputs this could be handled perfectly.

And of course, these classifications must be clear in the list of issues so that contributors can read them.

**Comment by Pkcarreno** [comment]
What if instead of redirecting the comments made in the app to GitHub, these are redirected to a dedicated channel in ivy's telegram group? 

This avoids comments that lack context in GitHub and end up in oblivion, but still persist in a log.

Also you could pin non-repeated comments that report a feature or a bug and have control and divide between useful comments and repeated comments.

In addition, a bot could be used to search for specific words and assign a tag like "duplicate" or "new".

This occurs to me because I just discovered ivy's group in telegram, and I think it's great.

**Comment by ILIYANGERMANOV** [comment]
The feature request form was discontinued and moved to GitHub
