### ISSUE TITLE
[FEATURES] AN OPTION FOR REFUNDS/MONEY BACK

### ISSUE THREAD

**Issue by seyus** [Ivy-Apps/ivy-wallet#916]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to get an option for refunds so that if I'm getting some money back/refunded it does not add in overall income but gets subtracted from expenses.

### Why do you need it?

- Avoid duplicate addition of income
- Calculate correct income and expenses

### How do you imagine it?

There can be option for Refunds where we could select any previous expense and add money in that expense using refund, and a new entry for this should be created for the selected date.

**Comment by ILIYANGERMANOV** [comment]
Hi @seyus simply delete the expense transaction that was refunded - that's the semantically correct way.

**Comment by seyus** [comment]
Hi @ILIYANGERMANOV This suggestion might work if the refund is equal to the expense created and not (let's say) less. And also if I just simply delete the expense then my record of that payment would be gone. **I'd want to have both expense and refund dates.** (Any workaround would work apart from just deleting the transaction, maybe an additional update expense option to update it on another date with new amount)

Btw just to let you know, really love the UI/UX part of the app. And I've just fallen in love with this design. Hope you keep on improving it with new features as well.
