### ISSUE TITLE
[FEATURES] Tasker Integration

### ISSUE THREAD

**Issue by imjuzcy** [Ivy-Apps/ivy-wallet#919]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to use Tasker to automate adding transactions when bank apps send notifications about new transactions.

### Why do you need it?

- I'm aware that there is another feature request regarding bank apps notifications/SMS, but I think it's always the same thing to do when bank apps send transaction notifications (assuming that Ivy Wallet's implementation will be similar to other expense tracker app): Bank apps notifications -> Ivy Wallet notifications -> User tap on notification to confirm transactions -> Add transaction
- Hence, I think it should be easily automated. 

### How do you imagine it?

Ivy Wallet doesn't have to do the parsing and automation because I think it's too complicated and unnecessary to be included in a expense tracker app (and also there are too many different bank apps that send notifications with different contents, won't be possible to support every app). Dev can just add an intent that can be called by Tasker to add transactions. Or even better, Tasker plugin.

Users can create their own filters to parse the banking apps' notifications with Tasker, and pass relevant information to Ivy Wallet to automatically add transactions. 

[Here](https://tasker.joaoapps.com/pluginslibrary.html)  are relevant informations about Tasker Plugins.

**Comment by ILIYANGERMANOV** [comment]
Out of scope
