### ISSUE TITLE
[FEATURE] Transfer Fee

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#954]
Wouldn't it be better to have a feature for specifying an amount fee when doing transfer from one account to another? :)

**Comment by yulose9** [comment]
Make it either a fixed value or a percentage of that money because sometimes banks charge you with a certain percentages of the money that you're about to transfer

**Comment by Bakr-Ali** [comment]
@ILIYANGERMANOV  Was this implemented? I don't see any option to add transfer fee in the latest play store version.
