### ISSUE TITLE
[FEATURES] Web Api

### ISSUE THREAD

**Issue by byeze** [Ivy-Apps/ivy-wallet#970]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a developer, I want to have the possibility to push new balance changes and transactions or change things in my wallet without using the app directly.

For example, let's say that I have a webhook that is activated when my debit card is used. As a developer, I would connect that webhook to the app api, so I can push that update.

If it's possible to add this feature in the app, I could help to create a nodejs backend so we can have a server. Maybe we can create an AWS Lambda or something like that.

### Why do you need it?

- Integrate other solutions that may provide the app with new balance changes.

**Comment by ILIYANGERMANOV** [comment]
We're serverless - cannot provide an API
