### ISSUE TITLE
Missing translation for new strings

### ISSUE THREAD

**Issue by code-a1** [Ivy-Apps/ivy-wallet#996]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What would you like to improve?

- Add the missing translations for the recently added strings for all languages

### Other

@mhss1 @ILIYANGERMANOV @Pkcarreno @llama-0 @StarHamster @dubeyanant, I saw that you have already started translating the app into other languages, your help will be great now!

### Development

- #997 
- #998 
- #999

**Comment by Pkcarreno** [comment]
I'm on it 👍
